Webui cleanup
raedahgroup/godcr-old pull request #104
Opened 2019-01-01 15:33 UTC by codemaestro64

this performs cleanup that fixes #57

2019-01-01 16:53 UTC, barisere requested changes
![image](https://user-images.githubusercontent.com/20553476/50574675-39d23b00-0ded-11e9-998c-b92b22050cb7.png)
> If only one account is available, it should just be printed and not a widget.
(See https://github.com/raedahgroup/godcr/issues/57#issuecomment-446794830)

- I have only one account, but it is not selected. Clicking the select menu displays nothing.
- There's a checkbox for custom transaction, and a link to "customize transaction". How do they differ?
- The heading for the form can be worded better. "Send From" is not a good description of what the form is meant for.
- The heading for the form should not be a link.

2019-01-01 22:56 UTC, itswisdomagain requested changes
You haven't added code to use the value of the "Spend Unconfirmed" checkbox. That checkbox ought to alter the way a transaction is created. If the box is checked, then the value of `required confirmation` for both normal send and custom send should be 0. Otherwise, a higher value should be used to ensure that only **confirmed** transactions are spent.

2019-01-04 00:52 UTC, itswisdomagain requested changes
Just one code that caught my attention. Will take another look and test properly after you are done with the changes you're working to add.

2019-01-04 00:52 UTC, itswisdomagain commented on web/views/balance.html
> +            $("#nav-balance").addClass("active");
Instead of manually setting this in every page, we should have a single code probably in footer that compares the current `window.href` value against each `a.navlink` element to identify which of the nav links is currently visited and mark that as active instead

2019-01-06 01:25 UTC, itswisdomagain requested changes
Required adjustments for now. Will be able to test more when these are fixed

2019-01-06 01:25 UTC, itswisdomagain commented on web/views/send.html
> +                                       {{ $numberOfAccounts := len .accounts }} {{ if eq $numberOfAccounts 1 }}
Can simplify this to `{{ if eq (len .accounts) 1 }}`

2019-01-06 01:25 UTC, itswisdomagain commented on web/views/send.html
> +                                            <strong>{{ $account.Name }} - {{ $account.Balance }} </strong>
Add some padding or margin, the default account is too close to the header
![screenshot 2019-01-06 at 1 55 22 am](https://user-images.githubusercontent.com/18400051/50730825-d5014280-1156-11e9-8adc-df7f2897865c.png)

2019-01-06 01:25 UTC, itswisdomagain commented on web/views/send.html
> +                                            <strong>{{ $account.Name }} - {{ $account.Balance }} </strong>
Also, `$account.Balance` is a struct object, holding sub values
You can instead use `{{ simpleBalance $account.Balance false }}`, a template function defined in line 28 of templates.go to display a properly formatted amount summary

2019-01-06 01:25 UTC, itswisdomagain commented on web/views/send.html
> +                                            <div class="d-none">
This div can go, we are not showing a dropdown when there's just one account in the wallet, it's not enough to hide it with `class="d-none"`.

2019-01-06 01:25 UTC, itswisdomagain commented on web/views/send.html
> +                                        <label for="use-custom">Select custom inputs</label>
- this checkbox should go below destination address
- text should be "Build custom transaction"
- the section showing the utxos should not have a scroll bar within it, it should extend to fill the page and push the send button down
- also notice that the utxo amounts are not showing
![screenshot 2019-01-06 at 2 07 08 am](https://user-images.githubusercontent.com/18400051/50730895-3c6bc200-1158-11e9-96c5-0e7cfc1e88c0.png)

2019-01-06 01:25 UTC, itswisdomagain commented on web/views/send.html
> +                                            <div class="progress-bar" style="width: 0%"></div>
This progress bar is not in any specification I'm aware of. Did @raedah request this? If not, it should go.

2019-01-06 01:25 UTC, itswisdomagain commented on web/public/js/send.js
>      if (passphraseEl.val() == "") {
Use strict comparison operator `===` and `!==`. The lose comparison operator `==` and `!=` is used in so many places in this file, please find all occurences and correct.

2019-01-06 01:25 UTC, itswisdomagain commented on web/public/js/send.js
> +        errors["#custom-tx-row .alert-info"] = "The sum of selected inputs is less than send amount";
Displaying errors next to the div that has error makes it hard for the error to be noticed. Display errors immediately before or after the "Next" button instead

2019-01-06 10:27 UTC, yaowork commented on web/views/send.html
> +                                            <div class="progress-bar" style="width: 0%"></div>
a visual indicator that indicates whether a user has selected "enough" or "not enough" inputs was requested.

2019-01-06 10:29 UTC, yaowork commented on web/views/send.html
> +                                        <label for="use-custom">Select custom inputs</label>
- The checkbox is there as per instructions
- Same with the "Select custom inputs" text

2019-01-06 10:33 UTC, codemaestro64 commented on web/views/send.html
> +                                            <div class="d-none">
it is needed in submitting the form

2019-01-06 17:02 UTC, itswisdomagain commented on web/views/send.html
> +                                        <label for="use-custom">Select custom inputs</label>
Okay, how about the scrolling area? And the progress bar? Both specifically required?

If yes to both, then the progress bar should not be inside the scrollable area. When I scroll away from the top of the utxo list, the progress bar is no longer visible.

2019-01-06 18:07 UTC, itswisdomagain requested changes
Some more cleanup required.

2019-01-06 18:07 UTC, itswisdomagain commented on web/public/js/send.js
>          for (var i in errors) {
`errors` could simply be an array of error messages instead of a key-value pair, since the keys are no longer used.

2019-01-06 18:07 UTC, itswisdomagain commented on app/walletcore/types.go
> +	FormattedAmount float64        `json:"formatted_amount"`
This `FormattedAmount` field in the `UnspentOutput` type is really only needed in the web interface. Other interfaces can quite easily get the dcr amount by calling `utxo.Amount.ToCoin()`.

Also, it's really just duplication of data. We have similar duplication in `Time` and `FormattedTime` in some other types that we'll also have to cleanup.

If an interface requires value in a particular format, there's no need to add a new field to the parent type if the value in the desired format can be easily gotten from a field already existing in the parent type.

In this case, you can get the formatted time in the web interface handler that needs this value, no need to have it here. I understand the data is used in JS code and you cannot call `.ToCoin()` in JS, but you can do so in the `getUnspentOutputs` handler before marshalling the data as JSON.

Or you could change `Amount` type to `float64` and modify it's usages in other interfaces. Don't duplicate value.

2019-01-06 18:07 UTC, itswisdomagain commented on app/walletmediums/dcrwalletrpc/walletfunctions.go
> +			FormattedAmount: amount.ToCoin(),
As explained above, not needed. At the very least, take off either `Amount` or `FormattedAmount`, one of those values can be used to get the other seamlessly.

2019-01-06 18:07 UTC, itswisdomagain commented on web/public/js/send.js
> +    if (sourceAccountEl.find(":selected").text() === "") {
You should be creative here, if there's only one account in the wallet, `source account` should not be dropdown that requires the `:selected` element selector to determine its value.

2019-01-06 18:07 UTC, itswisdomagain commented on web/public/js/send.js
> +    var isCustomTransaction = $("#use-custom").prop("checked")?true:false;
`$('#use-custom').is(':checked')`

2019-01-06 18:07 UTC, itswisdomagain commented on web/public/js/send.js
>          passphraseEl.after("<div class='passphrase-error'>" + error + "</div>");
Why not add this div to the modal directly and if there's an error, you set the error text and show as appropriate. Also the if statement above and this one can be merged.

2019-01-06 18:07 UTC, itswisdomagain commented on web/public/js/send.js
>          passphraseEl.after("<div class='passphrase-error'>" + error + "</div>");
This function can be simplified thus:
```
$(".passphrase-error").remove();

var passphraseEl = $("#wallet-passphrase");

if (passphraseEl.val() === "") {
    passphraseEl.after("<div class='passphrase-error'>Your wallet passphrase is required</div>");
    return false
}

return true
```

As mentioned, would be better (performance-wise) to be add the error div to the modal directly instead of creating the element and appending to the dom each time an error needs to be displayed and removing the element from the dom every time this function is called

2019-01-06 18:07 UTC, itswisdomagain commented on web/public/js/send.js
> +    var account_number = $("#source-account").find(":selected").val();
You may need a `getSelectedAccount` function that gets the selected account from dropdown or simply displayed text

2019-01-06 18:07 UTC, itswisdomagain commented on web/public/js/send.js
> +                        "<td width='25%'>" + receiveDateTime.toString().split(' ').slice(0,5).join(' '); + "</td>" +
This doesn't look good. We may need a `formatTime` js function, for now, `toLocaleString()` or something similarly simple should do

2019-01-06 18:07 UTC, itswisdomagain commented on web/public/js/send.js
> +                        "<td width='25%'>" + receiveDateTime.toString().split(' ').slice(0,5).join(' '); + "</td>" +
If the particular time display format is a requirement from @raedah, you should consider using moment.js

2019-01-06 18:07 UTC, itswisdomagain commented on web/public/js/send.js
This JS file needs a lot of cleanup.
- Code should be simplified. Variables properly named (e.g. `destinationAddressElement` instead of `destinationAddressEl`).
- The functions should be arranged in order of use. `validatePassphrase` should likely not be the first function in this file.
- I notice some potentially unused functions such as `clearMessages()`, confirm and delete unused code.
- Add more comments.
- You should probably make more use of the `setErrorMessage` function in displaying error messages.
- And other considerations I may not be able to point out at this time.

It's worth remembering we want other devs to be able to maintain this code, not just you.

2019-01-06 18:07 UTC, itswisdomagain commented on web/views/send.html
> +                                            <div class="d-none">
That's a hack, you should find a better way to solve the issue with form submission. One way is to use a single hidden input field.
`<input type="hidden" id="source-account" name="source-account" value="{{ $account.Number }}">`

Also, since you're submitting the form with JavaScript, you might not even need a hidden field. As introduced in this PR, there are 2 areas where the selected source account could display: as a simple text (if there's only 1 account in the wallet) and as a dropdown (if there are more 2 or more accounts). Your JS code for validating and submitting the send form should check either places for the presence of a selected account value, not resolving to hacks and work arounds.

2019-01-06 18:07 UTC, itswisdomagain commented on web/views/send.html
> +                                            <div class="progress-bar" style="width: 0%"></div>
The progress bar and the `Select inputs to build custom transaction` prompt should not be inside the scrollable area. When I scroll away from the top of the utxo list, they are no longer visible

2019-01-06 18:08 UTC, itswisdomagain commented
Other observations.

The error message and the button look off, they should probably be in the card. And some spacing should separate them.
![screenshot 2019-01-06 at 6 05 03 pm](https://user-images.githubusercontent.com/18400051/50739887-623fa800-11e6-11e9-8ed1-8a5a598de695.png)

Repeated error messages:
![screenshot 2019-01-06 at 6 34 22 pm](https://user-images.githubusercontent.com/18400051/50739893-6966b600-11e6-11e9-8a14-49c2aa5db3dc.png)

2019-01-10 12:37 UTC, itswisdomagain commented
The git history for this PR branch is polluted and no longer in sync with `raedahgroup/master` because of a recent history re-write done on master.

Follow the steps below to re-create this PR
- Keep a copy of this PR branch's code in some folder in your PC for reference
- Delete your forked repo (codemaestro64/godcr)
- Fork https://github.com/raedahgroup/godcr again
- Clone your newly forked repo
- Create a new branch for your work (`git checkout -b webui-cleanup`)
- Re-apply the changes you made on this PR to the newly created branch
- Push the new branch and create a new PR
- Delete the copy of this code you saved initially

2019-01-10 12:37 UTC, closed without merging