Staking menu cli
raedahgroup/godcr-old pull request #118
Opened 2019-01-02 22:42 UTC by barisere

Partial solution to #65

2019-01-03 09:38 UTC, itswisdomagain requested changes

2019-01-03 09:38 UTC, itswisdomagain commented on app/walletcore/types.go
> +	Tickets []Ticket `json:"tickets"`
go fmt

2019-01-03 09:38 UTC, itswisdomagain commented on app/walletcore/types.go
> +	Tickets []Ticket `json:"tickets"`
maybe use pointer for the tickets slice

2019-01-03 09:38 UTC, itswisdomagain commented on app/walletcore/types.go
> +type PurchaseTicketRequest struct {
We can and should use `dcrlibwallet.PurchaseTicketsRequest` instead. One objective of making changes to the `dcrlibwallet` library is to minimise code repetition. Several functions that were once in this godcr codebase have been migrated to the `dcrlibwallet` library to allow code reuse (`txhelper.NewUnsignedTx` for example)

2019-01-03 09:38 UTC, itswisdomagain commented on app/walletcore/wallet.go
> +import "context"
group imports

2019-01-03 09:38 UTC, itswisdomagain commented on app/walletmediums/dcrlibwallet/walletfunctions.go
> +
space can go

2019-01-03 09:38 UTC, itswisdomagain commented on app/walletmediums/dcrlibwallet/walletfunctions.go
> +	total := data.OwnMempoolTix + data.Live + data.Immature
Also return the number of tickets in mempool, that are live and that are immature. Aside from showing the individual tickets and their statuses, the `godcr getstakeinfo` command should show a nice summary of the status of the wallet's tickets, not just the total.  Something like:
```
Stake Info
Total Tickets:    20
In mempool:       5
Live:             15

Tickets
hash             status
```

No need to show an entry if there are zero tickets of that nature, in the sample above, "Immature" was ommitted from the output because there are no immature tickets

2019-01-03 09:38 UTC, itswisdomagain commented on app/walletmediums/dcrlibwallet/walletfunctions.go
> +		case err := <-errorCh:
also listen for `ctx.Done` in case user sends interrupt signal. `main.go` catches such signals and cancels the context here as long as the context here is the same context created in `main.go` for long running operations. That context is usually passed to all interfaces and interfaces can in turn pass it to functions performing long operations

2019-01-03 09:38 UTC, itswisdomagain commented on app/walletmediums/dcrlibwallet/walletfunctions.go
> +		SpendLimit:            int64(sendAmount),
`request.SpendLimit` was already int64, conversion above and reverse conversion here unnecessary

2019-01-03 09:38 UTC, itswisdomagain commented on app/walletmediums/dcrlibwallet/walletfunctions.go
> +		ticketHashes[i] = hash.String()
we should probably modify `lib.walletLib.PurchaseTickets` to return []string instead

2019-01-03 09:38 UTC, itswisdomagain commented on app/walletmediums/dcrlibwallet/walletfunctions.go
> +		ticketHashes[i] = hash.String()
I'll do this, push to dcrlibwallet repo and provide you with the latest version for use in go.mod to access the updated function

2019-01-03 09:38 UTC, itswisdomagain commented on app/walletmediums/dcrwalletrpc/dcrwalletrpc.go
> +type WalletRPCClient struct {
Nice catch

2019-01-03 09:38 UTC, itswisdomagain commented on app/walletmediums/dcrwalletrpc/helpers.go
>  	ctx := context.Background()
Perhaps, dcrwallet rpc function calls should use the context created in `main.go`, the context passed as parameter to different rpc function calls are used by those functions to know when to terminate long-running processes - which is an expected behaviour when user sends SIGINT

Likely work for a different PR

2019-01-03 09:38 UTC, itswisdomagain commented on app/walletmediums/dcrwalletrpc/walletfunctions.go
> +	for response, err := ticketsResponse.Recv(); err != io.EOF; response, err = ticketsResponse.Recv() {
Err... maybe simplify this? Took me a moment to realise this is the `for initializer; condition; next` syntax used in familiar operations like `for i := 0; i < 10; i++`

2019-01-03 09:38 UTC, itswisdomagain commented on app/walletmediums/dcrwalletrpc/walletfunctions.go
> +		SpendLimit:            int64(amount),
The conversion above and reverse conversion here are unnecessary

2019-01-03 09:38 UTC, itswisdomagain commented on app/walletmediums/dcrwalletrpc/walletfunctions.go
> +	ticketPrice := dcrutil.Amount(priceResponse.GetTicketPrice())
`priceResponse.GetTicketPrice()` is int64, can be compared directly with `request.SpendLimit`, no need for converting both to dcrutil.Amount before comparing

2019-01-03 09:38 UTC, itswisdomagain commented on app/walletmediums/dcrwalletrpc/walletfunctions.go
> +	if balance.Spendable < ticketPrice {
There's a tiny issue with this comparison. `balance` was gotten from `c.AccountBalance`, which uses 0 required confirmations to fetch the account's balance. This purchase ticket request might want to use a higher value for required confirmations (`request.MinConfirmations > 0`). If that happens, `balance.Spendable` (gotten with 0 required confirmations) might be sufficient to cover `ticketPrice` but `balance.Spendable` (gotten with `request.MinConfirmations` required confirmations) might not.

It's time to modify the `wallet.AccountBalance` function to allow passing a required confirmations parameter.

2019-01-03 09:38 UTC, itswisdomagain commented on cli/commands/commands.go
> +// ExperimentalCommands defines experimental commands and options available on the cli
😆

2019-01-03 09:38 UTC, itswisdomagain commented on cli/commands/commands.go
> +	StakeInfo       GetStakeInfoCommand    `command:"getstakeinfo" description:"Show information about the wallet stakes, tickets and their statuses"`
Change command name to `stakeinfo` (discussed with @raedah); and command type to `StakeInfoCommand`

I think `show-transaction` should probably also be `transaction`, no need to prefix with verbs like `gethistory`, `getbalance`, `show-transaction`, `gethelp`.

`show-transaction` may be an exception though. `godcr transaction [hash]` versus `godcr show-transaction [hash]`, the latter is nicer.

2019-01-03 09:38 UTC, itswisdomagain commented on cli/commands/getstakeinfo.go
> +	"github.com/raedahgroup/godcr/app"
separate imports

2019-01-03 09:38 UTC, itswisdomagain commented on cli/commands/getstakeinfo.go
> +func (g GetStakeInfoCommand) Run(ctx context.Context, wallet app.WalletMiddleware) error {
This `Run` method should implement `WalletCommandRunner` so that the wallet is opened before getting here. You can add `ctx context.Context` to the signature of `WalletCommandRunner.Run`

2019-01-03 09:48 UTC, itswisdomagain requested changes

2019-01-03 09:48 UTC, itswisdomagain commented on app/walletmediums/dcrlibwallet/walletfunctions.go
> +func (lib *DcrWalletLib) PurchaseTicket(ctx context.Context, request walletcore.PurchaseTicketRequest) (ticketHashes []string, err error) {
This function implementation for dcrwalletrpc performs a check for account balance and ticket price before proceeding. We should do that here also. Will add the `GetTicket` price function to dcrlibwallet and provide the updated dep version

2019-01-03 09:48 UTC, itswisdomagain commented on cli/commands/getstakeinfo.go
> +	output.WriteString(fmt.Sprintf("Tickets: %d\n", stakeInfo.Total))
When using dcrlibwallet as wallet medium, `stakeInfo` might be nil even if `err != nil`. That would be similar to `stakeInfo.Total == 0` in the case of dcrwalletrpc. In either cases, display a simple status message: `No tickets in wallet`

2019-01-03 09:48 UTC, itswisdomagain commented on cli/commands/purchase-ticket.go
> +	Args             struct {
Maybe put this struct in a different type (PurchaseTicketCommandArgs) and reference here

2019-01-03 09:48 UTC, itswisdomagain commented on cli/commands/purchase-ticket.go
> +		FromAccount string `required:"yes" positional-arg-name:"from account"`
Just "account"?

2019-01-03 09:48 UTC, itswisdomagain commented on cli/commands/purchase-ticket.go
> +		SpendLimit  int64  `required:"yes" positional-arg-name:"spend limit"`
"spend-limit" to keep with pattern in receive command and to make for nicer output in `godcr help purchaseticket`

2019-01-03 09:48 UTC, itswisdomagain commented on cli/commands/purchase-ticket.go
> +func (ptc PurchaseTicketCommand) Run(ctx context.Context, middleware app.WalletMiddleware) error {
As with `StakeInfoCommand`, this should implement `WalletCommandRunner`

2019-01-03 09:48 UTC, itswisdomagain commented on go.mod
> -	github.com/decred/dcrwallet v1.2.3-0.20181120205657-8690f1096aa7
Retain this version of dcrwallet for this import and for `dcrwallet/rpc/walletrpc` below. `go mod tidy` afterwards, most of the golang.org/x/ dependencies should no longer be needed

2019-01-03 09:48 UTC, itswisdomagain commented on go.mod
> +	github.com/raedahgroup/dcrlibwallet v1.0.0-rc1.0.20190102215219-497892e692815b32cbd80623373fcaa91394d7bb
Will give you a new version for this dep. The replace directive at the end of the file can be removed then

2019-01-03 09:53 UTC, barisere commented on app/walletcore/types.go
> +	Tickets []Ticket `json:"tickets"`
> maybe use pointer for the tickets slice

It holds only simple scalars that won't likely be modified. Making a copy of it is cheap, if we need to modify it.

2019-01-03 10:13 UTC, itswisdomagain commented on go.mod
> +	github.com/raedahgroup/dcrlibwallet v1.0.0-rc1.0.20190102215219-497892e692815b32cbd80623373fcaa91394d7bb
`github.com/raedahgroup/dcrlibwallet v0.0.0-20190103100403-47981b2244f5`

2019-01-03 10:39 UTC, barisere commented on app/walletcore/types.go
> +type PurchaseTicketRequest struct {
There'll be repetition nonetheless. `dcrlibwallet.PurchaseTicketsRequest` and `walletrpc.PurchaseTicketsRequest` are not the same type. But I've make the change.

2019-01-03 10:51 UTC, barisere commented on app/walletmediums/dcrlibwallet/walletfunctions.go
> +		SpendLimit:            int64(sendAmount),
It wasn't an `Amount`, so the purchase failed due to insufficient balance.

2019-01-03 11:05 UTC, barisere commented on app/walletmediums/dcrwalletrpc/walletfunctions.go
> +		SpendLimit:            int64(amount),
https://github.com/raedahgroup/godcr/pull/118#discussion_r244964200

2019-01-03 11:07 UTC, barisere commented on app/walletmediums/dcrwalletrpc/walletfunctions.go
> +	ticketPrice := dcrutil.Amount(priceResponse.GetTicketPrice())
https://github.com/raedahgroup/godcr/pull/118#discussion_r244964200

2019-01-03 11:25 UTC, itswisdomagain commented on app/walletcore/types.go
> +type PurchaseTicketRequest struct {
Yes, as much as we want to avoid repetition, I'm skeptical about using `walletrpc` types in godcr because dcrwalletrpc is out of our control. `dcrlibwallet` isn't. At least for now, and hopefully never, seeing as 1 major goal of dcrlibwallet is to abstract features across `dcrandroid`, `dcrios,` and `godcr`

2019-01-04 00:46 UTC, itswisdomagain requested changes

2019-01-04 00:46 UTC, itswisdomagain commented on app/walletmediums/dcrlibwallet/walletfunctions.go
> +		Unspent:       data.Unspent,
Not sure this is needed. As the wallet rpc doc says, `Unspent` could include live, missed or expired tickets, adding live tickets to unspent could lead to an incorrect total.

The issue description only mentions displaying count for mempool, live and immature tickets

2019-01-04 00:46 UTC, itswisdomagain commented on app/walletmediums/dcrlibwallet/walletfunctions.go
> +			stakeInfo.Tickets = append(stakeInfo.Tickets, walletcore.Ticket{
Adjusted requirement from @raedah says the list of individual tickets is no longer needed with the `StakeInfo` command. I think this information is already provided with the `GetTransaction` command but if not, we can add it in a different PR

2019-01-04 00:46 UTC, itswisdomagain commented on app/walletmediums/dcrlibwallet/walletfunctions.go
> +	sendAmount, err := dcrutil.NewAmount(float64(request.SpendLimit))
This is wrong conversion. `request.SpendLimit` which represents amount in atoms. To convert that to dcutil.Amount, you use `dcrutil.Amount(request.SpendLimit)`. Still not sure the conversion is needed though, the value can be used directly

2019-01-04 00:46 UTC, itswisdomagain commented on app/walletmediums/dcrlibwallet/walletfunctions.go
> +	sendAmount, err := dcrutil.NewAmount(float64(request.SpendLimit))
To emphasize, if `request.SpendLimit == 1`, converting it to float will produce 1.0, and `dcrutil.NewAmount(1.0)` is equal to 1 DCR, not 1 Atom which is what `request.SpendLimit == 1` represents. Maybe we need to update the property name to `SpendLimitInAtom` or change the type to `dcutil.Amount` which is an int64 alias?

2019-01-04 00:46 UTC, itswisdomagain commented on app/walletmediums/dcrlibwallet/walletfunctions.go
> +			request.SpendLimit, ticketPrice)
Both `request.SpendLimit` and `ticketPrice` are int64, might be more informative to the user to convert to dcr amount string using `dcrutil.Amount(ticketPrice).String()` and use `%s` instead of `%v` in both cases

2019-01-04 00:46 UTC, itswisdomagain commented on app/walletmediums/dcrlibwallet/walletfunctions.go
> +	for i, ticketHash := range response {
you could just assign `lib.walletLib.PurchaseTickets` result to `ticketHashes`

2019-01-04 00:46 UTC, itswisdomagain commented on app/walletmediums/dcrwalletrpc/walletfunctions.go
> +		return nil, fmt.Errorf("could not determine ticket ticketPrice: %s", err.Error())
"could not determine ticket price, %s"

2019-01-04 00:46 UTC, itswisdomagain commented on app/walletmediums/dcrlibwallet/walletfunctions.go
> +			request.SpendLimit, ticketPrice)
Typo too, "less than", and "ticket price" instead of "ticket ticketPrice"

2019-01-04 00:46 UTC, itswisdomagain commented on app/walletmediums/dcrwalletrpc/walletfunctions.go
> +		return nil, fmt.Errorf("insufficient funds: spend limit %v is less that ticket ticketPrice %v", amount, ticketPrice)
spend limit doesn't mean user does not have more funds in their wallet..., compare the message displayed in dcrlibwallet's version of this function

2019-01-04 00:46 UTC, itswisdomagain commented on app/walletmediums/dcrwalletrpc/walletfunctions.go
> +	balance, err := c.AccountBalance(request.Account)
Account balance should be retrieved with min confirmations equal to `request.RequiredConfirmations`

2019-01-04 00:46 UTC, itswisdomagain commented on app/walletmediums/dcrwalletrpc/walletfunctions.go
> +	if balance.Spendable < dcrutil.Amount(ticketPrice) {
Similar comparison is not done in dcrlibwallet's version of this function

2019-01-04 00:46 UTC, itswisdomagain commented on cli/commands/purchase-ticket.go
> +	Account    string `required:"yes" positional-arg-name:"from-account"`
New suggestion from @raedah: this shouldn't be required, use default account (account number 0) by default if no value is passed for this argument

2019-01-04 00:46 UTC, itswisdomagain commented on cli/commands/purchase-ticket.go
> +	SpendLimit int64  `required:"yes" positional-arg-name:"spend-limit"`
Another comment from @raedah: this is obsolete, should no longer be requested from the user. Use the `ticketPrice` value directly instead.

The dcrwalletrpc docs explain that the spend limit is

> The maximum amount to pay for a single ticket. If the current stake difficulty _(aka ticket price)_ is above this amount, the wallet will return an error

Since the spend limit cannot be lower than ticket price and has no meaning if it is higher (the price for a single ticket is constant and equal to ticketPrice), we can safely use the ticketPrice in place of this value gotten from the user

2019-01-04 00:46 UTC, itswisdomagain commented on cli/commands/purchase-ticket.go
> +		SpendLimit:            ptc.Args.SpendLimit,
No longer required. I will modify the `dcrlibwallet.PurchaseTicketsRequest` struct to no longer include this field. Also when submitting the actual purchase request to the wallet, I'll modify the `dcrlibwallet.PurchaseTicket` function to use the `TicketPrice()` value instead.

2019-01-04 00:46 UTC, itswisdomagain commented on cli/commands/purchase-ticket.go
> +		SpendLimit:            ptc.Args.SpendLimit,
Will reply this comment with a new dcrlibwallet dep version to use to access the changes

2019-01-04 00:46 UTC, itswisdomagain commented on cli/commands/stakeinfo.go
> +	if stakeInfo == nil {
`stakeInfo.Total` could also be equal to 0, doesn't that mean there is no ticket in wallet? If that's not the meaning, then we may need to reword the term `Total` (maybe `Active`?), I think total should be a count of ALL tickets in wallet regardless of their statuses

2019-01-04 00:46 UTC, itswisdomagain commented on cli/runner/runner.go
> +	if err := prepareWallet(runner.ctx, runner.walletMiddleware, options); err != nil {
Commands implementing `WalletMiddlewareCommandRunner` should ideally not **require** that the wallet be pre-opened. An example is the `createwallet` command, it certainly does not need a wallet to be open prior to running and probably should even fail if a wallet already exists.

With this change, `createwallet` will fail if a wallet doesn't exist. Maybe we should rename the type but commands requiring wallet to be pre-opened should use the `WalletCommandRunner` interface, not this one

2019-01-04 00:55 UTC, itswisdomagain commented on cli/commands/stakeinfo.go
> +	if stakeInfo == nil {
New feedback from @raedah: `When in doubt, return all available information and we can prune it in review.`

2019-01-04 01:48 UTC, itswisdomagain commented on cli/commands/purchase-ticket.go
> +		SpendLimit:            ptc.Args.SpendLimit,
`github.com/raedahgroup/dcrlibwallet v0.0.0-20190104023021-65f2f2be4b06`

2019-01-04 06:29 UTC, barisere commented on app/walletmediums/dcrlibwallet/walletfunctions.go
> +		Unspent:       data.Unspent,
wallet rpc returns 0 for Live, and returns the expected value for live as `Unspent`.
```
*walletrpc.StakeInfoResponse {PoolSize: 0, AllMempoolTix: 0, OwnMempoolTix: 0, Immature: 0, Live: 0, Voted: 0, Missed: 0, Revoked: 5, Expired: 0, TotalSubsidy: 0, Unspent: 7}
```
```
$ ./godcr stakeinfo
stake info for wallet:
total 7  revoked 5  unspent 7
```

2019-01-05 16:54 UTC, itswisdomagain requested changes
Additional note:
`godcr purchaseticket` (via dcrlibwallet) gave insufficient balance error:
`Unable to purchase tickets: wallet.PurchaseTickets: insufficient balance:: txauthor.NewUnsignedTransaction`

2019-01-05 16:54 UTC, itswisdomagain commented on app/walletcore/wallet.go
> +	// GetTransaction returns information about the transaction witht the given hash.
*with* typo

2019-01-05 16:54 UTC, itswisdomagain commented on app/walletcore/wallet.go
> +	PurchaseTicket(ctx context.Context, request dcrlibwallet.PurchaseTicketsRequest) (ticketHashes []string, err error)
Since this command supports purchasing more than 1 or more tickets, won't a better name be `purchasetickets`?

2019-01-05 16:54 UTC, itswisdomagain commented on app/walletmediums/dcrlibwallet/walletfunctions.go
> +			Direction:     txDirection(int32(tx.Direction)),
Let's replace `walletcore.TransactionDirection` with `txhelper.TransactionDirection`. The `txDirection()` declared in line 220 above would no longer be necessary

2019-01-05 16:54 UTC, itswisdomagain commented on app/walletmediums/dcrlibwallet/walletfunctions.go
> +		return nil, fmt.Errorf("could not fetch account: %v", err.Error())
- `err.Error()` is of type string, use `%s` instead of `%v`
- message should be could not fetch `account balance`, not `account`
- use the value of `request.RequiredConfirmations` in the call to fetch account balance so your comparison below will be valid

2019-01-05 16:54 UTC, itswisdomagain commented on app/walletmediums/dcrlibwallet/walletfunctions.go
> +			balance.Spendable, ticketPrice.TicketPrice)
`return nil, fmt.Errorf("insufficient funds: spendable account balance (%s) is less than ticket price (%s)", balance.Spendable, dcrutil.Amount(ticketPrice.TicketPrice))`

2019-01-05 16:54 UTC, itswisdomagain commented on app/walletmediums/dcrwalletrpc/walletfunctions.go
> +
space can go

2019-01-05 16:54 UTC, itswisdomagain commented on app/walletmediums/dcrwalletrpc/walletfunctions.go
> +	totalTickets := stakeInfo.OwnMempoolTix + stakeInfo.Live + stakeInfo.Immature + stakeInfo.Unspent
Does this really represent the total number of tickets in the querying wallet? I think the sum of the following better represent the total:
`stakeInfo.OwnMempoolTix + stakeInfo.Live + stakeInfo.Immature + stakeInfo.Expired + stakeInfo.Revoked + stakeInfo.Voted + stakeInfo.Missed`

2019-01-05 16:54 UTC, itswisdomagain commented on app/walletmediums/dcrwalletrpc/walletfunctions.go
> +		return nil, fmt.Errorf("could not determine ticket ticketPrice: %s", err.Error())
*ticket ticketPrice*

2019-01-05 16:54 UTC, itswisdomagain commented on cli/commands/purchase-ticket.go
> +
space can go

2019-01-05 16:54 UTC, itswisdomagain commented on cli/commands/purchase-ticket.go
> +	Account string `positional-arg-name:"from-account"`
Let's make this an option instead, no default value. I'm thinking `godcr purchaseticket from=default`. If `args.from == ""`, use 0 as account number else use `wallet.AccountNumber` function to look up account number

`godcr receive [account]` is a little intuitive - user can quite easily understand that the `[account]` argument represents the account that funds will be received into.

`godcr purchaseticket [account]` would make sense if `[account]` means the account that the purchased ticket will be added to but tickets are not added to individual accounts but to the wallet as a whole (I think).

2019-01-05 16:54 UTC, itswisdomagain commented on cli/commands/purchase-ticket.go
> +	termio.PrintStringResult(strings.TrimSpace(output.String()))
This currently simply prints out the hashes on terminal, some contextual message would help.
`n tickets purchased with hash <hash1>, <hash2>` or something of that nature, just precede the hash printing with a message that provides context for the command output the user sees

2019-01-05 16:54 UTC, itswisdomagain commented on app/walletmediums/dcrwalletrpc/walletfunctions.go
> +	return &walletcore.StakeInfo{
This should include counts for `Voted` and `Missed`

2019-01-05 16:54 UTC, itswisdomagain commented on cli/commands/purchase-ticket.go
> +	MinConfirmations uint32             `long:"min-conf" default:"1" description:"The number of required confirmations for funds used to purchase a ticket." long-description:"If set to zero, it will use
`long:"minconf" default:"0"`
the godcr program has used 0 as default number of required/minimum confirmations for various operations, let's stick to that for now. See #125 for more

I think we should avoid hyphens for option names, makes it harder to type. I see a number of such here

2019-01-05 16:54 UTC, itswisdomagain commented on cli/commands/purchase-ticket.go
> +	passphrase, err := getWalletPassphrase()
Currently, `godcr purchaseticket` just shows "Wallet passphrase" prompt on terminal. This can be "Enter private passphrase to purchase ticket"

2019-01-05 16:54 UTC, itswisdomagain commented on cli/commands/stakeinfo.go
> +	termio.PrintStringResult(output)
Based on recent comment from @raedah, show all counts whether 0 or not. We'll prune later

2019-01-05 16:54 UTC, itswisdomagain commented on go.mod
> +	github.com/davecgh/go-spew v1.1.1 // indirect
I'm not sure what introduced some of these dependencies. Can you confirm? `go mod tidy` too if it helps.

2019-01-05 16:54 UTC, itswisdomagain commented on app/walletmediums/dcrwalletrpc/walletfunctions.go
> +		TxFee:                 request.TxFee,
`SpendLimit: priceResponse.TicketPrice,` is missing here. A recent comment mentioned using the ticket price as the spend limit.

Without providing a valid spend limit, the following error was encountered while trying to purchase ticket with dcrwallet rpc:
`error purchasing tickets: rpc error: code = FailedPrecondition desc = Unable to purchase tickets: wallet.PurchaseTickets: invalid operation: ticket price 16.07545648 DCR above spend limit 0 DCR`

2019-01-05 18:51 UTC, itswisdomagain commented on cli/commands/purchase-ticket.go
> +	passphrase, err := getWalletPassphrase()
I think @raedah has mentioned using `Spending Passphrase` before. That also makes sense for a "purchase..." command

2019-01-05 21:17 UTC, barisere commented on app/walletmediums/dcrlibwallet/walletfunctions.go
> +		return nil, fmt.Errorf("could not fetch account: %v", err.Error())
Where is `RequiredConfirmations` passed or used in getting the account balance? The function accepts on the account number.

2019-01-05 21:23 UTC, barisere commented on app/walletmediums/dcrwalletrpc/walletfunctions.go
> +	totalTickets := stakeInfo.OwnMempoolTix + stakeInfo.Live + stakeInfo.Immature + stakeInfo.Unspent
I'll defer to @raedah on this. A different requirement was given in #65. I'm confused too.

2019-01-05 21:28 UTC, barisere commented on cli/commands/purchase-ticket.go
> +	Account string `positional-arg-name:"from-account"`
`godcr purchasetickets --pay-from=default`
How about that?

2019-01-05 21:31 UTC, barisere commented on app/walletmediums/dcrwalletrpc/walletfunctions.go
> +	return &walletcore.StakeInfo{
Let @raedah clarify what the total should be.

2019-01-05 21:50 UTC, barisere commented on cli/commands/purchase-ticket.go
> +	MinConfirmations uint32             `long:"min-conf" default:"1" description:"The number of required confirmations for funds used to purchase a ticket." long-description:"If set to zero, it will use
It makes it readable.
```
$ docker run --memory-reservation 
```
Try typing --memoryreservation, or --disablecontenttrust=false. See how readable it gets when you add hyphens. It depends on the words in the flag, and how readable they are when they run together.

2019-01-05 21:53 UTC, raedah commented on app/walletmediums/dcrwalletrpc/walletfunctions.go
> +	totalTickets := stakeInfo.OwnMempoolTix + stakeInfo.Live + stakeInfo.Immature + stakeInfo.Unspent
We dont need to calculate a total. Simply display the values that the api offers.

2019-01-08 12:21 UTC, itswisdomagain commented on app/walletmediums/dcrlibwallet/walletfunctions.go
> +		return nil, fmt.Errorf("could not fetch account: %v", err.Error())
Check #143

2019-01-08 20:03 UTC, itswisdomagain requested changes

2019-01-08 20:03 UTC, itswisdomagain commented on app/walletcore/types.go
> +type StakeInfo struct {
`AllMempoolTix`, `PoolSize` and `TotalSubsidy` were not assigned or used. It'd be nice to also show these values on cli.
`Missed` and `Voted` are needed for display on cli but they were not assigned or used either.
`Total` was assigned but never read. It should probably go, we can bring it back when it's usefulness is affirmed after testing by @raedah

2019-01-08 20:03 UTC, itswisdomagain commented on app/walletmediums/dcrlibwallet/walletfunctions.go
> +		return nil, fmt.Errorf("error getting stake info: %v", err.Error())
`%s` instead of `%v`

2019-01-08 20:03 UTC, itswisdomagain commented on app/walletmediums/dcrlibwallet/walletfunctions.go
> +	total := data.OwnMempoolTix + data.Live + data.Immature + data.Unspent
Since it's still unclear what `total` should be, let's do without it for now, stick to displaying the returned data only for now until further direction is received post-testing

2019-01-08 20:03 UTC, itswisdomagain commented on app/walletcore/types.go
> +	PoolSize     uint32 `json:"poolSize"`
`AllMempoolTix` should come here as well, so the properties above the empty line space are those that relate to the querying wallet, while below the line, properties defined are general blockchain info. Comments should be added as well

2019-01-08 20:03 UTC, itswisdomagain commented on app/walletmediums/dcrlibwallet/walletfunctions.go
> +	if balance.Spendable < dcrutil.Amount(ticketPrice.TicketPrice) {
This should also account for when user specifies more than 1 ticket to purchase in `request.NumTickets`

2019-01-08 20:03 UTC, itswisdomagain commented on app/walletmediums/dcrwalletrpc/walletfunctions.go
> +		return nil, fmt.Errorf("could not fetch account: %v", err.Error())
`%s`

2019-01-08 20:03 UTC, itswisdomagain commented on app/walletmediums/dcrwalletrpc/walletfunctions.go
> +		return nil, fmt.Errorf("insufficient funds: account balance %v is less than ticket price %v",
`%s` in both instances of `%v`, also see other review about balance and number of tickets above, also applies here

2019-01-08 20:03 UTC, itswisdomagain commented on cli/commands/helpers.go
> +	return getWalletPassphraseWithPrompt("Wallet passphrase")
"Spending Passphrase"

2019-01-08 20:03 UTC, itswisdomagain commented on cli/commands/purchase-ticket.go
> +	MinConfirmations uint32  `long:"min-conf" default:"0" description:"The number of required confirmations for funds used to purchase a ticket." long-description:"If set to zero, it will use unconfirme
default should be 2, that represents fully confirmed tx

2019-01-08 20:03 UTC, itswisdomagain commented on cli/commands/purchase-ticket.go
> +	output.WriteString(fmt.Sprintf("You have purchased %d ticket(s)\n", len(tickets)))
You can create the needed string without the builder and without the loop below using:
`output := fmt.Sprintf("You have purchased %d ticket(s)\n%s", strings.Join(tickets, "\n"))`

2019-01-08 20:03 UTC, itswisdomagain commented on go.mod
> +	github.com/raedahgroup/dcrlibwallet v1.0.0-rc1.0.20190106225103-e608e7f143af
Update this to `github.com/raedahgroup/dcrlibwallet v1.0.0-rc1.0.20190108195612-81f0df0be7a3` to get the latest changes to the dcrlibwallet repo that improves the `StakeInfo` function

2019-01-09 06:45 UTC, itswisdomagain requested changes
Some little changes here and there and this should be good to merge

2019-01-09 06:45 UTC, itswisdomagain commented on app/walletcore/types.go
> +	Voted         uint32 `json:"voted"`
`Voted` is related to the wallet, the number of tickets owned by the wallet that have participated in a vote

2019-01-09 06:45 UTC, itswisdomagain commented on app/walletcore/types.go
>  	Total         uint32 `json:"total"`
`Total` can be removed, no longer assigned or used

2019-01-09 06:45 UTC, itswisdomagain commented on cli/commands/commands.go
> +	PurchaseTicket  PurchaseTicketsCommand `command:"purchasetickets" description:"Purchase tickets"`
`PurchaseTickets` to maintain uniformity
description:Purchase 1 or more tickets

2019-01-09 06:45 UTC, itswisdomagain commented on cli/commands/purchase-ticket.go
> +	termio.PrintStringResult(strings.TrimSpace(output))
`TrimSpace` should no longer be necessary, `strings.Join` does not leave trailing spaces

2019-01-09 06:54 UTC, itswisdomagain requested changes
These also

2019-01-09 06:54 UTC, itswisdomagain commented on app/walletmediums/dcrwalletrpc/walletfunctions.go
> +		return nil, fmt.Errorf("could not fetch account: %s", err.Error())
account balance

2019-01-09 06:54 UTC, itswisdomagain commented on app/walletmediums/dcrlibwallet/walletfunctions.go
> +		return nil, err
dcrwallet uses `return nil, fmt.Errorf("could not determine ticket ticketPrice: %s", err.Error())`, preferred

2019-01-09 06:54 UTC, itswisdomagain commented on app/walletmediums/dcrwalletrpc/walletfunctions.go
> +			return ticketHashes, fmt.Errorf("error purchasing tickets: %s", err.Error())
error purchasing tickets? I believe at this point, the tickets were indeed purchased but the returned hash could not be parsed/processed, user should know they may have been debited so they don't repeat the command and get debited twice

2019-01-09 06:54 UTC, itswisdomagain commented on cli/commands/purchase-ticket.go
> +	TicketFee        int64   `description:"Fees per kB to use for all purchased tickets." long-description:"If 0 is passed, the global value for a ticket fee will be used."`
No short/long name?

2019-01-09 06:58 UTC, itswisdomagain commented
General stake info returned by dcrlibwallet is different from dcrwallet rpc. This might have something to do with the implementation of the `StakeInfo` functions in both projects, should probably file as a bug and attend to it later.

dcrlibwallet:
```
stake info for wallet:
expired 0  immature 0  live 0  revoked 0  unmined 0  unspent 0  allmempooltix 0  poolsize 0  missed 0  voted 0  total subsidy 0
```

dcrwallet rpc:
```
stake info for wallet:
expired 0  immature 0  live 0  revoked 0  unmined 0  unspent 1  allmempooltix 10  poolsize 5098  missed 1  voted 0  total subsidy 0
```

2019-01-09 15:11 UTC, itswisdomagain requested changes

2019-01-09 15:11 UTC, itswisdomagain commented on app/walletmediums/dcrwalletrpc/walletfunctions.go
> +			"Please check your balance before retrying.\nError: %s", err.Error())
- A different error message is displayed for this same scenario when using dcrlibwallet, let's harmonize the messages.
- The first line of this error message begins with a small letter, the next line starts with a capital letter

2019-01-09 15:11 UTC, itswisdomagain commented on app/walletmediums/dcrwalletrpc/walletfunctions.go
> +			"Please check your balance before retrying.\nError: %s", err.Error())
I have to add, I like the simplicity of the error message displayed when using dcrlibwallet. When the error message displayed is long, it becomes harder to make sense of the message displayed. The message displayed here has at least 2 sentences before the main error. The main error itself (knowing how verbose dcrwallet rpc can be) is gonna be another long story.

2019-01-09 15:11 UTC, itswisdomagain commented on app/walletmediums/dcrlibwallet/walletfunctions.go
> +		return nil, fmt.Errorf("could not complete ticket(s) purchase, encountered an error: %s", err.Error())
might be better (more readable) to move the actual error message to the next line

2019-01-09 15:11 UTC, itswisdomagain commented on app/walletmediums/dcrwalletrpc/walletfunctions.go
> +				"please check your balance before retrying\nError: %s", err.Error())
- first line of error begins with small letter, next line begins with capital letter
- can this error message be simplified?

2019-01-09 16:58 UTC, itswisdomagain approved these changes

2019-01-09 16:59 UTC, merged