send feature - multiple destination addresses and improved utxo display and selection
raedahgroup/godcr-old pull request #119
Opened 2019-01-03 05:50 UTC by ademuanthony

Added the feature to allow sending to multiple destinations
![001](https://user-images.githubusercontent.com/11990092/50624550-c251f800-0f21-11e9-811e-4d1507f9bcf7.png)
Added a -l flag for the user to control weather or not the output option list should be selected automatically or manually.
If the flag is not provided, the best-sized input is selected automatically, shown to the user and used for the transaction if the user agree to continue
![002](https://user-images.githubusercontent.com/11990092/50624614-4dcb8900-0f22-11e9-82db-22e0b9768665.png)
if the -l flag is provided, the best-sized input is provided as default selection for the user who is provided with the option to either use it or manually select the inputs for the transaction.
The list is sorted by the amount given a tabular display showing receiving address, amount, date and no of confirmations
![003](https://user-images.githubusercontent.com/11990092/50624748-64261480-0f23-11e9-9046-fea68ce3930d.png)
![004](https://user-images.githubusercontent.com/11990092/50624818-df87c600-0f23-11e9-9d4a-6fd7b059f8f1.png)
![005](https://user-images.githubusercontent.com/11990092/50624824-e44c7a00-0f23-11e9-8cf7-472108682e06.png)

2019-01-03 10:41 UTC, itswisdomagain commented
#114 has been updated to no longer include a list flag for the `send-custom` command. 

Instead, after user enters destination addresses and amounts, ask user whether to manually chose inputs for the transaction or not:
```
Would you like to (a)utomatically or (m)anually select inputs? (A/m)
```

If user choses to automatically select inputs, run your best size algorithm to decide what utxos to use as inputs for the transaction. No need to display the automatically selected inputs at this time.

If user choses manual selection, list the utxos and ask user to select the unspent outputs to use as inputs for the new transaction:
```
Select unspent outputs to use as inputs for this transaction (e.g. 1-4,6)
```

Regardless of the user's choice, we should have a list of utxos to use as inputs for this transaction. If the user choses manual selection, it may be appropriate to calculate the total sum selected by the user and confirm that it is not less than the total send amount. If it is less, inform the user and ask the user to make a new selection.

Afterwards, request for the spending password and display a following prompt using the format specified in #115:
```
You are about to spend the input(s)
9.423 DCR from TsgUAq54uZ6GW1VQwgjtgG7KB68pJwy73dJ
and send
2.123 DCR to TsgQwgjtgG7KB68pJwyUAq54uZ6GW1V73dJ
1.123 DCR to TsgJwyUAq54uZ6GWQwgjtgG7KB68p1V83dJ
Do you want to broadcast it? (y/n): y
Sent. Txid b5f844895a4e5b4e496929be0356e8435a8c30976d6bd59a29539fddd37fc9d7
```

2019-01-03 11:22 UTC, itswisdomagain requested changes
Some more things to consider. Will review once more when the desired behaviour is fully actualised.

2019-01-03 11:22 UTC, itswisdomagain commented on cli/commands/helpers.go
> +
space can go

2019-01-03 11:22 UTC, itswisdomagain commented on app/walletcore/types.go
> +	PkScript        []byte
`Address string` instead. Instead of returning the `PkScript` with the `UnspentOutput` object, use it to get the address and return the address with the `UnspentOutput` object

2019-01-03 11:22 UTC, itswisdomagain commented on cli/commands/helpers.go
> +func getSendDestinationAddress(wallet walletcore.Wallet, index int) (string, error) {
Modify this function to return `[]dcrwalletlib.TransactionDirection` instead. Change the function name to `getSendTxDestinations`. The whole process of continuously asking for addresses and amounts until a blank space is encountered should be done here, to keep the send command's `Run` method uncluttered.

2019-01-03 11:22 UTC, itswisdomagain commented on cli/commands/send.go
> +
space can go

2019-01-03 14:09 UTC, ademuanthony commented
![bs-1](https://user-images.githubusercontent.com/11990092/50641836-893d7600-0f69-11e9-8be3-5718c0e93abb.png)
![bs-2](https://user-images.githubusercontent.com/11990092/50641838-893d7600-0f69-11e9-8003-4ed6453dc044.png)
![bs-3](https://user-images.githubusercontent.com/11990092/50641839-893d7600-0f69-11e9-8d54-45aef28536bf.png)
![bs-4](https://user-images.githubusercontent.com/11990092/50641840-89d60c80-0f69-11e9-8743-c00a91ad31a4.png)

2019-01-03 23:20 UTC, itswisdomagain requested changes

2019-01-03 23:20 UTC, itswisdomagain commented on cli/commands/helpers.go
> +			promptMessage := fmt.Sprintf("The address %s has already been added. Do you want to change the amount", destinationAddress)
Should end with a question mark

2019-01-03 23:20 UTC, itswisdomagain commented on cli/commands/helpers.go
> +		if _, addressExists := sendAmounts[destinationAddress]; addressExists {
I absolutely love your use of the variable name `addressExists` here, instead of the regular `ok`

2019-01-03 23:20 UTC, itswisdomagain commented on cli/commands/helpers.go
>  	var err error
You can use `err` and `selectedUtxos` as named returned parameters instead of declaring them here

2019-01-03 23:20 UTC, itswisdomagain commented on cli/commands/helpers.go
> +		options[index] = fmt.Sprintf("%s (%s) \t %s \t %v confirmation(s)", utxo.Address, utxo.Amount.String(), date, txn.Confirmations)
Add `Confirmations` to the `UnspentOutput` type and assign the appropriate value there instead of here. The value will also be needed by other interfaces such as the web and desktop when listing unspent outputs, we want to avoid writing much core code in the different interfaces and abstract as much functionality to the core `wallet` interface and the different mediums implementing the interface

2019-01-03 23:20 UTC, itswisdomagain commented on cli/commands/send.go
> +		return fmt.Errorf("Selected account has low balance. Cannot proceed")
has **insufficient** balance

2019-01-03 23:20 UTC, itswisdomagain commented on cli/commands/send.go
> +			case "":
Can handle all cases here
`case "", "a", "m":`

2019-01-03 23:20 UTC, itswisdomagain commented on cli/commands/send.go
> +		fmt.Println("You are about to spend the input")
input(s), in case they are more than 1

2019-01-03 23:20 UTC, itswisdomagain commented on cli/commands/send.go
> +		fmt.Println("and send it to")
`and send` should be sufficient here, each destination below already says "amount to address"

2019-01-03 23:20 UTC, itswisdomagain commented on cli/commands/send.go
> +			fmt.Println(fmt.Sprintf(" %v DCR to %s", destinatoin.Amount, destinatoin.Address))
You can use `%f` instead of `%v` here for float

2019-01-03 23:20 UTC, itswisdomagain commented on cli/commands/send.go
> +		for _, destinatoin := range sendDestinations {
`destination` 😉

2019-01-03 23:20 UTC, itswisdomagain commented on cli/commands/send.go
>  	sendConfirmed, err := terminalprompt.RequestYesNoConfirmation("Are you sure?", "")
I think the question here should be `Do you want to broadcast it?`

2019-01-03 23:20 UTC, itswisdomagain commented on go.mod
> +	github.com/btcsuite/go-flags v0.0.0-20150116065318-6c288d648c1c
We have another go-flags dependency below `(github.com/jessevdk/go-flags)`, which I believe is what we actually use for this project. Please ensure there is no mix of go-flag dependencies and run `go mod tidy` to remove unused imports from go.mod and go.sum

2019-01-03 23:20 UTC, itswisdomagain commented on .gitignore
> +godcr.conf
`go fmt ./...`

2019-01-03 23:31 UTC, itswisdomagain commented
When I update amount for a previously added destination address, the numbering should not increase
![screenshot 2019-01-04 at 12 29 47 am](https://user-images.githubusercontent.com/18400051/50667079-f8da5200-0fb7-11e9-95c1-1846c941979b.png)

Destination 2 was an update to destination 1, so I should have been asked for Destination address 2 again

2019-01-04 05:15 UTC, ademuanthony commented
![006](https://user-images.githubusercontent.com/11990092/50674599-2808b780-0fe8-11e9-8697-3fe75f9624cf.png)

2019-01-04 05:30 UTC, ademuanthony commented
![007](https://user-images.githubusercontent.com/11990092/50674862-39eb5a00-0fea-11e9-80ba-80d2326cea7e.png)

2019-01-05 18:21 UTC, itswisdomagain requested changes

2019-01-05 18:21 UTC, itswisdomagain commented on app/walletcore/helper.go
> +	return addresses[0].EncodeAddress(), nil
There are cases where a `pkScript` references more than 1 address, haven't seen it before but it exists. Let's not throw other such addresses away, instead let's return all of them. Here's an idea:
```
encodedAddresses := make([]string, len(addresses))
for i, address := range addresses {
     encodedAddresses[i] = address.EncodeAddress()
}

return strings.Join(encodedAddresses, ", ")
```

2019-01-05 18:21 UTC, itswisdomagain commented on app/walletcore/helper.go
> +	return addresses[0].EncodeAddress(), nil
By the way, having this shared code here is really nice. The current direction for godcr is to have shared codes kept in [the WIP branch of dcrlibwallet](https://github.com/raedahgroup/dcrlibwallet/tree/dcrlibwallet-wip) so that such functions are accessible from `godcr`, `dcrandroid` and `dcrios` (all those wallet apps connect to `dcrlibwallet`)

Will move this function over there later, no need to have the PR stalled for that reason. I'll provide more information soon on when and how to put shared codes in `dcrlibwallet` subsequently.

2019-01-05 18:21 UTC, itswisdomagain commented on cli/commands/helpers.go
> +	var destinationAddresses []string
This is not important, I see its real use is in line 125. See the comment there for an alternative that uses `sendAmounts` only instead of `destinationAddresses`

2019-01-05 18:21 UTC, itswisdomagain commented on cli/commands/helpers.go
> +	for _, address := range destinationAddresses {
```
for address, amount := range sendAmounts {
     destinations = append(destinations, txhelper.TransactionDestination{Address: address, Amount: amount})
}
```

2019-01-05 18:21 UTC, itswisdomagain commented on cli/commands/helpers.go
> +func getUtxosForNewTransaction(wallet walletcore.Wallet, utxos []*walletcore.UnspentOutput, sendAmount float64) (selectedUtxos []*walletcore.UnspentOutput, err error) {
`wallet walletcore.Wallet` is not used

2019-01-05 18:21 UTC, itswisdomagain commented on cli/commands/helpers.go
> +		options[index] = fmt.Sprintf("%s (%s) \t %s \t %v confirmation(s)", utxo.Address, utxo.Amount.String(), date, utxo.Confirmations)
`%d` instead of `%v` for int

2019-01-05 18:21 UTC, itswisdomagain commented on cli/commands/send.go
> +				fmt.Println(fmt.Sprintf(" %v DCR to %s", destination.Amount, destination.Address))
`%f` instead of `%v`

2019-01-05 18:21 UTC, itswisdomagain commented on cli/commands/send.go
> +		for _, output := range utxoSelection {
`utxo` instead of `output`

2019-01-05 18:21 UTC, itswisdomagain commented on cli/commands/send.go
> +		for _, utox := range utxoSelection {
`utxo`

2019-01-05 18:21 UTC, itswisdomagain commented on go.sum
> +github.com/aarzilli/nucular v0.0.0-20181227101716-d1a942545d6d h1:F486Q0BO+uFwzGSCfNkuQYr86h0Oap7zYdimuCyr0/0=
I can't build your code as is, without deleting go.sum before building:
```
go: verifying github.com/aarzilli/nucular@v0.0.0-20181227101716-d1a942545d6d: checksum mismatch
        downloaded: h1:BLhrKkQNOBeRDRJdevy7tE7ca2+sp3daQ6xG7vagEzg=
        go.sum:     h1:F486Q0BO+uFwzGSCfNkuQYr86h0Oap7zYdimuCyr0/0=
```

The checksum currently on master `(BLhrKkQNOBeRDRJdevy7tE7ca2+sp3daQ6xG7vagEzg=)` was built with go 1.11.4. Are you using same version? Remember to delete go.sum and perhaps clear mod cache at least once after updating to go 1.11.4 before building. Also run `go mod tidy`

We can't merge this in until this is fixed as it will not build on machines running go 1.11.4 which is the go version now used for this project

2019-01-05 18:28 UTC, itswisdomagain commented
Some anomalies to note and correct

- **Inputs or outputs**
See the screenshot below. The prompt asks: `Would you like to (a)utomatically or (m)anually select **inputs**?`, then says `Select unspent **outputs**`. Also, invalid selection message reads: ` Total amount from selected **outputs** is smaller than amount to send`
![screenshot 2019-01-05 at 7 03 37 pm](https://user-images.githubusercontent.com/18400051/50727731-51782f00-111f-11e9-82ea-c67991a32285.png)

- **utxo confirmation message**
I have 3 available utxos and I select all 3. Confirmation message says I selected 6 utxos, no idea where the rest came from...
![screenshot 2019-01-05 at 7 10 15 pm](https://user-images.githubusercontent.com/18400051/50727732-550bb600-111f-11e9-9651-20938ce3d619.png)

2019-01-05 22:15 UTC, itswisdomagain requested changes

2019-01-05 22:15 UTC, itswisdomagain commented on cli/commands/helpers.go
> +			selectedUtxos = append(selectedUtxos, utxo)
Clear `selectedUtxos` every time this validate function runs before appending to `selectedUtxos`, to prevent repeated utxos. See https://github.com/raedahgroup/godcr/pull/119#issuecomment-451679344 for an example of the repeated utxos issue.

2019-01-05 23:52 UTC, itswisdomagain commented
Everything looks good, just this https://github.com/raedahgroup/godcr/pull/119#issuecomment-451311595 I thought was resolved, still there.

![screenshot 2019-01-06 at 12 47 54 am](https://user-images.githubusercontent.com/18400051/50730406-476d2500-114d-11e9-94db-46efd7037615.png)

2019-01-06 18:11 UTC, itswisdomagain approved these changes

2019-01-06 18:13 UTC, merged