implimented the webui transaction details page
raedahgroup/godcr-old pull request #122
Opened 2019-01-03 16:31 UTC by Sirmorrison

2019-01-03 17:24 UTC, barisere requested changes

2019-01-03 17:24 UTC, barisere commented on .gitignore
> +seed
What's seed? Is it a file that we all need to ignore?

2019-01-03 17:24 UTC, barisere commented on web/routes/handlers.go
> +func (routes *Routes) transaction_detailsPage(res http.ResponseWriter, req *http.Request) {
`transaction_detailsPage` should be camel-cased, in Go style.

2019-01-03 17:24 UTC, barisere commented on web/routes/handlers.go
> +	hash := chi.URLParam(req, "Hash")
The URL parameter should be lowercased. Title-cased URL parameters are ugly.

2019-01-03 17:24 UTC, barisere commented on web/routes/routes.go
> +	router.Get("/transaction_details/{Hash}", routes.transaction_detailsPage)
Hash => hash

2019-01-03 17:26 UTC, Sirmorrison commented on .gitignore
> +seed
yes

2019-01-03 19:06 UTC, barisere commented on .gitignore
> +godcr.exe
Instead of changing that line, add a new line. On Linux and Mac the app builds to a binary named "godcr".

2019-01-03 19:11 UTC, raedah commented
This looks good. Needs a navigation bar though so the user can see the title of where they are in the app and be able to go back to the previous screen.

2019-01-04 00:53 UTC, itswisdomagain commented on .gitignore
> +seed
How did that file get on your project directory? Haven't seen it before...

2019-01-04 00:54 UTC, itswisdomagain commented on web/routes/handlers.go
> +func (routes *Routes) transaction_detailsPage(res http.ResponseWriter, req *http.Request) {
`transactionDetailsPage` actually

2019-01-04 00:56 UTC, itswisdomagain commented on web/routes/routes.go
> +	router.Get("/transaction_details/{Hash}", routes.transaction_detailsPage)
I also think "/transaction/{hash}" is a better-named path

2019-01-04 01:05 UTC, itswisdomagain requested changes

2019-01-04 01:05 UTC, itswisdomagain commented on .gitignore
> +seed
How did that file get on your project directory? Haven't seen it before...

2019-01-04 01:05 UTC, itswisdomagain commented on web/routes/handlers.go
> +		routes.renderError(fmt.Sprintln("Error fetching Transaction: %s", err.Error()), res)
`fmt.Sprintf`

2019-01-04 01:05 UTC, itswisdomagain commented on web/routes/handlers.go
> +		routes.renderError(fmt.Sprintln("Error fetching Transaction: %s", err.Error()), res)
"Error fetching transaction:"

2019-01-04 01:05 UTC, itswisdomagain commented on web/routes/handlers.go
> +	txns, err := routes.walletMiddleware.GetTransaction(hash)
It's a single transaction this method returns, not multiple
This should be `tx`

2019-01-04 01:05 UTC, itswisdomagain commented on web/routes/handlers.go
> +		"result": txns,
A better variable name here to add meaning where it is used in `transaction_details.html` is `tx` instead of `result`. What is `result`?

2019-01-04 01:05 UTC, itswisdomagain commented on web/views/transaction_details.html
> +                                  <td>{{ .result.Transaction.Hash }}</td>
You should be able to use `.result.Hash` directly here, `Transaction` is an embedded type. Same goes for all other similar usages in this file

2019-01-04 01:05 UTC, itswisdomagain commented on web/views/transaction_details.html
> +                              <td>{{ .result.Transaction.Timestamp }}</td>
This isn't needed. We're building a page for regular humans not people like you and me that will quite easily recognise and understand a timestamp when we see one. Formatted time below is sufficient

2019-01-04 17:37 UTC, itswisdomagain requested changes
There's a binary file in this PR, we can't merge it in. I see the file was introduced in this commit `58a89da66a579adfbd970c034561d88eb13d8661`. Simply deleting the file and committing won't completely work as the file will remain on this repo's git history and cause the repo size to be unnecessarily bigger.

Here's one way to remove it cleanly:
- On your PR branch, do a soft reset (your files will be intact, but your commit history will be rolled back)
`git reset 58a89da66a579adfbd970c034561d88eb13d8661`
- Delete the binary file (godcr.exe)
- Commit and force push with `git push -f`

This will delete some of your commits history but the alternative approach I know (`git filter-branch`) may do worse. The last time I tried it, it was a nightmare

2019-01-04 17:37 UTC, itswisdomagain commented on .gitignore
> +godcr.conf
`go fmt ./...` should restore the end of file line

2019-01-06 20:19 UTC, itswisdomagain requested changes

2019-01-06 20:19 UTC, itswisdomagain commented on .gitignore
> -godcr.conf
Please bring this back

2019-01-06 20:19 UTC, itswisdomagain commented on web/views/transaction_details.html
> +                              <td>{{ .tx.Size }}</td>
Include the units (bytes) e.g. `1024 bytes`

2019-01-06 20:19 UTC, itswisdomagain commented on web/views/transaction_details.html
> +                              <td>{{ .tx.FeeRate }}</td>
Unit for fee rate is DCR/KB, you'd need to append `/KB` here

2019-01-06 20:19 UTC, itswisdomagain commented on web/views/transaction_details.html
> +                                <th>Amount In</th>
No need to display `Previous Transaction Hash` and `Previous Transaction Index`. `Amount In` should be `Value`

2019-01-06 20:19 UTC, itswisdomagain commented on web/views/transaction_details.html
> +                                <th>Index</th>
Not necessary

2019-01-06 20:19 UTC, itswisdomagain commented on web/views/transaction_details.html
> +                                <th>Version</th>
Not necessary

2019-01-06 20:19 UTC, itswisdomagain commented on web/views/transaction_details.html
> +                                <th>ScriptType</th>
Just `Type`

2019-01-06 20:19 UTC, itswisdomagain commented on web/views/transaction_details.html
> +                                <th>Addresses</th>
`Address`

2019-01-06 20:19 UTC, itswisdomagain commented on web/views/transaction_details.html
> +                        <li class="breadcrumb-item active" aria-current="page">Transation Details</li>
*Transaction Details* typo

2019-01-06 20:19 UTC, itswisdomagain commented on web/views/transaction_details.html
> +                                <td>{{ .AmountIn }}</td>
`.AmountIn` is a number of type `int64`, this should be an amount value in DCR. To perform the conversion from int64 to dcr amount here, you'd need to create a template function in `web/routes/templates.go` and call it here.

**Create the template function**
In `web/routes/templates.go`, add the following function to the template funcmap:
```
"amountDcr": func(amount int64) string {
	return dcrutil.Amount(amount).String()
},
```

To call this function, replace `{{ .AmountIn }}` with `{{ amountDcr .Value }}`

2019-01-06 20:19 UTC, itswisdomagain commented on web/views/transaction_details.html
> +                                <td>{{ .AmountIn }}</td>
This comment also applies to how amount is displayed in the **Outputs** section

2019-01-06 20:19 UTC, itswisdomagain commented on web/views/transaction_details.html
> +                                <td>{{ .Value }}</td>
See the comment above on how to display this value as a dcr amount

2019-01-06 20:19 UTC, itswisdomagain commented on web/views/transaction_details.html
> +                                <td>{{ .Internal }}</td>
Remove this please. This value is never set, it shouldn't even exist anymore.

2019-01-06 20:19 UTC, itswisdomagain commented on web/views/transaction_details.html
> +                                <td>{{ .Addresses }}</td>
Did you test this? How did "Addresses" display?
- `.Addresses` is an "array"
- Each address in the array is not a simple address string, it's an object

This should produce a better display:
```
<thead>
<tr>
    <th>Address</th>
    <th>Account</th>
    <th>Value</th>
    <th>Type</th>
</tr>
</thead>
<tbody>
{{ range $txn := .tx.Outputs }}
<tr>
    {{ range .Addresses }}
    <td>{{ .Address }}</td>
    <td>{{ if .IsMine }}{{ .AccountName }}{{ else }}external address{{ end }}</td>
    <td>{{ amountDcr $txn.Value }}</td>
    <td>{{ $txn.ScriptType }}</td>
    {{ end }}
</tr>
{{ end }}
</tbody>
```

2019-01-07 13:33 UTC, itswisdomagain requested changes
Aside from the adjustments required below, also give attention to the anomaly depicted in this screenshot. The right section is too small in width, notice how the outputs table overflows outside of the container.

![screenshot 2019-01-07 at 2 19 15 pm](https://user-images.githubusercontent.com/18400051/50770902-2f022500-1289-11e9-952d-e9520ead0870.png)

2019-01-07 13:33 UTC, itswisdomagain commented on web/views/transaction_details.html
> +                            <td>{{ .tx.Size }}<span>Bytes</span></td>
There should be space between the size and the unit

2019-01-07 13:33 UTC, itswisdomagain commented on web/views/transaction_details.html
> +                            <td>{{ .tx.Fee }} <span>/KB</span></td>
The per kb unit is for **FEE RATE**, not **fee**, please check the previous review and aim for thoroughness going forward.

2019-01-07 13:33 UTC, itswisdomagain commented on web/views/transaction_details.html
> +                            <td>{{ .tx.Fee }} <span>/KB</span></td>
Also there should be no space in `DCR /KB`, should be `DCR/KB`

2019-01-07 13:33 UTC, itswisdomagain commented on web/views/transaction_details.html
> +                        </tr>
This is not how the outputs table should display. Please re-read the previous review comment (https://github.com/raedahgroup/godcr/pull/122#discussion_r245520861)

2019-01-07 15:54 UTC, itswisdomagain requested changes

2019-01-07 15:54 UTC, itswisdomagain commented on web/views/transaction_details.html
> +                            <td>{{ .tx.FeeRate }} <span>/KB</span></td>
There's still space here, the unit should not have space

2019-01-07 15:54 UTC, itswisdomagain commented on web/views/transaction_details.html
> +
This space is unnecessary. Also the table columns are not arranged as requested
![screenshot 2019-01-07 at 4 49 05 pm](https://user-images.githubusercontent.com/18400051/50777545-341c9f80-129c-11e9-8ffb-056f492e9026.png)

2019-01-07 15:54 UTC, itswisdomagain commented on web/views/transaction_details.html
> +
Also, does this output look okay to you?
![screenshot 2019-01-07 at 4 53 20 pm](https://user-images.githubusercontent.com/18400051/50777781-cde44c80-129c-11e9-82a6-e32b906e89ea.png)

2019-01-07 18:08 UTC, itswisdomagain approved these changes

2019-01-07 18:15 UTC, itswisdomagain requested changes
Noticed this anomaly with the latest set of changes, see the inputs table colliding with the outputs table:

![screenshot 2019-01-07 at 7 14 20 pm](https://user-images.githubusercontent.com/18400051/50785317-88317f00-12b0-11e9-8b5d-d20ad639b53a.png)

2019-01-08 08:11 UTC, itswisdomagain approved these changes

2019-01-08 12:26 UTC, barisere approved these changes

2019-01-08 12:42 UTC, merged