[WIP] Multi change out
raedahgroup/godcr-old pull request #123
Opened 2019-01-04 09:21 UTC by ademuanthony

Resolves [Issue](https://github.com/raedahgroup/godcr/issues/115)

2019-01-05 19:24 UTC, itswisdomagain requested changes
The `send` function is a mess, please let's simplify it. The code for generating change addresses as user manually enters amounts progressively can be improved, even if it means creating or modifying core wallet functions.

I haven't tested this PR yet, will test after these changes are made. The code might work now but after simplifying the `send` function, a re-test would definitely be needed, so will just wait till then.

Also, this https://github.com/raedahgroup/godcr/pull/119#discussion_r245484660 affects this PR as well.

2019-01-05 19:24 UTC, itswisdomagain commented on cli/commands/helpers.go
> +	var err error
Use named variables for instances like this

2019-01-05 19:24 UTC, itswisdomagain commented on cli/commands/helpers.go
> +	// todo dcrwallet should define this as typed errors
As discussed, this can go

2019-01-05 19:24 UTC, itswisdomagain commented on cli/commands/helpers.go
> +			input = "1"
you can just assign `number = 1` and `return nil` here, no need to proceed to parse "1" and see if an error will occur

2019-01-05 19:24 UTC, itswisdomagain commented on cli/commands/helpers.go
> +	return int(number), nil
`number` and `err` are assigned in line 130, once you make them named return parameters, you can just do `return` here

2019-01-05 19:24 UTC, itswisdomagain commented on cli/commands/helpers.go
> +	var err error
named parameters

2019-01-05 19:24 UTC, itswisdomagain commented on cli/commands/helpers.go
> +			input = "0"
just assign `amount = 0` here and `return nil`

2019-01-05 19:24 UTC, itswisdomagain commented on cli/commands/helpers.go
> +	return amount, nil
can just `return` here after using named return parameters

2019-01-05 19:24 UTC, itswisdomagain commented on cli/commands/helpers.go
> +// getSendAmount fetches the amount of DCRs to send from the user.
`// getChangeAmount...`

2019-01-05 19:24 UTC, itswisdomagain commented on cli/commands/helpers.go
> +	fmt.Println(fmt.Sprintf("Enter the amount to be sent to each change address. The sum of all the amounts should not be more than %f", changeAmountInDcr))
`fmt.Printf("Enter the amount to be sent to each change address. The sum of all the amounts should not be more than %f DCR\n", changeAmountInDcr)
`

2019-01-05 19:24 UTC, itswisdomagain commented on cli/commands/helpers.go
>  	var err error
named variables

2019-01-05 19:24 UTC, itswisdomagain commented on cli/commands/send.go
> +	useRandomNo, err := terminalprompt.RequestYesNoConfirmation("Use random amounts for the change outputs?", "y")
`useRandomNo` sounds like use random? no
`useRandomChangeAmounts` is better

2019-01-05 19:24 UTC, itswisdomagain commented on cli/commands/send.go
> +			allDestination := append(sendDestinations, changeOutputDestinations...)
`changeOutputDestinations` is an empty slice at this point, this operation does nothing, what are you trying to achieve?

2019-01-05 19:24 UTC, itswisdomagain commented on cli/commands/send.go
> +			changeAddress, err := wallet.GenerateReceiveAddress(sourceAccount)
Line 126 above generated a change address that was discarded, don't generate another one here, use that address instead

2019-01-05 19:24 UTC, itswisdomagain commented on cli/commands/send.go
> +			_, remainingChange, err := wallet.GenerateChangeAddresses(sourceAccount, 1, len(utxoSelection),
The generated address here should be used in the next cycle, just as `remainingChange` is stored in `lastChangeAmountInDcr` for use in the next cycle

2019-01-05 19:24 UTC, itswisdomagain commented on cli/commands/send.go
> +	if useRandomNo {
This whole `send` function has grown too big. Split into smaller functions. The if and else case here can be made into separate functions; perhaps other parts of this function can be split out too.

2019-01-06 06:14 UTC, ademuanthony commented on cli/commands/send.go
> +			allDestination := append(sendDestinations, changeOutputDestinations...)
in this loop, at first run, `changeOutputDestinations` will be empty but a `changeDestination` will be added to it at every successful run. This list we are building, the sendDestination and the `changeDestination` we want to check and see if it can be added to our `changeOutputDestinations` makes up `allDestination` that we are sending to the `wallet.GenerateChangeAddresses` to get the estimated `remainingChange`

2019-01-07 15:22 UTC, itswisdomagain requested changes
This is great improvement. Some more code adjustments below.

Also, please modify `getSendTxDestinations` in `cli/commands/helpers.go` to also return `sendAmountTotal` and eliminate the loop performed in line 54 of `cli/commands/send.go`

2019-01-07 15:22 UTC, itswisdomagain commented on cli/commands/helpers.go
> +func getNChangeOutput() (number int, err error) {
This function is only called in `getChangeDestinationsWithRandomAmounts`. That function is not very big, the code here can go there for simplicity.

2019-01-07 15:22 UTC, itswisdomagain commented on cli/commands/helpers.go
> +func getNChangeOutput() (number int, err error) {
Alternatively, preferably, we can have a `RequestNumberInput` function in the `terminalprompt ` package that performs the number validation done here and returns the valid number entered by a user

2019-01-07 15:22 UTC, itswisdomagain commented on cli/commands/helpers.go
> +func getChangeAmount(prompt string) (amount float64, err error) {
This `getChangeAmount` function is called by `getChangeDestinationsFromUser`. Please move it to below the `getChangeDestinationsFromUser` function for easier code scanning. Functions should appear in the order they are called.

`getChangeOutputDestinations` is called by `send.go`, which then calls `getChangeDestinationsWithRandomAmounts` or `getChangeDestinationsFromUser` in that order. When scanning, I expect to see those functions in the following order:
- `getChangeOutputDestinations`
- `getChangeDestinationsWithRandomAmounts`
- `getChangeDestinationsFromUser`
- `getChangeAmount`

Also note that `getChangeDestinationsWithRandomAmounts` and `getChangeDestinationsFromUser` would need re-placement to conform to the order described above.

Ordered placement of functions allow for easier code scanning.

2019-01-07 15:22 UTC, itswisdomagain commented on cli/commands/helpers.go
> +// getChangeDestinationsFromUser fetches change destination from the user
`// getChangeDestinationsFromUser fetches change destination from the user progressively until the total available change amount is covered`

2019-01-07 15:22 UTC, itswisdomagain commented on cli/commands/helpers.go
> +func getChangeDestinationsFromUser(wallet walletcore.Wallet, amountInAtom int64, sourceAccount uint32, nUtxoSelection int, sendDestinations []txhelper.TransactionDestination) (changeOutputDestination
Since `err` is shadowed in the loop below, this function can survive without named parameters. You'll only need to declare `var changeOutputDestinations []txhelper.TransactionDestination` below

2019-01-07 15:22 UTC, itswisdomagain commented on cli/commands/helpers.go
> +		if err != nil {
Reject negative amounts and cases where user enters "0" as amount. `amount` must be greater than 0 here. Only treat amount as 0 if user enters "" (which is already done above)

I'm thinking, respond with invalid amount if `err != nil || amount <= 0`

2019-01-07 15:22 UTC, itswisdomagain commented on cli/commands/helpers.go
> +		err = fmt.Errorf("error reading your response: %s", err.Error())
If you don't use named variables, you can just return the error directly here

2019-01-07 15:22 UTC, itswisdomagain commented on cli/commands/helpers.go
> +		changeOutputDestinations, err = getChangeDestinationsWithRandomAmounts(wallet, amountInAtom, sourceAccount,
If you don't use named variables, you can just return the result of calling this function directly instead of assigning:
`return getChangeDestinationsWithRandomAmounts(wallet, amountInAtom, sourceAccount, nUtxoSelection, sendDestinations)`

2019-01-07 15:22 UTC, itswisdomagain commented on cli/commands/helpers.go
> +			fmt.Println(fmt.Sprintf("Error: %s. Try again with a smaller amount", errMsgInputNotEnoughForTxn))
A more correct error message would be `fmt.Sprintf("Invalid amount. Enter an amount less than %f", dcrutil.Amount(defaultAmount).ToCoin())`

2019-01-07 15:22 UTC, itswisdomagain commented on cli/commands/helpers.go
> +		defaultAmount := totalChangeAmount - amountAssigned
`defaultAmount` is always converted to float64 everywhere it's used, could just make the value a float64 value directly here instead:

`defaultAmount := dcrutil.Amount(totalChangeAmount - amountAssigned).ToCoin()`

2019-01-07 15:22 UTC, itswisdomagain commented on cli/commands/helpers.go
> +			fmt.Println(fmt.Sprintf("Error: %s. Try again with a smaller amount", errMsgInputNotEnoughForTxn))
This change would mean both `errMsgInputNotEnoughForTxn` and `errMsgInputNotEnoughForFee` constants defined above will no longer be used and can be deleted

2019-01-07 15:22 UTC, itswisdomagain commented on cli/commands/helpers.go
> +	for i, address := range changeAddresses {
This last loop can be merged with the previous. Here's something I played with:
```
for i, portion := range portionRations {
	portionPercentage := portion / rationSum
	amount := portionPercentage * float64(changeAmount)

	changeOutput := txhelper.TransactionDestination{
		Address: changeAddresses[i],
		Amount: dcrutil.Amount(amount).ToCoin(),
	}
	changeOutputDestinations = append(changeOutputDestinations, changeOutput)
}
```

2019-01-07 15:22 UTC, itswisdomagain commented on cli/commands/send.go
>  	if custom {
Let's split this point onwards into 2 functions `completeCustomSend` and `completeNormalSend` to avoid the  multiple `if custom` blocks that make this function a harder to read. Both `completeCustomSend` and `completeNormalSend` should return `hash string, err error`

The ending part of this function should then look like this:
```
var sentTxHash string
if custom {
      sentTxHash, err = completeCustomSend(....)
} else {
      sentTxHash, err = completeNormalSend(....)
}

if err != nil {
	return err
}

fmt.Println("Sent txid", sentTxHash)
return nil
```

2019-01-07 15:22 UTC, itswisdomagain commented on cli/commands/send.go
> +			utxoSelection, totalInputAmount, err = getUtxosForNewTransaction(utxos, sendAmountTotal)
any `err` returned is not handled

2019-01-07 15:22 UTC, itswisdomagain commented on cli/commands/send.go
>  			fmt.Println(fmt.Sprintf(" %f DCR to %s", destination.Amount, destination.Address))
tabs would help here to achieve cleaner message display here:
` %f DCR \t to %s`

2019-01-07 15:22 UTC, itswisdomagain commented on cli/commands/send.go
> +			fmt.Println(fmt.Sprintf(" %f DCR to %s(change)", destination.Amount, destination.Address))
there should be a single space between the address and `(change)`

2019-01-07 15:22 UTC, itswisdomagain commented on cli/commands/send.go
>  			fmt.Println(fmt.Sprintf(" %f DCR to %s", destination.Amount, destination.Address))
do same when printing the selected utxos

2019-01-07 18:06 UTC, itswisdomagain requested changes
Some more changes. Also, I marked some comments from the previous review as resolved. Look at the other ones that I have not marked resolved, you didn't attend to them

2019-01-07 18:06 UTC, itswisdomagain commented on cli/termio/terminalprompt/terminalprompt.go
> +// RequestNumberInput uses RequestInput requests numeric input from the user.
`// RequestNumberInput uses RequestInput **to** request numeric input from the user.`

2019-01-07 18:06 UTC, itswisdomagain commented on cli/commands/helpers.go
> +	errMsgInputNotEnoughForFee = "total input amount not enough to cover transaction fee"
These constants are not necessary, the second one is never used and the first was wrongly used, it actually shouldn't be used either.

2019-01-07 18:06 UTC, itswisdomagain commented on cli/commands/helpers.go
> +		sendAmountTotal += sendAmount
This should be done in the loop in line 130 to prevent the possibility of incorrect sum in the event an address is entered multiple times and the amount updated. Line 130 is where the final map of addresses and amounts collected from the users is processed.

2019-01-07 18:06 UTC, itswisdomagain commented on cli/commands/helpers.go
> +	nUtxoSelection int, sendDestinations []txhelper.TransactionDestination) (changeOutputDestinations []txhelper.TransactionDestination, err error) {
No need to use named parameters, see [this unresolved comment on line 213 of helpers.go](https://github.com/raedahgroup/godcr/pull/123#discussion_r245670635) and [this other one on line 233 of same file](https://github.com/raedahgroup/godcr/pull/123/files#r245670953)

2019-01-07 18:06 UTC, itswisdomagain commented on cli/commands/helpers.go
> +	nUtxoSelection int, sendDestinations []txhelper.TransactionDestination) (changeOutputDestinations []txhelper.TransactionDestination, err error) {
Add an empty line below this line to separate where the function signature ends and where the body begins.

2019-01-07 18:06 UTC, itswisdomagain commented on cli/commands/helpers.go
> +	var portions []float64
Unused variable

2019-01-07 18:06 UTC, itswisdomagain commented on cli/commands/helpers.go
> +			// we cannot just use return here as the named varaible `err` has been shadowed in line 207 above
Comment no longer necessary

2019-01-07 18:06 UTC, itswisdomagain commented on cli/commands/send.go
> +	sentTransactionHash, err = wallet.SendFromUTXOs(sourceAccount, outputKeys, sendDestinations, changeOutputDestinations, passphrase)
You can just return `wallet.SendFromUTXOs(...)` directly, no need to check if there was an error, the calling function does that check

2019-01-07 18:06 UTC, itswisdomagain commented on cli/commands/send.go
> +			fmt.Println(fmt.Sprintf(" %f DCR to %s", destination.Amount, destination.Address))
tabs here as well

2019-01-07 18:06 UTC, itswisdomagain commented on cli/commands/send.go
> +	sentTransactionHash, err = wallet.SendFromAccount(sourceAccount, sendDestinations, passphrase)
`return wallet.SendFromAccount(...)` directly

2019-01-08 00:31 UTC, ademuanthony commented
![change-ouptut](https://user-images.githubusercontent.com/11990092/50801455-250e0f80-12e5-11e9-9e3a-19f1b69d0483.png)

2019-01-08 08:10 UTC, itswisdomagain approved these changes

2019-01-08 08:19 UTC, merged