auto detecting rpc address
raedahgroup/godcr-old pull request #156
Opened 2019-01-11 14:27 UTC by ademuanthony

Resolves [Issue 152](https://github.com/raedahgroup/godcr/issues/152)

Added the ability to detect dcrwallet RPC address from a dcrwallet running process, the default wallet addresses and/or the dcrwallet config file.

The user is asked to enter the address manually if all these options fail. The captured address will be added to the config file for subsequent use
![auto-detect-address](https://user-images.githubusercontent.com/11990092/51096528-555e1e00-17bd-11e9-94a5-cd3f3aaeaf9d.png)

2019-01-11 16:28 UTC, itswisdomagain requested changes

2019-01-11 16:28 UTC, itswisdomagain commented on cli/termio/terminalprompt/terminalprompt.go
> +var RequiredValidator = func(v string) error {
`InputRequiredValidator`

2019-01-11 16:28 UTC, itswisdomagain commented on main.go
> +	if _config.WalletRPCServer == "" {
Move this whole op to `app/walletmediums/dcrwalletrpc`, it's specific to that medium

2019-01-11 16:28 UTC, itswisdomagain commented on app/address.go
> +package app
This file should be in `app/walletmediums/dcrwalletrpc`, it contains code specific to that medium

2019-01-11 16:28 UTC, itswisdomagain commented on app/config/config.go
> +func SaveRpcAddress(address string) error {
This can be made more generic, I'm thinking a function that can accept any form of update to config file: `UpdateConfigFile(option string, newValue interface{})`

2019-01-11 16:28 UTC, itswisdomagain commented on main.go
> +func connectToWallet(ctx context.Context, _config config.Config) app.WalletMiddleware {
maybe `cfg` instead of `_config` or `appConfig` as used in some other parts of this file or `parsedConfig` to signify that it has been parsed and values set for it's various fields

2019-01-18 09:17 UTC, itswisdomagain requested changes

2019-01-18 09:17 UTC, itswisdomagain commented on app/walletmediums/dcrwalletrpc/address.go
> +type walletConfig struct {
Several fields in this struct can be done without, retaining just what is needed: `GRPCListeners`, `DisableServerTLS` and `RPCCert`

2019-01-18 09:17 UTC, itswisdomagain commented on app/walletmediums/dcrwalletrpc/address.go
> +	return wConfig.LegacyRPCListeners, wConfig.DisableServerTLS, rpcCert, nil
`wConfig.GRPCListeners` instead of `wConfig.LegacyRPCListeners`
LegacyRPCListeners are for JSON-RPC connections, which godcr does not support (yet, maybe never will).

2019-01-18 09:17 UTC, itswisdomagain commented on app/walletmediums/dcrwalletrpc/dcrwalletrpc.go
> +	promt := "No valid RPC address is provided to connect to. Press 'Y' to automatically detect or 'N' to manually enter the address?"
- typo: _prompt_
- `No RPC address provided to connect to dcrwallet` (No valid address means address was provided but it is not valid)
- this should be the first op in this method, before even parsing the dcrwallet config file

2019-01-18 09:17 UTC, itswisdomagain commented on app/walletmediums/dcrwalletrpc/address.go
> +		if _, ok := err.(*os.PathError); !ok {
simply `return`, we don't need details of what went wrong, we simply need to know if this parsing operation was a success or not

2019-01-18 09:17 UTC, itswisdomagain commented on app/walletmediums/dcrwalletrpc/dcrwalletrpc.go
> +	rpcConfAddresses, wnoTLS, wrpcCert, err := walletAddressFromDcrdwalletConfig()
you're not using `err`, you should check that `err == nil` before overriding values for `rpcCert` and `noTLS`

2019-01-18 09:17 UTC, itswisdomagain commented on app/walletmediums/dcrwalletrpc/dcrwalletrpc.go
> +			fmt.Println("rpc address saved")
Only display a message if saving the address fails

2019-01-18 09:17 UTC, itswisdomagain commented on app/walletmediums/dcrwalletrpc/dcrwalletrpc.go
> +		address, err := terminalprompt.RequestInput("Enter dcrwallet rpc address", terminalprompt.InputRequiredValidator)
Move line 125 to 136 to a different function, say `requestRPCAddressFromUser`

2019-01-18 09:17 UTC, itswisdomagain commented on app/walletmediums/dcrwalletrpc/dcrwalletrpc.go
> +	for {
This `for` is unnecessary, the code here never loops, only runs once

2019-01-18 09:17 UTC, itswisdomagain commented on app/walletmediums/dcrwalletrpc/dcrwalletrpc.go
> +				fmt.Println("error occured while trying to get port by process: %s", err.Error())
any need? we should swallow all errors, no need to provide details of what went wrong to the user
if at the end of the day, an address could not be detected, we just say address not detected

2019-01-18 09:17 UTC, itswisdomagain commented on app/walletmediums/dcrwalletrpc/dcrwalletrpc.go
> +		var address string
No real use for creating a general variable for address. It's usage is limited to different scopes below, never used aside those scopes. Declare, assign and use where needed for simplicity.

2019-01-18 09:17 UTC, itswisdomagain commented on app/walletmediums/dcrwalletrpc/dcrwalletrpc.go
> +		proc, err := ps.ProcessByName(dcrwalletExecutableName)
- `dcrwalletProcess` instead of `proc`
- move this line 142 to 159 to separate function, say `detectAddressFromRunningProcess`

2019-01-18 09:17 UTC, itswisdomagain commented on app/walletmediums/dcrwalletrpc/dcrwalletrpc.go
> +		if err == nil && len(rpcConfAddresses) > 0 {
No need to check if `err == nil`, `err` here is gotten from line 142 above where `proc, err := ps.ProcessByName(dcrwalletExecutableName)`

Getting the process may return an error, but doesn't mean we should not attempt to connect to addresses found in config file

2019-01-18 09:17 UTC, itswisdomagain commented on app/walletmediums/dcrwalletrpc/dcrwalletrpc.go
> +		if err == nil && len(rpcConfAddresses) > 0 {
Also move this line 161 to line 169 to a different function, say `useParsedConfigAddresses`

2019-01-18 09:17 UTC, itswisdomagain commented on app/walletmediums/dcrwalletrpc/dcrwalletrpc.go
> +		// try connecting with default testnet3 params
move line 171 - 185 to a different function, say `connectToDefaultAddresses` and only call that function if the process of getting ports from running process fails.

If there is no running process or process was found and ports were retrieved, don't see a point in trying the default addresses.

2019-01-18 09:17 UTC, itswisdomagain commented on app/walletmediums/dcrwalletrpc/dcrwalletrpc.go
> +			return New(ctx, address, rpcCert, noTLS)
No need to call `New` again, simply return the `walletMiddleware, err` gotten from the last call in line 199

2019-01-18 09:17 UTC, itswisdomagain commented on app/walletmediums/dcrwalletrpc/dcrwalletrpc.go
> +			address, err := terminalprompt.RequestInput("Enter dcrwallet rpc address", terminalprompt.InputRequiredValidator)
Seeing some repeated code here, similar code exists in line 125 to 136, which should be moved to a function and possibly called here

2019-01-18 09:17 UTC, itswisdomagain commented on app/walletmediums/dcrwalletrpc/dcrwalletrpc.go
> +		promt := "Do you want to set the address now?"
It's important to check after each connection attempt if `ctx.Err() != nil`, because a user could hit ctrl+c to terminate the app while the detection process is ongoing.

I noticed a scenario where hitting ctrl+c halted the program but I still got this prompt, which shouldn't be.

2019-01-18 09:17 UTC, itswisdomagain commented on app/walletmediums/dcrwalletrpc/dcrwalletrpc.go
> +		address, err := terminalprompt.RequestInput("Enter dcrwallet rpc address", terminalprompt.InputRequiredValidator)
Also, do not make input compulsory, allow user to enter empty string and then quit the app.
Currently, if I don't set rpc address, I'm asked if to detect or set address. What if I don't want to do either? I have to hit ctrl+c. If we allow empty input, user could say enter address and enter nothing to quit.

2019-01-18 09:42 UTC, ademuanthony commented on app/walletmediums/dcrwalletrpc/address.go
> +type walletConfig struct {
I added ```TBOpts ticketBuyerOptions 'group:"Ticket Buyer Options" namespace:"ticketbuyer"'``` because of the `group`, the parser is throwing if it's not present.

2019-01-21 07:28 UTC, itswisdomagain commented on app/walletmediums/dcrwalletrpc/address.go
> +type walletConfig struct {
I tried it without and it didn't throw. Will try again

2019-01-24 03:52 UTC, itswisdomagain requested changes

2019-01-24 03:52 UTC, itswisdomagain commented on app/walletmediums/dcrwalletrpc/dcrwalletrpc.go
> +const dcrwalletExecutableName = "dcrwallet"
this is no longer used, can be removed

2019-01-24 03:52 UTC, itswisdomagain commented on app/walletmediums/dcrwalletrpc/dcrwalletrpc.go
>  	if rpcAddress == "" {
This should never happen, if an rpc connection attempt is being made, then the user has to have set the rpc address. This if statement can go

2019-01-24 03:52 UTC, itswisdomagain commented on app/walletmediums/dcrwalletrpc/dcrwalletrpc.go
> +	if err1 == nil {
Rename `err1` to `originalConnectionError`

2019-01-24 03:52 UTC, itswisdomagain commented on app/walletmediums/dcrwalletrpc/dcrwalletrpc.go
> +	if client, err = useParsedConfigAddresses(ctx, rpcConfAddresses, rpcCert, noTLS); err != errSkip {
The only error returned by the `useParsedConfigAddresses` function is `errSkip`, if statement not necessary

2019-01-24 03:52 UTC, itswisdomagain commented on app/walletmediums/dcrwalletrpc/dcrwalletrpc.go
> +	if client, err = connectToDefaultAddresses(ctx, rpcCert, noTLS); err != errSkip {
The only error returned by the `connectToDefaultAddresses ` function is `errSkip`, if statement not necessary
Also, the `errSkip` variable declaration can also be removed and it's usage replaced with a generic error

Since `err` is always `errSkip`, the only thing we should be checking is if `client != nil`. As a matter of fact, both `useParsedConfigAddresses` and `connectToDefaultAddresses` can be modified to only return `*WalletRPCClient`, which would be nil if the connection attempt failed

2019-01-24 03:52 UTC, itswisdomagain commented on app/walletmediums/dcrwalletrpc/dcrwalletrpc.go
> +	client, err1 := createConnection(ctx, rpcAddress, rpcCert, noTLS)
`walletRPCClient` instead of `client`

2019-01-24 03:52 UTC, itswisdomagain commented on app/walletmediums/dcrwalletrpc/dcrwalletrpc.go
>  // returns an instance of `dcrwalletrpc.Client`
Will need to update this comment to explain how this function behaves if the specified address does not connect

2019-01-24 03:52 UTC, itswisdomagain commented on app/walletmediums/dcrwalletrpc/dcrwalletrpc.go
> +		return nil, err
Since the error being returned here is not a direct error from a connection attempt, would be better to wrap in an explanatory message:
`fmt.Errorf("Cannot connect to %s. Trying to check dcrwallet config for different address failed. %s", rpcAddress, err.Error())`

2019-01-24 03:52 UTC, itswisdomagain commented on app/walletmediums/dcrwalletrpc/dcrwalletrpc.go
> +	rpcConfAddresses, wnoTLS, wrpcCert, err := walletAddressFromDcrdwalletConfig()
`dcrwalletConfAddresses, dcrwalletConfNoTLS, dcrwalletConfCert` are more descriptive variable names. Computer would always understand the variables, however short or long, so we should go with whatever is more readable for the sake of humans, even if it is long (but not too long).

2019-01-24 03:52 UTC, itswisdomagain commented on app/walletmediums/dcrwalletrpc/address.go
> +	TBOpts ticketBuyerOptions `group:"Ticket Buyer Options" namespace:"ticketbuyer"`
Can just use `struct{}` here instead of creating a `ticketBuyerOptions` and referencing it here (since the type is never really used)

2019-01-24 03:52 UTC, itswisdomagain commented on app/walletmediums/dcrwalletrpc/address.go
> +	TBOpts ticketBuyerOptions `group:"Ticket Buyer Options" namespace:"ticketbuyer"`
Also need to go fmt

2019-01-24 03:52 UTC, itswisdomagain commented on app/walletmediums/dcrwalletrpc/address.go
> +func walletAddressFromDcrdwalletConfig() (addresses []string, notls bool, certpath string, err error) {
- `dcrwallet`, not `dcrdwallet` 😉 
- this function returns more than just the addresses, so maybe `connectionParamsFromDcrwalletConfig`?

2019-01-24 03:52 UTC, itswisdomagain commented on app/walletmediums/dcrwalletrpc/dcrwalletrpc.go
> +		fmt.Printf("unable to save rpc address: %s", err.Error())
Printing this error would have been necessary if the user was prompted for an address and saving it failed. Since we're autodetecting, ignore this error. That would also mean that this function can be removed in favor of simply using `config.UpdateConfigFile("walletrpcserver", address, true)` in the call sites

2019-01-24 03:52 UTC, itswisdomagain commented on app/walletmediums/dcrwalletrpc/dcrwalletrpc.go
>  func getNetParam(walletService walletrpc.WalletServiceClient) (param *chaincfg.Params, err error) {
This function should go below `connectToRPC` to follow the order in which they're called for easier code scanning

2019-01-24 03:52 UTC, itswisdomagain commented on cli/termio/terminalprompt/terminalprompt.go
> +var InputRequiredValidator = func(v string) error {
Don't think this is used anymore, can remove

2019-01-24 12:47 UTC, itswisdomagain approved these changes

2019-01-24 12:47 UTC, merged