implemented send and custom send spend unconfirmed feature for web and cli
raedahgroup/godcr-old pull request #160
Opened 2019-01-11 21:27 UTC by Sirmorrison

fix #138 

implemented send and custom send spend unconfirmed feature for web and cli

2019-01-11 21:40 UTC, itswisdomagain requested changes
Looks neat, a few corrections

2019-01-11 21:40 UTC, itswisdomagain commented on cli/commands/send.go
> +	Spendunconfirmed bool `short:"u" long:"spendunconfirmed" description:"Use unconfirmed outputs for send transactions."`
CamelCasing for variable/field names: `SpendUnconfirmed`

2019-01-11 21:40 UTC, itswisdomagain commented on cli/commands/send.go
> +	var requireConfirmation int32
`requiredConfirmations`

2019-01-11 21:40 UTC, itswisdomagain commented on cli/commands/send.go
> +	if s.Spendunconfirmed{
this code is repeated, you should instead pass a `spendUnconfirmed bool` parameter to the `send` function and do this if/else statement there

2019-01-11 21:40 UTC, itswisdomagain commented on cli/commands/send.go
> +func send(wallet walletcore.Wallet, requireConfirmation int32, custom bool) error {
modify this to `func send(wallet walletcore.Wallet, sendUnconfirmed, custom bool) error {`
see above comment

2019-01-11 21:40 UTC, itswisdomagain commented on web/routes/handlers.go
> +	unconfirmed := req.FormValue("SpendUnconfirmed")
why not `spendUnconfirmed`?
what does `unconfirmed` mean?

2019-01-11 21:40 UTC, itswisdomagain commented on web/routes/handlers.go
> +	if unconfirmed == "on"{
it might be a good idea to accept any value for `spendUnconfirmed`
we know for sure that the value of `spendUnconfirmed` would be an empty string if the checkbox was not checked, use that instead

`if spendUnconfirmed != "" {`

2019-01-11 21:40 UTC, itswisdomagain commented on web/routes/handlers.go
> +	var RequiredConfirmations int32
`requiredConfirmations`

2019-01-11 21:40 UTC, itswisdomagain commented on web/views/send.html
> +                                        <input type="checkbox" class="form-check-input" name="SpendUnconfirmed" id="SpendUnconfirmed">
`spendUnconfirmed`
follow the pattern used for ids and names in other input fields

2019-01-12 09:22 UTC, Sirmorrison commented on cli/commands/send.go
> +	Spendunconfirmed bool `short:"u" long:"spendunconfirmed" description:"Use unconfirmed outputs for send transactions."`
tried the camel casing didnt work for 'Spendunconfirmed'. had to capitalize the 'Spend' before it was passed across the send function

2019-01-12 10:21 UTC, itswisdomagain commented on cli/commands/send.go
> +	Spendunconfirmed bool `short:"u" long:"spendunconfirmed" description:"Use unconfirmed outputs for send transactions."`
The review said to use `SpendUnconfirmed`, are you saying that won't work?

2019-01-12 10:33 UTC, itswisdomagain requested changes

2019-01-12 10:33 UTC, itswisdomagain commented on cli/commands/send.go
> +	var requireConfirmations int32
This `if/else` block can be simplified. Here's what I'm thinking:
```
requiredConfirmations := walletcore.DefaultRequiredConfirmations
if spendUnconfirmed {
     requiredConfirmations = 0
}
```

Also, notice the space at the end of the if line, before the curly brace. That's the correct formatting.
Also run `go fmt ./...` to ensure your code is properly formatted before pushing again

2019-01-12 10:33 UTC, itswisdomagain commented on cli/commands/send.go
> +	var requireConfirmations int32
Also notice I used `requiredConfirmations` as against `requireConfirmations`

2019-01-12 10:33 UTC, itswisdomagain commented on cli/commands/send.go
> +	accountBalance, err := wallet.AccountBalance(sourceAccount, requireConfirmations)
The `completeCustomSend` and `completeNormalSend` functions in this file also need to be updated to use the value of `requiredConfirmations` instead of `walletcore.DefaultRequiredConfirmations` which is currently used in both functions

2019-01-12 10:33 UTC, itswisdomagain commented on web/routes/handlers.go
> +	var requireConfirmations int32
This `if/else` block can be simplified. Here's what I'm thinking:
```
requiredConfirmations := walletcore.DefaultRequiredConfirmations
if spendUnconfirmed != "" {
     requiredConfirmations = 0
}
```

2019-01-12 11:35 UTC, Sirmorrison commented on cli/commands/send.go
> +	var requireConfirmations int32
having type issues so had to declare it explicitly

2019-01-12 12:19 UTC, itswisdomagain requested changes

2019-01-12 12:19 UTC, itswisdomagain commented on web/routes/handlers.go
> +	fmt.Println(requiredConfirmations)
Testing, I guess. Delete please

2019-01-12 22:07 UTC, itswisdomagain approved these changes

2019-01-12 22:07 UTC, merged