Skeletal framework tview
raedahgroup/godcr-old pull request #167
Opened 2019-01-15 12:10 UTC by hintact-platform

This PR has resolved this issue - #162 

Created a terminal package with a terminal.go file that initialize the rivo/tview to create the skeletal terminal ui

I created a new mode **--mode=terminal**

![tview](https://user-images.githubusercontent.com/15618127/51179397-a822fd00-18c5-11e9-8699-74aed802ed03.png)

2019-01-16 09:51 UTC, itswisdomagain requested changes

2019-01-16 09:51 UTC, itswisdomagain commented on terminal/terminal.go
> +		AddItem("Close / Shutdown", "Press to exit", 'q', func() {
This list should only have
- (b) Balance (not Account Balance)
- (r) Receive
- (s) Send
- (h) History
- (q) Exit (not Close / Shutdown, also the explanatory text is not necessary)

2019-01-16 09:51 UTC, itswisdomagain commented on main.go
> +		//enterDesktopMode(ctx, walletMiddleware)
comment is unnecessary

2019-01-16 09:51 UTC, itswisdomagain commented on terminal/terminal.go
> +func OpenTerminal() {
We're not actually opening a terminal, are we? This can be renamed to `StartTerminalApp`

2019-01-16 09:51 UTC, itswisdomagain commented on terminal/terminal.go
> +
This space can go

2019-01-16 09:51 UTC, itswisdomagain commented on terminal/terminal.go
> +		panic(err)
Don't panic from an interface, interfaces should return any execution errors back to main for proper handling
- modify this function's signature to return `error`
- in main.go, modify the `enterTerminalMode` function to receive any errors returned from this function: `opError = terminal.OpenTerminal()`
- instead of this if statement, do the following, include the comment too, helps whoever reads/maintains your code to understand what's happening here:
```
// `Run` blocks until app.Stop() is called before returning
return app.SetRoot(list, true).SetFocus(list).Run()
```

2019-01-16 10:46 UTC, hintact-platform commented on terminal/terminal.go
> +		panic(err)
Ohk... Done

2019-01-16 14:52 UTC, hintact-platform commented
This is the Terminal view ui

![new terminal](https://user-images.githubusercontent.com/15618127/51256773-7a61b500-19a6-11e9-9107-75ac4327ddee.PNG)

2019-01-16 15:04 UTC, itswisdomagain requested changes

2019-01-16 15:04 UTC, itswisdomagain commented on main.go
> +	if opError != nil {
this if statement is unnecessary, because regardless of whether `opError` is nil or not, you trigger shutdown

2019-01-16 15:04 UTC, itswisdomagain commented on main.go
> +	opError := terminal.StartTerminalApp(ctx, walletMiddleware)
there's already `opError` declared earlier in this file that is used in the `handleShutdown` function at the end of this file, simply assign to that variable instead of creating a new one here

2019-01-16 15:04 UTC, itswisdomagain commented on terminal/terminal.go
> +	app := tview.NewApplication()
`app` is the name of an import above, rename this to `tviewApp` instead

2019-01-16 15:04 UTC, itswisdomagain commented on terminal/terminal.go
> +	list.SetBorder(true).SetTitle("GoDCR Terminal")
Avoid hardcoding the app name anywhere in code, instead use 
`fmt.Sprintf("%s Terminal", strings.ToUpper(app.Name))`

2019-01-16 15:04 UTC, itswisdomagain commented on terminal/terminal.go
> +	if err != nil || !walletExists {
if wallet does not exist, err will not be nil. Checking if `err != nil` is enough

2019-01-16 15:04 UTC, itswisdomagain commented on terminal/terminal.go
> +	walletExists, err := walletloader.OpenWallet(ctx, walletMiddleware)
This is applaudable, but ideally should only be used in the `cli` interface. We'll leave it for now and correct it later

2019-01-23 13:30 UTC, itswisdomagain approved these changes

2019-01-23 13:31 UTC, merged