Stake Info and Purchase Tickets implementation
raedahgroup/godcr-old pull request #168
Opened 2019-01-15 15:13 UTC by codemaestro64

This adds stake info and purchase tickets pages to the web interface that fixes #158 . It also abstracts common javascript functions to allow for code readability.
![purchaseticketspage](https://user-images.githubusercontent.com/42093751/51189429-59369100-18e0-11e9-972a-e304f2d0a214.png)
![purchaseticketsresult](https://user-images.githubusercontent.com/42093751/51189451-5fc50880-18e0-11e9-805b-15665483b707.png)
![stakeinfopage](https://user-images.githubusercontent.com/42093751/51189471-681d4380-18e0-11e9-95d5-df88f9ba4959.png)

2019-01-18 14:10 UTC, itswisdomagain requested changes

2019-01-18 14:10 UTC, itswisdomagain commented on app/walletcore/wallet.go
> -	StakeInfo(ctx context.Context) (*StakeInfo, error)
Restore `ctx context.Context`, the plan is to replace all usages of `context.Background()` with the `ctx` created in [main.go](https://github.com/raedahgroup/godcr/blob/master/main.go#L68)

That `ctx` is passed to `web.StartServer`. Modify the `routes.Setup` function to also receive that `ctx` and add `ctx context.Context` to the `Routes` struct which you can then use afterwards for calls to `wallet.*()`

2019-01-18 14:10 UTC, itswisdomagain commented on web/public/js/app.js
> +        var value = "";
Move this declaration closer to where it's used, just before line 16

2019-01-18 14:10 UTC, itswisdomagain commented on web/public/js/app.js
> +        var elementType = $(this).prop("type");
`$(this)` is used quite a number of times in this function, may be better to declare a `element = $(this)`

2019-01-18 14:10 UTC, itswisdomagain commented on web/public/js/app.js
> +        var elementName = $(this).prop("name").replace(/(\-\w)/g, function(text){return " " + text[1].toUpperCase();});
I have no idea what you're trying to achieve here and in the next line, maybe add a comment?

2019-01-18 14:10 UTC, itswisdomagain commented on web/public/js/app.js
> +
multiple blank lines, one should do

2019-01-18 14:10 UTC, itswisdomagain commented on web/public/js/app.js
> +        var elementName = $(this).prop("name").replace(/(\-\w)/g, function(text){return " " + text[1].toUpperCase();});
Also, I see `elementName` is only used in line 24, can move this declaration and assignment there instead

2019-01-18 14:10 UTC, itswisdomagain commented on web/public/js/app.js
> +    $("#walletPassphrase").val("");
It's best to clear this value immediately after submitting the form, "for security reasons"

2019-01-18 14:10 UTC, itswisdomagain commented on web/public/js/app.js
> +    $("#passphrase-submit").on("click", function(){
if this `getWalletPassphraseAndSubmit` function is called multiple times, this button will receive multiple click listeners, either set this listener once or call `$("#passphrase-submit").off("click")` to remove any previous listeners before calling `on` again

2019-01-18 14:10 UTC, itswisdomagain commented on web/public/js/app.js
> +    if (error != "") {
This if block and the previous if block can be merged

2019-01-18 14:10 UTC, itswisdomagain commented on web/public/js/app.js
> +        success: function(response){
can do `success: onSuccessFunc` instead, same for the other functions below

2019-01-18 14:10 UTC, itswisdomagain commented on web/public/js/purchase_tickets.js
> +
multiple empty lines can be reduced to 1 empty line

2019-01-18 14:10 UTC, itswisdomagain commented on web/public/js/purchase_tickets.js
> +            //setSuccessMessage(response.message);
this needed?

2019-01-18 14:10 UTC, itswisdomagain commented on web/public/js/purchase_tickets.js
> +
empty line can go

2019-01-18 14:10 UTC, itswisdomagain commented on web/views/purchase_tickets.html
> +                <div class="alert alert-danger hide-empty"></div>
This isn't hidden, may need to introduce a `site.css` or `app.css` file for general styles such as `.hide-emtpy`. By the way, won't bootstrap's `d-none` class work here?

2019-01-18 14:10 UTC, itswisdomagain commented on web/views/purchase_tickets.html
> +                                        <select class="form-control" id="source-account" name="source-account" {{ if eq (len .accounts) 1 }}disabled{{ end }}>
Could make this into a template for better code reusability

2019-01-18 14:10 UTC, itswisdomagain commented on web/views/purchase_tickets.html
> +                                        <label for="number-of-tickets">Number of Tickets</label>
Ideal to also show the ticket price somewhere on this form. Also need a `Spend Unconfirmed` checkbox here too

2019-01-18 14:10 UTC, itswisdomagain commented on web/routes/routes.go
> +	router.Post("/purchase_tickets", routes.submitPurchaseTicketsForm)
I think it's preferred to use dash (-) to separate compound words rather than underscore. Underscore is more of a programmer's thing. Regardless, whatever's used should be consistent. We have `/unspent-outputs` above, using a dash.

2019-01-18 14:10 UTC, itswisdomagain commented on web/views/layout.html
> +    <script src="/static/js/app.js"></script>
If the code here does not need to run when the page is run before the body is loaded, would be better to have this in footer instead

2019-01-18 14:10 UTC, itswisdomagain commented on web/routes/handlers.go
> +
can do without this empty line

2019-01-18 14:10 UTC, itswisdomagain commented on web/routes/handlers.go
> +	walletPassphrase := req.FormValue("walletPassphrase")
`wallet- passphrase` for form name instead of `walletPassphrase`

2019-01-18 14:10 UTC, itswisdomagain commented on web/routes/handlers.go
> +	ticketAddress, err := routes.walletMiddleware.ReceiveAddress(uint32(sourceAccount))
do not generate an address for `PurchaseTicketsRequest. TicketAddress`, leave it empty as is done in the cli implementation of purchase tickets

2019-01-18 14:10 UTC, itswisdomagain commented on web/routes/routes.go
> +	router.Post("/purchase_tickets", routes.submitPurchaseTicketsForm)
Also update `transaction_details` as appropriate

2019-01-18 14:10 UTC, itswisdomagain commented on web/views/layout.html
> +                        <a class="nav-link" href="/stakeinfo">
`stakeinfo` and `purchase_tickets` do not get highlighted when both pages are visited.

2019-01-18 15:38 UTC, itswisdomagain commented
> ![purchaseticketsresult](https://user-images.githubusercontent.com/42093751/51189451-5fc50880-18e0-11e9-805b-15665483b707.png)

Can the success messages appear in one div instead of 2 as in the screenshot above?

-----

I got a wrong "success" message, the 157 tickets it's seeing is actually the number of characters in the error message. The error message was something about incorrect wallet passphrase. Try to make a purchase with an incorrect wallet passphrase to see if you'll get similar output
![screenshot 2019-01-18 at 3 08 01 pm](https://user-images.githubusercontent.com/18400051/51396356-39e96f00-1b3f-11e9-9c10-5088cd1325d4.png)

2019-01-24 05:14 UTC, itswisdomagain requested changes

2019-01-24 05:14 UTC, itswisdomagain commented on app/walletmediums/dcrlibwallet/walletfunctions.go
> +		return nil, fmt.Errorf("could not fetch account balance: %s", err.Error())
Should simply return `err`.

If the error encountered in the process of executing an operation is directly related to the operation being executed, the error alone should be returned since interfaces usually add some explanatory text before displaying the error. Adding another explanation here would lead to excessive explanations.

If on the other hand, the error is not directly related to the operation, adding minimal explanation aids debugging and makes the overall explanation displayed to the user more sensible

2019-01-24 05:14 UTC, itswisdomagain commented on app/walletmediums/dcrlibwallet/walletfunctions.go
> -		return nil, fmt.Errorf("could not determine ticket price: %s", err.Error())
Restore the accompanying error description since it is not directly related to the operation, to provide more context to the user

2019-01-24 05:14 UTC, itswisdomagain commented on app/walletcore/types.go
> +	Height      int32 `json:"height"`
`Height` is assigned but never read / displayed. This struct/type can be removed entirely and the associated functions modified to simply return the ticket price as an `int64` or `dcrutil.Amount`

2019-01-24 05:14 UTC, itswisdomagain commented on app/walletmediums/dcrwalletrpc/walletfunctions.go
>  		return nil, fmt.Errorf("could not determine ticket price: %s", err.Error())
Should simply return `err`

2019-01-24 05:14 UTC, itswisdomagain commented on app/walletmediums/dcrwalletrpc/walletfunctions.go
> +		return nil, err
`return nil, fmt.Errorf("could not determine ticket price: %s", err.Error())`

2019-01-24 05:14 UTC, itswisdomagain commented on web/public/css/style.css
> +.alert.hide-empty:empty {
Can use `class="d-none"` in html (from bootstrap) rather than adding this new style

2019-01-24 05:14 UTC, itswisdomagain commented on web/views/purchase_tickets.html
> +                <div class="alert alert-danger hide-empty"></div>
Use `d-none` instead of `hide-empty`

2019-01-24 05:14 UTC, itswisdomagain commented on web/public/js/app.js
> +    if (passphraseEl.val() == "") {
`===`

2019-01-24 05:14 UTC, itswisdomagain commented on web/public/js/purchase_tickets.js
> +                $("#success-msg-container").append("<p><strong>" + response.message[i] + "</strong></p>");
The final success message is not displayed. Need to remove the `hide-empty` class. Also, good to make use of `array.map` rather than looping:
```
var successMsg = ["<p>You have purchased " + response.message.length + " ticket(s)</p>"];
var ticketHashes = response.message.map(ticketHash => "<p><strong>" + ticketHash + "</strong></p>");
successMsg.push(ticketHashes);
$("#success-msg-container").html(successMsg.join()).removeClass('d-none hide-empty');
```

2019-01-24 05:14 UTC, itswisdomagain commented on web/public/js/purchase_tickets.js
> +    if ($("#source-account").prop("disabled")) {
You don't do this for the send form. Is this necessary? If so, the send form should also adopt this behaviour

2019-01-24 05:14 UTC, itswisdomagain commented on web/views/purchase_tickets.html
> +                                    <div class="form-group">
Need a `Spend unconfirmed` checkbox here to use 0 min confirmations

2019-01-24 05:14 UTC, itswisdomagain commented on web/views/layout.html
>          if (pathname != "/" && paths.length > 1) {
`!==`

2019-01-31 06:48 UTC, itswisdomagain requested changes

2019-01-31 06:48 UTC, itswisdomagain commented on app/walletmediums/dcrlibwallet/walletfunctions.go
> -		return nil, fmt.Errorf("could not determine ticket price: %s", err.Error())
Restore the accompanying error description since it is not directly related to the operation, to provide more context to the user

2019-01-31 06:48 UTC, itswisdomagain commented on app/walletmediums/dcrlibwallet/walletfunctions.go
>  		return nil, fmt.Errorf("insufficient funds: spendable account balance (%s) is less than ticket price %s",
This error message isn't really correct, we're not checking the spendable balance against the ticket price, instead it's against `ticketPrice*int64(request.NumTickets)`

If the ticke price was 20dcr, spendable balance is 30 dcr and numTickets is 2, then this would return an error that spendable balance (30dcr) is less than ticket price (20dcr) which is not correct

2019-01-31 06:48 UTC, itswisdomagain commented on app/walletmediums/dcrlibwallet/walletfunctions.go
>  		return nil, fmt.Errorf("insufficient funds: spendable account balance (%s) is less than ticket price %s",
Also update the message for dcrwalletrpc

2019-01-31 06:48 UTC, itswisdomagain commented on web/public/css/style.css
> +.alert.hide-empty:empty {
Did you see this?
`Can use class="d-none" in html (from bootstrap) rather than adding this new style`

2019-01-31 06:48 UTC, itswisdomagain commented on web/public/js/purchase_tickets.js
> +                $("#success-msg-container").append("<p><strong>" + response.message[i] + "</strong></p>");
A good idea to set the html once rather than appending in a loop for performance reasons as each append causes the page to re-render. Also, if a user makes a successful purchase twice, won't this append the new tickets hashes to the previous success message?

Also, the success message is currently not visible to the user. Please refer to https://github.com/raedahgroup/godcr/pull/168/files#r250467706 again

2019-01-31 06:48 UTC, itswisdomagain commented on web/routes/handlers.go
> +		routes.renderError(err.Error(), res)
Should add explanatory text with this error to provide context as you did above for fetch accounts error

2019-01-31 06:48 UTC, itswisdomagain commented on web/views/purchase_tickets.html
> +                <div class="alert alert-danger hide-empty"></div>
Seems you missed this:
`Use d-none instead of hide-empty`

2019-02-10 08:19 UTC, itswisdomagain requested changes

2019-02-10 08:19 UTC, itswisdomagain commented on terminal/terminal.go
> +	list := tview.NewList().
Lines 17 to 25 seem to have been added during a recent merge conflict resolution. They're unnecessary and should be deleted.

2019-02-10 09:00 UTC, itswisdomagain requested changes

2019-02-10 09:00 UTC, itswisdomagain commented on app/walletmediums/dcrlibwallet/walletfunctions.go
> +		return nil, err
Should be `return nil, fmt.Errorf("could not determine ticket price: %s", err.Error())`

2019-02-10 09:00 UTC, itswisdomagain commented on app/walletmediums/dcrlibwallet/walletfunctions.go
> +		return nil, fmt.Errorf("insufficient funds: spendable account balance (%s) is less than total ticket price %s",
`is less than ticket purchase cost` instead of `total ticket price`

2019-02-10 09:00 UTC, itswisdomagain commented on app/walletmediums/dcrwalletrpc/walletfunctions.go
> +		return nil, fmt.Errorf("insufficient funds: spendable account balance (%s) is less than total ticket price %s",
`is less than ticket purchase cost` instead of `total ticket price`

2019-02-10 09:00 UTC, itswisdomagain commented on web/public/js/purchase_tickets.js
> +            setSuccessMessage(successMsg.join());
Using `.join()` without specifying a separator uses "," by default, causing the output of this div to have extra lines for each comma.

Change to `successMsg.join("")` or `successMsg.join("\n")`

2019-02-10 09:00 UTC, itswisdomagain commented on web/public/js/purchase_tickets.js
> +        submit_btn.removeAttr("disabled").html("Next");
Don't think this button text should be "Next", as though there's another form to fill. A logical text for this button will be "Purchase" or "Purchase Tickets"

2019-02-10 09:00 UTC, itswisdomagain commented on web/routes/walletloader.go
> +		blockchainSyncStatus = syncStatusSuccess
Just noticing this, why do we have this?

2019-02-15 20:19 UTC, ademuanthony commented
Despite having 1000 DCR, I am getting error insufficient balance.

![ticket-error](https://user-images.githubusercontent.com/11990092/52882163-1ed24500-3167-11e9-82af-a8689b9bbc4b.png)

2019-02-19 16:46 UTC, ademuanthony requested changes
some few changes

2019-02-19 16:46 UTC, ademuanthony commented on web/public/app/src/controllers/send_controller.js
> -    this.submitButtonTarget.innerHTML = 'Sending...'
there is a breakage on the send page.
`Error: Missing target element "send.submitButton"`
Please check it

2019-02-19 16:46 UTC, ademuanthony commented on web/views/layout.html
> +    <script src="/static/app/dist/js/vendors~app.bundle.js"></script>
can we have the link point directly to the `dist`, that will mean updating the static file routing
All the FE source files are currently exposed as the `static` route is pointing to the `public` folder which now contains the `scr` folder for the FE

2019-02-19 16:46 UTC, ademuanthony commented on web/views/send.html
> +                    {{ template "send-passphrase-modal" "send" }}
Let us rename the `send-passphrase-modal` to `passphrase-modal`

2019-02-21 13:03 UTC, codemaestro64 commented on web/public/app/src/controllers/send_controller.js
> -    this.submitButtonTarget.innerHTML = 'Sending...'
fixed

2019-02-21 21:35 UTC, ademuanthony commented
There is an error on the send page
`Error: Missing target element "send.submitButton"`
Can you check it please

2019-02-22 17:31 UTC, codemaestro64 commented
@ademuanthony I'm not able to reproduce the error. Do you have the latest code?

2019-02-26 12:04 UTC, Sirmorrison requested changes
please run go fmt ./...

2019-02-26 14:39 UTC, codemaestro64 commented
@Sirmorrison done

2019-02-26 23:24 UTC, Sirmorrison approved these changes

2019-02-27 19:37 UTC, ademuanthony approved these changes

2019-02-28 11:45 UTC, itswisdomagain requested changes
Also, rename web/public to web/static, the content of that directory are not all public to the end user

2019-02-28 11:45 UTC, itswisdomagain commented on .gitignore
> -web/public/dist
The dist folder should also be excluded. I see we can't do that currently as it also holds bootstrap and jquery files. We'd need to use bootstrap and jquery deps from npm so they are bundled together by webpack, something for a different PR anyways

2019-02-28 11:45 UTC, itswisdomagain commented on go.mod
> +	github.com/decred/dcrwallet v1.2.2
Is there a reason for changing this version?
This new version could cause issues, we should stick with the version that's been well tested unless absolutely necessary

2019-03-01 23:15 UTC, itswisdomagain requested changes
Due to the change of public to static, we now have copies of the bundled js files in 2 locations - public/dist/js and static/dist/js. Need to delete the public folder entirely.

2019-03-03 04:54 UTC, itswisdomagain approved these changes

2019-03-03 04:55 UTC, merged