WIP new connection command to show best block and number of peers connected.
raedahgroup/godcr-old pull request #169
Opened 2019-01-15 23:32 UTC by Jujhar

To compile you need to update go.sum for a quick hack fix to match checksum line 5 with F486Q0BO+uFwzGSCfNkuQYr86h0Oap7zYdimuCyr0/0=

Addresses #68

2019-01-16 12:56 UTC, itswisdomagain requested changes

2019-01-16 12:56 UTC, itswisdomagain commented on app/walletmediums/dcrlibwallet/walletloader.go
> +	return int64(0)
does `int64(lib.walletLib.GetBestBlock())` this not work?
this function can simply `return int64(lib.walletLib.GetBestBlock())`

2019-01-16 12:56 UTC, itswisdomagain commented on app/walletmediums/dcrlibwallet/walletfunctions.go
> +/*
Do you need these commented code somewhere? It's good practice to not have dead code (code that is commented out) on git history

2019-01-16 12:56 UTC, itswisdomagain commented on main.go
> +
Eliminate multiple empty lines, a single empty line between different code sections is enough

2019-01-18 00:03 UTC, Jujhar commented on app/walletmediums/dcrlibwallet/walletloader.go
> +	return int64(0)
No

2019-01-22 04:25 UTC, Jujhar commented
Updated

2019-01-24 06:48 UTC, itswisdomagain requested changes
Take a look at these first before I do further review

2019-01-24 06:48 UTC, itswisdomagain commented on app/config/config.go
> +	QueryBlockchain bool `long:"status" description:"Queries blockchain when running in cli mode. If used with a command, command is executed after blockchain is queried"`
What does `QueryBlockchain` do? I've scanned your code in this PR and only find it's usage in line 55-57 of `dcrlibwallet/walletloader.go` where you disable logging to console. Why does `QueryBlockchain` disable logging instead of "querying" the blockchain according to your description?

If this config variable have no real use, it should be removed please.

2019-01-24 06:48 UTC, itswisdomagain commented on app/walletcore/wallet.go
> +	ConnectionInfo() (connection string)
Why is this function not implemented for dcrwallet rpc?

2019-01-24 06:48 UTC, itswisdomagain commented on app/walletcore/wallet.go
> +	// AccountsOverview returns the name, account number and balance for all accounts in wallet
Correct this comment

2019-01-24 06:48 UTC, itswisdomagain commented on app/walletmediums/dcrlibwallet/dcrlibwallet.go
> +var NBestBlock int64
No need to store latest block while syncing, we can always query for the latest block at anytime

2019-01-24 06:48 UTC, itswisdomagain commented on app/walletmediums/dcrlibwallet/spvsync.go
> +	NumOfPeers = peerCount
Should also update this value `OnPeerDisconnected`

2019-01-24 06:48 UTC, itswisdomagain commented on app/walletmediums/dcrlibwallet/spvsync.go
> +	fmt.Printf("Number of connected peers: %d\n", NumOfPeers)
Why are we printing the number of connected peers and best block **at the end** of a sync operation? The task was to add a cli command that can be issued at any time to display the required info, not display it after every sync operation. These added lines should go

2019-01-24 06:48 UTC, itswisdomagain commented on app/walletmediums/dcrlibwallet/walletloader.go
> +		if statusMode == true {
I have no idea why this is necessary. There's already a `showLog` variable in place for changing the logging behaviour as desired

2019-01-24 06:48 UTC, itswisdomagain commented on app/walletmediums/dcrwalletrpc/walletfunctions.go
> +	//return fmt.Sprintf("Connected to %d peers • Latest block %d",NumOfPeers, NBestBlock)
Don't leave commented lines of code in git. Delete all such codes before committing, it doesn't have any use in git history as it is.

2019-01-24 06:48 UTC, itswisdomagain commented on app/walletmediums/dcrwalletrpc/walletfunctions.go
> +	return "Not Available"
Why is this not implemented?

2019-01-24 06:48 UTC, itswisdomagain commented on app/walletmediums/dcrwalletrpc/walletloader.go
> +//func (c *WalletRPCClient) BestBlock() {}
Delete commented lines of code

2019-01-24 06:48 UTC, itswisdomagain commented on app/walletmediums/dcrwalletrpc/walletloader.go
> +func (c *WalletRPCClient) SyncBlockChain(listener *app.BlockChainSyncListener, showLog bool, statusMode bool) error {
`statusMode` is never used in this function; and I also have no idea what `statusMode` means or why it exists in the first place.

2019-01-24 22:10 UTC, Jujhar commented on app/walletmediums/dcrwalletrpc/walletloader.go
> +func (c *WalletRPCClient) SyncBlockChain(listener *app.BlockChainSyncListener, showLog bool, statusMode bool) error {
What this does is log nothing when it sync queries and returns: 
Also useful for gui modes as it updates these messages cleanly periodically there as well
```
Blockchain sync started
Number of connected peers: 2
Best block: 312594
Blockchain synced successfully
```

as opposed to huge wall of data)

2019-01-24 22:10 UTC, Jujhar commented on app/walletmediums/dcrwalletrpc/walletfunctions.go
> +	//return fmt.Sprintf("Connected to %d peers • Latest block %d",NumOfPeers, NBestBlock)
Appologies first time I did a WIP (thinking would tidy up at end)

2019-01-24 22:10 UTC, Jujhar commented on app/walletmediums/dcrlibwallet/spvsync.go
> +	NumOfPeers = peerCount
The way it syncs it would go back to 0 at the end.
Also it is updated with other actions

2019-01-24 22:10 UTC, Jujhar commented on app/walletmediums/dcrlibwallet/dcrlibwallet.go
> +var NBestBlock int64
Do you have an example for non-rpc?

2019-01-24 22:11 UTC, Jujhar commented on app/walletcore/wallet.go
> +	ConnectionInfo() (connection string)
Had a problem with seeing the big picture with rpc but figured out.

2019-01-24 22:11 UTC, Jujhar commented on app/config/config.go
> +	QueryBlockchain bool `long:"status" description:"Queries blockchain when running in cli mode. If used with a command, command is executed after blockchain is queried"`
What it does is give an accurate snapshot of how many peers connected try it out with the http gui.

Regarding querying by default the app is in non rpc mode which does not sync or connect at the beginning with example being balance, help, & recieve commands. If it did connect it would have logged out these messages (non rpc mode) 

```
2019-01-24 13:02:09.977 [WRN] SYNC: Peering attempt failed: localpeer.ConnectOutbound([2001:bc8:4700:2500::213b]:9108): context deadline exceeded
2019-01-24 13:02:10.586 [INF] SYNC: New peer 185.24.216.149:9108 /dcrwire:0.3.0/dcrd:1.4.0(pre)/ SFNodeNetwork|SFNodeCF
2019-01-24 13:02:10.608 [INF] SYNC: New peer 85.255.13.238:9108 /dcrwire:0.3.0/dcrd:1.3.0/ SFNodeNetwork|SFNodeCF
2019-01-24 13:02:31.839 [INF] SYNC: Connected 803 blocks, new tip 00000000000000001d009e63e7d545374970290a5c1bbda92081015e40c7b3a5, height 312594, date 2019-01-24 12:52:39 -0800 PST
2019-01-24 13:02:32.163 [INF] WLLT: Discovering used addresses for 1 account(s)
2019-01-24 13:02:32.693 [INF] WLLT: Account 0 next child indexes: external:1 internal:1
2019-01-24 13:02:32.693 [INF] WLLT: Updating DB with discovered addresses...

2019-01-25 00:45 UTC, Jujhar commented on app/walletmediums/dcrwalletrpc/walletfunctions.go
> +	return "Not Available"
Added

2019-01-25 07:43 UTC, itswisdomagain commented on app/walletmediums/dcrwalletrpc/walletloader.go
> +func (c *WalletRPCClient) SyncBlockChain(listener *app.BlockChainSyncListener, showLog bool, statusMode bool) error {
GUI modes do not log anything to the console, that's why there is a `showLog` variable. The log ought to only appear in cli mode, other interfaces ought to provide a UI to display sync progress.

2019-01-25 07:50 UTC, itswisdomagain requested changes

2019-01-25 07:50 UTC, itswisdomagain commented on app/walletcore/wallet.go
> +	// ConnectionInfo returns string with latest block and number of peers
Shouldn't return a formatted string, instead return the actual data to be displayed (could create a struct/type for that). Each interface should be allowed to decide how best to display the needed information

2019-01-25 07:50 UTC, itswisdomagain commented on app/walletmediums/dcrwalletrpc/dcrwalletrpc.go
> +var NBestBlock int64
For dcrwalletlib, `lib.walletLib.GetBestBlock`

2019-01-25 07:50 UTC, itswisdomagain commented on app/walletmediums/dcrwalletrpc/spvsync.go
> +			NBestBlock = s.bestBlock
Should not print number of connected peers or best block after sync. Task was to add a command that a user can issue to get this information at any time,  not display it after every sync.

Also, no need to store the best block value. Better to fetch it when requested.

2019-01-29 01:58 UTC, Jujhar commented on app/walletmediums/dcrwalletrpc/dcrwalletrpc.go
> +var NBestBlock int64
You meant to use that for just dcrwalletlib or both rpc dcrwalletrpc?

2019-01-29 01:58 UTC, Jujhar commented on app/walletmediums/dcrwalletrpc/spvsync.go
> +			NBestBlock = s.bestBlock
The http uses the sync so I think we may be good there?

For getting information anytime in essence I think we would need to recreate the OnPeerConnected command from sync I am unsure how to decouple that how should I proceed with getting the connected peers? 

You previously mentioned store it as a variable as it syncs what is alternative route or ideal way?

2019-01-31 06:52 UTC, itswisdomagain commented
Too much unnecessary stuff done in this PR and the original task isn't yet achieved. Closing this to allow someone else tackle this from a fresher perspective.

2019-01-31 06:52 UTC, closed without merging

2019-02-02 23:21 UTC, Jujhar commented
Original task was achieved though unconventionally.
Main thing missing though was http mode did not show account balance.