send feature improvements (web)
raedahgroup/godcr-old pull request #176
Opened 2019-01-20 10:59 UTC by ademuanthony

Resolves #140 

Added the functionality for sending tx to multiple destinations and worked on the display of the utxos on the web to match that of the cli
![send-feature-web](https://user-images.githubusercontent.com/11990092/51438265-6a015100-1caa-11e9-8987-95c8c5f0d910.png)

2019-01-21 13:56 UTC, engprodigy commented
I need an extra address I can send to to test for when sending to multiple addresses. @ademuanthony Please can you provide a receiving I can ass to the one I have to test.

2019-01-22 10:34 UTC, ademuanthony commented
> I need an extra address I can send to to test for when sending to multiple addresses. @ademuanthony Please can you provide a receiving I can ass to the one I have to test.

TsodqRbyRz2j164YcyyLJC2WuF8Z8hx6S5u

2019-01-23 07:08 UTC, engprodigy reviewed
the additional input addresses are not able to receive dcr token, only the first input address receives dcr token. Its not yet working perfectly.

2019-01-23 12:54 UTC, engprodigy commented
@ademuanthony what is select custom input all about? I'm new to the platform and I'm trying to review this PR. I think it will help me understand the whole process occurring in the  send page. So I will be able to properly review the code. Thanks.

2019-01-24 02:43 UTC, itswisdomagain requested changes
In addition to the comments below, we need a way to remove destination fields, say a user mistakenly added 5 fields but only wants to send to 3 or 4 destinations, currently, the user will have to refresh and start over again.

Please also modify the `getWalletPassphraseAndSubmit` function in `send.js` to prevent multiple send attempts when the send button is clicked:
```
var passphraseModal = $("#passphrase-modal");
var submitPassphrase = $("#passphrase-submit");

submitPassphrase.off("click");
submitPassphrase.on("click", function(){
    if (validatePassphrase()) {
        passphraseModal.modal('hide');
        submitSendForm();
    }
});
passphraseModal.modal();
```

2019-01-24 02:43 UTC, itswisdomagain commented on web/public/js/send.js
> +        e.preventDefault();
If you add `type="button"` to `#add-destination-btn`, you won't need to prevent default. See https://stackoverflow.com/a/41904218

2019-01-24 02:43 UTC, itswisdomagain commented on web/public/js/send.js
>      if ($("#use-custom").prop("checked") && (getSelectedInputsSum() < $("#amount").val()) ) {
replace `$("#amount").val()` with `getTotalSendAmount()`

2019-01-24 02:43 UTC, itswisdomagain commented on web/public/js/send.js
> +    for(let i = 1; i <= destinationCount; i++) {
Can iterate through the inputs in the `#destination` div:
```
for (const field of $('#destinations input')) {
    if ($(field).val() === "") {
        $(".errors").html("<div class='error'>The destination address and amount are required</div>");
        return false;
    }
}
```

2019-01-24 02:43 UTC, itswisdomagain commented on web/public/js/send.js
> +    for(let i = 1; i <= destinationCount; i++) {
Also a good idea to check that the amount is a positive, non-zero number as part of the validation

2019-01-24 02:43 UTC, itswisdomagain commented on web/public/js/send.js
> +                        <input type="text" class="form-control" id="destination-address-${destinationCount}" name="destination-address[${destinationCount}]" />
Should probably use an array instead of the amounts and addresses. Using the same form name in multiple form fields will produce an array when the form data is parsed on the backend. I tested with `destination-address` and `destination-amount` as name attributes for the destination fields and was able to get the collated information as an array in the backend (more on that in a separate comment)

Using the same form name would mean we won't need the `destinationCount` variable and the id attribute can be done without as well, to prevent multiple fields having the same id, also since the id attribute isn't really needed

2019-01-24 02:43 UTC, itswisdomagain commented on web/public/js/send.js
> +                        <input type="text" class="form-control" id="destination-address-${destinationCount}" name="destination-address[${destinationCount}]" />
Put succinctly, this line should be:
```
<input type="text" class="form-control" name="destination-address" />
```

2019-01-24 02:43 UTC, itswisdomagain commented on web/public/js/send.js
> +                        <input type="number" class="form-control amount" id="amount-${destinationCount}" name="amount[${destinationCount}]" />
This line should simplify to
```
<input type="number" class="form-control amount" name="destination-amount" />
```

2019-01-24 02:43 UTC, itswisdomagain commented on web/routes/handlers.go
> +	var sendDestinations []txhelper.TransactionDestination
Going with the approach of using an array for the address and amount input fields, the `sendDestinations` slice can be populated thus:
```
destinationAddresses := req.Form["destination-address"]
destinationAmounts := req.Form["destination-amount"]

sendDestinations := make([]txhelper.TransactionDestination, len(destinationAddresses))
for i := range destinationAddresses {
	amount, err := strconv.ParseFloat(destinationAmounts[i], 64)
	if err != nil {
		data["error"] = err.Error()
		return
	}
	sendDestinations[i] = txhelper.TransactionDestination{
		Address: destinationAddresses[i],
		Amount: amount,
	}
}
```

2019-01-24 02:43 UTC, itswisdomagain commented on web/routes/handlers.go
> +
additional empty line space can go

2019-01-24 14:12 UTC, ademuanthony commented
![send-feature-multi-destination-web](https://user-images.githubusercontent.com/11990092/51683560-6d6a4480-1fea-11e9-85dd-3157cea226ef.png)

2019-01-24 15:07 UTC, itswisdomagain requested changes
I think this is good to merge, just some cleanup.
Also help to simplify line 221 of `web/handlers.go` to `if getUnconfirmed == "true" {`

2019-01-24 15:07 UTC, itswisdomagain commented on web/public/js/send.js
> +    $("#add-destination-btn").on("click", function (e) {
`e` is not used

2019-01-24 15:07 UTC, itswisdomagain commented on web/views/send.html
> +                                    <button id="add-destination-btn" type="button" class="btn btn-sm">
Add `btn-outline-secondary` class to the buttons so they actually look like buttons. Also use `btn-primary` or something for the final send button as well.

2019-01-25 06:48 UTC, itswisdomagain approved these changes

2019-01-25 06:48 UTC, merged