Qt interface balance page: show account, name, balance and others in Qt Grid layout
raedahgroup/godcr-old pull request #177
Opened 2019-01-21 04:18 UTC by engprodigy

2019-01-21 04:24 UTC, engprodigy commented
It shows like this:





![balance_page_grid_view](https://user-images.githubusercontent.com/1181072/51452822-96fe4400-1d3c-11e9-9df2-ac4c6677fd17.PNG)

2019-01-21 08:45 UTC, engprodigy commented
I'm not sure this will work for a wallet with more than one account, I will do that in a new PR.

2019-01-22 08:54 UTC, itswisdomagain requested changes

2019-01-22 08:54 UTC, itswisdomagain commented on qt/qt.go
This space can go

2019-01-22 08:54 UTC, itswisdomagain commented on qt/pages/balance.go
> +
this space is not necessary

2019-01-22 08:54 UTC, itswisdomagain commented on qt/pages/balance.go
> +	VotingAuthorityLabel *widgets.QLabel
variables that are not used outside this package should start with small letters.

2019-01-22 08:54 UTC, itswisdomagain commented on qt/pages/balance.go
> +	b.balanceGrid = widgets.NewQGridLayout(pageContent)
Use a table instead. https://github.com/therecipe/examples/tree/master/advanced/widgets/tableview

Also compare how the balance page is on the web interface and try to replicate same thing

2019-01-22 09:04 UTC, itswisdomagain commented
> I'm not sure this will work for a wallet with more than one account, I will do that in a new PR.

It does:
![screenshot 2019-01-22 at 10 02 01 am](https://user-images.githubusercontent.com/18400051/51523873-e02dc100-1e2c-11e9-9304-72f7e9895446.png)

But best to use a table view for this use case. Also, the balance column shows spendable and there is another spendable column, duplicated information. Re-check the web interface for the expected display of the balance page

2019-01-22 09:41 UTC, engprodigy commented on qt/pages/balance.go
> +	b.balanceGrid = widgets.NewQGridLayout(pageContent)
Table view makes the field automatically editable.

2019-01-22 09:50 UTC, engprodigy commented
> > I'm not sure this will work for a wallet with more than one account, I will do that in a new PR.
> 
> It does:
> ![screenshot 2019-01-22 at 10 02 01 am](https://user-images.githubusercontent.com/18400051/51523873-e02dc100-1e2c-11e9-9304-72f7e9895446.png)
> 
> But best to use a table view for this use case. Also, the balance column shows spendable and there is another spendable column, duplicated information. Re-check the web interface for the expected display of the balance page

Its not showing on my own platform (Windows)

![balance_page_grid_view](https://user-images.githubusercontent.com/1181072/51526838-82e93e00-1e33-11e9-9d6d-2fc59bebc18a.PNG)

2019-01-24 06:21 UTC, itswisdomagain requested changes
Please temporarily remove files and code related to the send page, work on the following review comments and others from the previous review relating to the balance page so we can get this merged sooner.

Also, there's a comment below regarding adding labels to the gridview dynamically after fetching the balance for all accounts. You'd need to use slots and signals (have little idea about them), but here's something I came up with which you can build on:
```
type grid struct {
	*widgets.QGridLayout
	_ func(text string, row, column int, alignment core.Qt__AlignmentFlag) `signal:"addLabel"`
	_ func(text string, row, column, rowSpan, colSpan int, alignment core.Qt__AlignmentFlag) `signal:"addLabel2"`
}

func (g *grid) addLabel(text string, row, column int, alignment core.Qt__AlignmentFlag) {
	g.AddWidget(widgets.NewQLabel2(text, nil, 0), row, column, alignment)
}

func (g *grid) addLabel2(text string, row, column, rowSpan, colSpan int, alignment core.Qt__AlignmentFlag) {
	g.AddWidget3(widgets.NewQLabel2(text, nil, 0), row, column, rowSpan, colSpan, alignment)
}

func (b *balancePage) getAndDisplayBalance(wallet walletcore.Wallet) {
	accounts, err := wallet.AccountsOverview(walletcore.DefaultRequiredConfirmations)
	if err != nil {
		errMsg := fmt.Sprintf("Error reading account balance: %s", err.Error())
		b.balanceGrid.addLabel2(errMsg, 1, 0, 1, b.balanceGrid.ColumnCount(), core.Qt__AlignCenter)
		return
	}

	for i, account := range accounts {
		b.balanceGrid.addLabel(account.Name, i + 1, 0, core.Qt__AlignLeft)
		b.balanceGrid.addLabel(account.Balance.Total.String(), i + 1, 1, core.Qt__AlignLeft)
		b.balanceGrid.addLabel(account.Balance.Spendable.String(), i + 1, 2, core.Qt__AlignLeft)
		b.balanceGrid.addLabel(account.Balance.LockedByTickets.String(), i + 1, 3, core.Qt__AlignLeft)
		b.balanceGrid.addLabel(account.Balance.VotingAuthority.String(), i + 1, 4, core.Qt__AlignLeft)
		b.balanceGrid.addLabel(account.Balance.Unconfirmed.String(), i + 1, 5, core.Qt__AlignLeft)
	}
}
```

2019-01-24 06:21 UTC, itswisdomagain commented on qt/pages/balance.go
> +	balanceGrid          *widgets.QGridLayout
All other widgets are not necessary, remove all except `balanceGrid`

2019-01-24 06:21 UTC, itswisdomagain commented on qt/pages/balance.go
> +	// create Qlabels widgets to hold values
Do not create these labels here, do so when the data is fetched. Simply add the headers to the grid view only for now

2019-01-24 06:21 UTC, itswisdomagain commented on qt/pages/balance.go
> +		accountNameSummary[i] = fmt.Sprintf("%s", account.Name)
For sake of next time, `fmt.Sprintf("%s", account.Name)` is same thing as `account.Name`. Only use string formatting when you want to combine literal string and a variable

2019-01-24 06:21 UTC, itswisdomagain commented on qt/pages/balance.go
>  	for i, account := range accounts {
No need for the slices/arrays above.
In this loop, create labels for each column and for each account and add to the grid view directly.

There would also be no use for the `summarizeBalance` function above, until we add a checkbox to show fewer details, that's when the summary will become useful.

2019-01-24 06:35 UTC, engprodigy commented on qt/pages/balance.go
> +	balanceGrid          *widgets.QGridLayout
Yes , I was thinking of doing it dynamically but I just wanted to have something working first as a foundation. Thats why I commented earlier that it might not work properly for multiple accounts but I was surprised you said it worked. Generating dynamically is the ultimately best option.

2019-01-24 06:45 UTC, engprodigy commented on qt/pages/balance.go
> +	balanceGrid          *widgets.QGridLayout
I 

> Please temporarily remove files and code related to the send page, work on the following review comments and others from the previous review relating to the balance page so we can get this merged sooner.
> 
> Also, there's a comment below regarding adding labels to the gridview dynamically after fetching the balance for all accounts. You'd need to use slots and signals (have little idea about them), but here's something I came up with which you can build on:
> 
> ```
> type grid struct {
> 	*widgets.QGridLayout
> 	_ func(text string, row, column int, alignment core.Qt__AlignmentFlag) `signal:"addLabel"`
> 	_ func(text string, row, column, rowSpan, colSpan int, alignment core.Qt__AlignmentFlag) `signal:"addLabel2"`
> }
> 
> func (g *grid) addLabel(text string, row, column int, alignment core.Qt__AlignmentFlag) {
> 	g.AddWidget(widgets.NewQLabel2(text, nil, 0), row, column, alignment)
> }
> 
> func (g *grid) addLabel2(text string, row, column, rowSpan, colSpan int, alignment core.Qt__AlignmentFlag) {
> 	g.AddWidget3(widgets.NewQLabel2(text, nil, 0), row, column, rowSpan, colSpan, alignment)
> }
> 
> func (b *balancePage) getAndDisplayBalance(wallet walletcore.Wallet) {
> 	accounts, err := wallet.AccountsOverview(walletcore.DefaultRequiredConfirmations)
> 	if err != nil {
> 		errMsg := fmt.Sprintf("Error reading account balance: %s", err.Error())
> 		b.balanceGrid.addLabel2(errMsg, 1, 0, 1, b.balanceGrid.ColumnCount(), core.Qt__AlignCenter)
> 		return
> 	}
> 
> 	for i, account := range accounts {
> 		b.balanceGrid.addLabel(account.Name, i + 1, 0, core.Qt__AlignLeft)
> 		b.balanceGrid.addLabel(account.Balance.Total.String(), i + 1, 1, core.Qt__AlignLeft)
> 		b.balanceGrid.addLabel(account.Balance.Spendable.String(), i + 1, 2, core.Qt__AlignLeft)
> 		b.balanceGrid.addLabel(account.Balance.LockedByTickets.String(), i + 1, 3, core.Qt__AlignLeft)
> 		b.balanceGrid.addLabel(account.Balance.VotingAuthority.String(), i + 1, 4, core.Qt__AlignLeft)
> 		b.balanceGrid.addLabel(account.Balance.Unconfirmed.String(), i + 1, 5, core.Qt__AlignLeft)
> 	}
> }
> ```

I will go through the details to be sure this will work

2019-02-04 20:00 UTC, closed without merging