change outputs customization - web
raedahgroup/godcr-old pull request #186
Opened 2019-01-26 06:22 UTC by ademuanthony

Resolve #139 

This PR adds change output customization to the web. 

This feature is available only when the user chose to specify a custom input
![co-no-show-if-not-custom](https://user-images.githubusercontent.com/11990092/51783492-fe503580-213a-11e9-991a-e272c92e9e2d.png)

It gives the user the ability to auto-generate random amounts for his desired number of random output
![co-auto-change](https://user-images.githubusercontent.com/11990092/51783489-f5f7fa80-213a-11e9-9e10-ebf7672630c0.png)

 or to manually add change amount for a desired number of destinations.
![co-custom-change](https://user-images.githubusercontent.com/11990092/51783499-0314e980-213b-11e9-8708-22bdd2b5013d.png)

2019-01-26 10:21 UTC, itswisdomagain requested changes

2019-01-26 10:21 UTC, itswisdomagain commented on web/public/js/send.js
> +    $("#changeOutputsCard").hide();
best to hide this directly in html to prevent the flicker that is visible when the page loads. At first the element is visible, then it quickly hides. Can be avoided.

Can use `class="d-none"` on those elements and when you need to make them visible, use `element.show()` or `element.removeClass('d-none')`, if the `show` doesn't work.

2019-01-26 10:21 UTC, itswisdomagain commented on web/views/send.html
> +                                    <h5 class="mb-0">
`h5` element is unnecessary, can use button directly

2019-01-26 10:21 UTC, itswisdomagain commented on web/views/send.html
> +                                                    <label for="amount">Number Of Change Outputs</label>
`for="numberOfChangeOutput"`

2019-02-06 17:57 UTC, itswisdomagain commented
Work on this is paused temporarily for PR #190 to be completed and merged in order to avoid over-complicating the already complicated js files

2019-02-20 13:43 UTC, ademuanthony commented
I have migrated the code base to stimulusjs
I also added the ability to reset the form after a successful send operation and a reset button.

Based on my discussion with @raedah we now have a single panel for the change output and a checkbox for the user to specify whether or not to use a random amount

![change-output-no-random](https://user-images.githubusercontent.com/11990092/53095716-d1b2f200-351d-11e9-8753-b90e5adbcdc6.PNG)

![change-output-random](https://user-images.githubusercontent.com/11990092/53095724-d677a600-351d-11e9-9ca5-61ccbaf7a17c.PNG)

2019-02-28 12:31 UTC, itswisdomagain requested changes
**Some observations:**
- If I send using custom inputs without **generating** change outputs, I get a success message without an hash, the transaction does not go through and my balance is unaffected. This happens even if I enter number of change outputs

- New destination addresses should be added below the previous not to the side for easier scanning by the eyes
![screenshot 2019-02-28 at 1 11 25 pm](https://user-images.githubusercontent.com/18400051/53566306-12cd8680-3b5c-11e9-9578-9aef6a77b8e2.png)

**Some ideas:**
- The change outputs section should not be collapsible, should be always visible. By default, it should assume 1 output with random amount.
- The change outputs should be generated whenever the number value changes or the checkbox is checked/unchecked
- If the user wants to manually enter amounts for each change address, there should be an indication somewhere of the maximum change address that the user can assign. This value should reduce as the user assigns amounts to different addresses and must be equal to zero before the transaction should be submitted

2019-02-28 12:31 UTC, itswisdomagain commented on web/routes/handlers.go
> +func buildTxDestinations(destinationAddresses []string, destinationAmounts []string) (destinations []txhelper.TransactionDestination, err error) {
This should go into a helper file in this package

2019-02-28 12:31 UTC, itswisdomagain commented on web/routes/routes.go
> +	router.Post("/random-change-outputs", routes.getRandomChangeOutputs)
This should be a "GET" request, the route function even says as much

2019-02-28 12:31 UTC, itswisdomagain commented on web/src/controllers/send_controller.js
> +    return ['sourceAccount', 'address', 'amount', 'destinations', 'destinationTemplate', 'changeAddress', 'changeAmount', 'errors', 'customInput', 'customTxRow', 'customInputContent', 'submitButton',
Please break this into multiple lines

2019-02-28 12:31 UTC, itswisdomagain commented on web/src/controllers/send_controller.js
> +    postData += `&totalSelectedInputAmountDcr=${this.getSelectedInputsSum()}`
make this into `queryParams`, I think prepending the output of `$('#send-form').serialize()` with "?" should do the trick

2019-02-28 12:31 UTC, itswisdomagain commented on web/src/controllers/send_controller.js
> +    $.ajax({
Why are we not using axios?

2019-02-28 12:31 UTC, itswisdomagain commented on web/views/send.html
> +                                    <h5 class="mb-0">
Surrounding `h5` element is unnecessary.

2019-02-28 12:31 UTC, itswisdomagain commented on web/src/controllers/send_controller.js
> +  resetSendForm () {
this function should also clear error and success messages

2019-02-28 12:31 UTC, itswisdomagain commented on web/views/send.html
> +                                <button data-action="click->send#resetSendForm" class="btn btn-danger" id="reset-btn" type="button">Reset</button>
The reset button should be on the left

2019-02-28 12:31 UTC, itswisdomagain commented on web/views/send.html
> +                                <button data-action="click->send#resetSendForm" class="btn btn-danger" id="reset-btn" type="button">Reset</button>
Also the "Next' button on the passphrase modal should be "Submit" please

2019-02-28 12:31 UTC, itswisdomagain commented on web/views/send.html
> +                                                    <input data-target="send.useRandomChangeOutputs" class="form-check-input" type="checkbox" id="inlineFormCheck">
`send#generateChangeOutputs` should be triggered when this checkbox is checked or unchecked

2019-03-05 04:18 UTC, itswisdomagain requested changes
Delete `web/public` and restore `web/static/app/yarn.lock`

2019-03-05 04:18 UTC, itswisdomagain commented on web/static/app/src/controllers/send_controller.js
> +    while (this.destinationCount() > 1) {
best to call this function only once and save the value in a variable, then use a for loop
the current pattern makes multiple calls to the dom..

2019-03-05 10:05 UTC, itswisdomagain requested changes
Validate the change outputs client-side before displaying the wallet passphrase prompt. In the screenshot below, the change outputs do not have amounts but I'm able to submit the form, which leads to a `strconv.ParseFloat: parsing "": invalid syntax` error
![screenshot 2019-03-05 at 11 00 37 am](https://user-images.githubusercontent.com/18400051/53797338-47638880-3f36-11e9-8f4e-653c186cf856.png)

Also, if the change outputs section is hidden, I think that can be assumed to mean the user does not want to customize the change outputs and any previous customization done should be disregarded. In the screenshot above, I did not set amounts for the change outputs and that gave an error. I expected that by closing the change outputs section, it'd revert to the default autogenerated change output but it still gave the error gotten earlier.

2019-03-05 14:55 UTC, itswisdomagain requested changes

2019-03-05 14:55 UTC, itswisdomagain commented on web/static/app/src/controllers/send_controller.js
> +    // todo validate amount constraint, reset element
should this be here?

2019-03-06 15:51 UTC, itswisdomagain approved these changes

2019-03-06 15:51 UTC, merged