Creating grid layout
raedahgroup/godcr-old pull request #188
Opened 2019-01-28 10:30 UTC by hintact-platform

2019-01-29 11:39 UTC, itswisdomagain requested changes

2019-01-29 11:39 UTC, itswisdomagain commented on terminal/pageshandler/balance.go
> +package pageshandler
This file is empty, don't see a need for it in this PR. Please delete temporarily and re-commit.

2019-01-29 11:39 UTC, itswisdomagain commented on terminal/terminal.go
> +var tviewApp *tview.Application
This isn't necessary, usage of `tviewApp` can be localised. More on this below

2019-01-29 11:39 UTC, itswisdomagain commented on terminal/terminal.go
> +func GridLayout() tview.Primitive {
This function isn't needed outside this package, no need to make it public. Use `gridLayout` to make it private.
Also, the function can be better named to effectively describe what it does.

2019-01-29 11:39 UTC, itswisdomagain commented on terminal/terminal.go
> +	PagesColumn := func(text string) tview.Primitive {
This function and the next (MenuColumn) are not necessary, they're called only once and just as soon as they're declared, can just write the code directly instead of wrapping in a function

2019-01-29 11:39 UTC, itswisdomagain commented on terminal/terminal.go
> +	tviewGrid := GridLayout()
You can pass `tviewApp` to this function to avoid having to create a global variable for it

2019-01-29 15:27 UTC, hintact-platform commented
Note: Once you select the send menu, the menu column will become inactive and the Focus will be on the form. The form in the send page has to be closed by selecting "close button" to enable the menu to become active.

![balance](https://user-images.githubusercontent.com/15618127/51918493-f82fb280-23e1-11e9-975c-9f48122d584b.png)
![history](https://user-images.githubusercontent.com/15618127/51918494-f82fb280-23e1-11e9-827d-2f600d3a3e4f.png)
![receive](https://user-images.githubusercontent.com/15618127/51918496-f82fb280-23e1-11e9-8aee-5dfb59060c47.png)
![send](https://user-images.githubusercontent.com/15618127/51918519-febe2a00-23e1-11e9-8a84-a231247ecfc3.png)

2019-01-29 16:02 UTC, itswisdomagain requested changes

2019-01-29 16:02 UTC, itswisdomagain commented on terminal/terminal.go
>  	tviewApp = tview.NewApplication()
you can declare and assign in one line
`tviewApp := tview.NewApplication()`

2019-01-29 16:02 UTC, itswisdomagain commented on terminal/terminal.go
> +	terminalLayoutApp := terminalLayout(tviewApp)
Does this variable represent an app?? I like the function name `terminalLayout`, variable could simply be `layout` or something that actually describe what it is

2019-01-29 16:02 UTC, itswisdomagain commented on terminal/terminal.go
> +	var menuColumn *tview.List
this declaration is unnecessary, you can declare and assign all at once in line 48

2019-01-29 16:02 UTC, itswisdomagain commented on terminal/terminal.go
> +	//The Default page onload
should add a space after // before the actual comment, makes it easier to read

2019-01-29 16:02 UTC, itswisdomagain commented on terminal/pages/balance.go
> +	title := pageTitle("Balance")
No need to display a page title on the right section, the left section does a good job of highlighting the currently active page

2019-01-29 16:02 UTC, itswisdomagain commented on terminal/pages/balance.go
> +	title := pageTitle("Balance")
This applies to other pages and also means there won't be need to create grids either

2019-01-29 16:02 UTC, itswisdomagain commented on terminal/pages/send.go
> +	form.AddButton("Close", func() {
"Cancel" instead of "Close"

2019-01-29 16:02 UTC, itswisdomagain commented on terminal/pages/send.go
> +func SendPage(tviewApp *tview.Application, menuColumn *tview.List) tview.Primitive {
Instead of passing `tviewApp` and `menuColumn`, should pass 2 functions, `setFocus` and `clearFocus`. More about this in the next comment.

Use `setFocus` in line 29 and `clearFocus` in line 22.

2019-01-29 16:02 UTC, itswisdomagain commented on terminal/terminal.go
> +	var tviewApp *tview.Application
This declaration is unnecessary, can declare and assign at once in the next line:
`tviewApp := tview.NewApplication()`

2019-01-29 16:02 UTC, itswisdomagain commented on terminal/terminal.go
> +	terminalLayoutApp := terminalLayout(tviewApp)
`layout` instead of `terminalLayoutApp`, it's not an app, is it?

2019-01-29 16:02 UTC, itswisdomagain commented on terminal/terminal.go
> +	var menuColumn *tview.List
Declaration unnecessary, can declare and assign together in line 48

2019-01-29 16:02 UTC, itswisdomagain commented on terminal/terminal.go
> +	currentPage := pages.BalancePage()
You can do without this variable, do without it. Don't see a need to store the current page in a variable

2019-01-29 16:02 UTC, itswisdomagain commented on terminal/terminal.go
> +			gridLayoutApp.AddItem(currentPage, 1, 1, 1, 2, 0, 0, true)
this function should remove the previously added item before adding a new one

2019-01-29 16:02 UTC, itswisdomagain commented on terminal/terminal.go
> +		    changePageColumn(pages.SendPage(tviewApp, menuColumn))
As mentioned in an earlier comment, you should create 2 functions here and pass to this function.
```
setFocus := tviewApp.setFocus
clearFocus := func() {
     tviewApp.SetFocus(menuColumn)
}
pages.SendPage(setFocus, clearFocus)
```

2019-01-29 16:02 UTC, itswisdomagain commented on terminal/terminal.go
> +
one of these empty line spaces can go

2019-01-29 16:02 UTC, itswisdomagain commented on terminal/terminal.go
> +	gridLayoutApp.AddItem(header, 0, 0, 1, 3, 0, 0, false)
3 is too much for the row span, isn't it? there isn't so much space to work with in terminal... 2 may be better

2019-01-29 16:02 UTC, itswisdomagain commented on terminal/terminal.go
> +	gridLayoutApp := tview.NewGrid().SetBorders(true).SetRows(3, 0).SetColumns(30, 0)
why are we calling this `App`? `gridLayout` sounds more descriptive to me

2019-01-29 17:09 UTC, hintact-platform commented on terminal/terminal.go
> +	var menuColumn *tview.List
Yes it can be declared an assign to on the same line, but the challenge here is that menuColumn variable can not be access withing the menuColumn function

2019-01-30 07:22 UTC, itswisdomagain requested changes
need to `go fmt ./...` as well

2019-01-30 07:22 UTC, itswisdomagain commented on terminal/pages/balance.go
> +
Empty line spaces as these (at the start of a function) are unnecessary

2019-01-30 07:22 UTC, itswisdomagain commented on terminal/pages/send.go
> +	//Form for Sending
a single white space should separate the actual comment from the last /
this also applies to other comments in this PR

2019-01-30 07:22 UTC, itswisdomagain commented on terminal/terminal.go
> +	Layout := terminalLayout(tviewApp)
`layout`

2019-01-31 07:06 UTC, itswisdomagain approved these changes

2019-01-31 07:06 UTC, merged