Create wallet nuklear
raedahgroup/godcr-old pull request #189
Opened 2019-01-28 11:48 UTC by codemaestro64

This adds the create wallet page to the nuklear app. The page is displayed only when dcrwallet does not exist

2019-01-29 12:11 UTC, itswisdomagain requested changes

2019-01-29 12:11 UTC, itswisdomagain commented on nuklear/desktop.go
> +func (desktop *Desktop) renderWithoutNav(window *nucular.Window) {
`renderWithoutNav` is called by `renderWithNav`, please re-order the functions

2019-01-29 12:11 UTC, itswisdomagain commented on nuklear/desktop.go
> +		desktop.renderWithoutNav(w)
You should create a `render` function that triggers either `renderWithNav` or `renderWithoutNav` depending on the  value of currentPage. It doesn't make sense for `renderWithNav` to trigger `renderWithoutNav`

2019-01-29 12:11 UTC, itswisdomagain commented on nuklear/desktop.go
> +func (desktop *Desktop) renderWithNav(w *nucular.Window) {
`window` is better than `w`

2019-01-29 12:11 UTC, itswisdomagain commented on nuklear/handlers/createwallet.go
> +					contentWindow.Label("", "LC")
Is this meant to create a space between the 2 error message labels? If so, it's a hack, doesn't look good.

2019-01-29 12:11 UTC, itswisdomagain commented on nuklear/handlers/createwallet.go
> +		handler.validationErrors["confirmpassword"] = "Please confirm wallet password"
This is unnecessary. The only validation for the confirm password field is if it matches with the password field. If the password field is empty and the confirm password field is empty, it matches. The only error is that the main password field should not be empty - and that is handled already

2019-01-29 12:11 UTC, itswisdomagain commented on nuklear/handlers/createwallet.go
> +	if len(handler.validationErrors) > 0 {
can simplify to `return len(handler.validationErrors) > 0`

2019-01-29 12:11 UTC, itswisdomagain commented on nuklear/handlers/createwallet.go
> +func (handler *CreateWalletHandler) submitForm(wallet app.WalletMiddleware) {
Don't see a need for this function, can use the body directly instead of having a function, it's just one line of code, it's not reused and does not improve readability

2019-01-29 12:11 UTC, itswisdomagain commented on nuklear/helpers/style.go
> +	WhiteColor             = color.RGBA{0xff, 0xff, 0xff, 0xff}
Will `color.RGBA{0, 0, 0, 0}` work? That's simpler

2019-01-29 12:17 UTC, itswisdomagain commented
I'm also unable to use the Create Wallet page. It keeps re-painting every time I move the mouse or try to type or check the checkbox. Does it work on your end?

2019-01-29 12:43 UTC, codemaestro64 commented on nuklear/handlers/createwallet.go
> +					contentWindow.Label("", "LC")
The space is needed. No alternatives

2019-01-29 15:13 UTC, itswisdomagain requested changes

2019-01-29 15:13 UTC, itswisdomagain commented on nuklear/desktop.go
> +func (desktop *Desktop) renderStandalone(window *nucular.Window) {
`renderStandalonePage` sounds more descriptive

2019-01-29 15:13 UTC, itswisdomagain commented on nuklear/desktop.go
> +	standaloneHandlers map[string]Handler
- `standaloneHandlers` does not contrast well with `handlers`, could use `standalonePageHandlers` and `navPageHandlers`
- when looping through all the handlers in lines 38-40 of this file, check if the `standalone` property is true and if so, don't add the handler to `handlers`, add it instead to `standalonePageHandlers`

2019-01-29 15:13 UTC, itswisdomagain commented on nuklear/desktop.go
> +		desktop.pageChanged = true
I think when the app launches, `desktop.pageChanged` should always be true; this would be best set in line 32 above when initializing the `desktop` object.

Also, `desktop.currentPage` should always be set when the app is launched. If there's no wallet, then `desktop.currentPage = "createwallet"` else `desktop.currentPage = "balance"`

2019-01-29 15:13 UTC, itswisdomagain commented on nuklear/desktop.go
> +	if desktop.currentPage == "createwallet" {
Here, could do something like
if `handler, ok := desktop.standalonePageHandlers[desktop.currentPage]`, call the `renderStandalonePage` function and pass `handler` as a parameter to the function

then else if `handler, ok := desktop.navPageHandlers[desktop.currentPage]`, call the `renderNavPage` function and pass `handler` in as a parameter as well

finally, if current page does not exist as a key in `desktop.standalonePageHandlers` and `desktop.navPageHandlers`, show an error message in `window`. Of course, this last case should not happen but good to write code like this to catch it in case it does happen. Also, this prepares the ground to support other possible ways of rendering a window.

2019-01-29 15:13 UTC, itswisdomagain commented on nuklear/desktop.go
> +func (desktop *Desktop) renderWithNav(window *nucular.Window) {
`renderNavPage` here, to par with the alternate function `renderStandalonePage`

2019-01-29 15:13 UTC, itswisdomagain commented on nuklear/desktop.go
>  	if desktop.currentPage == "" { // ideally, this should only be false once in the lifetime of an instance
There's a comment above about always setting a value for `desktop.currentPage` when the app is launched, doing that would render this check unnecessary.

2019-01-29 15:13 UTC, itswisdomagain commented on nuklear/handlers/createwallet.go
> +					contentWindow.Label("", "LC")
From your form validation code below, this should never happen, so we can gladly take this off. Best to keep it that way too, one error message on the password region is okay.

2019-01-29 15:13 UTC, itswisdomagain commented on nuklear/helpers/style.go
> +	WhiteColor             = color.RGBA{255, 255, 255, 255}
`WhiteColor` is only used in this package, good to keep it private `whiteColor`. Also confirm that other variables declared publicly here are actually needed outside the package. Would be good to group public variables separate from private variables using an empty line to separate them. Public variables would ideally be declared first

2019-01-29 15:13 UTC, itswisdomagain commented on nuklear/helpers/style.go
> +	WhiteColor             = color.RGBA{255, 255, 255, 255}
Also add a `colors.go` file and put all these there, especially since some of these variables are used outside this file but in this same package

2019-01-29 15:20 UTC, itswisdomagain requested changes

2019-01-29 15:20 UTC, itswisdomagain commented on nuklear/handlers/createwallet.go
> +					handler.err = wallet.CreateWallet(string(handler.passwordInput.Buffer), handler.seed)
- after creating the wallet, a blockchain sync should be performed (could just add a comment for now and implement it later since similar functionality is required when the nuklear app is launched)
- should also change the page if the wallet creation succeeds, it doesn't currently, user has to close and re-launch

2019-01-31 14:52 UTC, itswisdomagain commented on nuklear/desktop.go
> +	standalone bool
This is a big no, why duplicating this property in 2 structs? There was a recommendation to maintain 2 handler maps without duplication, anything wrong with that approach? Will continue review after this is attended to.

2019-02-06 17:05 UTC, itswisdomagain requested changes

2019-02-06 17:05 UTC, itswisdomagain commented on nuklear/handler.go
> +	Render(*nucular.Window, app.WalletMiddleware, func(page string))
The changes to this method now require a different interface. All handlers except the create wallet handler do not need
- `app.WalletMiddleware`, a minimal version `walletcore.Wallet` is all that's needed
- `func(page string)` is not at all needed in other handlers

Instead of having all handlers declare parameters that they'll never use, better to have difference interfaces with the ability to provide just the dependencies required by each handler to perform its operation. Look into the cli interface to see how similar objective is achieved.

2019-02-06 17:05 UTC, itswisdomagain commented on nuklear/handler.go
> +type handlerData struct {
The data defined in this `handlerData` struct best describes a page. It makes sense for a page to have a `name`, a `label`, to be `standalone` or not, to have a `handler`. Other related comments brings the need for this change to life.

2019-02-06 17:05 UTC, itswisdomagain commented on nuklear/handler.go
> +func getHandlers() []handlerData {
This would be `getPages()` based on the previous comment

2019-02-06 17:05 UTC, itswisdomagain commented on nuklear/desktop.go
> +	desktop.renderNavPage(window, handler.handler)
`handler.handler` doesn't make much sense. Here's what makes more sense.
- line 72 reads better as `page := desktop.pages[desktop.currentPage]`
- line 73 reads better as `if page.standalone`
- line 74 reads better as `desktop.renderStandalonePage(window, page.handler)`, same goes for this line 78

2019-02-06 17:05 UTC, itswisdomagain commented on nuklear/helpers/style.go
>  	ColorText:                  color.RGBA{106, 106, 106, 255},
These color constants should also go to the `colors.go` file

2019-02-06 17:48 UTC, itswisdomagain commented
Also run `go mod tidy` to update `go.mod`

2019-02-28 12:35 UTC, itswisdomagain approved these changes

2019-02-28 12:36 UTC, merged