Introduced stimulusjs on web
raedahgroup/godcr-old pull request #190
Opened 2019-01-28 15:59 UTC by ademuanthony

Resolved #170 

This PR introduced stimulus on the web and reduced the use of jquery
Jquery is not entirely removed as the frontend template uses bootstrap which depends on jquery.
This PR also uses npm for dependency management

Follow this instruction to run the app

1. `cd web`
2. `sudo npm install`
3. `npm run build`
4. You can now run `./godcr --mode=http`

2019-01-31 14:40 UTC, itswisdomagain requested changes
I've only reviewed the usage of babel, webpack, eslint and stylelint so far. Will review the usage of stimulus and axios next

2019-01-31 14:40 UTC, itswisdomagain commented on .gitignore
> +web/package-lock.json
You shouldn't ignore `package-lock.json`, it's important to keep track of the versions of different packages used to prevent issues that could arise when breaking changes are introduced in later versions

2019-01-31 14:40 UTC, itswisdomagain commented on web/package.json
> +    "webpack-merge": "^4.2.1"
`webpack-merge` should be a dev dependency - it's only used during build by the webpack config files

2019-01-31 14:40 UTC, itswisdomagain commented on web/webpack/webpack.common.js
> +    new StyleLintPlugin()
This is not properly configured, css errors are not caught currently when `npm run build` is run

2019-01-31 14:40 UTC, itswisdomagain commented on web/package.json
> +  "devDependencies": {
- `@babel/plugin-syntax-dynamic-import` isn't registered as a plugin in `.babelrc`, not necessary
- `babel-polyfill` is not properly setup. See https://babeljs.io/docs/en/next/babel-polyfill.html
- `clean-webpack-plugin` doesn't have any real use, can go
- `stimulus` is not a dev dependency
- `style-loader` isn't used anymore, can go
- `stylelint` isn't properly configured, might consider taking off related deps

2019-01-31 14:44 UTC, itswisdomagain commented
Should consider bundling all js files to `public/js` rather than having js files in `public/js` and `public/dist/js`
This would mean adding bootstrap and jquery to webpack bundles. [This](https://stevenwestmoreland.com/2018/01/how-to-include-bootstrap-in-your-project-with-webpack.html) may help.

2019-01-31 14:48 UTC, itswisdomagain commented on web/webpack/webpack.common.js
> +    new StyleLintPlugin()
To properly set this up, would need to pass in some options to `StyleLintPlugin()` and add a `.stylelintrc` file that `"extends": "stylelint-config-standard"`

2019-02-06 17:55 UTC, itswisdomagain requested changes
With regards to the dependencies, let's aim to keep things as simple as possible. We can add support for other stuffs such as sass/scss later when they become more necessary.

2019-02-06 17:55 UTC, itswisdomagain commented on web/package.json
> +    "autoprefixer": "^9.4.7",
`autoprefixer` and `babel-polyfill` should be devDependencies I believe

2019-02-06 17:55 UTC, itswisdomagain commented on web/webpack/webpack.common.js
> +      {
Do we need these things at this time? [See here](https://medium.com/a-beginners-guide-for-webpack-2/webpack-loaders-css-and-sass-2cc0079b5b3a) for how style-loader work. For brevity, using style-loader, there would be no need to link to css files, instead css files would need to simply be imported or required in js code and the css file content will be injected into the html dom structure

Not sure we need this for now, we can keep linking to css files from html files and use a later PR to change this behaviour if necessary.

2019-02-06 17:55 UTC, itswisdomagain commented on web/webpack/webpack.common.js
> +    new MiniCssExtractPlugin({
Also don't see a need for this

2019-02-06 17:55 UTC, itswisdomagain commented on web/yarn-error.log
> +Arguments:
This and other log files have no real use in shared repo, should add `*.log` to gitignore.

2019-02-06 17:55 UTC, itswisdomagain commented on web/package.json
> +    "popper.js": "^1.14.7",
Are these `bootstrap `, `jquery` and `popper.js` deps used? I still see the downloaded, minified js files for bootstrap and jquery in `/web/public/js`

If they're not use, they should be removed from this file along with references to them...

2019-02-10 09:52 UTC, itswisdomagain requested changes
Looking better, will review again after these changes

2019-02-10 09:52 UTC, itswisdomagain commented on .gitignore
> +# files generated by qt
These qt files need no longer be git ignored, a recent PR removed the qt interface and along with it, any qt generated files. If you still have such files in your working directory, manually delete them to ensure they don't get added to future commits.

2019-02-10 09:52 UTC, itswisdomagain commented on web/.eslintrc.json
> +        "jquery": true
What's this do? Useful?

2019-02-10 09:52 UTC, itswisdomagain commented on web/views/layout.html
> +    <link rel="stylesheet" href="/static/css/bootstrap.min.css?v={{timestamp}}"/>
`bootstrap.min.css` shouldn't need versioning, since it shouldn't be modified

2019-02-10 09:52 UTC, itswisdomagain commented on web/views/layout.html
> +    window.$(function(){
we can revert to simply using `$`

2019-02-10 21:24 UTC, ademuanthony commented on web/.eslintrc.json
> +        "jquery": true
Yes, otherwise eslint will flag `$` as undefined

2019-02-12 05:08 UTC, merged