Send page nuklear
raedahgroup/godcr-old pull request #191
Opened 2019-01-29 12:10 UTC by codemaestro64

This adds the send page to the nuklear app

2019-01-30 08:52 UTC, ademuanthony requested changes
I am unable to paste content from the clipboard into the address field

2019-01-30 09:02 UTC, ademuanthony requested changes

2019-01-30 09:02 UTC, ademuanthony commented on nuklear/handlers/send.go
> +		utxos, totalInputAmount := handler.getUTXOSAndSelectedAmount()
If a user is selecting custom input, we have to verify that the total amount selected is enough to cover the transaction amount

2019-01-30 09:02 UTC, ademuanthony commented on nuklear/handlers/send.go
> +	}
It will be nice to reset the form after a successful transaction

2019-01-31 11:36 UTC, itswisdomagain requested changes
- Need to add sync functionality in a separate PR to make this PR work. Trying to send funds says `decred wallet backend is unreachable`
- Need to remove the [WIP] text from the Send button in the navigation window as well

2019-01-31 11:36 UTC, itswisdomagain commented on nuklear/handlers/send.go
> +
can do without this empty line

2019-01-31 11:36 UTC, itswisdomagain commented on nuklear/handlers/send.go
> +	addressErrStr      string
the type already shows this is a string, the variable name need not repeat it, `addressErr` and `amountErr` is just fine

2019-01-31 11:36 UTC, itswisdomagain commented on nuklear/handlers/send.go
> +type input struct {
The data defined in this struct does not represent a generic input but rather a recipient / destination set. Variable name can be better

2019-01-31 11:36 UTC, itswisdomagain commented on nuklear/handlers/send.go
> +	inputs []*input
Similar to the comments above, this variable `inputs` does not represent generic inputs, it's actually an input set and the variable should be better named to show what it holds

2019-01-31 11:36 UTC, itswisdomagain commented on nuklear/handlers/send.go
> +// fetch accounts for select source account field
`// fetch accounts to display in select source account dropdown`

2019-01-31 11:36 UTC, itswisdomagain commented on nuklear/handlers/send.go
> +			if handler.err != nil {
Have you noticed that lines 76 to 81 above are repeated across different pages? Could refactor into a function. Could modify the `helpers.NewWindow` function to do the following
- create the page window
- draw the header
- create the content window
- set the font
- return the page window and content window

2019-01-31 11:36 UTC, itswisdomagain commented on nuklear/handlers/send.go
> +	selectedAccountIndex int
should group related variables, `selectedAccountIndex` should be with `accountNumbers` and `accountOverviews`

2019-01-31 11:36 UTC, itswisdomagain commented on nuklear/handlers/send.go
> +			for i := 0; i < len(handler.inputs); i++ {
Can simplify to `for _, destInputPair := range handler.inputs`

2019-01-31 11:36 UTC, itswisdomagain commented on nuklear/handlers/send.go
> +			if contentWindow.ButtonText("Add anohter address") {
`another`

2019-01-31 11:36 UTC, itswisdomagain commented on nuklear/handlers/send.go
> +				if contentWindow.ButtonText("Remove last address") {
this can be simplified to `if len(handler.inputs) > 1 && contentWindow.ButtonText("Remove last address")`
the button will not be drawn if the first if evaluates to false

2019-01-31 11:36 UTC, itswisdomagain commented on nuklear/handlers/send.go
> +				contentWindow.Row(20).Ratio(0.1, 0.3, 0.2, 0.2, 0.2)
I've also noticed this form of creating a table in at least one other page. Can this be refactored into a `drawTable` function? Perhaps taking, `columnWidthRatios []float64, rowHeader []string, rows [][]string`

2019-01-31 11:36 UTC, itswisdomagain commented on nuklear/handlers/send.go
> +				contentWindow.Row(20).Ratio(0.1, 0.3, 0.2, 0.2, 0.2)
This could also be something for later anyways

2019-01-31 11:36 UTC, itswisdomagain commented on nuklear/handlers/send.go
> +func (handler *SendHandler) addSendInputPair(updateWindow bool, window nucular.MasterWindow) {
`updateWindow` should probably be the second parameter to this function

2019-01-31 11:36 UTC, itswisdomagain commented on nuklear/handlers/send.go
> +	handler.inputs = handler.inputs[:len(handler.inputs)-1]
should set `handler.inputs[len(handler.inputs)-1] = nil` first

2019-01-31 11:36 UTC, itswisdomagain commented on nuklear/handlers/send.go
> +		if string(input.amount.Buffer) == "" {
should also check to ensure that the amount is a valid amount (> 0)

2019-01-31 11:36 UTC, itswisdomagain commented on nuklear/handlers/send.go
> +		if string(input.destinationAddress.Buffer) == "" {
Should also check that the address is a valid address (as is done in the cli interface)

2019-01-31 11:36 UTC, itswisdomagain commented on nuklear/handlers/send.go
> +				handler.validateAndSubmit(window, wallet)
should not recall this function if `handler.isSubmitting == true`, or the function could check if `handler.isSubmitting == true` and return without performing any op

2019-01-31 11:36 UTC, itswisdomagain commented on nuklear/handlers/send.go
> +	for index := range handler.inputs {
Is there a reason you're using `index` and not `_, input`?

2019-01-31 11:36 UTC, itswisdomagain commented on nuklear/handlers/send.go
> +	var utxos []string
`totalInputAmount` and `utxos` could be named return variables

2019-01-31 11:36 UTC, itswisdomagain commented on nuklear/handlers/send.go
> +	for i := range handler.utxos {
`for _, utxo` instead

2019-01-31 11:36 UTC, itswisdomagain commented on nuklear/handlers/send.go
> +// fetchCustomInputsCheck is called everytime the 'select custom inputs' checbox is checked or unchecked.
`checbox` => `checkbox`

2019-01-31 11:36 UTC, itswisdomagain commented on nuklear/handlers/send.go
> +		handler.fetchUTXOError = err
should also add `handler.isFetchingUTXOS = false` so that the render function shows the error message instead of showing the loading indicator

2019-01-31 11:36 UTC, itswisdomagain commented on nuklear/handlers/send.go
> +	defer window.Master().Changed()
should also reset `handler.isSubmitting` to false when this function returns to update the UI accordingly
```
defer func() {
	window.Master().Changed()
	handler.isSubmitting = false
}()
```

2019-01-31 11:38 UTC, itswisdomagain requested changes
Missed this

2019-01-31 11:38 UTC, itswisdomagain commented on nuklear/handlers/send.go
> +		utxos = append(utxos, handler.utxos[i].utxo.Address)
- you should only append to the slice if the utxo is selected
- you should be appending `utxo.OutputKey` not `Address`

2019-01-31 15:06 UTC, itswisdomagain commented
Need to separate the UI into sections with some space between sections to look better. Everything currently looks jumbled together

![screenshot 2019-01-31 at 8 50 37 am](https://user-images.githubusercontent.com/18400051/52063065-1a583a80-2572-11e9-9caf-0a91baae87c5.png)

2019-02-02 12:09 UTC, codemaestro64 commented on nuklear/handlers/send.go
> +			if handler.err != nil {
i've reserved this for a later PR

2019-02-02 12:09 UTC, codemaestro64 commented on nuklear/handlers/send.go
> +				contentWindow.Row(20).Ratio(0.1, 0.3, 0.2, 0.2, 0.2)
also reserved this for a later PR

2019-02-02 12:10 UTC, codemaestro64 commented on nuklear/handlers/send.go
> +		handler.fetchUTXOError = err
done

2019-02-03 04:00 UTC, itswisdomagain requested changes
Still getting `Decred network is unreachable` error, send feature is not working

Also, the error message should wrap so it can be completely displayed
![screenshot 2019-02-03 at 4 37 47 am](https://user-images.githubusercontent.com/18400051/52172488-a768e280-2770-11e9-9356-4ea92f45eb18.png)

2019-02-03 04:00 UTC, itswisdomagain commented on nuklear/handlers/send.go
> +			amountInt, err := strconv.ParseFloat(amountStr, 64)
`amountInt`? You're parsing float...

2019-02-03 04:00 UTC, itswisdomagain commented on nuklear/handlers/send.go
> +					handler.fetchCustomInputsCheck(wallet, masterWindow)
No need to validate the form before displaying custom inputs, an invalid form would only affect form submission. User should be able to view and select custom inputs even if the form has invalid fields. Doesn't affect listing/selecting custom inputs

2019-02-03 04:00 UTC, itswisdomagain commented on nuklear/handlers/send.go
> +				if handler.validate(window, wallet) {
validation should not be performed if a form submission process is already ongoing. Also, need to clear `handler.err` before validation - assuming of course, that the form is not already being submitted.

2019-02-27 13:41 UTC, codemaestro64 commented on nuklear/handlers/send.go
> +		utxos, totalInputAmount := handler.getUTXOSAndSelectedAmount()
validation rules concerning this have been added

2019-02-27 13:42 UTC, codemaestro64 commented on nuklear/handlers/send.go
> +	}
done

2019-02-28 12:40 UTC, itswisdomagain commented
Will revisit this PR after #207 is merged. @codemaestro64, you'll need to rebase, may wait till #207 is merged

2019-03-05 12:24 UTC, itswisdomagain requested changes

2019-03-05 12:24 UTC, itswisdomagain commented on nuklear/handler.go
> +		{
The nav order should be maintained. Balance, receive, send... Compare the http interface

2019-03-05 12:24 UTC, itswisdomagain commented on terminal/terminal.go
> +		AddItem("Purchase Tickets", "", 't', func() {
Why does this PR include these changes?

2019-03-05 12:24 UTC, itswisdomagain commented on test/config_test.go
> +package test
This file belongs in a different PR, please remove

2019-03-05 12:24 UTC, itswisdomagain commented on web/routes/walletloader.go
> +		blockchainSyncStatus = walletcore.SyncStatusSuccess
This was meant to be a temporary hack I believe. Please remove

2019-03-05 12:29 UTC, codemaestro64 commented on terminal/terminal.go
> +		AddItem("Purchase Tickets", "", 't', func() {
Did a rebase that caused conflicts.

2019-03-05 12:51 UTC, itswisdomagain requested changes
After successful sending, only 1 set of destination address fields should be left on the page; and the utxo list should be cleared

![screenshot 2019-03-05 at 1 49 29 pm](https://user-images.githubusercontent.com/18400051/53806655-cb753a80-3f4d-11e9-9764-0e1fb04ad652.png)

2019-03-05 12:53 UTC, ademuanthony approved these changes

2019-03-05 14:14 UTC, itswisdomagain requested changes

2019-03-05 14:14 UTC, itswisdomagain commented on nuklear/handlers/send.go
> +	handler.sendDetailInputPairs[0].amount.Buffer = []rune("")
This throws `panic: runtime error: index out of range`

2019-03-05 15:15 UTC, itswisdomagain approved these changes

2019-03-05 15:15 UTC, merged