add detailed and simple views to balance page on nuklear
raedahgroup/godcr-old pull request #194
Opened 2019-01-30 12:25 UTC by codemaestro64

This adds the option of displaying simple and detailed balance to the balance page of the nuklear app interface. 

Fixes #181

2019-01-30 13:11 UTC, ademuanthony requested changes

2019-01-30 13:11 UTC, ademuanthony commented on nuklear/handlers/balance.go
> +
empty space should be remove

2019-01-31 15:02 UTC, itswisdomagain requested changes
After building, I'm unable to run the desktop app with `godcr --mode=nuklear`. It just prints a "launching" message on my terminal and exits without even showing the window. Anyone else having this issue?

Also, preliminary review below shows that this code does not yet produce the expected behaviour. Will test more when that is fixed and I'm able to run the app in nuklear mode.

2019-01-31 15:02 UTC, itswisdomagain commented on nuklear/handlers/balance.go
> +func (handler *BalanceHandler) showDetailedView(window *nucular.Window) {
`showSimpleView` should come before this method

2019-01-31 15:02 UTC, itswisdomagain commented on nuklear/handlers/balance.go
> +					handler.showSimpleView(content.Window)
Don't understand what's going on here. Please compare the http interface for what's expected. 1 anomaly I've noticed is mentioned in the next comment...

2019-01-31 15:02 UTC, itswisdomagain commented on nuklear/handlers/balance.go
> +			window.Label(account.Balance.Spendable.String(), "LC")
`if handler.detailed == true`, line 81 would be showing the wrong value for the `Balance` column. Detailed view should not combine the total balance and spendable balance in the `Balance` column

2019-02-04 20:43 UTC, itswisdomagain requested changes
The second column here is trimmed off, what can be done about it?
![screenshot 2019-02-04 at 9 41 08 pm](https://user-images.githubusercontent.com/18400051/52235953-c88f1780-28c5-11e9-9ace-212fb1b6e315.png)

2019-02-04 20:43 UTC, itswisdomagain commented on app/shared.go
> +func SimpleBalance(balance *walletcore.Balance, detailed bool) string {
There is an existing file where this function could be better placed: `app/walletcore/helper.go`

2019-02-04 20:43 UTC, itswisdomagain commented on nuklear/handlers/balance.go
> +					handler.showDetailedView(content.Window)
This function does not only cover scenarios where `handler.detailed == true`, it also covers scenario where the `handler.detailed == false`. Better to rename this to `showTabularView` or something that more closely represent what the function actually does

2019-02-05 10:43 UTC, itswisdomagain approved these changes

2019-02-05 12:21 UTC, ademuanthony approved these changes

2019-02-05 12:22 UTC, merged