Apply Decred Color to terminal ui
raedahgroup/godcr-old pull request #198
Opened 2019-02-04 11:44 UTC by hintact-platform

Applying Decred color and improving the design of the terminal ui

![17](https://user-images.githubusercontent.com/15618127/52206325-285fd100-287a-11e9-8448-052c5cc4622f.png)

2019-02-05 15:41 UTC, ademuanthony requested changes
Good job
Just few observations below

2019-02-05 15:41 UTC, ademuanthony commented on terminal/pages/history.go
> +	color := tcell.NewRGBColor(255, 255, 255)
seeing that you also used this color in other function below, I think it should be moved up as package level variable. `labelColor` should be a descriptive name

2019-02-05 15:41 UTC, ademuanthony commented on terminal/pages/send.go
> +	body.SetLabelColor(tcell.NewRGBColor(255, 255, 255))
use the color created above

2019-02-05 15:41 UTC, ademuanthony commented on terminal/terminal.go
> +	menuColumn.SetShortcutColor(tcell.NewRGBColor(112, 203, 255))
This color should be created at as package level variable as well. `borderColor` should be a good name

2019-02-28 12:42 UTC, itswisdomagain commented
@Sirmorrison please take this up to completion. Discuss with @raedah and @ademuanthony for details of this task.

2019-02-28 16:27 UTC, Sirmorrison commented
on it

2019-02-28 22:06 UTC, itswisdomagain commented
This solution is completed in #211

2019-02-28 22:06 UTC, closed without merging