implement the terminal UI history page
raedahgroup/godcr-old pull request #200
Opened 2019-02-06 03:02 UTC by Sirmorrison

made the terminal history demo page to into a full functional history page by fetching the wallet history from wallet core

2019-02-06 20:36 UTC, itswisdomagain requested changes

2019-02-06 20:36 UTC, itswisdomagain commented on terminal/pages/history.go
> +		color := tcell.ColorYellow
`go fmt ./...` please

2019-02-06 20:36 UTC, itswisdomagain commented on terminal/terminal.go
> +	// "github.com/raedahgroup/godcr/cli/walletloader"
commented code should not make their way into shared repo, also don't see the need for the empty line space in line 10 above

2019-02-06 20:36 UTC, itswisdomagain commented on terminal/terminal.go
> +	// err := syncBlockChain(ctx, walletMiddleware)
commented code should not be committed into repo
also, while it may be necessary to remove this code for testing, it's important to retain it in the project source code
what should ideally be done about this is to stop displaying sync progress as messages on the terminal and instead use a progress bar on the terminal UI app, but that's for a later PR

2019-02-06 20:36 UTC, itswisdomagain commented on terminal/terminal.go
> +			changePageColumn(pages.HistoryPage(terminal.wallet))
You could just pass `walletMiddleware` here directly, don't see no need for the `Terminal` struct type or the `terminal` variable declared in line 46.

2019-02-06 20:36 UTC, itswisdomagain commented on terminal/terminal.go
> +
this space is unnecessary

2019-02-06 20:36 UTC, itswisdomagain commented on terminal/pages/history.go
> +		color := tcell.ColorYellow
Getting an `undefined: tcell` error from this line, PR is not building

2019-02-06 20:36 UTC, itswisdomagain commented on terminal/pages/history.go
> +	body.SetCell(0, 0, tview.NewTableCell("Date").SetAlign(tview.AlignCenter).SetBackgroundColor(color))
Not sure what this background color does, can't notice it in the screenshot attached to this PR

2019-02-06 20:36 UTC, itswisdomagain commented on terminal/pages/history.go
> +		i = i + 1
no, no, no,
don't re-assign (change the value of) a loop variable, it automatically increases and that behaviour should be maintained
Instead create another variable to use as appropriate: `row := i + 1`

2019-02-06 20:36 UTC, itswisdomagain commented on terminal/pages/history.go
> +	return fmt.Sprintf("%d DCR", int(amount))
Why rounding the amount to remove the decimal part? Space?
Assuming this is necessary, there is another function of this nature in the nuklear interface, to avoid code repetition, put this function in `app/walletcore/helpers.go` and have both this interface and the nuklear interface call the function from there.

2019-02-07 01:00 UTC, itswisdomagain requested changes

2019-02-07 01:00 UTC, itswisdomagain commented on main.go
> +		err := fmt.Errorf("%s: %v", "loadConfig", err.Error())
not part of this PR, but this code could be better written: `fmt.Errorf("loadConfig: %s", err.Error())`
- `err.Error()` is of type string
- string formatting should be for variables not string literals

2019-02-07 01:00 UTC, itswisdomagain commented on terminal/pages/history.go
> +func HistoryPage(walletMiddleware app.WalletMiddleware) tview.Primitive {
this can be, and should be `wallet walletcore.Wallet`, you can still call `HistoryPage` with `app.WalletMiddleware ` because `app.WalletMiddleware` is a super type of `walletcore.Wallet`

2019-02-07 01:00 UTC, itswisdomagain commented on web/server.go
>  	// fmt.Println("Web server stopped")
Commented code in repo? No please

2019-02-07 01:15 UTC, itswisdomagain requested changes

2019-02-07 01:15 UTC, itswisdomagain commented on terminal/terminal.go
> -	err := syncBlockChain(ctx, walletMiddleware)
Restore this sync functionality. The `syncBlockChain` also opens the wallet without which trying to use the wallet to perform operations like load history causes the app to panic with the following error: `panic: runtime error: invalid memory address or nil pointer dereference`

2019-02-07 21:45 UTC, itswisdomagain requested changes
In addition to the changes below, also make the history table scrollable. That might mean, focusing the table instead of the nav menu, which would also require a way to move focus back to the menu in case the user wants to select another menu item. Compare how similar stuff is done in `SendPage`

2019-02-07 21:45 UTC, itswisdomagain commented on terminal/pages/history.go
> +		panic(err)
This is a big no, `panic` causes the app to fail ungracefully. Should instead use a view to display the error message and return

2019-02-07 21:45 UTC, itswisdomagain commented on terminal/terminal.go
> +	list.SetBorder(true).SetTitle(fmt.Sprintf("%s Terminal", strings.ToUpper(app.Name)))
There should be a space between this line 27 and the next line 28, to show separation of concerns

2019-02-09 15:18 UTC, itswisdomagain submitted a review, later dismissed
There was a previous comment about making the history table scrollable. Is that done yet? I'll test after this last change mentioned below is attended to

2019-02-09 15:18 UTC, itswisdomagain commented on terminal/pages/history.go
> +		fmt.Println(err)
- seeing as this is a GUI mode, errors should not simply be printed to terminal, they should be displayed on the GUI page
- should return if there's an error, there's no need to show table headers when an error occurs, just show the error message

Here's something that could work (with some tweaking if possible):
```
if err != nil {
    return tview.NewTextView().SetTextAlign(tview.AlignCenter).SetText(err.Error())
}
```

Going with this approach, the declaration `body := tview.NewTable().SetBorders(true)` should be moved to after the if statement, since it will never be use before that point

2019-02-19 21:53 UTC, ademuanthony commented
You need to `go fmt ./...`

2019-02-19 22:00 UTC, ademuanthony requested changes

2019-02-19 22:00 UTC, ademuanthony commented on terminal/pages/history.go
> +	for i, tx := range transactions {
Can we have the history paginated?
This result will keep building up and it will become a lot to handle at one call

2019-02-20 04:48 UTC, ademuanthony requested changes

2019-02-20 04:48 UTC, ademuanthony commented on nuklear/handlers/transactions.go
> +						contentWindow.Label(walletcore.AmountToString(tx.Amount.ToCoin()), "LC")
Use `tx.Amount.String()` instead

2019-02-20 04:48 UTC, ademuanthony commented on nuklear/handlers/transactions.go
> +						contentWindow.Label(walletcore.AmountToString(tx.Fee.ToCoin()), "LC")
Use `tx.Amount.String()` instead

2019-02-20 04:48 UTC, ademuanthony commented on app/walletcore/helper.go
> +func AmountToString(amount float64) string {
You can delete this function as it's same as `amount.String()`
update the consumers both and `terminal/history.go` and in `nuklear/handlers/transactions.go` line 53 and 54

2019-02-20 10:45 UTC, ademuanthony requested changes

2019-02-20 10:45 UTC, ademuanthony commented on app/walletcore/helper.go
> -
app\walletcore\helper.go:6:2: imported and not used: "math"
Please also test your code locally before giving out for review

2019-02-20 10:55 UTC, ademuanthony approved these changes

2019-02-20 10:59 UTC, merged