[WIP]terminal ui send page implementation
raedahgroup/godcr-old pull request #201
Opened 2019-02-08 11:11 UTC by Sirmorrison

2019-03-08 21:30 UTC, itswisdomagain requested changes

2019-03-08 21:30 UTC, itswisdomagain commented on terminal/pages/send.go
> +		return body.AddItem(textView.SetText(fmt.Sprintf("Error: %s", err.Error())), 0, 1, false)
Follow the pattern suggested in the recent review of #213:
- Move the declaration of `textView` lower
- Rename the `textView` variable
- Use a function for displaying output message

2019-03-08 21:30 UTC, itswisdomagain commented on terminal/pages/send.go
> +	form := tview.NewForm()
Move this below to just before where it's used

2019-03-08 21:30 UTC, itswisdomagain commented on terminal/pages/send.go
> +	form.AddDropDown("Account", accountNames, 0, func(option string, optionIndex int) {
Should maintain the same terms and expressions across all the interfaces. The web calls this dropdown "Source Account", do same.

2019-03-08 21:30 UTC, itswisdomagain commented on terminal/pages/send.go
> +	form.AddCheckbox("spend Unconfirmed", false, func(checked bool) {
"Spend Unconfirmed"

2019-03-08 21:30 UTC, itswisdomagain commented on terminal/pages/send.go
> +	form.AddCheckbox("Select custom inputs", false, func(checked bool) {
Take this off, add it when the implementation is ready

2019-03-08 21:30 UTC, itswisdomagain commented on terminal/pages/send.go
> +		sendDestinations := make([]txhelper.TransactionDestination, len(destination))
How many destinations? Thought this PR only supports sending to one destination?

2019-03-08 21:30 UTC, itswisdomagain commented on terminal/pages/send.go
> +	form.AddButton("Cancel", func() {
What about `form.SetCancelFunc`?

2019-03-08 21:30 UTC, itswisdomagain commented on terminal/terminal.go
> -			tviewApp.Stop()
Why is this deleted?

2019-03-08 22:19 UTC, Sirmorrison commented on terminal/terminal.go
> -			tviewApp.Stop()
mistake from rebase

2019-03-11 19:22 UTC, itswisdomagain requested changes

2019-03-11 19:22 UTC, itswisdomagain commented on terminal/pages/send.go
> +		if checked {
Seriously? A recent review discussed this. Simply `spendUnconfirmed  = checked`

2019-03-11 19:22 UTC, itswisdomagain commented on terminal/pages/send.go
>  	//Form for Sending
`// form for sending`
There should be a space between the second forward slash and the comment

2019-03-11 19:22 UTC, itswisdomagain commented on terminal/pages/send.go
> +	form.AddButton("Send", func() {
Should be a space before this line

2019-03-11 19:22 UTC, itswisdomagain commented on terminal/pages/send.go
> +		for i := range destination {
I believe I asked this in a previous review comment; how many destinations does this PR support sending to? Why are you creating multiple destinations, each having the same amount and address?

More importantly, what does `len(destination)` mean?

2019-03-11 19:22 UTC, itswisdomagain commented on terminal/pages/send.go
> +			Amount, err := strconv.ParseFloat(string(amount), 64)
Although supported, not a good idea to use `Amount` and `amount` in the same scope - can be easily confusing. Rename one of the 2 variables. Also, variable names and function names should generally begin with lower case unless they are meant to be used/accessed outside a package

2019-03-21 07:17 UTC, itswisdomagain requested changes

2019-03-21 07:17 UTC, itswisdomagain commented on terminal/pages/send.go
> +	body.AddItem(tview.NewTextView().SetTextAlign(tview.AlignCenter).SetText("Send Fund"), 4, 1, false)
Just `Send`

2019-03-21 07:17 UTC, itswisdomagain commented on terminal/pages/send.go
> +			outputMessage(err.Error())
Don't display the error message, won't be user-friendly. Instead simply display `"Invalid amount"`

2019-03-21 07:17 UTC, itswisdomagain commented on terminal/pages/send.go
> +		fmt.Println(sendDestination)
This can go, yeah?

2019-03-21 07:17 UTC, itswisdomagain commented on terminal/pages/send.go
> +		outputMessage(result)
Combine lines 86 and 87: `outputMessage(fmt.Sprintf("Sent txid", txHash))`

2019-03-21 07:17 UTC, itswisdomagain commented on terminal/pages/send.go
> +	form.AddButton("Cancel", func() {
Remove the cancel button, let's rely on escape as we've always been doing

2019-03-21 13:12 UTC, itswisdomagain requested changes
There's too much space between the page title and the top of the form and between the bottom of the form (the send button) and the error message:
![Screenshot 2019-03-21 at 2 10 57 PM](https://user-images.githubusercontent.com/18400051/54754241-552a3680-4be3-11e9-8046-f69c3a36aef3.png)

2019-03-21 13:12 UTC, itswisdomagain commented on terminal/pages/send.go
> +		fmt.Println(sendDestination)
This is still here?

2019-03-21 13:12 UTC, itswisdomagain commented on terminal/pages/send.go
> +	accountNumber := make([]uint32, len(accounts))
`accountNumbers`

2019-03-21 13:12 UTC, itswisdomagain commented on terminal/pages/send.go
> +		accountNames[index] = fmt.Sprintf("%s - %s ", account.Name, account.Balance.Total.String())
`accountNames[index] = account.String()`

2019-03-21 13:12 UTC, itswisdomagain commented on terminal/pages/send.go
> +		outputMessage(fmt.Sprintf("Sent txid", txHash))
Just seeing this clearly. This can simplify to `outputMessage("Sent txid " + txHash)`
ps: note the space after "sent txid "

2019-03-21 20:10 UTC, raedah commented
Looks like the Destination address field isnt wide enough to show all the characters of the address.

Source account amount can be followed by the DCR suffix.

2019-03-22 15:11 UTC, Sirmorrison commented
![image](https://user-images.githubusercontent.com/27733432/54832759-15378200-4cbd-11e9-9f16-709d75cdab29.png)

2019-03-25 22:34 UTC, itswisdomagain requested changes
This is looking very merge-ready. Just a couple more additions

2019-03-25 22:34 UTC, itswisdomagain commented on terminal/pages/send.go
> +		outputMessage("Sent txid " + txHash)
Clear the form fields after successful purchase and set focus to the first form field.

2019-03-25 22:34 UTC, itswisdomagain commented on terminal/pages/send.go
> +		sendDestination := make([]txhelper.TransactionDestination, 1)
First thing to do when the Send button is clicked is clear/hide the message textview. I noticed that while the send transaction was ongoing, I was still seeing a previous error message.

2019-03-27 02:02 UTC, itswisdomagain approved these changes

2019-03-27 02:02 UTC, merged