implemented terminal stake info demo page to live
raedahgroup/godcr-old pull request #203
Opened 2019-02-11 07:36 UTC by Sirmorrison

![image](https://user-images.githubusercontent.com/27733432/52550357-17faa980-2dd8-11e9-876c-997f9d173edf.png)

2019-02-11 21:59 UTC, ademuanthony requested changes
I am experiencing a panic whenever I try to navigate to the `Stake info` page.
I am using decrlibwallet, the `walletrpcserver` is not set in the config

2019-02-12 14:48 UTC, Sirmorrison commented
> 
> 
> I am experiencing a panic whenever I try to navigate to the `Stake info` page.
> I am using decrlibwallet, the `walletrpcserver` is not set in the config

2019-02-19 20:36 UTC, ademuanthony commented on terminal/terminal.go
> +			changePageColumn(pages.StakeinfoPage(walletMiddleware, setFocus, clearFocus))
Since there is no user interaction on this page, the focus should remain on the menu

2019-02-19 21:46 UTC, ademuanthony commented on terminal/terminal.go
> +			changePageColumn(pages.StakeinfoPage(walletMiddleware, setFocus, clearFocus))
I see that the Esc key works as we discussed.
But we will need to have a help-tip at the footer of every page that explains the control keys

2019-02-19 21:46 UTC, ademuanthony approved these changes

2019-02-19 21:46 UTC, merged