add sync feature
raedahgroup/godcr-old pull request #207
Opened 2019-02-14 17:11 UTC by codemaestro64

This adds sync blockchain feature/page to the nuklear app. It runs automatically on running godcr in nuklear mode

2019-02-26 20:29 UTC, Sirmorrison requested changes

2019-02-26 20:29 UTC, Sirmorrison commented on nuklear/handlers/sync.go
> +
this space is not needed

2019-02-26 20:34 UTC, Sirmorrison requested changes

2019-02-26 20:34 UTC, Sirmorrison commented on nuklear/desktop.go
>  		return err
remove the commented line of code on line 72

2019-02-27 04:36 UTC, itswisdomagain commented on nuklear/desktop.go
>  		return err
Good catch @Sirmorrison. @codemaestro64, I understand that line wasn't introduced in this PR but shouldn't even be in master ideally. Please delete it...

2019-02-27 19:25 UTC, itswisdomagain requested changes

2019-02-27 19:25 UTC, itswisdomagain commented on nuklear/desktop.go
> +	startPage = "sync"
Can do without these `homePage` and `startPage` constants. `homePage` is only  referenced in line 133 **if desktop.currentPage == ""**, with  the  introduction  of the sync page, there should no longer be a case where currentPage is empty. Thus, the  if statement  can go.

`startPage` is only used in line 77. That line can be deleted and the declaration of `desktop` in line 34  modified to include the `currentPage: "sync"` property assignment.

2019-02-27 19:25 UTC, itswisdomagain commented on nuklear/desktop.go
> +	desktop.currentPage = startPage
Add `currentPage: "sync"`  to line 35 and delete this line and the `startPage` constant declaration

2019-02-27 19:25 UTC, itswisdomagain commented on nuklear/desktop.go
> +func (desktop *Desktop) renderNavPage(window *nucular.Window, handler NavPageHandler) {
`renderStandalonePage` should come before this function

2019-02-27 19:25 UTC, itswisdomagain commented on nuklear/handler.go
> +	Render(*nucular.Window, app.WalletMiddleware, func(string))
Introduce an alias for this function so it's expected usage is immediately obvious:
`type  pageChangeFunc func(string)`

2019-02-27 19:25 UTC, itswisdomagain commented on nuklear/handlers/sync.go
> +func (s *SyncHandler) Render(window *nucular.Window, wallet app.WalletMiddleware, pageChangeFunc func(string)) {
`pageChangeFunc` should be `changePage`  so line 45 makes more sense  as `changePage("balance")`

2019-02-27 19:25 UTC, itswisdomagain commented on nuklear/handler.go
> +type NavPageHandler interface {
`NavPageHandler` and `StandalonePageHandler` do not need to be exported

2019-02-27 19:25 UTC, itswisdomagain commented on nuklear/handlers/sync.go
> +	if contentWindow := helpers.NewWindow("dd", window, 0); contentWindow != nil {
Why is the title of this window  "dd"?

2019-02-27 19:25 UTC, itswisdomagain commented on nuklear/handlers/sync.go
> +type syncStatus uint8
this  exists in  the web interface  as well, abstract  shared code and  avoid repetition/duplication

2019-02-27 19:25 UTC, itswisdomagain commented on nuklear/handlers/sync.go
> +type syncStatus uint8
on further thought, seems to me that all you really need is to determine if the sync operation is completed, the other status are irrelevant. You can replace `SyncHandler.status` with `SyncHandler.syncCompleted (bool)` instead

2019-03-01 22:45 UTC, itswisdomagain requested changes

2019-03-01 22:45 UTC, itswisdomagain commented on nuklear/desktop.go
> +		err = fmt.Errorf("No wallet found. Use 'godcr create' to create a wallet before launching the desktop app")
This is already implemented, guess it was mistakenly taken out due to rebase. See https://github.com/raedahgroup/godcr/blob/master/nuklear/desktop.go#L50.

Also remember that after wallet is created, the next page should be sync page not balance...

2019-03-01 22:45 UTC, itswisdomagain commented on nuklear/desktop.go
> +		wallet:      walletMiddleware,
Why rename `walletMiddleware` to `wallet`. Remember there is a `walletcore.Wallet` type. The variable name `wallet` should only be associated with the `walletcore.Wallet` type to maintain consistency.

Always `wallet walletcore.Wallet` and `walletMiddleware app.WalletMiddleware`

2019-03-01 22:45 UTC, itswisdomagain commented on nuklear/desktop.go
> +		return nil
Should return `err` please

2019-03-01 22:45 UTC, itswisdomagain commented on nuklear/desktop.go
> +	navPages := getNavPagesData()
`getNavPages` is better, same for `getStandalonePages`

2019-03-01 22:45 UTC, itswisdomagain commented on nuklear/handler.go
> +	Render(*nucular.Window, app.WalletMiddleware, func(string))
Introduce an alias for this function so it's expected usage is immediately obvious:
`type pageChangeFunc func(string)`

2019-03-01 22:45 UTC, itswisdomagain commented on nuklear/handler.go
> +type navPageData struct {
Can this be just `navPage` rather than `navPageData`? It's obvious structs hold data for an object/entity, no need t append data to the object/entity name. It's like saying `WalletData`, just `Wallet` is fine. Same for `standalonePageData`, rename to `standalonePage`

2019-03-04 07:03 UTC, itswisdomagain requested changes
Create wallet -> Passphrase inputs are not masked
![screenshot 2019-03-04 at 7 58 51 am](https://user-images.githubusercontent.com/18400051/53715948-adc3aa80-3e53-11e9-8eac-7dadd212c099.png)

Wallet seed doesn't display completely (the last word in the screenshot below is "k" which is not a word). Also, individual words should not be broken (aimless is broken in the screenshot below)
![screenshot 2019-03-04 at 7 59 15 am](https://user-images.githubusercontent.com/18400051/53716070-f54a3680-3e53-11e9-8409-054019c2a98a.png)

2019-03-05 10:47 UTC, itswisdomagain approved these changes

2019-03-05 10:51 UTC, merged