Terminal ui tickets
raedahgroup/godcr-old pull request #213
Opened 2019-03-01 18:15 UTC by Sirmorrison

![image](https://user-images.githubusercontent.com/27733432/53657350-3f65c900-3c56-11e9-82d9-16637dd5a7a6.png)

2019-03-02 01:07 UTC, itswisdomagain requested changes
Please attend to the issues raised below before I can continue review

2019-03-02 01:07 UTC, itswisdomagain commented on terminal/pages/tickets.go
> +package pages
This file should be `purchase-tickets.go`. Let's make it easier for another dev to find his way around with less stress

2019-03-02 01:07 UTC, itswisdomagain commented on terminal/pages/tickets.go
> +		body.AddItem(form.AddDropDown("Source Account", []string{accountOverviews[index]}, 0, func(option string, optionIndex int) {
You're adding views/controls/widgets to the form and body multiple times, that's terrible!
Your loop should only be to append elements to the `accountNumbers` and `accountOverviews` slices.

```
accountNumbers := make([]uint32, len(accounts))
accountOverviews := make([]string, len(accounts))
for index, account := range accounts {
	accountOverviews[index] = fmt.Sprintf("%s - Total %s (Spendable %s)", account.Name, account.Balance.Total.String(), account.Balance.Spendable.String())
	accountNumbers[index] = account.Number
}
```

2019-03-02 01:07 UTC, itswisdomagain commented on terminal/pages/tickets.go
> +	textView := tview.NewTextView()
Variables should ideally be declared just before they're used. Don't declare variables in Jericho only to use them 10 years later in Samaria.

Where is `textView` and `form` used? Move the declarations to the line just before they're used

2019-03-02 01:07 UTC, itswisdomagain commented on terminal/pages/tickets.go
> +		body.AddItem(form.AddDropDown("Source Account", []string{accountOverviews[index]}, 0, func(option string, optionIndex int) {
Too much nesting done here, makes the code harder to read. Break it down. Notice also that the following example code follows the one above. Also notice the spacing for easier readability and the placement of variables (right before they're used)

```
accountNumbers := make([]uint32, len(accounts))
accountOverviews := make([]string, len(accounts))
for index, account := range accounts {
	accountOverviews[index] = fmt.Sprintf("%s - Total %s (Spendable %s)", account.Name, account.Balance.Total.String(), account.Balance.Spendable.String())
	accountNumbers[index] = account.Number
}

var accountNum uint32
form.AddDropDown("Source Account", accountOverviews, 0, func(option string, optionIndex int) {
	accountNum = accountNumbers[optionIndex]
})

var numTickets string
form.AddInputField("Number of tickets", "", 20, nil, func(text string) {
	numTickets = text
})
```

2019-03-02 21:01 UTC, Sirmorrison commented on terminal/pages/tickets.go
> +		body.AddItem(form.AddDropDown("Source Account", []string{accountOverviews[index]}, 0, func(option string, optionIndex int) {
declaring variables between the forms fields will not work as form is nested inside of a flex box.

2019-03-04 06:56 UTC, itswisdomagain requested changes

2019-03-04 06:56 UTC, itswisdomagain commented on terminal/pages/purchase-tickets.go
> +func PurchaseTicketPage(wallet walletcore.Wallet, setFocus func(p tview.Primitive) *tview.Application, clearFocus func()) tview.Primitive {
`PurchaseTicketsPage`

2019-03-04 06:56 UTC, itswisdomagain commented on terminal/pages/purchase-tickets.go
> +	textView := tview.NewTextView().SetTextAlign(tview.AlignCenter)
Why is `textView` declared here? Should be declared just above `form.AddButton` and the variable name should be more descriptive of its function. `errorTextView` perhaps

2019-03-04 06:56 UTC, itswisdomagain commented on terminal/pages/purchase-tickets.go
> +		if checked {
2 problems here
- If it is checked, `spendUnconfirmed` becomes true, if it is unchecked, `spendUnconfirmed` _remains_ true
- This can be simplified to `spendUnconfirmed = checked`

2019-03-04 06:56 UTC, itswisdomagain commented on terminal/pages/purchase-tickets.go
> +	form.AddButton("Submit", func() {
Give a single line space before this

2019-03-04 06:56 UTC, itswisdomagain commented on terminal/pages/purchase-tickets.go
> +	form.AddPasswordField("wallet Passphrase", "", 20, '*', func(text string) {
"W" in "Wallet Passphrase" should be capitalized. Also, the expression is now "Spending Passphrase"

2019-03-04 06:56 UTC, itswisdomagain commented on terminal/pages/purchase-tickets.go
> +			body.AddItem(textView.SetText(fmt.Sprintf("Error: %s", "Please specify the number of tickets to purchase")).SetDoneFunc(func(key tcell.Key) {
Why do we have `SetDoneFunc` in each of the lines of code where the error message is displayed? Line 76 below is how I expect it to be...

2019-03-04 06:56 UTC, itswisdomagain commented on terminal/pages/purchase-tickets.go
> +		body.RemoveItem(textView)
A single line space before this to show separation of concerns please

2019-03-04 06:56 UTC, itswisdomagain commented on terminal/pages/purchase-tickets.go
> +			body.AddItem(textView.SetText(fmt.Sprintf("Error: %s", "please enter your wallet passphrase")).SetDoneFunc(func(key tcell.Key) {
Only use string formatting when combining string literal with variable(s). You can simply use `"Error: please enter your wallet passphrase"` directly

2019-03-04 06:56 UTC, itswisdomagain commented on terminal/pages/purchase-tickets.go
> +	form.SetCancelFunc(func() {
This can simplify to `form.SetCancelFunc(clearFocus)`

2019-03-04 06:56 UTC, itswisdomagain commented on terminal/pages/purchase-tickets.go
> +		Account:               uint32(accountNum),
`accountNum` is already `uint32`, conversion is unnecessary

2019-03-05 13:00 UTC, itswisdomagain requested changes

2019-03-05 13:00 UTC, itswisdomagain commented on terminal/pages/purchase-tickets.go
> +	outputTextView := tview.NewTextView().SetTextAlign(tview.AlignCenter)
You can move this declaration lower to just before `form.AddButton` and use `tview.NewTextView().SetTextAlign(tview.AlignCenter)` below in line 23. The variable will not be reused in this case and it's pointless to keep a reference to it.

2019-03-05 13:00 UTC, itswisdomagain commented on terminal/pages/purchase-tickets.go
> +			spendUnconfirmed = checked
go fmt ./... please

2019-03-05 13:00 UTC, itswisdomagain commented on terminal/pages/purchase-tickets.go
> +			body.AddItem(outputTextView.SetText(fmt.Sprintf("Error: Please specify the number of tickets to purchase")), 0, 1, true)
P in "Please" should not be capitalized

2019-03-05 13:00 UTC, itswisdomagain commented on terminal/pages/purchase-tickets.go
> +			body.AddItem(outputTextView.SetText(fmt.Sprintf("Error: Please specify the number of tickets to purchase")), 0, 1, true)
Instead of having this set of code in multiple places, you can have a function `dislayError` that removes the outputTextView and re-adds it when called

2019-03-06 17:08 UTC, itswisdomagain requested changes

2019-03-06 17:08 UTC, itswisdomagain commented on terminal/pages/purchase-tickets.go
> +			outputMessage(nil, err)
Make the `outputMessage` function take a single string parameter. Then send the error message directly rather than creating an error object

2019-03-06 17:08 UTC, itswisdomagain commented on terminal/pages/purchase-tickets.go
> +			body.AddItem(outputTextView.SetText(fmt.Sprintf(err.Error())), 0, 1, true)
`fmt.Sprintf(err.Error())` is the same as `err.Error()`, only use fmt when COMBINING literal text with variable

2019-03-06 17:08 UTC, itswisdomagain commented on terminal/pages/purchase-tickets.go
> +		outputMessage(ticketHashes, nil)
Once you make the `outputMessage` function take a single string parameter, you can no longer pass the ticketHashes slice to the function.  Convert to string using `fmt.Sprintf("You have purchased %d ticket(s)\n%s", len(ticketHashes), strings.Join(ticketHashes, "\n"))` and pass the string message to be displayed

2019-03-08 19:44 UTC, itswisdomagain approved these changes

2019-03-08 19:44 UTC, merged