[WIP] Terminal create wallet
raedahgroup/godcr-old pull request #221
Opened 2019-03-08 21:35 UTC by Sirmorrison

![image](https://user-images.githubusercontent.com/27733432/54057140-5b3b1300-41f2-11e9-80dd-773b2d12d48b.png)

2019-03-08 21:46 UTC, itswisdomagain requested changes

2019-03-08 21:46 UTC, itswisdomagain commented on terminal/terminal.go
> -		// `Run` blocks until app.Stop() is called before returning
Restore this comment, it's important

2019-03-11 19:41 UTC, itswisdomagain requested changes
Make use of the `createwallet.go` file, and re-order the UI elements: Display wallet seed before the important notice and before the buttons

2019-03-14 07:27 UTC, itswisdomagain submitted a review, later dismissed

2019-03-14 07:27 UTC, itswisdomagain commented on terminal/createwallet.go
> +	newPrimitive := func(text string) tview.Primitive {
`newPrimitive` is not a good name, `primitive` is generic, can mean button or image or any other number of things really. Also not good enough to just say `newLabel`. `newWordWrappedTextView` perhaps

2019-03-14 07:27 UTC, itswisdomagain commented on terminal/createwallet.go
> +	walletExists, err := openWalletIfExist(ctx, walletMiddleware)
This doesn't belong in this file.
- This file should only deal with creating wallets, not opening one if it exists
- Very soon, we'd support creating new wallets even if a wallet already exists, which makes the previous point even more important

2019-03-14 07:27 UTC, itswisdomagain commented on terminal/createwallet.go
> +		var confPassword string
`confirmPassword` is better
Or even `passphrase` and `confirmPassphrase` respectively

2019-03-14 07:27 UTC, itswisdomagain commented on terminal/createwallet.go
> +			if hasStoredSeed == false {
`if !hasStoredSeed`

2019-03-14 07:27 UTC, itswisdomagain commented on terminal/createwallet.go
> +				outputMessage("please Store seed in a szfe location and check the box")
**safe**
"please" is not capitalised, but "Store" is?

2019-03-14 07:27 UTC, itswisdomagain commented on terminal/createwallet.go
> +			err := CreateWallet(tviewApp, seed, password, walletMiddleware)
The `CreateWallet` function isn't very big, you can just bring the code over here directly and do away with the function; unless the function is called from more than 1 place

2019-03-14 07:27 UTC, itswisdomagain commented on terminal/createwallet.go
> +			pages.AddAndSwitchToPage("main", terminalLayout(ctx, tviewApp, walletMiddleware), true)
Should also remove the "create" page.

2019-03-14 07:27 UTC, itswisdomagain commented on terminal/createwallet.go
> +		layout.AddItem(seedInfo, 7, 1, false)
The has stored seed checkbox should come below the seed and notice boxes, you should aim to replicate the http version

2019-03-14 07:27 UTC, itswisdomagain commented on terminal/createwallet.go
> +
How many times do you have to call `layout.SetFullScreen(true)`?

2019-03-14 07:27 UTC, itswisdomagain commented on terminal/helpers/colors.go
> +	PrimaryColor     = tcell.NewRGBColor(0, 255, 255)
What does `PrimaryColor` mean?

2019-03-14 07:27 UTC, itswisdomagain commented on terminal/layout.go
> +	if Status == walletcore.SyncStatusError {
Line 22 above starts a background process - a subroutine. By the time line 23 is executed, the sync status may not have changed and the if statements below become pretty much invalid.

The background process started by line 22 has callback functions, similar to nodejs callback functions; the `SyncStarted`, `SyncEnded`, `OnHeadersFetched`, `OnDiscoveredAddress` and `OnRescanningBlocks` functions are called at different times while the background process is running.

You should add code in those `SyncStarted`, `OnHeadersFetched`, `OnDiscoveredAddress` and `OnRescanningBlocks` functions to display the report **whenever** those functions are called instead of using the 2 if statements below.

You should also add the code in the 3rd if statement below to the `SyncEnded` function so that those code only actually run when the sync has ended.

2019-03-21 22:13 UTC, ademuanthony requested changes
You have done such a neat job. 
I am impressed with how you maintained the line of sight. 
Here are few change requests
Please work on them and also rebase and `go fmt ./...` so that we can get this merged

2019-03-21 22:13 UTC, ademuanthony commented on terminal/helpers/walletloader.go
> +// this method may stall until previous godcr instances are closed (especially in cases of multiple dcrlibwallet instances)
comments should start with the function name `OpenWalletIfExist`

2019-03-21 22:13 UTC, ademuanthony commented on terminal/helpers/walletloader.go
> +func OpenWalletIfExist(ctx context.Context, walletMiddleware app.WalletMiddleware) (walletExists bool, err error) {
This is a duplicate of `walletloader.OpenWallet`
We should remove this function and use that instead

2019-03-21 22:13 UTC, ademuanthony commented on terminal/terminal.go
> +	walletExists, err := helpers.OpenWalletIfExist(ctx, walletMiddleware)
WE should use  `walletloader.OpenWallet` instead

2019-03-21 22:13 UTC, ademuanthony commented on terminal/terminal.go
> +var Report string
this field is not used outside this package, it should be `report` instead

2019-03-21 22:13 UTC, ademuanthony commented on terminal/terminal.go
> +var Status walletcore.SyncStatus
this field is not used outside this package, it should be `status` instead

2019-03-24 11:38 UTC, ademuanthony approved these changes

2019-03-24 11:39 UTC, ademuanthony commented
I think this PR is now ready

2019-03-25 22:18 UTC, itswisdomagain requested changes
I notice some improvements with how sync updates are handled but the desired solution isn't what we have here yet. Primarily, sync update messages should not be displayed on (logged to) the terminal/command prompt window directly. Such informative messages should be displayed on a primitive - perhaps a text view.

See other required changes below:

2019-03-25 22:18 UTC, itswisdomagain commented on terminal/createwallet.go
> +	createButton := tview.NewForm().
No need to create a form just to display a button. Instead...
```
createWalletButton := tview. NewButton("Create Wallet").SetSelectedFunc(func() {
...
})
```

- Also notice I opted for `createWalletButton` instead of `createButton`

2019-03-25 22:18 UTC, itswisdomagain commented on terminal/createwallet.go
> +				outputMessage("passphrase does not match")
Output message should begin with capital letter

2019-03-25 22:18 UTC, itswisdomagain commented on terminal/createwallet.go
> +			res := pageLoader(tviewApp, walletMiddleware)
- What does `res` mean? Response? Resource? Need to give better variable names.
- In trying to understand what `res` represents, I discovered that `pageLoader` has 2 issues
  - The `pageLoader` function returns a nil primitive - doesn't make sense. Why does a PAGE **LOADER** return no page?
  - The `pageLoader` function seems to have nothing to do with loading pages, more to do with listening for sync status updates. Function needs to be renamed appropriately

2019-03-25 22:18 UTC, itswisdomagain commented on terminal/terminal.go
> +func pageLoader(tviewApp *tview.Application, walletMiddleware app.WalletMiddleware) tview.Primitive {
- This `pageLoader` function returns a nil primitive - doesn't make sense. Why does a PAGE **LOADER** return no page?
- Also, this function seems to have nothing to do with loading pages, more to do with listening for sync status updates. Function needs to be renamed appropriately

2019-03-25 22:18 UTC, itswisdomagain commented on terminal/createwallet.go
> +	// listen to escape and left key press events on all form items and buttons
Correct this comment, and add similar comment to each section of code where you set input capture. The comment should accurately tell what the input capture function does

2019-03-25 22:18 UTC, itswisdomagain commented on terminal/helpers/walletloader.go
> +package helpers
Is the content of this file any different from similar code found in the `cli` package? We should avoid code duplication and opt for shared code/functions.

2019-03-27 22:07 UTC, ademuanthony requested changes
There is a panic during shutdown

2019-03-27 22:07 UTC, ademuanthony commented on terminal/terminal.go
> +	walletExists, err := nuklear.OpenWalletIfExist(ctx, walletMiddleware)
This cross-reference is not ideal. I think we should move `nuklear.OpenWalletIfExist` to walletcore so that other interfaces can call it from there.

2019-03-27 22:07 UTC, ademuanthony commented on terminal/terminal.go
> +			fmt.Println(msgOutput)
There is a review comment that recommended that this message is written to a Primitive, maybe, a textview

2019-04-02 13:29 UTC, itswisdomagain approved these changes

2019-04-02 16:23 UTC, ademuanthony approved these changes

2019-04-02 23:23 UTC, merged