generate address directly on receive page
raedahgroup/godcr-old pull request #231
Opened 2019-03-21 13:51 UTC by ademuanthony

Resolve [Issue 187](https://github.com/raedahgroup/godcr/issues/182)
This PR generate address automatically in the receive on the web and only show the generate button if the user has more than 1 account

The size of the account control is also reduced while the embedded jquery script for the address generation is rewritten and moved to a new stimulusjs controller

2019-03-25 23:23 UTC, itswisdomagain requested changes
Let's aim to make the receive page look a lot more similar to what we have on the Android/iOS apps:
<img src="https://user-images.githubusercontent.com/18400051/54960054-7ed4bc00-4f5b-11e9-91ea-502ed52fd45a.jpeg" width="300">

Required changes/additions would include:
- Remove the generate the button and generate address when the account dropdown selection is changed
- Add "Click to copy" button
- If a previously generated address exists that has not been used, invoking `wallet.CurrentAddress` will return that address. Should include a means to force generating a different (next) address. The mobile apps have an option for this on the top right

2019-03-25 23:23 UTC, itswisdomagain commented on web/routes/handlers.go
> +		"accountsCount": len(accounts),
This value can be evaluated in the template, no need to include it in this map

2019-03-25 23:23 UTC, itswisdomagain commented on web/views/receive.html
> +                                        {{ if gt .accountsCount 1 }}
The send page template has a simpler, more straightforward way of doing this:
```
<select data-target="send.sourceAccount" class="form-control" id="source-account" name="source-account" {{ if eq (len .accounts) 1 }}disabled{{ end }}>
{{ range $account := .accounts }}	                                                
    <option value="{{ $account.Number }}">{{ accountString $account }}</option>
{{ end }}	                                              
</select>
```

Notice also that `.accountsCount` is not required

2019-03-25 23:23 UTC, itswisdomagain commented on web/views/receive.html
> +                                            <button data-action="click->receive#generate" type="submit" id="submit" class="btn btn-success form-control">Generate</button>
In keeping feature-par with the mobile wallet apps, let's retire this generate button and auto-generate an address when a different account is selected from the dropdown

2019-03-25 23:23 UTC, itswisdomagain commented on web/static/app/src/controllers/receive_controller.js
> +  generate (evn) {
`e` or `event`

2019-03-25 23:23 UTC, itswisdomagain commented on web/static/app/src/controllers/receive_controller.js
> +          window.alert(result.message)
Alert dialogs = terrible user experience; display error messages on the page instead.

2019-03-25 23:23 UTC, itswisdomagain commented on web/static/app/src/controllers/receive_controller.js
> +        console.log(error)
This shouldn't be in production app. Also, don't use `window.alert`.

2019-03-25 23:27 UTC, itswisdomagain commented on web/views/receive.html
> +                                        {{ if gt .accountsCount 1 }}
Just noticed you refactored this code on another PR; should make this into a reusable template in `utils.html` and prevent duplicating code

2019-03-26 10:02 UTC, ademuanthony commented on web/views/receive.html
> +                                        {{ if gt .accountsCount 1 }}
moving this to a template may not work for other use cases where change event is not used the way it will now be used here to generate new address

2019-03-26 10:08 UTC, ademuanthony commented
I have worked on all the changes requested in the review

![new-receive-page](https://user-images.githubusercontent.com/11990092/54988779-74481000-4fb7-11e9-9b0c-8109c437940e.PNG)

2019-03-30 07:18 UTC, itswisdomagain requested changes
Remove auto generated font awesome files from dist, probably add `dist/font-awesome*` to gitignore for now. Will test/review again after this

2019-03-30 20:18 UTC, itswisdomagain requested changes

2019-03-30 20:18 UTC, itswisdomagain commented on .gitignore
> +*.log*.bat
This should be separate lines

2019-03-30 20:18 UTC, itswisdomagain commented on web/routes/templates.go
> +		"gt": func(a, b int) bool {
This isn't necessary, there's a default `gt` function for go templates

2019-03-30 20:18 UTC, itswisdomagain commented on web/static/app/package.json
> +    "@fortawesome/free-solid-svg-icons": "^5.8.1",
Why do we have several icon-font-related libraries? won't font-awesome alone do the job? I'd prefer we use only font-awesome

2019-03-30 20:18 UTC, itswisdomagain commented on web/static/app/src/controllers/receive_controller.js
> +    copyToClipboard(this.addressTarget.textContent)
Does this work? Even if it does, there's need to rename one of these functions to aid readability

2019-03-30 20:18 UTC, itswisdomagain commented on web/static/app/package.json
> +    "file-loader": "^3.0.1",
Is this needed or used?

2019-04-03 03:58 UTC, itswisdomagain requested changes
Will build, run and test after these changes.

2019-04-03 03:58 UTC, itswisdomagain commented on web/static/app/package.json
> +    "autoprefixer": "^9.4.7",
Need to update webpack config for this to become relevant. See https://github.com/postcss/autoprefixer#webpack

2019-04-03 03:58 UTC, itswisdomagain commented on web/static/app/package.json
> +    "@fortawesome/free-solid-svg-icons": "^5.8.1",
I believe there's another PR that introduced font-awesome, let's stick to one library for fonts, preferably font-awesome. These 2 libraries are only added because of the copy icon. If we can't get that icon in font-awesome, let's use a link that looks like [(copy)](url) instead

2019-04-03 10:31 UTC, ademuanthony commented on web/static/app/package.json
> +    "@fortawesome/free-solid-svg-icons": "^5.8.1",
we are using the same lib

2019-04-04 06:10 UTC, itswisdomagain requested changes

2019-04-04 06:10 UTC, itswisdomagain commented on .gitignore
> +web/static/dist/font-awesome/*
Is this still necessary as we're no longer using font-awesome?

2019-04-04 06:10 UTC, itswisdomagain commented on web/static/app/src/utils.js
> +export const setErrorMessage = (ctl, message) => {
- Rename `ctl` to `controller`
- Refactor all controllers to use these utility methods

2019-04-04 06:10 UTC, itswisdomagain commented on web/static/app/src/css/style.scss
> +  font-size: 30px;
This text doesn't need to be this big, it's just a hint sort of text. We're not looking to do a perfect replica of the android app, but take what is there and make it work for the web.

2019-04-04 06:10 UTC, itswisdomagain commented on web/views/receive.html
> +                       <p class="lead-text">Each time you request payment, a new <br/>address is created to protect your privacy</p>
This doesn't need to be in 2 lines, should preferably be in 1 line, in smaller fonts. It's just a notice, that users will get accustomed to after a few times opening the page, doesn't need to be the focus of attention

2019-04-04 06:10 UTC, itswisdomagain commented on web/views/receive.html
> +                                <button data-action="click->receive#copyAddressToClipboard" class="btn btn-xs btnCopy" title="Copy to clipboard"><i class="fas fa-copy"></i></button>
This button icon doesn't look conspicuous at all, ran this PR for the first time yesterday and "almost" missed the copy button. Please, let's go with `<button class="btn btn-sm btn-link">(copy)</button>`. And then after the address is successfully copied, the button should say `(copied)` for a few seconds before reverting back to `(copy)`

2019-04-04 07:19 UTC, itswisdomagain commented
Also need to have a "Generate New Address" button to ignore the current address and generate a new address using `wallet.GenerateNewAddress`

2019-04-06 02:50 UTC, itswisdomagain commented
![Screen Shot 2019-04-06 at 3 48 55 AM](https://user-images.githubusercontent.com/18400051/55663996-17eab900-581f-11e9-96b3-253533b4341a.png)

2019-04-06 03:14 UTC, itswisdomagain approved these changes

2019-04-06 04:33 UTC, merged