http send page cleanup
raedahgroup/godcr-old pull request #232
Opened 2019-03-21 14:49 UTC by ademuanthony

Resolves #228

This PR makes the account balance on the http send page selectable and remove the restricting validation in selecting custom input

2019-03-25 23:39 UTC, itswisdomagain requested changes
I'm rethinking the requirement to make the source account amount selectable... If there's just 1 account, we can make this requirement work. But where we have more than 1 account, user can't highlight the text in the dropdown.

I'll recommend sticking to the dropdown pattern for both cases of single and multiple accounts - using `disabled` for single account.

To enable copying amount, we could and should follow the pattern in the mobile apps - have a "Send Max" or "Send All" button. This will also have the added advantage of calculating the fee required for the transaction and subtracting it from the total balance before displaying it on the amount field.

Alternatively, we could have the account balance info displayed in small italics below the account selection widget.

Will need to confer with @raedah for the desired use case and UI presentation.

UPDATE:
- Let's add a Send Max button to each destination address/amount pair (assigns the remaining spendable balance to the destination amount field after subtracting amount set for other destination fields, should be smart enough to update the amount value as other destination amount values are changed)
- No need to display balance separately, we can stick to making the balance text selectable when there's just one account

2019-03-25 23:39 UTC, itswisdomagain commented on web/views/send.html
> +                                                <input type="text" readonly class="form-control" value="{{ accountString $account }}">
Why do we need 2 inputs?

2019-03-25 23:39 UTC, itswisdomagain commented on web/views/send.html
> +                                        {{ if eq (len .accounts) 1 }}
Need some formatting.

2019-03-26 10:17 UTC, ademuanthony commented on web/views/send.html
> +                                                <input type="text" readonly class="form-control" value="{{ accountString $account }}">
so as to make the balance highlightable when there is just one account

2019-03-26 12:44 UTC, ademuanthony commented
I have implemented the requested changes. The destinations now have a send max button


![send-page-send-max](https://user-images.githubusercontent.com/11990092/54997958-41107b80-4fcd-11e9-8c2b-21677182fe38.PNG)

2019-03-30 20:11 UTC, itswisdomagain requested changes
**Observed error 1**
There's an anomaly with the add and remove destination address buttons:
Only 1 address, yet remove destination address button shows
![Screenshot 2019-03-30 at 9 07 03 PM](https://user-images.githubusercontent.com/18400051/55281113-f7f35b00-532f-11e9-95b2-bc1953caea23.png)
2 addresses, no remove destination address button
![Screenshot 2019-03-30 at 9 07 34 PM](https://user-images.githubusercontent.com/18400051/55281115-fd50a580-532f-11e9-8166-58b5eaaa88e3.png)

**Observed error 2**
If I use the Send Max button on a destination field and try to use it on another destination field, the following error is presented. The error message does not even appear to be related to the attempted action:
![Screenshot 2019-03-30 at 9 07 44 PM](https://user-images.githubusercontent.com/18400051/55281121-23764580-5330-11e9-88a3-d1aa2f74b1b2.png)

2019-03-30 20:11 UTC, itswisdomagain commented on web/routes/handlers.go
> +	if len(utxos) < 1 {
`len(utxos) == 0` makes more sense

2019-03-30 20:11 UTC, itswisdomagain commented on web/routes/handlers.go
> +			data["error"] = err.Error()
`fmt.Errorf("error fetching unspent outputs for new tx: %s", err.Error()`

2019-03-30 20:11 UTC, itswisdomagain commented on web/routes/handlers.go
> +func (routes Routes) getAllUtoxs(accountNumber uint32, requiredConfirmations int) ([]string, float64, error) {
- This should be in a helper.go file
- The `getUnspentOutputs` may benefit from this function too

2019-04-01 13:01 UTC, itswisdomagain requested changes
Will review some more after these changes...
Also, 
- create a separate route for the send max button (`/max-send-amount`) that behaves just like the getChangeOutputs route
- refactor the current getChangeOutputs handler into a shared function
- make both routes point to different handlers, then the handlers can call the shared function

2019-04-01 13:01 UTC, itswisdomagain commented on app/walletcore/helper.go
> +func GetAllUtoxs(walletMiddleware Wallet, accountNumber uint32, requiredConfirmations int) ([]string, float64, error) {
- `GetAllUtxos` (typo)
- `wallet Wallet`
- Use named return variables so you don't declare in the function body and the return values will be have more meaning (`utxos []string, total float64, err error`)

2019-04-01 13:01 UTC, itswisdomagain commented on web/routes/handlers.go
> +	// This is so as to make getting max amount possible for normal sending from the UI
Since this method doesn't just cover send max button click scenarios, this comment will need to be updated.

2019-04-01 13:01 UTC, itswisdomagain commented on web/routes/handlers.go
> +		// return error key for the frontend to process
error key?

2019-04-01 13:01 UTC, itswisdomagain commented on web/routes/handlers.go
> +		getUnconfirmed := req.URL.Query().Get("getUnconfirmed")
url params should not be camel cased
getUnconfirmed => get-unconfirmed

2019-04-01 19:55 UTC, itswisdomagain requested changes

2019-04-01 19:55 UTC, itswisdomagain commented on web/routes/handlers.go
> +func (routes *Routes) maxSendAmount(res http.ResponseWriter, req *http.Request) {
Most of the code in this function is repeated in the `getRandomChangeOutputs` handler function. With proper refactoring, the repeated code can be extracted into a helper function (in a helpers.go) file.

2019-04-01 19:55 UTC, itswisdomagain commented on web/routes/handlers.go
> +	// the max send amount is the change to one output for the payload
This is close but not perfect yet. The change amount returned is "tied" to an address. If the address changes, the fee could change and therefore the change amount.

There's need to get the address to which the user wants to send max amount; and then use that address as a "change address" to generate the change amount. The function you'll need is:
```
changeAmount, err := txhelper.EstimateChange(nUtxoSelection, amountInAtom, sendDestinations, changeAddresses)
```
where
- the `sendDestinations` should not include the address for which the max amount is to be calculated and
- the `changeAddresses` is a single slice of the address for which the max amount is to be calculated

This function is used in the `walletcore.GetChangeDestinationsWithRandomAmounts`, more insight may be found there.

2019-04-01 19:55 UTC, itswisdomagain commented on web/static/app/src/controllers/send_controller.js
> +      if (!changeOutputs || changeOutputs.length < 1) {
Under what conditions could this happen? We should show the user a message explaining why we could not calculate the max amount that can be sent to the address.

2019-04-01 19:55 UTC, itswisdomagain commented on web/static/app/src/controllers/send_controller.js
> +    this.resetChangeOutput()
Shouldn't this be done **_after_** the max amount is retrieved from the server and set to the appropriate amount field? If the amount is not changed, any previously generated change outputs would remain valid.

2019-04-01 19:55 UTC, itswisdomagain commented on web/static/app/src/controllers/send_controller.js
> +      if (errMsg.indexOf('total input amount not enough to cover transaction') > -1) {
2 things here
1) If the total input amount is not enough to generate another amount for another address (the "change address"), we should show the user a proper message; perhaps: `Total send amount is already at maximum`
2) This if statement feels like a hack... what if the error message returned is different? There should be a better way to determine this scenario on the server and the server should return the proper error message described above; and the error message should always be shown to the user

2019-04-01 19:55 UTC, itswisdomagain commented on web/static/app/src/controllers/send_controller.js
> +      queryParams += '&get-unconfirmed=true'
`spend-unconfirmed` is better I believe

2019-04-01 19:55 UTC, itswisdomagain commented on web/static/app/src/controllers/send_controller.js
> +        let result = response.data
This block can be simplified:

```
if (!result.error) {
  successCallback(result.message)
} else if (errorCallback) {
  errorCallback(result.error)
} else {
  _this.setErrorMessage(result.error)
}
```

2019-04-01 19:55 UTC, itswisdomagain commented on web/static/app/src/controllers/send_controller.js
> +      if (!_this.useCustomChangeOutput || !changeOutputs) {
Why would there be no change outputs? If that happens, an explanatory error message should be displayed

2019-04-01 19:55 UTC, itswisdomagain commented on web/static/app/src/controllers/send_controller.js
> +      queryParams += '&get-unconfirmed=true'
This query param isn't needed for this endpoint.

2019-04-01 19:55 UTC, itswisdomagain commented on web/static/app/src/controllers/send_controller.js
> +          if (errorCallback) {
This code block can also be simplified. See similar comment above.

2019-04-01 19:55 UTC, itswisdomagain commented on web/views/send.html
> +                                    {{ range $account := .accounts }}
Instead of `{{ range }} ... {{ end }}`, can do `{{ $account := index .accounts 0 }}`. Compare balance.html

2019-04-01 19:55 UTC, itswisdomagain commented on web/static/app/src/controllers/send_controller.js
>      if (this.sourceAccountTarget.disabled) {
Don't think this is necessary anymore. There is never an instance of a disabled form control. What we have instead is a hidden input and that is serialized, I believe.

2019-04-01 19:55 UTC, itswisdomagain commented on web/static/app/src/controllers/send_controller.js
> +      queryParams += `&source-account=${this.sourceAccountTarget.value}`
Don't think this is necessary anymore. There is never an instance of a disabled form control. What we have instead is a hidden input and that is serialized, I believe.

2019-04-01 19:55 UTC, itswisdomagain commented on web/views/send.html
Line space should be after the closing </div>

2019-04-01 19:55 UTC, itswisdomagain commented on web/views/send.html
> +                                            unconfirmed</label>
"Spend" and "unconfirmed" can be in one line.

2019-04-01 19:55 UTC, itswisdomagain commented on web/views/send.html
> +                                <button id="add-destinatvion-btn" type="button" data-action="click->send#newDestination"
button id is unnecessary

2019-04-01 19:55 UTC, itswisdomagain commented on web/views/send.html
> +                                        data-action="click->send#removeDestination" id="remove-destination-btn"
button id is unnecessary

2019-04-01 20:12 UTC, itswisdomagain requested changes

2019-04-01 20:12 UTC, itswisdomagain commented on web/routes/handlers.go
> +	data["message"] = changeOutputDestinations
- message?
- also, we only need the amount...

2019-04-03 04:29 UTC, itswisdomagain requested changes

2019-04-03 04:29 UTC, itswisdomagain commented on web/routes/helpers.go
> +
Can remove one empty line

2019-04-03 04:29 UTC, itswisdomagain commented on web/routes/helpers.go
> +
Empty line can go

2019-04-03 04:29 UTC, itswisdomagain commented on web/routes/helpers.go
> +	Utxos []string
These properties are only used within this package, I believe. No need to make them public

2019-04-03 04:29 UTC, itswisdomagain commented on web/routes/helpers.go
> +		return nil, err
Can just `return`, same for line 46 below

2019-04-03 04:29 UTC, itswisdomagain commented on web/routes/handlers.go
> +	payload, err := retrieveSendPagePayload(req)
`payload` may be nil and `err` may need to be displayed

2019-04-03 04:29 UTC, itswisdomagain commented on web/routes/handlers.go
> +			data["error"] = fmt.Errorf("error fetching unspent outputs for new tx: %s", err.Error())
This error isn't helpful. User clicks "Send Max" and sees error fetching unspent outputs;  that would be confusing.

2019-04-03 04:29 UTC, itswisdomagain commented on web/routes/handlers.go
> +		if payload.SendDestinations[i].Address == selectedAddress {
Would need another way to determine which address is selected because there's a new requirement to allow addresses to be repeated in the send form.

2019-04-03 04:29 UTC, itswisdomagain commented on web/routes/handlers.go
> +		if strings.Contains(err.Error(), "total input amount not enough to cover transaction") {
If you look at the implementation of `txhelper.EstimateChange`, this error occurs when `totalInputAmount < totalSendAmount`. You can sum the total send amount and check if the input amount can cover it before calling `txhelper.EstimateChange`. Then you won't need to do a string comparison on the error returned from that function.

2019-04-03 04:29 UTC, itswisdomagain commented on web/routes/handlers.go
>  		data["error"] = err.Error()
The `err` returned from `retrieveSendPagePayload` doesn't have accompanying context. Need to add that here before sending to client. `fmt.Sprintf("Error reading values from form submitted form: %s", err.Error())`

2019-04-03 04:29 UTC, itswisdomagain commented on web/routes/helpers.go
> +		return nil, err
Do not return the direct error from parse failures; it's usually not presentable. Instead return `fmt.Errorf(Invalid source account selected)`

2019-04-03 04:29 UTC, itswisdomagain commented on web/routes/helpers.go
> +		return
Do not return the direct error from parse failures; it's usually not presentable. Instead 
```
err = `fmt.Errorf(Cannot read total send amount value)`
return
```

2019-04-03 04:29 UTC, itswisdomagain commented on web/routes/helpers.go
> +		return
```
err = `fmt.Errorf(Invalid total send amount value)`
return
```

2019-04-03 04:29 UTC, itswisdomagain commented on web/routes/helpers.go
> +		return
Confirm if `walletcore.BuildTxDestinations` returns proper error messages, otherwise, add some extra information here before returning.

2019-04-03 04:29 UTC, itswisdomagain commented on web/static/app/src/controllers/send_controller.js
> +  resetChangeOutput () {
I think this should also reset the `numberOfChangeOutputs` value, so a user does not think that a previously entered value is still valid.

2019-04-05 11:43 UTC, ademuanthony commented on web/static/app/src/controllers/send_controller.js
> +  resetChangeOutput () {
yes it does

2019-04-05 23:01 UTC, itswisdomagain requested changes

2019-04-05 23:01 UTC, itswisdomagain commented on web/routes/handlers.go
> +	"strconv"
Re-arrange imports

2019-04-05 23:01 UTC, itswisdomagain commented on web/routes/handlers.go
> +		data["error"] = fmt.Sprintf("cannot get max amount: %s", err.Error())
This can start with a capital letter, only `fmt.Errorf` has that restriction. Do same for other similar occurences.

2019-04-05 23:01 UTC, itswisdomagain commented on web/routes/handlers.go
> +			payload.sendDestinations = append(payload.sendDestinations[:i], payload.sendDestinations[i+1:]...)
Instead of doing this, modify the `retrieveSendPagePayload` to ignore 0 amount destinations, as even a normal send operation will fail with a 0 amount destination.

2019-04-05 23:01 UTC, itswisdomagain commented on web/routes/handlers.go
> +			data["error"] = fmt.Errorf("cannot get max amount, error in converting input amount to atom: %s", err.Error())
- No need to return the actual `err.Error`, it won't be human readable
- Also, it's not input amount you're converting but a destination amount...

2019-04-05 23:01 UTC, itswisdomagain commented on web/routes/handlers.go
> +	if payload.totalInputAmount < totalSendAmount {
Change to `totalSendAmount >= payload.totalInputAmount`, makes the next line easier to understand: the total send amount is greater than the total input amount, therefore, send amount is at maximum.

2019-04-05 23:01 UTC, itswisdomagain commented on web/routes/handlers.go
> +	destinations := append(payload.sendDestinations, payload.changeDestinations...)
If we're trying to get change outputs, why are we adding previously set change destinations to the actual send destinations? This will return a wrong change address. I think you should only use the actual send destinations so you can get the actual change amount which you can then randomize.

PS: I noticed that the frontend clears the previously generated change destinations before calling this endpoint but that's even the more reason why we shouldn't do this.

2019-04-05 23:01 UTC, itswisdomagain commented on web/routes/handlers.go
> +	changeOutputDestinations, err := walletcore.GetChangeDestinationsWithRandomAmounts(routes.walletMiddleware, int(nChangeOutputs), payload.totalInputAmount, payload.sourceAccount, len(payload.utxos),
- This is a long line, please split
- Before calling this function, also check `if totalSendAmount >= payload.totalInputAmount`, because the error returned is not very helpful. It says `error in getting change amount: total input amount not enough to cover transaction fee`, message should be `error in getting change amount: total input amount cannot cover total send amount and transaction fee`
- You may need to modify the `retrieveSendPagePayload` to also return `totalSendAmount`

2019-04-05 23:01 UTC, itswisdomagain commented on web/routes/helpers.go
> +	"github.com/pkg/errors"
Wrong import, goland can be dumb sometimes.

2019-04-05 23:08 UTC, itswisdomagain commented
2 issues just surfaced while trying to use the Send Max button with a destination address
- if I select custom inputs, I get a success message with hash undefined, the tx didn't really go through
- if I don't select custom inputs, I get insufficient balance error

I think there's need to re-look at how we're getting the max send amount. This feature already exists in dcrandroid, we should get some insight from there.

2019-04-06 21:05 UTC, ademuanthony commented
> 2 issues just surfaced while trying to use the Send Max button with a destination address
> 
> * if I select custom inputs, I get a success message with hash undefined, the tx didn't really go through
> * if I don't select custom inputs, I get insufficient balance error
> 
> I think there's need to re-look at how we're getting the max send amount. This feature already exists in dcrandroid, we should get some insight from there.

dcrandroid only set spendable as max amount without fee considerable and there does seem to be multiple address support

2019-04-07 01:32 UTC, itswisdomagain commented
These issues are still there. Does it work on your end?

> 2 issues just surfaced while trying to use the Send Max button with a destination address
> 
> * if I select custom inputs, I get a success message with hash undefined, the tx didn't really go through
> * if I don't select custom inputs, I get insufficient balance error
> 
> I think there's need to re-look at how we're getting the max send amount. This feature already exists in dcrandroid, we should get some insight from there.

2019-04-07 07:52 UTC, itswisdomagain commented on web/routes/handlers.go
> +	payload.sendDestinations = append(payload.sendDestinations, txhelper.TransactionDestination{Address:selectedAddress})
This doesn't work, neither should it. I'm working on a fix.

2019-04-07 22:37 UTC, itswisdomagain commented
Made changes to
- the max amount estimation code
- normal send and utxo send with dcrlibwallet (to account for max change amount recipient, this isn't done for dcrwallet rpc yet)
- error messages display

Haven't been able to confirm if sending max amount works now, but it probably should. Here's the new look:
![Screen Shot 2019-04-07 at 11 34 47 PM](https://user-images.githubusercontent.com/18400051/55690801-0d026680-598e-11e9-98fa-cbf8af062757.png)

2019-04-09 10:49 UTC, ademuanthony commented
New update

![send-remove-destination-button](https://user-images.githubusercontent.com/11990092/55794572-76cd5e00-5abd-11e9-9741-1b6629c394fb.PNG)

2019-04-13 12:25 UTC, ademuanthony commented
Added transaction summary to the passphrase modal and worked on the other requested changes
![send-with-confirm](https://user-images.githubusercontent.com/11990092/56079673-861b1700-5def-11e9-9530-78b735b61092.PNG)

2019-04-14 02:50 UTC, ademuanthony commented
![send-page-14-4-empty](https://user-images.githubusercontent.com/11990092/56087723-71c73080-5e68-11e9-86d7-3b4645f4a930.PNG)

![send-page-14-4-with-pass](https://user-images.githubusercontent.com/11990092/56087725-7855a800-5e68-11e9-9920-2ac3cf652210.PNG)

2019-04-16 05:03 UTC, itswisdomagain requested changes
Something else I noticed is that when you generate a high (5+) number of change outputs, the total is either less than or more than 100% and you get this kind of error when you want to send: `Total change amount percentage must be equal to 100. Current total is 101`. This doesn't happen for manual change outputs even if the number of outputs is high.

2019-04-16 05:03 UTC, itswisdomagain commented on web/routes/handlers.go
> +	req.ParseForm()
This is already called in `retrieveSendPagePayload`, no longer necessary here

2019-04-16 05:03 UTC, itswisdomagain commented on web/routes/templates.go
> +				if account.Balance.Total != account.Balance.Spendable {
`Total` might be different from `Spendable` but doesn't necessarily mean there is unconfirmed balance that can be spent. Some funds might be locked by tickets. Should check `if account.Balance.Unconfirmed > 0`

2019-04-16 05:03 UTC, itswisdomagain commented on web/views/send.html
> +                                    <div class="form-group form-check mb-0 {{ if haveUnconfirmedBalance .accounts }} d-none {{ end }}">
This says the checkbox should be hidden if there is unconfirmed balance. The reverse should be the case. Should modify the function to `if noUnconfirmedBalance`.

Also, this puts a lot of spaces between `d-none` in the class attribute. Some spaces can be removed.

Use class `mt-1 mb-0` for margin on this element so that when it is visible, there'd be a space between it and the previous element. Only when it is visible.

2019-04-16 05:03 UTC, itswisdomagain commented on web/views/send.html
> +                                    <div class="form-group mb-1">
Should be `mb-0`, margin should only be present if the next element (spend unconfirmed is visible). See previous comment.

2019-04-16 05:03 UTC, itswisdomagain commented on web/views/send.html
> +                                    <tbody data-target="send.customInputsTable"></tbody>
When adding utxos to this table, the code sets a utxo selected event listener that calculates the custom inputs percentage. Let's modify that a bit. The utxo checkbox click event listener in line 276 of `send_controller.js` should not directly trigger `calculateCustomInputsPercentage`. Instead it should trigger the following function:

```
  utxoSelectedOrDeselected () {
    this.calculateCustomInputsPercentage()
    this.updateMaxAmountFieldIfSet()
  }
```

The goal is to re-calculate the max amount if there is a change in utxo selection. We cannot trigger this max amount recalculation inside the `calculateCustomInputsPercentage` function because that function is also called after the max amount is calculated and that would lead to circular function calls.

2019-04-16 05:03 UTC, itswisdomagain commented on web/routes/handlers.go
> +	if payload.totalSendAmount >= payload.totalInputAmount {
This if check is no longer necessary. The new dcrlibwallet `txhelper.EstimateMaxSendAmount` function returns a pretty okay error message that can be displayed to the user such as

`Error in estimating max send amount: total send amount (20 DCR) is higher than or equal to the total input amount (20 DCR)`
and
`Error in estimating max send amount: total send amount (20 DCR) is higher than or equal to the total input amount (9 DCR)`

2019-04-16 05:03 UTC, itswisdomagain commented on web/views/send.html
> +            <div data-target="send.errorMessage" class="alert alert-danger d-none"></div>
I think both error and success message boxes should go down to where we have the next button. If I try to send a tx by clicking send and there's an error, I have to scroll back up to see the error message. Same thing if the send is successful. I can't immediately tell if there was an error or success until I scroll up

2019-04-16 05:03 UTC, itswisdomagain commented on web/static/app/src/controllers/send_controller.js
>    toggleSpendUnconfirmed () {
- re-order the functions on this file so that `toggleSpendUnconfirmed`, `toggleUseCustom` and other input selection related functions are displayed at the top
- when use custom is selected, check if there is a send max destination set. If so, reset and hide the change outputs customization section.
- similarly, when a destination's send max checkbox is checked and use custom is checked, reset and hide the change outputs customization section.

2019-04-17 09:22 UTC, yaowork requested changes
I'm not able to send funds. Seems my passphrase isn't included in the form data sent to the server as seen from chrome inspector. 
![Screenshot from 2019-04-17 10-14-17](https://user-images.githubusercontent.com/42093751/56276351-49eefb80-60fa-11e9-9c78-7ae6eda50d62.png)

2019-04-17 09:34 UTC, yaowork requested changes
The remove address/amount pair button should be hidden for the first input pair if there's only one pair on the form, and should only be visible if there's more than one input pairs.

![Screenshot from 2019-04-17 10-30-59](https://user-images.githubusercontent.com/42093751/56277418-35abfe00-60fc-11e9-96c1-533d0b1c29bc.png)

2019-04-17 12:17 UTC, itswisdomagain requested changes

2019-04-17 12:17 UTC, itswisdomagain commented on web/routes/templates.go
> +			unconfirmedBalance := account.Balance.Total - account.Balance.Spendable
- `unconfirmedBalance` is not `account.Balance.Total - account.Balance.Spendable` but rather `account.Balance.Unconfirmed`
- shouldn't you only show unconfirmed balance if it is greater that zero?

2019-04-17 21:16 UTC, merged