rearrange balance page on the web
raedahgroup/godcr-old pull request #233
Opened 2019-03-21 15:35 UTC by ademuanthony

reduce the font size and conditionally show spendable balance on second line
![balance-page](https://user-images.githubusercontent.com/11990092/54764012-45b4e880-4bf7-11e9-941e-260ca9762c9f.PNG)

2019-03-22 04:00 UTC, ademuanthony commented
Following @raedah's suggestion, the page is now modified to have the following look
![balance-page-mod](https://user-images.githubusercontent.com/11990092/54799888-6f095f00-4c5f-11e9-81b1-e5e499c042b0.PNG)

2019-03-26 00:02 UTC, itswisdomagain requested changes

2019-03-26 00:02 UTC, itswisdomagain commented on app/walletcore/helper.go
> +	return balance.Spendable.String()
Don't see a need for this `SpendableBalance` function, can always simply invoke `balance.Spendable.String()` where necessary instead of having this wrapper function

2019-03-26 00:02 UTC, itswisdomagain commented on app/walletcore/helper.go
> +func NormalizeBalance(balanceString string) string {
- Make this function take the balance as float (`balance.ToCoin()`)
- `return fmt.Sprintf("%013.8f", balance)`

xxxx.xxxxxxxx = 13 characters, 4 before the decimal point, 8 characters after plus the decimal point character = 13
`%013.8f` says use '0' for leading and trailing padding, there should be a minimum of 13 characters and 8 of those should appear after the decimal point.

2019-03-26 00:02 UTC, itswisdomagain commented on web/views/balance.html
> +                                <p style="font-size: 16px;" class="mb-0"><b>Total</b>: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
Maybe use a table without borders to ensure the balance texts on the right are aligned; or use html tab escape character; or use `<span>` with `display: inline-block` and a set fixed width for the "Total" and "Spendable" texts, so that the actual balance texts in both cases begin at the same point to the right of the spans

2019-03-26 13:25 UTC, ademuanthony commented
I have worked on the requested changes

![blance-page-use-table](https://user-images.githubusercontent.com/11990092/55000546-07427380-4fd3-11e9-8bb7-f2020a4a43f2.PNG)

2019-03-30 06:10 UTC, itswisdomagain requested changes

2019-03-30 06:10 UTC, itswisdomagain commented on web/views/balance.html
> +                            {{/*{{ $account := index .accounts 0 }}
Please take off this commented code

2019-03-30 06:10 UTC, itswisdomagain commented on web/views/balance.html
> +                            {{ $account := index .accounts 0 }}
Move this to after line 21, it's easier to make sense of this declaration when it is placed just after the if statement:
If it's not detailed and it's one account, then declare $account

2019-03-30 06:10 UTC, itswisdomagain commented on web/views/balance.html
> +                                {{ if ne $account.Balance.Total $account.Balance.Spendable }}
Indent this line

2019-03-30 06:10 UTC, itswisdomagain commented on web/views/balance.html
> +                                {{ end }}
Indent this line

2019-03-30 09:25 UTC, itswisdomagain approved these changes

2019-03-30 09:25 UTC, merged