fixed bugs on the terminal GUI
raedahgroup/godcr-old pull request #234
Opened 2019-03-21 19:31 UTC by Sirmorrison

fixed issue with toggling between view detailed balance and simple balance view on terminal,
Unified all terminal page content,
fixed history page scroll, and more

2019-03-24 11:20 UTC, ademuanthony submitted a review, later dismissed
This is a big improvement. Just some minor changes

2019-03-24 11:20 UTC, ademuanthony commented on terminal/pages/balance.go
> +		"github.com/raedahgroup/godcr/terminal/helpers"
`go fmt ./...` please

2019-03-24 11:20 UTC, ademuanthony commented on terminal/pages/balance.go
> +		if event.Key() == tcell.KeyTAB{
`if event.Key() == tcell.KeyTAB || event.Key() == tcell.KeyBacktab {`

2019-03-24 11:20 UTC, ademuanthony commented on terminal/pages/balance.go
> +		if event.Key() == tcell.KeyBacktab {
This can now go

2019-03-24 11:20 UTC, ademuanthony commented on terminal/pages/history.go
> +		"github.com/raedahgroup/godcr/terminal/helpers"
`go fmt ./...`

2019-03-26 00:30 UTC, itswisdomagain requested changes
This PR attempts to solve too many problems making it cubersome to review effectively. Modify this PR to only focus on the fix to issue #225 and other balance page improvements solely. Also compare the screenshot, code and review comments in #233 for latest updates to the presentation of the balance page.

Create a different branch and PR for other changes.

2019-03-26 00:30 UTC, itswisdomagain commented on terminal/helpers/colors.go
> +	TitleColor       = tcell.NewRGBColor(0, 255, 255)
`PageHeaderColor` instead of `TitleColor`. Why this particular rgb combination. Let's aim for style uniformity across the GUI interfaces (http, nuklear and terminal). `nuklear` already has a page header color, should use the same rgb combination.

2019-03-26 00:30 UTC, itswisdomagain commented on terminal/pages/balance.go
> +	body.AddItem(hintText, 4, 0, false)
I think a height of `3` would be sufficient for most if not all hint text views; leaving more space for page content. Remember the terminal window is not usually big in size and thus doesn't have much room for content display

2019-03-26 00:30 UTC, itswisdomagain commented on terminal/pages/balance.go
> +	body.AddItem(primitives.NewLeftAlignedTextView("Wallet Balance").SetTextColor(helpers.TitleColor), 2, 0, false)
I believe this code (`primitives.NewLeftAlignedTextView("Wallet Balance").SetTextColor(helpers.TitleColor)`) will be a recurring code across all the terminal pages, create a function (`TitleTextView`) for it in the primitives package.

2019-03-26 00:30 UTC, itswisdomagain commented on terminal/pages/balance.go
>  					table.SetCell(0, 0, tview.NewTableCell("Account Name").SetAlign(tview.AlignCenter)).
You should not add the table headers in a loop. Table cells for different accounts should not be placed in the row = 1 position. See the history page code for how to properly populate a table header and rows.

This comment applies to lines 52-67 below as well

2019-03-26 00:30 UTC, itswisdomagain commented on terminal/pages/balance.go
> +			body.AddItem(textView.SetTextAlign(tview.AlignLeft).SetText(output), 5, 1, false)
You should only be calling `textView.SetText()` here. Use `primitives.NewLeftAlignedTextView` instead of `tview.NewTextView()` in line 27

2019-03-26 00:30 UTC, itswisdomagain commented on terminal/pages/balance.go
> +	table := tview.NewTable().SetBorders(true)
Variable needs better name. What kind of table is this? What data does it hold?

2019-03-26 00:30 UTC, itswisdomagain commented on terminal/pages/balance.go
> +	textView := tview.NewTextView()
Variable needs better name. What does this textview do? What data does it hold?

2019-03-26 00:30 UTC, itswisdomagain commented on terminal/pages/balance.go
> +	textView.SetBorderPadding(0, 0, 30, 0)
Why is this necessary?

2019-03-27 14:24 UTC, Sirmorrison commented on terminal/helpers/colors.go
> +	TitleColor       = tcell.NewRGBColor(0, 255, 255)
Difference in interface background would be a Major challenge to the colour choice on the terminal ui.

2019-03-30 08:24 UTC, itswisdomagain commented
The total and spendable text should align with the "Balance" header on the left. Also reduce the space between Total and Spendable. No need to show spendable balance if it is the same as total balance.
> ![image](https://user-images.githubusercontent.com/27733432/55265892-80172900-527a-11e9-8db9-16ac9caf516b.png)

When showing detailed balance, the page header should be "Balance (detailed)"
> ![image](https://user-images.githubusercontent.com/27733432/55265937-bbb1f300-527a-11e9-9f46-94a8de07c756.png)

2019-03-30 08:55 UTC, itswisdomagain requested changes
I've also kept this review round to just the balance page. I still recommend splitting this PR into multiple PRs for easier reviews, should just be a matter of creating new branch(es) and copying some code over. That way the different "bugs" fixed can be reviewed simultaneously with less stress. Also a better idea to keep PRs small and focused on just one task. Please split this PR

2019-03-30 08:55 UTC, itswisdomagain commented on terminal/helpers/colors.go
> +	PageHeaderColor  = tcell.NewRGBColor(0, 255, 255)
Is this PageHeaderColor the same with the nuklear interface?

2019-03-30 08:55 UTC, itswisdomagain commented on terminal/pages/balance.go
> +	hintText := primitives.WordWrappedTextView("(TIP: use TAB to switch between Detailed and Simple Balance, ARROW keys to Scroll table. Return with Esc)")
The default hint text should be "TIP: Press TAB to display detailed balance info, ESC to return to Navigation Menu". The text should/will be changed later when the detailed balance is displayed.

2019-03-30 08:55 UTC, itswisdomagain commented on terminal/pages/balance.go
> +	body.AddItem(primitives.TitleTextView("Balance"), 3, 0, false)
Other pages having hint and page title put the page title ABOVE the hint, let's maintain uniformity and do the same here. There shouldn't be any space between the title and hint. Title should have a height of 1 not 3.

Also, declare the `balanceTextView` separately before adding it to the page so that we can change the text later:
```
pageTitleTextView := primitives.TitleTextView("Balance")
body.AddItem(pageTitleTextView, 1, 0, false)
```

2019-03-30 08:55 UTC, itswisdomagain commented on terminal/pages/balance.go
> +	totalBalanceTextView.SetBorderPadding(0, 0, 5, 0)
This padding is not needed. Same for the `spendableBalanceTextView` below

2019-03-30 08:55 UTC, itswisdomagain commented on terminal/pages/balance.go
> +	removeTextview := func(balanceTable, spendableBalanceTextView, totalBalanceTextView tview.Primitive) {
Does this function only remove textviews? Please rename to `clearBalanceViews` or `resetBalancePage`. The function should not take in any parameters either, it can access those primitives directly since the function is declared in the same scope as the primitives.

2019-03-30 08:55 UTC, itswisdomagain commented on terminal/pages/balance.go
>  	body := tview.NewFlex().SetDirection(tview.FlexRow)
Rename `body` to `balancePage`

2019-03-30 08:55 UTC, itswisdomagain commented on terminal/pages/balance.go
> +		//removeTextview clear the screen before outputing new data
- This comment ideally belongs where the function is declared, not called
- Using a proper name for the function eliminates the need to add any comment even, for instance, using `clearBalancePage` as function name

2019-03-30 08:55 UTC, itswisdomagain commented on terminal/pages/balance.go
> +	simpleOutput = func(accounts []*walletcore.Account) {
`accounts` is declared above, no need to pass it as a parameter to this function; the function can access that variable directly

2019-03-30 08:55 UTC, itswisdomagain commented on terminal/pages/balance.go
> +			body.AddItem(spendableBalanceTextView.SetText(fmt.Sprintf("Total:        %s", output)), 2, 0, false)
Using spaces like this is a hack, use a table instead for even column spacing.

2019-03-30 08:55 UTC, itswisdomagain commented on terminal/pages/balance.go
> +			body.AddItem(totalBalanceTextView.SetText(fmt.Sprintf("Spendable:    %s", accounts[0].Balance.Spendable)), 2, 0, false)
Only show spendable balance if it's NOT the same as the total balance

2019-03-30 08:55 UTC, itswisdomagain commented on terminal/pages/balance.go
> +					SetCell(row, 2, tview.NewTableCell(account.Balance.Spendable.String()).SetAlign(tview.AlignCenter))
Only show spendable balance if it's NOT the same as the total balance

2019-03-30 08:55 UTC, itswisdomagain commented on terminal/pages/balance.go
> +			body.AddItem(balanceTable, 0, 2, true)
`proportion` should be 1 (doesn't need to be 2), to fill the available screen height

2019-03-30 08:55 UTC, itswisdomagain commented on terminal/pages/balance.go
> +	simpleOutput = func(accounts []*walletcore.Account) {
This function should also set the page title to "Balance" and the hint text to "TIP: Press TAB to display detailed balance info, ESC to return to Navigation Menu".

2019-03-30 08:55 UTC, itswisdomagain commented on terminal/pages/balance.go
> +	detailedOutput = func(accounts []*walletcore.Account) {
This function should also set the page title to "Balance (detailed)" and the hint text to "TIP: Press TAB to display simple balance info, ESC to return to Navigation Menu".

2019-03-30 08:55 UTC, itswisdomagain commented on terminal/pages/balance.go
> +	// use different key press listener on first form item to watch for escape and enter key to set focus on table
What comment is this please?

2019-03-30 08:55 UTC, itswisdomagain commented on terminal/pages/balance.go
> +		if event.Key() == tcell.KeyTab {
I remember mentioning that the code should add support for back tab key press. Please `if event.Key() == tcell.KeyTab || event.Key() == tcell.KeyBacktab {`

2019-03-30 08:55 UTC, itswisdomagain commented on terminal/pages/balance.go
> +			setFocus(balanceTable)
Move this code to inside the `detailedOutput` function

2019-03-30 08:55 UTC, itswisdomagain commented on terminal/pages/balance.go
> +	// use different key press listener on first form item to watch for escape and enter key to set focus on button
Correct your comment

2019-03-30 08:55 UTC, itswisdomagain commented on terminal/pages/balance.go
> +			setFocus(body)
Move this code to inside the `simpleOutput` function

2019-03-30 22:20 UTC, Sirmorrison commented on terminal/helpers/colors.go
> +	PageHeaderColor  = tcell.NewRGBColor(0, 255, 255)
will create a separate PR for colors lets keep this PR on balance only

2019-03-31 00:50 UTC, Sirmorrison commented
![image](https://user-images.githubusercontent.com/27733432/55283266-33ede680-5357-11e9-8074-50fb1f37e666.png)

![image](https://user-images.githubusercontent.com/27733432/55283276-5c75e080-5357-11e9-8fcf-2bf9b7c81052.png)

2019-04-03 22:51 UTC, itswisdomagain requested changes

2019-04-03 22:51 UTC, itswisdomagain commented on terminal/pages/balance.go
> +	balancePage.AddItem(titleTextView.SetText("Balance"), 1, 0, false)
Why not set the text in line 14 above and simply do `balancePage.AddItem(titleTextView, 1, 0, false)` here?

2019-04-03 22:51 UTC, itswisdomagain commented on terminal/pages/balance.go
> +	balancePage.AddItem(hintText.SetText("(TIP: Press TAB to display detailed balance info, ESC to return to Navigation Menu.)"), 3, 0, false)
Please set this text in line 17. Remove the period (.) at the end of the tip.

2019-04-03 22:51 UTC, itswisdomagain commented on terminal/pages/balance.go
> +
Delete empty line

2019-04-03 22:51 UTC, itswisdomagain commented on terminal/pages/balance.go
> +		balancePage.RemoveItem(titleTextView)
If I recall,  a previous review said don't remove the title and hint text view. Instead of removing and adding, simply change the text using `textView.SetText()`

2019-04-03 22:51 UTC, itswisdomagain commented on terminal/pages/balance.go
> +	clearBalanceViews := func(hintText, singleAccountBalanceTable, detailedBalanceTable, titleTextView, multipleAccountBalanceTable tview.Primitive) {
Last review also said to remove these function parameters, they're unnecessary.

2019-04-04 15:14 UTC, itswisdomagain commented
Updates:

![Screen Shot 2019-04-04 at 4 13 04 PM](https://user-images.githubusercontent.com/18400051/55566962-a1519c80-56f4-11e9-93a4-c1c90b7c413d.png)

![Screen Shot 2019-04-04 at 4 12 57 PM](https://user-images.githubusercontent.com/18400051/55566973-a44c8d00-56f4-11e9-8767-7e7bf3bb7a8c.png)

2019-04-05 14:00 UTC, itswisdomagain requested changes

2019-04-05 14:00 UTC, itswisdomagain commented on terminal/pages/overview.go
> +			SetCellRightAlign(row, 1, account.Balance.Total.String()).
The total and spendable balances should be normalized using `walletcore.NormalizeBalance`

2019-04-05 14:00 UTC, itswisdomagain commented on terminal/pages/overview.go
> +			SetCellRightAlign(row, 1, account.Balance.Total.String()).
The total and spendable balances should be normalized using `walletcore.NormalizeBalance`

2019-04-06 04:03 UTC, itswisdomagain approved these changes

2019-04-06 20:26 UTC, ademuanthony approved these changes

2019-04-06 20:26 UTC, merged