Nuklear layout
raedahgroup/godcr-old pull request #236
Opened 2019-03-22 14:38 UTC by codemaestro64

This is a general UI cleanup for the nuklear interface.

2019-03-23 04:31 UTC, itswisdomagain requested changes

2019-03-23 04:31 UTC, itswisdomagain commented on nuklear/handlers/sync.go
> +	// TODO remove next two lines
You forgot this...

2019-03-26 00:35 UTC, itswisdomagain commented
This PR changes how a number of pages look; include screenshots of affected pages and elements; update the PR description to inform what was accomplished in this PR

2019-03-30 13:45 UTC, itswisdomagain requested changes
Also reduce the account selection dropdown width.

2019-03-30 13:45 UTC, itswisdomagain commented on nuklear/helpers/colors.go
> +	ColorDanger  = color.RGBA{220, 53, 69, 255}
Use Orange color (237, 109, 71) from https://decred.org/brand/

2019-03-30 13:45 UTC, itswisdomagain commented on nuklear/helpers/colors.go
> +	ColorSuccess = color.RGBA{24, 85, 24, 255}
Use Green color (65, 191, 83) from https://decred.org/brand/

2019-03-30 13:45 UTC, itswisdomagain commented on nuklear/helpers/colors.go
> +	colorContentBackground = color.RGBA{240, 240, 250, 255}
This color is not in the decred style guide. Can this be white instead?

2019-03-30 13:45 UTC, itswisdomagain commented on nuklear/helpers/colors.go
> +	colorPrimaryBorder     = color.RGBA{255, 238, 232, 255}
- Is there a `colorSecondaryBorder`? I think `colorBorder` is just fine. `borderColor` is preferable actually, rename the variables to sound more "English" aka readable. `contentBackgroundColor` is more readable than `colorContentBackground`

- This color is not in the decred style guide, please pick a color from there, perhaps one of the complementary colors

2019-03-30 13:45 UTC, itswisdomagain commented on nuklear/helpers/colors.go
> +	colorAccent            = color.RGBA{237, 109, 71, 255}
I'm thinking you should create variables for the different decred brand colors, using variable names to match the names displayed on https://decred.org/brand/

2019-04-03 07:35 UTC, codemaestro64 commented
screenshots of latest changes 
![Screenshot from 2019-04-03 08-21-22](https://user-images.githubusercontent.com/42093751/55461034-5ef06880-55eb-11e9-87e7-30cb9b9a1e12.png)
![Screenshot from 2019-04-03 08-23-04](https://user-images.githubusercontent.com/42093751/55461035-5f88ff00-55eb-11e9-8ab3-a7230b650553.png)

2019-04-03 11:27 UTC, itswisdomagain submitted a review, later dismissed
Most of the comments in this review involve creating helper functions and packages. Look through the nuklear code more and aim to refactor other oft repeated code into functions.

2019-04-03 11:27 UTC, itswisdomagain commented on nuklear/handler.go
>  			label:   "Balance",
Rename to Overview

2019-04-03 11:27 UTC, itswisdomagain commented on nuklear/handler.go
>  			name:    "send",
History before send

2019-04-03 11:27 UTC, itswisdomagain commented on nuklear/handlers/createwallet.go
> +			contentWindow.Row(helpers.ErrorTextHeight).Dynamic(1)
What happens if the error text does not fit completely in this allocated space?
I think you should have a helper function that calculates the width of a text using the current window font, divides it by the available window width and returns the height to use for the label. Of course, the function might need to consider window padding and label padding to arrive at a valid height calculation.

Something of this nature (I didn't test this code, may need some improvements to work properly):
```
func (w *Window) EstimateTextHeight(text string) int {
	currentFont := w.Master().Style().Font
	textWidth := nucular.FontWidth(currentFont, text)
	fontHeight := nucular.FontHeight(currentFont)
	nLines := int(math.Ceil(float64(textWidth) / float64(w.Bounds.W)))
	return fontHeight * nLines
}
```

2019-04-03 11:27 UTC, itswisdomagain commented on nuklear/handlers/createwallet.go
> +		contentWindow.Row(helpers.LabelHeight).Dynamic(2)
Perhaps rename this to `helpers.SingleLineLabelHeight` to give the immediate impression that the height returned can only be used to display a single line of text.

If the text _could_ may require more lines, use the helper function mentioned above to determine a proper height to use.

2019-04-03 11:27 UTC, itswisdomagain commented on nuklear/handlers/createwallet.go
> +			seedWindow.Row(helpers.SeedTextHeight).Dynamic(1)
This shouldn't be a fixed height, use the text height estimator function mentioned above. Also compare the create wallet page of terminal ui.

2019-04-03 11:27 UTC, itswisdomagain commented on nuklear/handlers/history.go
> -	ctx                    context.Context
There is a problem with the way this file was rebased. All the changes related to history tx pagination is gone. Please compare this file on master and unless absolutely necessary, do not modify the code on master but copy it here in it's entirety.

2019-04-03 11:27 UTC, itswisdomagain commented on nuklear/handlers/receive.go
> +				contentWindow.Row(helpers.TextEditorHeight).Static(helpers.AccountSelectorWidth)
`helpers.TextEditorHeight` used for combo box height? Tells me the variable needs to be renamed.

2019-04-03 11:27 UTC, itswisdomagain commented on nuklear/handlers/receive.go
> +				handler.selectedAccountIndex = contentWindow.ComboSimple(accountNames, handler.selectedAccountIndex, 25)
Should also declare a constant for the combo box item height (=25)

2019-04-03 11:27 UTC, itswisdomagain commented on nuklear/handlers/receive.go
> +		window.Row(helpers.ErrorTextHeight).Dynamic(1)
Have a `window.DisplayError` helper function that does these 2 things:
- Calculate the text height and creates a row of that height
- Uses `window.LabelWrapColored` to add the error message as a colored label to the window

Modify all instances of error display in the nuklear interface to use this function to display errors

2019-04-03 11:27 UTC, itswisdomagain commented on nuklear/handlers/send.go
> +				contentWindow.Row(helpers.LabelHeight).Static(helpers.TextEditorWidth, helpers.TextEditorWidth)
I see lines similar to these lines 107 to 109 repeated everywhere. Let's have the following helper functions in a `label.go` file in the `helpers` package

```
type Label struct {
	Alignment label.Align
	Text 	  string
}

func (w *Window) AddLabel(height, width int, text string, alignment label.Align) {
	w.Row(height).Static(width)
	w.Label(text, alignment)
}

func (w *Window) AddLabels(height, width int, labels ...Label) {
	w.Row(height).Static(width)
	for _, lbl := range labels {
		w.Label(lbl.Text, lbl.Alignment)
	}
}
```

I'm thinking there would be need to move the existing `windows.go` file and the new `label.go` file to a `windows` package.

2019-04-03 11:27 UTC, itswisdomagain commented on nuklear/handlers/send.go
> +				contentWindow.Row(helpers.LabelHeight).Static(helpers.TextEditorWidth, helpers.TextEditorWidth)
You could/should also have another function `window.AddAutosizedLabel(text string, alignment label.Align)`:
```
func (w *Window) AddAutoSizedLabel(text string, alignment label.Align) {
	height := w.EstimateTextHeight(text)
	w.Row(height).Dynamic(1)
	w.Label(text, alignment)
}
```

2019-04-12 09:44 UTC, Sirmorrison commented
think adding a little padding between the `add another addresss` button and the `destination address` form field will be ok.

also a little space padding between the  `destination address` and the `amount input` form field will be in order

add little space padding between the `from` and `spend unconfirmed` also.

the area around the` send custom input` checkbox looks kind of crowded and disorganized too.

2019-04-12 10:11 UTC, Sirmorrison requested changes

2019-04-12 10:11 UTC, Sirmorrison commented on nuklear/handler.go
> +func (p *notImplementedNavPageHandler) Render(window *nucular.Window) {
add a space between lines 38 and 39

2019-04-12 10:11 UTC, Sirmorrison commented on nuklear/pagehandlers/send.go
> +	widgets.PageContentWindowDefaultPadding("Send", window, func(contentWindow *widgets.Window) {
`Send` should be `Sending Decred`

2019-04-12 10:11 UTC, Sirmorrison commented on nuklear/pagehandlers/send.go
> +		submitButtonText := "Submit"
I think `submit` should be `Send` then `submitting` should be `Sending`

2019-04-12 10:11 UTC, Sirmorrison commented on nuklear/pagehandlers/sync.go
> +	"image"
Re-Arrange imports

2019-04-12 10:11 UTC, Sirmorrison commented on nuklear/widgets/space.go
> +)
since we have only one import here i think it will be appropriate using `import  "github.com/aarzilli/nucular/rect"` instead

2019-04-12 10:11 UTC, Sirmorrison commented on nuklear/widgets/window.go
> +	"image/color"
Re-Arrange imports

2019-04-13 03:45 UTC, itswisdomagain commented on nuklear/pagehandlers/send.go
> +	widgets.PageContentWindowDefaultPadding("Send", window, func(contentWindow *widgets.Window) {
Will leave this for a different PR that will be focused on improving this page, more pre-approved, UI-related instructions will be made available then.

2019-04-13 03:45 UTC, itswisdomagain commented on nuklear/pagehandlers/send.go
> +		submitButtonText := "Submit"
Will leave this for a different PR that will be focused on improving this page, more pre-approved, UI-related instructions will be made available then.

2019-04-13 03:49 UTC, itswisdomagain commented
Stake info bug is fixed, send page error message formatting is corrected.

2019-04-13 08:48 UTC, ademuanthony approved these changes

2019-04-13 08:53 UTC, merged