Show connection info on the header and integrate websocket
raedahgroup/godcr-old pull request #242
Opened 2019-03-24 13:14 UTC by ademuanthony

Resolves [Issue 68](https://github.com/raedahgroup/godcr/issues/68)

This PR shows connection info and account balance in the header.

![connection-info](https://user-images.githubusercontent.com/11990092/54879890-e8ab7380-4e3e-11e9-96ee-e380c944a1ed.PNG)

Websocket is also implemented to notify the client of changes to this info.

Account balance on send and staking page is updated via web socker to reflect current value after each transaction

2019-03-26 10:48 UTC, itswisdomagain requested changes

2019-03-26 10:48 UTC, itswisdomagain commented on app/walletcore/types.go
> +	NetworkType        string `json:"networkType"`
`go fmt ./...`

2019-03-26 10:48 UTC, itswisdomagain commented on app/walletmediums/dcrlibwallet/spvsync.go
> +	if response.listener.OnPeerConnected == nil {
This function and the next can be simplified:
```
if response.listener.OnPeerConnected != nil {
    response.listener.OnPeerConnected(peerCount)
}
```

2019-03-26 10:48 UTC, itswisdomagain commented on app/walletmediums/dcrwalletrpc/walletfunctions.go
> +	return req.Height, err
`if err != nil`, won't `req == nil`? Trying to access `req.Height` then could panic. Best to:
```
if err != nil {
    return 0, err
}
return req.Height, nil
```

2019-03-26 10:48 UTC, itswisdomagain commented on app/walletcore/wallet.go
> +	BestBlock() (uint32, error)
Now that we have this function, update line 84 of `dcrwalletrpc/walletloader.go` and lines 33 and 51 of `dcrlibwallet/spvsync.go`

2019-03-26 10:48 UTC, itswisdomagain commented on main.go
> +	opError = web.StartServer(ctx, walletMiddleware, appConfig)
No need to send the entire `appConfig`, all that is really needed is `appConfig.HTTPHost, appConfig.HTTPPort`

2019-03-26 10:48 UTC, itswisdomagain commented on web/routes/handlers.go
> +	"github.com/raedahgroup/godcr/web/weblog"
arrange imports

2019-03-26 10:48 UTC, itswisdomagain commented on web/routes/handlers.go
> +func (routes *Routes) sendWsConnectionInfoUpdate() {
Move this function and the next to `websocket.go`, let's keep this file for route handlers only

2019-03-26 10:48 UTC, itswisdomagain commented on web/routes/handlers.go
> +		Message: info,
- `info. LatestBlock`  is not assigned
- most of the code in this function is duplicated in `routes. connectionInfo()`, move the repeated code into `walletcore/helpers.go`:

```
func WalletConnectionInfo(wallet Wallet, netType string) (*ConnectionInfo, error) {
	accounts, err := wallet.AccountsOverview(DefaultRequiredConfirmations)
	if err != nil {
		return nil, fmt.Errorf("error fetching account balance: %s", err.Error())
	}

	var totalBalance Balance
	for _, acc := range accounts {
		totalBalance.Spendable += acc.Balance.Spendable
		totalBalance.Total += acc.Balance.Total
	}

	bestBlock, _ := wallet.BestBlock()

	return &ConnectionInfo{
		NetworkType: netType,
		PeersConnected: wallet.GetConnectedPeersCount(),
		TotalBalance: totalBalance.String(),
		LatestBlock: bestBlock,
	}, nil
}
```

A different comment in this review explains how to setup the `wallet.GetConnectedPeersCount()` function. Yet another comment shows how this function may be invoked when loading pages.

2019-03-26 10:48 UTC, itswisdomagain commented on web/routes/routes.go
> +	conf             *config.Config
Assigned but never used, can be removed

2019-03-26 10:48 UTC, itswisdomagain commented on web/routes/routes.go
> +
1 of these empty lines should go

2019-03-26 10:48 UTC, itswisdomagain commented on web/routes/routes.go
> +	router.Get("/connection-info", routes.connectionInfo)
How about just `/connection`?

2019-03-26 10:48 UTC, itswisdomagain commented on web/routes/routes.go
> +	router.Get("/ws", routes.wsHandler)
The code in `routes.wsHandler` does not rely on an open wallet connection; it won't produce an error if there is no wallet or if sync is in progress or if the wallet is not open... A user (browser) should be able to establish a ws connection directly.

Setup this route handler in `loadRoutes`

2019-03-26 10:48 UTC, itswisdomagain commented on web/routes/walletloader.go
> +var numberOfPeers int32
Seeing as this value will also be needed in other interfaces, I recommend storing and updating it in `dcrlibwallet/spvsync.go` and `dcrwalletrpc/spvsync.go`. Then add a function `GetConnectedPeersCount() int` to `walletcore.Wallet`, implement the function in `dcrlibwallet/walletfunctions.go` and `dcrwalletrpc/walletfunctions.go` to return the value stored in `dcrlibwallet/spvsync.go` and `dcrwalletrpc/spvsync.go`

2019-03-26 10:48 UTC, itswisdomagain commented on web/routes/websocket.go
> +func handleMessages() {
`waitToSendMessagesToClients` is more informative

2019-03-26 10:48 UTC, itswisdomagain commented on web/static/app/src/controllers/info_controller.js
> +
Don't really need this empty line, can keep imports together

2019-03-26 10:48 UTC, itswisdomagain commented on web/views/layout.html
> +<div data-controller="info" class="header">
`info` is a poor name choice, `connection-info` is better

2019-03-26 10:48 UTC, itswisdomagain commented on web/static/app/src/controllers/info_controller.js
> +    axios.get('/connection-info').then(function (response) { // TODO use the actual url
This is a bad idea, the page was just loaded from the server, we should make it such that all required data are provided during page load.

- Assuming you've created the `walletcore.WalletConnectionInfo` function, add the following to `web/routes/render.go`:
```
func (routes *Routes) renderPage(tplName string, data map[string]interface{}, res http.ResponseWriter) {
	connectionInfo, err := walletcore.WalletConnectionInfo(routes.walletMiddleware, routes.walletMiddleware.NetType())
	if err != nil {
		weblog.LogError(err)
	}
	data["connectionInfo"] = connectionInfo
	routes.render(tplName, data, res)
}
```

- Modify all page handlers to use `routes.renderPage` instead of `routes.render`. The `createWalletPage` handler would need more work:
```
data := map[string]interface{}{
	"Seed": seed,
}
routes.renderPage("createwallet.html", data, res)
```

- Pass `.connectionInfo` when loading the header template in individual page html files:
```
{{ template "header" .connectionInfo }}
```

- Modify the header template to read the required information:
```
<div class="text-center">
    <h3>GoDCR <small data-target="info.networkType">{{ .NetworkType }}</small></h3>
    <p data-target="info.container" class="d-none">
        Balance: <b data-target="info.totalBalance">{{ .TotalBalance }}</b>
        | Synced with <b data-target="info.peersConnected">{{ .PeersConnected }}</b> Peers
        | Latest Block: <b data-target="info.latestBlock">{{ .LatestBlock }}</b>
    </p>
</div>
```

2019-03-26 10:48 UTC, itswisdomagain commented on web/static/app/src/controllers/send_controller.js
> +      if(_this.sourceAccountTarget.options) {
Need to run `yarn lint` to fix lint issues such as this line - there should be space after the `if` keyword

2019-03-26 10:48 UTC, itswisdomagain commented on web/static/app/src/index.js
> +  return protocol + '://' + loc.host + '/ws'
Use string interpolation: `${}`

2019-03-26 14:31 UTC, ademuanthony commented on app/walletcore/wallet.go
> +	BestBlock() (uint32, error)
did not see usage at `33 and 51 of dcrlibwallet/spvsync.go`

2019-03-26 14:33 UTC, ademuanthony commented on main.go
> +	opError = web.StartServer(ctx, walletMiddleware, appConfig)
I needed to also show DbDir before, but that has been moved to another PR

2019-03-30 20:27 UTC, itswisdomagain requested changes

2019-03-30 20:27 UTC, itswisdomagain commented on app/walletmediums/dcrwalletrpc/spvsync.go
> +			s.listener.OnPeerConnected(update.PeerInformation.PeerCount)
Should also do `numberOfPeers = update.PeerInformation.PeerCount`. Same thing for `case walletrpc.SyncNotificationType_PEER_DISCONNECTED` below

2019-03-30 20:27 UTC, itswisdomagain commented on web/routes/render.go
> +	"github.com/raedahgroup/godcr/app/walletcore"
Re-arrange imports

2019-03-30 20:27 UTC, itswisdomagain commented on web/routes/routes.go
> +
Empty line not necessary

2019-03-30 20:27 UTC, itswisdomagain commented on web/routes/walletloader.go
> +		// renderPage error on page if errMsg != ""
find and replace?
this comment should read `render error on page` not `renderPage error on page`

2019-03-30 20:27 UTC, itswisdomagain commented on web/routes/walletloader.go
> +				routes.sendWsConnectionInfoUpdate()
Should also listen for peer count updates and send ws connection info update

2019-03-30 20:27 UTC, itswisdomagain commented on web/routes/websocket.go
> +	"github.com/raedahgroup/godcr/app/walletcore"
Re-arrange imports

2019-03-30 20:27 UTC, itswisdomagain commented on web/static/app/src/controllers/connection-info_controller.js
> +      _this.show(_this.containerTarget)
Is `containerTarget` ever hidden? Do we need to create a target for the container element?

2019-03-30 20:27 UTC, itswisdomagain commented on web/static/app/src/controllers/send_controller.js
> +        _this.sourceAccountTarget.options[_this.sourceAccountTarget.selectedIndex].textContent = data
How are we certain that the balance received is for the selected account?

2019-04-03 04:49 UTC, itswisdomagain requested changes

2019-04-03 04:49 UTC, itswisdomagain commented on app/walletcore/helper.go
> +		return nil, fmt.Errorf("error fetching account balance: %s", err.Error())
On further thought, don't return nil. Return the network type, peers connected and latest block. This function should always return a `ConnectionInfo` object even if some error occured. The error should be returned too, so it can be logged appropriately by the calling interface.

2019-04-03 04:49 UTC, itswisdomagain commented on app/walletcore/helper.go
> +	bestBlock, _ := wallet.BestBlock()
Don't discard this error. Return it so it may be log appropriately.

2019-04-03 04:49 UTC, itswisdomagain commented on web/routes/walletloader.go
> +				routes.sendWsConnectionInfoUpdate()
- Is there any updated information to display at this time?
- There's need to register a `TransactionNotification` listener with either dcrlibwallet or dcrwallet to update the best block when there's a new block. Work for a different PR though, just add a todo comment here so we don't forget.

2019-04-03 04:49 UTC, itswisdomagain commented on web/static/app/package.json
> +    "lodash-es": "^4.17.11",
Can't find where this is used.

2019-04-03 04:49 UTC, itswisdomagain commented on web/static/app/src/index.js
> +function getSocketURI (loc) {
This `loc` param is not necessary, just use `window.location` directly.

2019-04-03 10:52 UTC, ademuanthony commented on app/walletcore/helper.go
> +		return nil, fmt.Errorf("error fetching account balance: %s", err.Error())
what happens when more than one error occurs, wish one should be returned?

2019-04-06 01:52 UTC, itswisdomagain requested changes
Please restore the yarn.lock file

2019-04-06 01:52 UTC, itswisdomagain commented on web/routes/render.go
> +	routes.renderPage("error.html", data, res)
This causes an error because connection info cannot be fetched when there is no wallet. We can stick with `rotues.render`

2019-04-06 01:52 UTC, itswisdomagain commented on web/routes/websocket.go
> +	var info = walletcore.ConnectionInfo{
The frontend expects to get all the connection info from this websocket update, but only net type and peers connected is set. This causes the balance and latest block to clear on the frontend after a websocket update.

Either we have different methods for updating specific connection info data or we call `walletcore.WalletConnectionInfo` here to get all the required data before sending to the client

2019-04-06 01:52 UTC, itswisdomagain commented on web/views/overview.html
> +    {{ template "header" .connectionInfo }}
This page isn't rendered with `routes.renderPage` so connection info doesn't show...

2019-04-06 01:52 UTC, itswisdomagain commented on web/views/staking.html
> +{{ template "html-head" .connectionInfo }}
Should be used with header template, not html-head

2019-04-06 01:52 UTC, itswisdomagain commented on web/routes/render.go
> +	routes.renderPage("error.html", data, res)
Also modify the `{{ template "header" }}` statement in the else block of the error.html file to `{{ template "header" .connectionInfo }}`. Sync progress (for now) is displayed on this page and it does not show the connection information on load

2019-04-06 01:52 UTC, itswisdomagain commented on web/static/app/src/controllers/send_controller.js
> +    ws.registerEvtHandler('updateBalance', function (data) {
This code is repeated across different controllers. Could create a shared utility function that the different controllers use to attach themselves to the balance update event. Something like:

```
export function listenForBalanceUpdate (_this) {
    ws.registerEvtHandler('updateBalance', function (data) {
        if (_this.sourceAccountTarget.options) {
            data.accounts.forEach(account => {
                for (let i = 0; i < _this.sourceAccountTarget.length; i++) {
                    const opt = _this.sourceAccountTarget.options[i]
                    if (parseInt(opt.value) === account.number) {
                        opt.textContent = account.info
                    }
                }
            })
        } else {
            _this.sourceAccountTarget.textContent = data.accounts[0].balance
        }
    })
}
```

2019-04-07 01:23 UTC, itswisdomagain requested changes

2019-04-07 01:23 UTC, itswisdomagain commented on app/walletcore/helper.go
> +		info.TotalBalance = totalBalance.String()
We should only show total balance here:
```
var totalBalance dcrutil.Amount
for _, acc := range accounts {
	totalBalance += acc.Balance.Total
}
info.TotalBalance = totalBalance.String()
```

- Also note there is no need to declare `totalBalance` outside the else block.
- `if loadAccountErr != nil`, `info.TotalBalance = "0 DCR"`, so it doesn't look off on the frontend

2019-04-07 01:23 UTC, itswisdomagain commented on app/walletcore/wallet.go
> +	NetType() string
This function's implementation in `dcrlibwallet` and `dcrwalletlib` need to move from the respective `walletloader.go` files to the `walletfunctions.go` files to complete this change

2019-04-07 01:23 UTC, itswisdomagain commented on web/routes/websocket.go
> +	var totalBalance walletcore.Balance
`var totalBalance dcrutil.Amount`

2019-04-07 01:23 UTC, itswisdomagain commented on web/routes/websocket.go
> +		totalBalance.Total += acc.Balance.Total
`totalBalance += acc.Balance.Total`

2019-04-07 01:23 UTC, itswisdomagain commented on .gitignore
> +web/static/dist/js/app.bundle.js
These files added to .gitignore should be manually deleted too

2019-04-07 01:23 UTC, itswisdomagain commented on web/views/receive.html
> +    <div class="body">
Bring back the `data-controller`

2019-04-08 13:31 UTC, itswisdomagain requested changes

2019-04-08 13:31 UTC, itswisdomagain commented on app/walletmediums/dcrlibwallet/walletfunctions.go
> +func (lib *DcrWalletLib) BestBlock() (uint32, error) {
Maintain the order of functions in the `Wallet` interface, makes it easier to find functions

2019-04-08 13:31 UTC, itswisdomagain commented on app/walletcore/wallet.go
> +	GetConnectedPeersCount() int32
This relates to syncing, should be in `app.WalletMiddleware`, the implementations should be in `dcrlibwallet/walletloader.go` and `dcrwalletrpc/walletloader.go`

2019-04-08 13:31 UTC, itswisdomagain commented on app/walletmediums/dcrwalletrpc/walletfunctions.go
> +func (c *WalletRPCClient) BestBlock() (uint32, error) {
Maintain the order of functions in the `Wallet` interface, makes it easier to find functions

2019-04-08 13:31 UTC, itswisdomagain commented on web/routes/websocket.go
> +	"github.com/decred/dcrd/dcrutil"
re-arrange imports

2019-04-09 16:46 UTC, itswisdomagain requested changes

2019-04-09 16:46 UTC, itswisdomagain commented on app/walletmediums/dcrlibwallet/spvsync.go
> +	if response.listener.OnPeerConnected != nil {
This if statement and the one in line 30 are not necessary. `response.listener` is never nil, and if `response.listener != nil`, then `response.listener.OnPeerConnected` cannot be nil. Other sync update functions do not perform similar check for similar reason.

2019-04-09 16:46 UTC, itswisdomagain commented on app/walletmediums/dcrwalletrpc/walletfunctions.go
> +	if c.activeNet.Name == "mainnet" {
Please return `c.activeNet.Name` to maintain consistency with `dcrlibwallet`; `dcrlibwallet` shows `testnet3` not `testnet`

2019-04-09 16:46 UTC, itswisdomagain commented on web/routes/handlers.go
> +	var info = walletcore.ConnectionInfo{
This should use `routes.walletMiddleware.WalletConnectionInfo()`. Remember to log any errors returned.

2019-04-09 16:46 UTC, itswisdomagain commented on web/routes/routes.go
> +	"github.com/raedahgroup/godcr/app/config"
Re-arrange imports

2019-04-09 16:46 UTC, itswisdomagain commented on web/routes/walletloader.go
> +				routes.sendWsConnectionInfoUpdate()
I think you should `sendWsConnectionInfoUpdate` regardless of whether an error occurs or not, it's a good idea to update the best block height after sync completes, whether successfully or not.

2019-04-09 16:46 UTC, itswisdomagain commented on web/routes/render.go
> +	connectionInfo, err := walletcore.WalletConnectionInfo(routes.walletMiddleware)
This should be `routes.walletMiddleware.WalletConnectionInfo()`

2019-04-09 16:46 UTC, itswisdomagain commented on web/routes/websocket.go
> +	UpdateBalance        eventType = "updateBalance"
I've noticed that these constants are only used in this file, we can make them unexported.

2019-04-09 23:01 UTC, itswisdomagain approved these changes

2019-04-09 23:01 UTC, merged