Fyne gui
raedahgroup/godcr-old pull request #243
Opened 2019-03-25 02:10 UTC by matthewjamesr

Implement base-level fyne gui module.

2019-03-28 12:41 UTC, itswisdomagain requested changes

2019-03-28 12:41 UTC, itswisdomagain commented on README.md
> +4. Native desktop app with [fyne](https://fyne.io/r) library.
This link (`https://fyne.io/r`) returns a 404 page
![Screenshot 2019-03-27 at 1 48 49 AM](https://user-images.githubusercontent.com/18400051/55042620-992d9900-5032-11e9-8376-061ad20b19d1.png)

2019-03-28 12:41 UTC, itswisdomagain commented on fyne/desktop.go
> +	a := app.New()
`a` is not a descriptive-enough variable name

2019-03-28 12:41 UTC, itswisdomagain commented on fyne/desktop.go
> +	w := a.NewWindow("GoDCR Wallet")
`w` can be `window`

2019-03-28 12:41 UTC, itswisdomagain commented on fyne/desktop.go
> +			widget.NewButton("Recieve", func() {
Typo, should be `Receive`

2019-03-28 12:41 UTC, itswisdomagain commented on fyne/desktop.go
> +	w.SetContent(fyne.NewContainerWithLayout(layout.NewGridLayout(1),
Declutter this line. Create variables for the different function arguments and pass those variables into each function called here instead. Make the code more readable. Use descriptive variable names so anyone reading the code has an idea what's going on even without having prior understanding of the fyne library

Here's what I came up with:
```
// need a comment here explaining what's happening in the next line, particularly why the grid layout has 1 column
menuLayout := fyne.NewContainerWithLayout(layout.NewGridLayout(1), menu)

// need a comment here explaining what's happening in the next line, particularly why the grid layout has 8 columns
contentLayout := fyne.NewContainerWithLayout(layout.NewGridLayout(8), content)

// need a comment here explaining what's happening in the next line, particularly why the grid layout has 4 columns
pageLayout := fyne.NewContainerWithLayout(layout.NewGridLayout(4), menuLayout, contentLayout)

w.SetContent(pageLayout)
```

2019-03-28 12:41 UTC, itswisdomagain commented on fyne/desktop.go
> +	content := widget.NewVBox(
Add a dummy text here for now, just to give more feeling to the app.

2019-03-28 12:41 UTC, itswisdomagain commented on fyne/desktop.go
> +	menu := widget.NewVBox(
No need to wrap the `Group` in a `VBox`
`VBox` only makes sense to use when there are more than 1 child object.

The following works just fine:
```
menu := widget.NewGroup("GoDCR", widget.NewVBox(
	widget.NewButton("Overview", func() {

	}),
	widget.NewButton("History", func() {

	}),
	widget.NewButton("Send", func() {

	}),
	widget.NewButton("Receive", func() {

	}),
	widget.NewButton("Accounts", func() {

	}),
	widget.NewButton("Security", func() {

	}),
	widget.NewButton("Governance", func() {

	}),
	widget.NewButton("Quit", func() {
		a.Quit()
	}),
))
```

2019-03-28 12:41 UTC, itswisdomagain commented on main.go
> +	//fyne.LaunchApp(ctx, walletMiddleware)
Commented out lines of code should not be included in version control. Such comments are practically useless - they are not compiled and unlike regular comments, they add no meaning to the code written.

2019-03-28 12:41 UTC, itswisdomagain commented on main.go
> +	// todo need to properly listen for shutdown and trigger shutdown
This comment isn't necessary. It was added to `nuklear` because the `nuklear` interface does not exit cleanly and so the shutdown operations are never triggered.

Fyne shuts down properly, so we're safe.

2019-03-28 21:54 UTC, itswisdomagain commented
- Also got a panic when I quit the app using the Quit button.
- And the navigation menu buttons expand/contract in width in response to window resizing, should keep the navigation area of fixed width.

2019-04-06 04:15 UTC, itswisdomagain approved these changes

2019-04-06 05:18 UTC, ademuanthony requested changes
The PR needs rebasing.

Can we monitor the Changed event of the window and redraw the interface accordingly? Some part of the app doesn't when you maximize the window.
![fyne-error-in-display](https://user-images.githubusercontent.com/11990092/55665200-df54da80-5832-11e9-997b-3ae48d7bdc0d.PNG)

Some part of the hash is
![fynt-partial-display](https://user-images.githubusercontent.com/11990092/55665244-c8fb4e80-5833-11e9-8c13-cfba847ed11b.png)
 missing

2019-04-06 05:18 UTC, ademuanthony commented on fyne/fyne.go
> +
Change the icon to Decred icon

2019-04-06 23:35 UTC, itswisdomagain commented on fyne/fyne.go
> +
This is something that will need to be done for other interfaces as well. #261 has been created to track this.

2019-04-07 00:37 UTC, ademuanthony approved these changes

2019-04-07 00:38 UTC, merged

2019-04-07 20:37 UTC, andydotxyz commented
> Can we monitor the Changed event of the window and redraw the interface accordingly? Some part of the app doesn't when you maximize the window.

With Fyne the window resize will cause the layout to be adjusted accordingly. If the layout is not changing correctly then correct change is to use a different layout rather than listening to events to change layout positions.