Auto-launch browser for http mode
raedahgroup/godcr-old pull request #245
Opened 2019-03-26 11:43 UTC by matthewjamesr

Gents,

This PR implements auto-launching of user's default browser if http server starts successfully.

2019-03-29 08:08 UTC, ademuanthony submitted a review, later dismissed
few changes needed

2019-03-29 08:08 UTC, ademuanthony commented on web/server.go
> +		fmt.Printf("Launching browser....\n")
`fmt.Println("Launching browser....")`

2019-03-29 08:08 UTC, ademuanthony commented on web/server.go
>  		return nil
`fmt.Println("Ready")`
`return nil`

2019-04-01 20:03 UTC, itswisdomagain requested changes

2019-04-01 20:03 UTC, itswisdomagain commented on web/server.go
> +	"github.com/pkg/browser"
We aim to use external libraries only if the solution provided cannot be quite easily accomplished with standard go libraries. For this use case, we don't need an external library. See this [SO answer](https://stackoverflow.com/a/39324149/6086027) and this [GH gist](https://gist.github.com/hyg/9c4afcd91fe24316cbf0).

2019-04-05 00:13 UTC, itswisdomagain approved these changes

2019-04-06 04:45 UTC, ademuanthony approved these changes

2019-04-06 04:45 UTC, merged