Transaction details nuklear
raedahgroup/godcr-old pull request #246
Opened 2019-03-27 11:06 UTC by codemaestro64

This adds a transaction details page to the nuklear interface.

2019-03-29 07:38 UTC, ademuanthony requested changes
We need to loop into the layout, some contents are cut under certain conditions.
I think we can reduce the margins and the width of the side menu to accommodate some of the long text.
Alternatively, we can break these contents to a new line.
See the attached screen for some suggestions


![nuklear-trans-details](https://user-images.githubusercontent.com/11990092/55216908-61734c80-51fe-11e9-8704-5faa805e98b8.png)

2019-04-03 05:50 UTC, itswisdomagain requested changes
- Rename "Transaction Details" header to "Transaction Detail"
- Rename "Time" to "Date"

2019-04-03 08:45 UTC, codemaestro64 commented
Updated screenshot 
![Screenshot from 2019-04-03 09-13-58](https://user-images.githubusercontent.com/42093751/55465458-163dad00-55f5-11e9-8451-a5d39f22732c.png)

2019-04-04 08:04 UTC, itswisdomagain requested changes
I see a lot of scroll bars everywhere when I resize the window. There should be only 1 scroll bar at the bottom and 1 at the right end of the page. Different sections shouldn't scroll. I think the scrolling is caused by your use of `window.GroupBegin`, I think.

![Screen Shot 2019-04-04 at 9 00 16 AM](https://user-images.githubusercontent.com/18400051/55539440-8e20db80-56b8-11e9-9e71-ea6b648ad61d.png)

2019-04-04 08:04 UTC, itswisdomagain commented on nuklear/handlers/history.go
> +type transaction struct {
These properties don't really describe a "transaction". They are more related to a transactionDetailsHandler or something, but since we don't have a separate handler for that, we can add these to the `HistoryHandler` directly. 

```
type HistoryHandler struct {
	err                    error
	ctx                    context.Context
	isRendering            bool
	transactions           []*walletcore.Transaction
	isFetchingTransactions bool
	nextBlockHeight        int32

	selectedTxHash         string
	selectedTxDetails      *walletcore.TransactionDetails
	hasFetchedTxDetails    bool
}
```

- You don't need `isDisplaying`, just check if `selectedTxHash != ""`.
- 1 err property can serve.

2019-04-04 08:04 UTC, itswisdomagain commented on nuklear/handlers/history.go
> +	if pageWindow := helpers.NewWindow("Transactions Page", window, 0); pageWindow != nil {
Noticing another issue here with previous changes to the history page being deleted. Please restore the history page code on master and only delete a code or comment there if it is ABSOLUTELY necessary.

2019-04-06 20:42 UTC, raedah commented
Reduce the empty space, more compact.

2019-04-06 22:32 UTC, itswisdomagain commented
Talking about reducing empty spaces, making the views more compact...
- Button heights can be reduced (including those in the nav section)
- The page title height can be reduced the spaces

Also, get rid of the short but inconveniencing scrollbar to the right of the entire window. There should only be a scrollbar in the content window. Currently some pages show 2 scrollbars - for the inner window content and for the entire window (including the page title).

2019-04-12 07:45 UTC, itswisdomagain commented
To take advantage of the latest changes in #236, let's hold off on working on this PR for a while. After #236 is merged, it might be a better idea to create a new branch of master and migrate some changes from here to the new branch, rebasing may take more time and require more work.

2019-04-16 11:22 UTC, codemaestro64 commented
![Screenshot from 2019-04-16 12-21-37](https://user-images.githubusercontent.com/42093751/56205623-3aac7700-6042-11e9-93ae-0ffe58fd0a5e.png)

2019-04-16 12:11 UTC, itswisdomagain submitted a review, later dismissed
This is looking very bright. Let's make these corrections and see where we go from there.

2019-04-16 12:11 UTC, itswisdomagain commented on nuklear/pagehandlers/history.go
> +	isFetchingTransactionDetails bool
- `selectedTxHash`, `selectedTxDetails` and `isFetchingTxDetails` make more sense
- let's add a `fetchTxDetailsError error` property and rename the first `err` property to `fetchHistoryError`

2019-04-16 12:11 UTC, itswisdomagain commented on nuklear/widgets/tablecell.go
> +	value       *bool
`selected` or `clicked` is better. I prefer `selected`. A link is ideally meant to be clicked but this particular link behaves like a checkbox, it is selectable and when it is selected or clicked, an action is triggered.

2019-04-16 12:11 UTC, itswisdomagain commented on nuklear/widgets/tablecell.go
> +	val := false
`selected` or `clicked` is better. I prefer `selected`

2019-04-16 12:11 UTC, itswisdomagain commented on nuklear/pagehandlers/history.go
> +	widgets.PageContentWindowDefaultPadding("Transaction Detail", window, func(contentWindow *widgets.Window) {
Transaction Details

2019-04-16 12:11 UTC, itswisdomagain commented on nuklear/pagehandlers/history.go
> +	handler.isFetchingTransactionDetails = false
- Remember to set `handler. fetchTxDetailsError = nil` here
- These four lines of code can be moved into a `handler.clearTxDetails` method which can then be triggered later by the "back button". The "back button" would call the `handler.clearTxDetails` method and then call `window.Master().Changed()`

2019-04-16 12:11 UTC, itswisdomagain commented on nuklear/pagehandlers/history.go
> +		if handler.err != nil {
Important to use a different error property here, so that when the tx details view is closed, and the history view is re-rendered, any previous fetch history error can be "remembered" and rendered.

2019-04-16 12:11 UTC, itswisdomagain commented on nuklear/pagehandlers/history.go
> +		if handler.isFetchingTransactionDetails {
This can be an `else if` to the previous `if` block, since it is either there is an error or tx details have been fetched or tx details is being fetched. All 3 possibilities are mutually inclusive.

2019-04-16 12:11 UTC, itswisdomagain commented on nuklear/pagehandlers/history.go
> +	contentWindow.Window.Row(0).Static(670, 700)
Add a comment here to signify why this row is being created, something like
```
// Create row to hold tx details in 2 columns
// Each column will display some data about the tx in a group window.
// Row height is set to 0 so the row takes entire available height of `contentWindow`.

2019-04-16 12:11 UTC, itswisdomagain commented on nuklear/pagehandlers/history.go
> +		table := widgets.NewTable()
`txDetailsTable1`

2019-04-16 12:11 UTC, itswisdomagain commented on nuklear/pagehandlers/history.go
> +		table = widgets.NewTable()
`txInputsTable`

2019-04-16 12:11 UTC, itswisdomagain commented on nuklear/pagehandlers/history.go
> +		table := widgets.NewTable()
`txDetailsTable2`

2019-04-16 12:11 UTC, itswisdomagain commented on nuklear/pagehandlers/history.go
> +		table = widgets.NewTable()
`txOutputsTable`

2019-04-16 12:11 UTC, itswisdomagain commented on nuklear/pagehandlers/history.go
>  	go handler.fetchTransactions(wallet, refreshWindowDisplay)
Bring the `handler.fetchTransactions` method closer to this `handler.BeforeRender` method, before the `handler.Render` method.

2019-04-16 12:11 UTC, itswisdomagain commented on nuklear/pagehandlers/history.go
> +	widgets.NoScrollGroupWindow("Transaction details column two", contentWindow.Window, func(window *widgets.Window) {
`tx-details-col-2`
These window titles are like unique ids in html, they're not displayed, just used as keys in organizing all created group windows

2019-04-16 12:11 UTC, itswisdomagain commented on nuklear/pagehandlers/history.go
> +	widgets.NoScrollGroupWindow("Transaction details column one", contentWindow.Window, func(window *widgets.Window) {
`tx-details-col-1`
These window titles are like unique ids in html, they're not displayed, just used as keys in organizing all created group windows

2019-04-16 12:11 UTC, itswisdomagain commented on nuklear/pagehandlers/history.go
> +	widgets.PageContentWindowDefaultPadding("Transaction Detail", window, func(contentWindow *widgets.Window) {
`tx-details`
These window titles are like unique ids in html, they're not displayed, just used as keys in organizing all created group windows

2019-04-16 12:11 UTC, itswisdomagain commented on nuklear/styles/styles.go
> +	// style link selectable
`// style selectable labels (links)`

2019-04-16 13:17 UTC, codemaestro64 commented on nuklear/pagehandlers/history.go
>  	go handler.fetchTransactions(wallet, refreshWindowDisplay)
done

2019-04-17 10:13 UTC, ademuanthony approved these changes

2019-04-17 21:22 UTC, merged