Settings page change password
raedahgroup/godcr-old pull request #249
Opened 2019-03-28 16:58 UTC by ademuanthony

This PR started working on the settings page on the web and implemented the change password feature

![settings-change-ske-design](https://user-images.githubusercontent.com/11990092/55177259-19631400-5183-11e9-9dcc-f2f8218f96ad.PNG)

![settings-change-pass](https://user-images.githubusercontent.com/11990092/55177269-2253e580-5183-11e9-907a-d65f0a7181b5.PNG)

2019-03-30 07:16 UTC, itswisdomagain requested changes
Let's work on these changes first, then I'll review some more. Also delete all auto-generated font-awesome files in the dist folder, ideally, we shouldn't even check the dist folder into source control since it should be re-generated by running `yarn build`

2019-03-30 07:16 UTC, itswisdomagain commented on app/config/config-file.go
> +	SpendUnconfirmedFunds bool          `long:"spendunconfirmedfunds" description:"Spend unconfirmed funds"`
- Rename all code usages/reference to `SpendUnconfirmedFunds` to `SpendUnconfirmed`
- Also, use `long:"spendunconfirmed"`
- We can display "Spend Unconfirmed Funds" to users but `spendUnconfirmed` is just fine for code

Also, create a separate struct for Settings and add to the `ConfFileOptions` struct as a group to give the following representation in the config file:
![Screenshot 2019-03-30 at 7 56 57 AM](https://user-images.githubusercontent.com/18400051/55272747-90062b80-52c1-11e9-9996-21bb6eb5d204.png)

This code should do the trick:
```
type ConfFileOptions struct {
        ...
	Settings `group:"Settings"`
}

type Settings struct {
	SpendUnconfirmed  bool `long:"spendunconfirmed"`
}
```

This means that instead of passing the entire config object to each interface, we can pass the settings object only.

2019-03-30 07:16 UTC, itswisdomagain commented on app/walletcore/wallet.go
> +	ChangePrivatePhrase(ctx context.Context, oldPass, newPass []byte) error
- Rename to `ChangePrivatePassphrase`
- Should accept `oldPass` and `newPass` as string just as is done for other wallet functions requiring passphrase to be provided

2019-03-30 07:16 UTC, itswisdomagain commented on app/walletmediums/dcrwalletrpc/walletfunctions.go
> +		NewPassphrase: newPass, OldPassphrase: oldPass, Key: walletrpc.ChangePassphraseRequest_PRIVATE,
Split into 3 lines

2019-03-30 07:16 UTC, itswisdomagain commented on web/routes/routes.go
> +	cnfg             *config.Config
Based on the other review comment about using a Settings struct, this can become
`settings     *config.Settings`

2019-03-30 07:16 UTC, itswisdomagain commented on web/routes/routes.go
> +		cnfg:             appConfig,
Based on the other review comment about using a Settings struct, this can become
`settings: appConfig.Settings`

2019-03-30 07:16 UTC, itswisdomagain commented on web/routes/routes.go
> +	router.Post("/settings/change-password", routes.changeSpendingPassword)
POST `/change-password` need not be a sub-path of `/settings`, can just be `/change-password`

2019-03-30 07:16 UTC, itswisdomagain commented on web/routes/routes.go
> +	router.Post("/settings/update-spend-unconfirmed", routes.updateSpendUnconfirmedFundSetting)
Have one PUT endpoint for updating all settings values -> PUT `/settings`, the handler should be able to determine which setting is about to be updated and update only that setting

2019-03-30 07:16 UTC, itswisdomagain commented on web/routes/handlers.go
> +	defer routes.render("settings.html", data, res)
Why `defer`? There is no code below this line...

2019-03-30 07:16 UTC, itswisdomagain commented on web/routes/handlers.go
> +		data["error"] = err.Error()
Do not display parse errors directly to users, simply say the input is invalid

2019-03-30 07:16 UTC, itswisdomagain commented on web/routes/handlers.go
> +		routes.cnfg.SpendUnconfirmedFunds = spendUnconfirmedFunds
Updating `routes.cnfg` or `routes.Settings` should only be done after the config file update is successful, that is if `err == nil`. Move this line of code to after line 451

2019-03-30 07:16 UTC, itswisdomagain commented on web/static/app/src/utils.js
> +export const setErrorMessage = (message) => {
`showErrorMessage` or `displayErrorMessage` or `showError` or `displayError` or `notifyError`. Definitely not `set`. Same for the success message function below

2019-03-30 07:16 UTC, itswisdomagain commented on web/static/app/src/controllers/settings_controller.js
> +      'errorMessage', 'successMessage',
Are these `'errorMessage', 'successMessage'` targets used?

2019-03-30 07:16 UTC, itswisdomagain commented on web/views/settings.html
> +                        <br/>
Use `mt-x` on the next h6 element instead of these multiple `<br/>` elements

2019-03-30 15:51 UTC, ademuanthony commented on web/routes/handlers.go
> +	defer routes.render("settings.html", data, res)
yes, not at the moment

2019-03-30 20:53 UTC, itswisdomagain requested changes

2019-03-30 20:53 UTC, itswisdomagain commented on app/walletmediums/dcrlibwallet/walletfunctions.go
> +	"github.com/pkg/errors"
Wrong import...

2019-03-30 20:53 UTC, itswisdomagain commented on app/config/config-file.go
> +	WalletRPCCert         string        `long:"walletrpccert" description:"Path to dcrwallet certificate file. Required if walletrpcserver is set."`
need to `go fmt ./...`

2019-03-30 20:53 UTC, itswisdomagain commented on app/walletmediums/dcrwalletrpc/walletfunctions.go
> +		NewPassphrase: []byte(newPass), OldPassphrase: []byte(oldPass), Key: walletrpc.ChangePassphraseRequest_PRIVATE,
Split into 3 lines for easier code readability

2019-03-30 20:53 UTC, itswisdomagain commented on web/routes/handlers.go
> +	err := routes.walletMiddleware.ChangePrivatePassphrase(context.Background(), oldPassword, newPassword)
`routes.ctx`

2019-03-30 20:53 UTC, itswisdomagain commented on web/routes/handlers.go
> +			data["error"] = "Invalid input"
Should specify which particular input is invalid. Also, since it's not cli, input may not be the right term to use. `Invalid value for spend unconfirmed funds setting`

2019-03-30 20:53 UTC, itswisdomagain commented on web/routes/handlers.go
> +			data["error"] = err.Error()
`fmt.Errorf("Error updating settings. %s", err.Error())`

2019-03-30 20:53 UTC, itswisdomagain commented on web/routes/handlers.go
> +	if newPassword != confirmPassword {
Also check if password is empty

2019-03-30 20:53 UTC, itswisdomagain commented on web/static/app/src/controllers/settings_controller.js
> +    submitBtn.textContent = 'Busy...'
`Updating...` or `Changing Password...` or `Submitting` is better

2019-03-30 20:53 UTC, itswisdomagain commented on web/static/app/src/controllers/settings_controller.js
> +      if (result.error !== undefined) {
`if !!result.error` or simply `if result.error`

2019-03-30 20:53 UTC, itswisdomagain commented on web/static/app/src/controllers/settings_controller.js
> +      $('#change-password-modal').modal('hide')
Only hide the modal if the passphrase change was successful. If there's an error, it would be a good idea to show the error on the modal persistently and keep the modal open so user can fix an issues and try again

2019-03-30 20:53 UTC, itswisdomagain commented on web/static/app/yarn.lock
> +jquery@>=1.12.0:
I see the `toastr` library brought with it jquery, is there a way we can benefit from this? definitely something for later

2019-03-30 20:53 UTC, itswisdomagain commented on web/views/layout.html
> +    <link rel="stylesheet" href="/static/font-awesome/css/font-awesome.css"/>
Link to node_modules and delete font_awesome files in the static dir

2019-03-30 20:55 UTC, ademuanthony commented on app/walletmediums/dcrlibwallet/walletfunctions.go
> +	"github.com/pkg/errors"
whoop

2019-03-30 21:08 UTC, ademuanthony commented on web/static/app/yarn.lock
> +jquery@>=1.12.0:
I am trying out the jquery issue even
including the dist folder is really disturbing me

2019-04-03 05:01 UTC, itswisdomagain requested changes

2019-04-03 05:01 UTC, itswisdomagain commented on go.mod
> +	github.com/pkg/errors v0.8.1
Need to run `go mod tidy`

2019-04-03 05:01 UTC, itswisdomagain commented on web/static/app/package.json
> +    "@fortawesome/fontawesome-svg-core": "^1.2.17",
No longer using font-awesome? Delete the files from dist

2019-04-03 05:01 UTC, itswisdomagain commented on web/static/app/src/utils.js
> +export const hide = (el) => {
Make other controllers import these `hide` and `show` functions

2019-04-05 12:12 UTC, ademuanthony commented on web/static/app/package.json
> +    "@fortawesome/fontawesome-svg-core": "^1.2.17",
we are using `fontawesome`, note that the namespace is `@fortawesome`

2019-04-06 03:30 UTC, itswisdomagain requested changes
Please delete the font-awesome files

2019-04-08 13:22 UTC, itswisdomagain requested changes

2019-04-08 13:22 UTC, itswisdomagain commented on web/static/app/src/index.js
>  dom.watch()
No need for duplicate `library.add` and `dom.watch`, can use 
```
library.add(faCog, faCopy)`
dom.watch()
```

Also, can you import both `faCopy` and `faCog` fonts at once? Like: 
```
import { faCog, faCopy } from '@fortawesome/free-solid-svg-icons'
```

2019-04-08 13:22 UTC, itswisdomagain commented on web/static/app/src/controllers/settings_controller.js
> +    const postData = `spendUnconfirmed=${this.spendUnconfirmedFundsTarget.checked}`
Url query param should be `spend-unconfirmed`

2019-04-08 14:06 UTC, itswisdomagain requested changes
![Screen Shot 2019-04-08 at 3 05 30 PM](https://user-images.githubusercontent.com/18400051/55730321-cfdeb880-5a0f-11e9-93b4-f1aa7b3d081e.png)

- The font sizes look really big
- The spend unconfirmed check is always there, should be toggled instead of using a background

![Screen Shot 2019-04-08 at 3 07 26 PM](https://user-images.githubusercontent.com/18400051/55730424-0caaaf80-5a10-11e9-9de8-b8bfbd4746b9.png)

-Passphrase change errors should be displayed on the form

2019-04-08 14:06 UTC, itswisdomagain commented on web/routes/routes.go
> +	router.Get("/settings", routes.settingsPage)
These endpoints do not require the wallet to be synced, they can be registered in the `loadRoutes` method. Also, this order makes more meaningful sense:
```
router.Get("/settings", routes.settingsPage)
router.Put("/settings", routes.updateSetting)
router.Post("/change-password", routes.changeSpendingPassword)
```

2019-04-08 16:25 UTC, ademuanthony commented
updated

![setting-page-update](https://user-images.githubusercontent.com/11990092/55740563-420cc880-5a23-11e9-9344-eac2d35b529a.PNG)

2019-04-08 21:51 UTC, itswisdomagain requested changes

2019-04-08 21:51 UTC, itswisdomagain commented on web/views/staking.html
>                                          <label for="spend-unconfirmed">Spend Unconfirmed</label>
Please move this label to after the checkbox

2019-04-08 21:51 UTC, itswisdomagain commented on web/views/settings.html
> +                                <p class="mb-1">Required to send fund</p>
`class="mb-0"` to achieve perfect top and bottom spacing

2019-04-08 21:59 UTC, itswisdomagain approved these changes

2019-04-08 21:59 UTC, merged