Overview page
raedahgroup/godcr-old pull request #252
Opened 2019-04-01 12:25 UTC by ademuanthony

Added overview page to the web with balance, recent transactions and common navigation buttons

![overview-page-web](https://user-images.githubusercontent.com/11990092/55327271-9b07ba00-5481-11e9-9cdd-d3008f1a981e.PNG)

2019-04-01 20:20 UTC, itswisdomagain requested changes

2019-04-01 20:20 UTC, itswisdomagain commented on web/routes/handlers.go
> +		routes.renderError(fmt.Sprintf("Error fetching recent activities: %s", err.Error()), res)
- `recent **activity**`
- also, no need to render an error if the account balance was retrieved successfully, instead show the balance, then show the error message just below the "Recent Activity" header on the page

2019-04-01 20:20 UTC, itswisdomagain commented on web/views/overview.html
> +                    <h5 class="mt-5">Recent Activities</h5>
Use `h4` too; and `Recent **Activity**`

2019-04-01 20:20 UTC, itswisdomagain commented on web/views/overview.html
> +                    <div class="row">
@raedah says these buttons are not necessary. We do already have the nav menu just above...

2019-04-03 05:06 UTC, itswisdomagain requested changes
Update the screenshot too

2019-04-03 05:06 UTC, itswisdomagain commented on web/views/overview.html
> +                    <div class="alert-danger"><p>{{.loadTransactionErr}}</p></div>
Wrap this div with `{{ if . loadTransactionErr }}`, then the rest should be in else. No need to show error and say no transaction found.

2019-04-03 10:28 UTC, ademuanthony commented
Updated to only show transactions if there is no error while loading tnxs

![overview-page-error](https://user-images.githubusercontent.com/11990092/55472279-9bc85980-5603-11e9-8c52-fe8197805143.PNG)

2019-04-04 06:14 UTC, itswisdomagain approved these changes

2019-04-04 06:23 UTC, merged