[WIP] Improve sync progress indicator on all interfaces
raedahgroup/godcr-old pull request #254
Opened 2019-04-02 01:46 UTC by itswisdomagain

Web (will add websocket updates after #242 is merged)
![Screenshot 2019-04-02 at 2 46 04 AM](https://user-images.githubusercontent.com/18400051/55370166-806d2980-54f1-11e9-86b2-13e322d330a7.png)

2019-04-16 05:29 UTC, ademuanthony requested changes

2019-04-16 05:29 UTC, ademuanthony commented on fyne/sync.go
> +		case 1:
Is there a way to know what this `1` and the `2` and `3` in the second and third case below mean without looking at the code block? I guess 1 => `FetchingBlockHeaders`, 2 => `DiscoveringUsedAddresses` and 3 => `ScanningBlockHeaders`. Maybe `dcrlibwallet` can declare these constants and we can use the same here

2019-04-16 05:29 UTC, ademuanthony commented on nuklear/pagehandlers/sync.go
> +		case 1:
The same issue as noted in `fyne/sync.go`

2019-04-16 05:29 UTC, ademuanthony commented on terminal/pages/sync.go
> +				tviewApp.Stop()
we can `return nil` here and remove the `else`

2019-04-16 05:29 UTC, ademuanthony commented on terminal/pages/sync.go
> +		case 1:
The same issue as noted in `fyne/sync.go`

2019-04-16 05:29 UTC, ademuanthony commented on web/routes/render.go
> +func (routes *Routes) renderSyncPage(syncInfo map[string]interface{}, res http.ResponseWriter) {
This is used only once in route/walletloader.go, line 56
WE can remove this and call `routes.render("sync.html", syncInfo, res)` directly there

2019-04-16 05:29 UTC, ademuanthony commented on web/static/app/src/controllers/sync_controller.js
> +      switch (syncInfo.CurrentStep) {
Can `dcrlibwallet` provide json tags for the `info` struct so that the fields here can start with a lower case such that we will have `syncInfo.currentStep`?

2019-04-16 05:46 UTC, itswisdomagain commented on terminal/pages/sync.go
> +				tviewApp.Stop()
nil should be returned in both cases, whether it’s the first time ESC is pressed or the second time. Not returning nil will cause some other key press handler to attempt to handle the ESC key press which is not desired.

2019-04-16 05:47 UTC, itswisdomagain commented on web/routes/render.go
> +func (routes *Routes) renderSyncPage(syncInfo map[string]interface{}, res http.ResponseWriter) {
I prefer we keep all page rendering events in this file, for easier debugging...

2019-04-16 05:47 UTC, itswisdomagain commented on web/static/app/src/controllers/sync_controller.js
> +      switch (syncInfo.CurrentStep) {
I thought about this too. Will implement

2019-04-18 04:33 UTC, ademuanthony approved these changes

2019-04-18 04:35 UTC, merged