implemented terminal transaction details page
raedahgroup/godcr-old pull request #257
Opened 2019-04-03 01:35 UTC by Sirmorrison

![image](https://user-images.githubusercontent.com/27733432/55446754-e2dd2d00-55b8-11e9-84e4-2daf2b674909.png)

![image](https://user-images.githubusercontent.com/27733432/55446791-0d2eea80-55b9-11e9-900b-4b3cc76e32df.png)

2019-04-03 05:49 UTC, itswisdomagain requested changes
Let's use your PR as an opportunity to align the tx detail page on all interfaces.

http
- Rename "Transactions" header to "Transaction Detail"
- Rename "Time" to "Date"

cli and terminal
- Rename "Rate" to "Fee Rate"
- terminal should follow the same order as in cli

2019-04-03 05:49 UTC, itswisdomagain commented on terminal/pages/history.go
> +	body.AddItem(hintText.SetText("(TIP: Use ARROW UP/DOWN to select txn, ENTER to view details, ESC to return to nav menu)"), 3, 0, false)
Move to bottom of page

2019-04-03 05:49 UTC, itswisdomagain commented on terminal/pages/history.go
> +		body.RemoveItem(titleTextView)
Leave the hint and title text view and just call `titleTextView.SetText` and `hintText.SetText` where necessary to update the text displayed.

2019-04-03 05:49 UTC, itswisdomagain commented on terminal/pages/history.go
> +	detailedTableHeaderCell := func(text string) *tview.TableCell {
- This is not used for creating table header cells!
- Also, this function isn't necessary, see below for alternative

2019-04-03 05:49 UTC, itswisdomagain commented on terminal/pages/history.go
> +	clearHistoryPage := func(hintText, historyTable, transactionDetailsTable, titleTextView tview.Primitive) {
No need for this parameters, this `clearHistoryPage` function can access them directly.

2019-04-03 05:49 UTC, itswisdomagain commented on terminal/pages/history.go
> +		body.AddItem(titleTextView.SetText("Transaction Detail"), 1, 0, false)
Simply `titleTextView.SetText` and `hintText.SetText`, no need to add first only to add it back immediately with different text.

2019-04-03 05:49 UTC, itswisdomagain commented on terminal/pages/history.go
> +		setFocus(transactionDetailsTable)
Call `setFocus` after adding the `transactionDetailsTable` to the page `body`

2019-04-03 05:49 UTC, itswisdomagain commented on terminal/pages/history.go
> +		fetchTransactionDetail(txHash, wallet, displayError, transactionDetailsTable)
Move lines 68 - 79 above into the `fetchTransactionDetail` function

2019-04-03 05:49 UTC, itswisdomagain commented on terminal/pages/history.go
> +		transactionDetailsTable.SetCell(0, 0, detailedTableHeaderCell("Date"))
Use `table.SetCellSimple(row, column int, text string)` for left-aligned text

2019-04-03 05:49 UTC, itswisdomagain commented on terminal/pages/history.go
> +		transactionDetailsTable.SetCell(7, 0, detailedTableHeaderCell("Included in block \n \n \t"))
What's the `\n \n \t` for?

2019-04-03 05:49 UTC, itswisdomagain commented on terminal/pages/history.go
> +	transactionDetailsTable.SetCell(0, 1, tview.NewTableCell(tx.FormattedTime).SetAlign(tview.AlignLeft))
Use `table.SetCellSimple(row, column int, text string)` for left-aligned text

2019-04-03 05:49 UTC, itswisdomagain commented on terminal/pages/history.go
> +	transactionDetailsTable.SetCell(4, 1, tview.NewTableCell(fmt.Sprintf("%s/kB\n", tx.FeeRate)).SetAlign(tview.AlignLeft))
What's `\n` for?

2019-04-03 05:49 UTC, itswisdomagain commented on terminal/pages/history.go
> +	transactionDetailsTable.SetCell(row, 0, tview.NewTableCell(" ").SetAlign(tview.AlignLeft))
Don't add an empty line/row

2019-04-03 05:49 UTC, itswisdomagain commented on terminal/pages/history.go
> +	for _, txIn := range tx.Inputs {
Where's the `Inputs` section title text. Use `-Inputs-` before listing the inputs

2019-04-03 05:49 UTC, itswisdomagain commented on terminal/pages/history.go
> +	transactionDetailsTable.SetCell(row, 0, tview.NewTableCell("Output").SetAlign(tview.AlignLeft))
`-Outputs-`

2019-04-03 05:49 UTC, itswisdomagain commented on terminal/pages/history.go
> +			transactionDetailsTable.SetCell(row, 0, tview.NewTableCell(fmt.Sprintf("  %s \t (no address)\n", dcrutil.Amount(txOut.Value).String())).SetAlign(tview.AlignLeft))
What's `\t` and `n` for?

2019-04-03 05:49 UTC, itswisdomagain commented on terminal/pages/history.go
> +			transactionDetailsTable.SetCell(row, 1, tview.NewTableCell(fmt.Sprintf("%s (%s)\n", address.Address, accountName)).SetAlign(tview.AlignLeft))
What's `\n` for?

2019-04-03 05:49 UTC, itswisdomagain commented on terminal/primitives/textview.go
> +func TitleTextView(text string) *TextView {
- What's wrong with just calling `NewLeftAlignedTextView` directly?
- Also, isn't a TextView by default left aligned?

2019-04-03 07:42 UTC, Sirmorrison commented on terminal/pages/history.go
> +	body.AddItem(hintText.SetText("(TIP: Use ARROW UP/DOWN to select txn, ENTER to view details, ESC to return to nav menu)"), 3, 0, false)
will fix this in the terminal colour and unify PR or will use a different PR so all pages will be affected.

2019-04-04 10:54 UTC, itswisdomagain requested changes
The tx detail display (from the screenshot) looks really better. But the code needs some work.

2019-04-04 10:54 UTC, itswisdomagain commented on terminal/pages/history.go
> +	body.AddItem(hintText.SetText("(TIP: Use ARROW UP/DOWN to select txn, ENTER to view details, ESC to return to nav menu)"), 3, 0, false)
Please set this text in line 23

2019-04-04 10:54 UTC, itswisdomagain commented on terminal/pages/history.go
> +		SetSelectable(false, false)
This isn't necessary, it's not selectable by default

2019-04-04 10:54 UTC, itswisdomagain commented on terminal/pages/history.go
> +		clearHistoryPage()
The `clearHistoryPage()` function isn't really needed actually. At this point, the `transactionDetailsTable` is not on the page so no need to remove it. Instead of calling `clearHistoryPage()`, what you should be doing really is `body.RemoveItem(historyTable)`

2019-04-04 10:54 UTC, itswisdomagain commented on terminal/pages/history.go
> +			history()
- Line 75 isn't needed. `history` also calls `clearHistoryPage()`, no need to call it twice.
- Also, line 77. `setFocus` should be part of that `history` function. Do we even need to call `setFocus`? The `history` function does this: `body.AddItem(historyTable, 0, 1, true)` which makes the table focused. No need for `setFocus`

2019-04-04 10:54 UTC, itswisdomagain commented on terminal/pages/history.go
> +	var history func()
Is there a reason why you can't declare and assign here directly?

2019-04-04 10:54 UTC, itswisdomagain commented on terminal/pages/history.go
> +		clearHistoryPage()
The `clearHistoryPage()` function isn't really needed actually. At this point, the `historyTable` is not on the page so no need to remove it. Instead of calling `clearHistoryPage()`, what you should be doing really is `body.RemoveItem(transactionDetailsTable)`

2019-04-04 10:54 UTC, itswisdomagain commented on terminal/pages/history.go
> +	history = func() {
- This function should be renamed to `displayHistoryTable`
- The function should not be "creating" the header everytime, just show the table and update the title and hint

```
displayHistoryTable = func() {
	body.RemoveItem(transactionDetailsTable)

	titleTextView.SetText("History")
	hintText.SetText("(TIP: Use ARROW UP/DOWN to select txn, ENTER to view details, ESC to return to nav menu)")

	body.AddItem(historyTable, 0, 1, true)
}
```

- The code for setting the table header should be moved to just before `fetchAndDisplayTransactions`. The idea is, you set the table header, make the table visible by calling `displayHistoryTable`, then call `fetchAndDisplayTransactions`.

2019-04-04 10:54 UTC, itswisdomagain commented on terminal/pages/history.go
>  	body.AddItem(nil, 1, 0, false) // add some "padding" at the bottom
Remove this line of code as your other PR will take care of padding

2019-04-04 10:54 UTC, itswisdomagain commented on terminal/pages/history.go
> +		setFocus(transactionDetailsTable)
This is not necessary. Line 61 above already makes the table focused.

2019-04-04 10:54 UTC, itswisdomagain commented on terminal/pages/history.go
>  	historyTable.SetSelectedFunc(func(row, column int) {
This function should go below.
The order of operation should be

- Create the title textview, hint textview, history table and details table
- Create the `displayHistoryTable` function and put the needed code inside
- Create the `displayError` function
- Add the "handlers" in this order (historyTable.SetDoneFunc, historyTable.SetSelectedFunc, transactionDetailsTable.SetInputCapture)
- Call `displayHistoryTable()` and then `fetchAndDisplayTransactions`
- Focus body and return

2019-04-04 10:54 UTC, itswisdomagain commented on terminal/pages/history.go
> +	// hander for setting focus on transaction Details Table and returning back to history table
- typo in hander - handler
- does this "set focus on transaction details table"?

2019-04-04 10:54 UTC, itswisdomagain commented on terminal/pages/history.go
> +		body.AddItem(transactionDetailsTable, 0, 1, true)
- `transactionDetailsTable.Clear()` before adding it to body
- that means, you won't need to do that again inside the `fetchTransactionDetail` function

2019-04-04 10:54 UTC, itswisdomagain commented on terminal/pages/history.go
> +	transactionDetailsTable.SetCellSimple(9, 0, "-Inputs-")
Move this to just below the for loop for displaying inputs. Keep related code together, make it easier to understand what's going on.

2019-04-04 10:54 UTC, itswisdomagain commented on terminal/pages/history.go
> +		row := transactionDetailsTable.GetRowCount()
Can just do `row++` here instead.

2019-04-04 12:24 UTC, Sirmorrison commented on terminal/pages/history.go
> +	body.AddItem(hintText.SetText("(TIP: Use ARROW UP/DOWN to select txn, ENTER to view details, ESC to return to nav menu)"), 3, 0, false)
issues with hint textview have been resolved in PR 259

2019-04-04 12:26 UTC, itswisdomagain commented on terminal/pages/history.go
> +	body.AddItem(hintText.SetText("(TIP: Use ARROW UP/DOWN to select txn, ENTER to view details, ESC to return to nav menu)"), 3, 0, false)
Doesn't mean you can't fix it here as well. It's a small, quick fix.

2019-04-04 13:10 UTC, Sirmorrison commented on terminal/pages/history.go
> +		setFocus(transactionDetailsTable)
it doesnt set the focus noticed it initially and just tried it now

2019-04-04 13:21 UTC, itswisdomagain commented on terminal/pages/history.go
> +		setFocus(transactionDetailsTable)
Okay

2019-04-04 23:23 UTC, itswisdomagain requested changes
Getting closer, should be good to merge after these.

2019-04-04 23:23 UTC, itswisdomagain commented on web/views/transaction_details.html
> +            <h3>Transactions Details</h3>
`Detail` not `Details`

2019-04-04 23:23 UTC, itswisdomagain commented on terminal/pages/history.go
> +	body.AddItem(titleTextView.SetText("History"), 1, 0, false)
You really need to stop doing this. You do realize that `body.AddItem` is supposed to take an item to add, yeah? Add the `item` not the `item.SetText`!
What prevents you from setting the text in line 20?

2019-04-04 23:23 UTC, itswisdomagain commented on terminal/pages/history.go
> +		SetSeparator(' ')
This is the default separator actually, so this line is really not needed. Can merge `transactionDetailsTable := tview.NewTable().SetBorders(false)` into one line

2019-04-04 23:23 UTC, itswisdomagain commented on terminal/pages/history.go
>  		SetSeparator('\t').
This separator setting has no effect, please remove this line

2019-04-04 23:23 UTC, itswisdomagain commented on terminal/pages/history.go
> +	// error handler
What is the `error handler`? The `errorTextView`? A handler should be a function not a view... Please correct or delete your comment

2019-04-04 23:23 UTC, itswisdomagain commented on terminal/pages/history.go
> +	// method for getting transaction details
`// method for getting transaction details when a tx is selected from the history table`

2019-04-04 23:23 UTC, itswisdomagain commented on terminal/pages/history.go
> +	displayHistoryTable()
The best time to display this table should be after setting the table headers

2019-04-04 23:23 UTC, itswisdomagain commented on terminal/pages/history.go
> +	// Table header
for which table, there are more than 1 table here, your comment can be improved

2019-04-04 23:23 UTC, itswisdomagain commented on terminal/pages/history.go
> +func fetchTransactionDetail(txHash string, wallet walletcore.Wallet, displayError func(errorMessage string), transactionDetailsTable *tview.Table) {
`fetchAndDisplayTransactions` should come before this function. It is triggered first in the scheme of things for this page.

2019-04-04 23:23 UTC, itswisdomagain commented on terminal/pages/history.go
> +	transactionDetailsTable.SetCellSimple(2, 0, "Included in block  ")
Why is there space at the end of this text?

2019-04-04 23:29 UTC, itswisdomagain commented on web/views/transaction_details.html
> +            <h3>Transactions Details</h3>
Ignore this actually, `Transaction Details` is just fine

2019-04-04 23:51 UTC, itswisdomagain requested changes
These changes too

2019-04-04 23:51 UTC, itswisdomagain commented on terminal/pages/history.go
> +		transactionDetailsTable.SetCellSimple(row, 0, dcrutil.Amount(txIn.AmountIn).String())
Use `SetCell` and make this right aligned.

2019-04-04 23:51 UTC, itswisdomagain commented on terminal/pages/history.go
> +			transactionDetailsTable.SetCellSimple(row, 0, outputAmount)
Use `SetCell` and make this right aligned.

2019-04-04 23:51 UTC, itswisdomagain commented on terminal/pages/history.go
> +		if event.Key() == tcell.KeyBackspace {
This doesn't work on mac for some reason, use `if event.Key() == tcell.KeyBackspace || event.Key() == tcell.KeyBackspace2`

2019-04-05 23:30 UTC, itswisdomagain approved these changes

2019-04-06 02:44 UTC, itswisdomagain requested changes
Final changes

2019-04-06 02:44 UTC, itswisdomagain commented on terminal/pages/history.go
> +		body.AddItem(historyTable, 0, 1, true)
Add `setFocus(historyTable)`

2019-04-06 02:44 UTC, itswisdomagain commented on terminal/pages/history.go
> +
Add the following code somewhere here
```
decimalPlaces := func(n float64) string {
	decimalPlaces := fmt.Sprintf("%f", n - math.Floor(n))
	decimalPlaces = strings.Replace(decimalPlaces, "0", "", -1)
	decimalPlaces = strings.Replace(decimalPlaces, ".", "", -1)
	return decimalPlaces
}

// calculate max number of digits after decimal point for inputs and outputs
maxDecimalPlaces := 0
for _, txIn := range tx.Inputs {
	decimalPlaces := decimalPlaces(dcrutil.Amount(txIn.AmountIn).ToCoin())
	nDecimalPlaces := len(decimalPlaces)
	if nDecimalPlaces > maxDecimalPlaces {
		maxDecimalPlaces = nDecimalPlaces
	}
}
for _, txOut := range tx.Outputs {
	decimalPlaces := decimalPlaces(dcrutil.Amount(txOut.Value).ToCoin())
	nDecimalPlaces := len(decimalPlaces)
	if nDecimalPlaces > maxDecimalPlaces {
		maxDecimalPlaces = nDecimalPlaces
	}
}

formatAmount := func(amount int64) string {
	dcrAmount := dcrutil.Amount(amount).ToCoin()
	wholeNumber := int(math.Floor(dcrAmount))
	decimalPlaces := decimalPlaces(dcrAmount)

	if len(decimalPlaces) == 0 {
		//decimalPlaces = "0"
		return fmt.Sprintf("%d%-*s DCR", wholeNumber, maxDecimalPlaces + 1, decimalPlaces)
	}

	return fmt.Sprintf("%d.%-*s DCR", wholeNumber, maxDecimalPlaces, decimalPlaces)
}
```

Then use `formatAmount(txIn.AmountIn)` and `formatAmount(txOut.Value)` to display input and output amounts respectively.

The goal is to achieve this:
![Screen Shot 2019-04-06 at 3 39 30 AM](https://user-images.githubusercontent.com/18400051/55663954-3c926100-581e-11e9-8f64-f785a8e8dbc9.png)

2019-04-06 04:14 UTC, itswisdomagain approved these changes

2019-04-06 04:37 UTC, itswisdomagain commented
![Screen Shot 2019-04-06 at 3 39 30 AM](https://user-images.githubusercontent.com/18400051/55664907-02c95680-582e-11e9-98b3-668c7edb285a.png)

2019-04-06 05:34 UTC, ademuanthony approved these changes

2019-04-06 05:34 UTC, merged