Added connection type to terminal header, aligned all page items
raedahgroup/godcr-old pull request #259
Opened 2019-04-03 22:14 UTC by Sirmorrison

Added connection type to terminal header, aligned all page items, moved hit text to bottom of screen for all pages.

![image](https://user-images.githubusercontent.com/27733432/55516768-280b6880-5666-11e9-86ee-549c4cea3876.png)

2019-04-03 22:46 UTC, itswisdomagain requested changes

2019-04-03 22:46 UTC, itswisdomagain commented on terminal/pages/balance.go
> +	hintText := primitives.WordWrappedTextView("")
Create the `hintTextView` in the rootpage and add it to the gridview there, then pass the textview to other pages, so the pages only need to set the text as required. This will reduce the amount of code you'll need to write in each page (simply `hintTextView.SetText("hint")` and also ensure that the hint text is ALWAYS visible at the bottom of each page.

2019-04-03 22:46 UTC, itswisdomagain commented on terminal/pages/history.go
> +	body.SetBorderPadding(1, 0, 2, 0)
Why are some page body padded and others are not? Can we unify the look across all pages?

2019-04-03 22:46 UTC, itswisdomagain commented on terminal/pages/rootpage.go
> +	header := primitives.NewCenterAlignedTextView(fmt.Sprintf("\n %s %s\n", strings.ToUpper(app.Name), netType))
Is it possible to show the network type in smaller fonts? Perhaps using a different text view for that? Compare ![the web version](https://user-images.githubusercontent.com/11990092/54953725-344a4400-4f49-11e9-9243-40448c1bd9f2.PNG)

2019-04-03 22:46 UTC, itswisdomagain commented on terminal/pages/sync.go
> +	// "github.com/gdamore/tcell"
Why are these commented? So many commented codes on this file, please fix.

2019-04-04 09:50 UTC, itswisdomagain requested changes

2019-04-04 09:50 UTC, itswisdomagain commented on terminal/pages/balance.go
> +func balancePage(wallet walletcore.Wallet, hintText *primitives.TextView, setFocus func(p tview.Primitive) *tview.Application, clearFocus func()) tview.Primitive {
Rename all instances of `hintText` to `hintTextView` please. It's not a text but a text view.

2019-04-04 09:50 UTC, itswisdomagain commented on terminal/pages/rootpage.go
> +	hintText := primitives.WordWrappedTextView("")
Rename to `hintTextView`

2019-04-04 09:50 UTC, itswisdomagain commented on terminal/pages/rootpage.go
> +	gridLayout.AddItem(hintText, 2, 1, 1, 2, 0, 0, false)
Make these changes to this function before the desired output can be gotten. I'll leave you to figure out what these codes do. I also trust you will know where these changes ought to be made.

At the top of the function
```
gridLayout := tview.NewGrid().
		SetRows(3, 1, 0, 1, 3).
		SetColumns(25, 2, 0, 2).
		SetBordersColor(helpers.DecredLightColor)

...

displayPage := func(page tview.Primitive) {
	gridLayout.RemoveItem(activePage)
	activePage = page
	gridLayout.AddItem(activePage, 2, 2, 1, 1, 0, 0, true)
}

...

gridLayout.AddItem(header, 0, 0, 1, 4, 0, 0, false)

...

gridLayout.AddItem(menuColumn, 1, 0, 4	, 1, 0, 0, true)

gridLayout.AddItem(hintText, 4, 2, 1, 1, 0, 0, false)
```

Those changes will fix the issue where the hint text takes half the page height on small windows:
![Screen Shot 2019-04-04 at 9 24 57 AM](https://user-images.githubusercontent.com/18400051/55541950-f32b0000-56bd-11e9-8a6b-649c8d2e3efa.png)

After the change:
![Screen Shot 2019-04-04 at 10 43 52 AM](https://user-images.githubusercontent.com/18400051/55546154-96801300-56c6-11e9-9482-47626eab11b5.png)

2019-04-04 09:50 UTC, itswisdomagain commented on terminal/pages/balance.go
> +	if len(accounts) != 1 {
Please revert this change!

2019-04-04 09:50 UTC, itswisdomagain commented on terminal/pages/history.go
> +	body.SetBorderPadding(1, 0, 2, 0)
Remove padding from all pages. The root gridview now has extra rows and columns at the right places to simulate the desired padding.

2019-04-04 09:50 UTC, itswisdomagain commented on terminal/pages/send.go
> +	hintText.SetText("TIP: Select source account with Arrow Down and Enter. Move around with Tab and Shift+Tab. Return to nav menu with Esc")
Need some consistency with the hint text. Is it **TAB** or Tab? Arrow or **ARROW**? Enter or **ENTER**? **SHIFT+TAB** or Shift+Tab? **ESC** or Esc? Nav Menu or Nav menu or nav menu or **navigation menu** or Navigation menu?

The preferred options are in bold. Use those consistently.

2019-04-04 09:50 UTC, itswisdomagain commented on terminal/pages/send.go
> +	body.AddItem(outputMessageTextView, 0, 1, false)
On small windows, this error may not be visible. Don't use a proportion, use a fixed width of 2.

2019-04-04 09:50 UTC, itswisdomagain commented on terminal/pages/send.go
>  	body.AddItem(form, 14, 0, true)
Since form scrolls, no need to set a fixed height. Use `0, 1` (proportion height) so it takes the remaining space after leaving space for the error message.

2019-04-04 23:42 UTC, itswisdomagain requested changes

2019-04-04 23:42 UTC, itswisdomagain commented on terminal/pages/rootpage.go
> +	header := primitives.NewCenterAlignedTextView(fmt.Sprintf("\n %s %s\n", strings.ToUpper(app.Name), netType))
Don't make the app name uppercased. Should be `GoDCR` with a small `o`

2019-04-04 23:42 UTC, itswisdomagain commented on terminal/pages/balance.go
> +						SetCell(1, 5, tview.NewTableCell(account.Balance.Unconfirmed.String()).SetAlign(tview.AlignCenter)), 0, 1, true)
I'm not comfortable with this change, it doesn't really concern this PR, please undo. Balance page modifications are done in a separate PR

2019-04-04 23:42 UTC, itswisdomagain commented on terminal/pages/balance.go
> +		body.AddItem(textView.SetTextAlign(tview.AlignCenter).SetText(output), 0, 1, false)
Undo this change please

2019-04-04 23:42 UTC, itswisdomagain commented on terminal/pages/balance.go
> +					SetCell(1, 1, tview.NewTableCell(walletcore.SimpleBalance(account.Balance, true)).SetAlign(tview.AlignCenter)), 0, 1, false)
Undo this change

2019-04-04 23:42 UTC, itswisdomagain commented on terminal/pages/history.go
> +	// page title and tip
This comment is no longer necessary

2019-04-04 23:42 UTC, itswisdomagain commented on terminal/pages/balance.go
> +	hintTextView.SetText("TIP: Use TAB to display detailed balance info, ESC to return to Navigation menu")
Since this view is displayed last, it makes sense to set this value at the bottom of the function for all pages. Shouldn't come between code related to the page itself

2019-04-04 23:42 UTC, itswisdomagain commented on terminal/pages/send.go
> +	outputMessageTextView.SetTextColor(tcell.ColorOrangeRed)
Please go through all pages to ensure that all error textviews use this color as well.

2019-04-05 23:26 UTC, itswisdomagain requested changes
Need to fix this issue with the staking page where the hint text view is not visible on small window heights:
![Screen Shot 2019-04-06 at 12 13 27 AM](https://user-images.githubusercontent.com/18400051/55661213-63429e80-5802-11e9-97c8-908953169f65.png)

The comments below should help.

2019-04-05 23:26 UTC, itswisdomagain commented on terminal/pages/rootpage.go
>  		gridLayout.RemoveItem(activePage)
`clearFocus` should also clear the text from the hint text view

2019-04-05 23:26 UTC, itswisdomagain commented on terminal/pages/staking.go
>  		body.AddItem(stakeInfo, 6, 0, true)
This is too much height for a table that has just 2 rows. Reduce this value to the barest minimum necessary to show the 2 rows and also remove the table borders so the table is smaller in size.

2019-04-05 23:26 UTC, itswisdomagain commented on terminal/pages/staking.go
>  		body.AddItem(statusTextView, 3, 0, true)
This status textview is empty until the ticket purchase is completed successfully. No need to waste this space displaying "invisible" content. Use the `displayError` method to display the result of the purchase rather than using this textview.

When displaying the result of a successful purchase, you'd need to change the text view color to green/success. When displaying error, change it back to the error color. Here's an idea, I've renamed `displayError` to `displayMessage`:
```
displayMessage := func(message string, error bool) {
	body.RemoveItem(errorTextView)
	errorTextView.SetText(message)
	if error {
		errorTextView.SetTextColor(tcell.ColorOrangeRed)
	} else {
		errorTextView.SetTextColor(tcell.ColorGreen)
	}
	body.AddItem(errorTextView, 2, 0, false)
}
```

Also rename `errorTextView` to `messageTextView`; and do not use a proportion of 1 to show messages, it'll take up too much space than necessary. Use a fixed height of 2.

2019-04-05 23:26 UTC, itswisdomagain commented on terminal/pages/staking.go
>  		body.AddItem(purchaseTicket, 12, 0, true)
This form should use a proportion of 1, so it scales to take up the available height instead of pushing everything else down. Even if the available height is not enough for it to display all it's fields, user can scroll with tab.

2019-04-06 15:14 UTC, Sirmorrison commented on terminal/pages/staking.go
>  		body.AddItem(stakeInfo, 6, 0, true)
i left the height so for the table because it includes padding between the table and ticket form

2019-04-06 15:45 UTC, itswisdomagain commented on terminal/pages/staking.go
>  		body.AddItem(stakeInfo, 6, 0, true)
It can still be reduced. Don’t forget terminal windows are not usually very large, need to make good use of available space

2019-04-06 20:37 UTC, raedah commented
History columns should have two spaces between columns. Currently seeing only one.

Rather then having an input field for spending passphrase, is there a popup dialog that can be used?

2019-04-06 20:52 UTC, ademuanthony requested changes
rebase and fixe the few comments below

2019-04-06 20:52 UTC, ademuanthony commented on terminal/pages/send.go
> +	errorTextView.SetTextColor(tcell.ColorOrangeRed)
can we define the color in the `helps/colors` file

2019-04-06 20:52 UTC, ademuanthony commented on terminal/pages/send.go
> +	displayMessage := func(message string) {
`displayError` or `displayErrorMessage` i think

2019-04-06 20:52 UTC, ademuanthony commented on terminal/pages/staking.go
> +	messageTextView.SetTextColor(tcell.ColorOrangeRed)
define color in the colors file

2019-04-06 22:19 UTC, Sirmorrison commented
> 
> 
> History columns should have two spaces between columns. Currently seeing only one.
> 
> Rather then having an input field for spending passphrase, is there a popup dialog that can be used?



Noted the instructions and i will get to work on them in a separate PR or even separate PRs

2019-04-06 22:35 UTC, ademuanthony approved these changes

2019-04-06 22:53 UTC, itswisdomagain requested changes
No longer use all caps for page titles and section headers.

I still see instances of inconsistent "nav menu", "navigation menu" and "Navigation menu" on the hint text. Please all pages should use "navigation menu" - in small caps

On the staking page, I still can't see the hint text on small screen heights. Is the purchase tickets form set to use available height or fixed height?
![Screen Shot 2019-04-06 at 11 49 24 PM](https://user-images.githubusercontent.com/18400051/55676161-b8e07f00-58c6-11e9-881d-6316b71be6c9.png)

Also the stake info table should not have grid lines, that should release additional space on the window.

2019-04-06 22:53 UTC, itswisdomagain commented on terminal/helpers/colors.go
>  	DecredColor      = tcell.NewRGBColor(41, 112, 255)
Let's rename the colors to tally with what we have on https://decred.org/brand/
- `DecredColor` to `DecredBlueColor`
- `DecredLightColor` to `DecredLightBlueColor`
- `DangerColor` and `ErrorColor` should be the same thing -`DecredOrangeColor` (#ED6D47, rgb(237,109,71))
- `SuccessColor` should be `DecredGreenColor` (#41BF53, rgb(65,191,83))
- Replace all usages of `SeedLabelColor` to`DecredLightBlueColor` and delete `SeedLabelColor`

2019-04-06 22:53 UTC, itswisdomagain commented on terminal/pages/history.go
>  	"math"
Re-arrange imports please

2019-04-06 22:53 UTC, itswisdomagain commented on terminal/pages/history.go
> +	body.AddItem(nil, 1, 0, false) // add some "padding" at the bottom
This shouldn't be necessary, the rootpage layout grid should already have this sorted out.

2019-04-06 22:53 UTC, itswisdomagain commented on terminal/pages/rootpage.go
> +		hintTextView.Clear()
Did you test and confirm that this work? I believe the code you're looking for is `hintTextView.SetText("")`

2019-04-06 22:53 UTC, itswisdomagain commented on terminal/pages/send.go
> +
go fmt ./...

2019-04-07 01:06 UTC, itswisdomagain requested changes

2019-04-07 01:06 UTC, itswisdomagain commented on terminal/pages/staking.go
> +	return form, statusOutput, nil
This is just terrible, at this point `statusOutput` is an empty string, it is only assigned when the button is clicked. Please declare and assign `statusOutput` at the end of the button click function, where it is needed and display the output. Also need to rename that variable. 
```
successMessage := fmt.Sprintf("You have purchased %d ticket(s)\n%s", len(ticketHashes), strings.Join(ticketHashes, "\n"))
displayMessage(successMessage, false)
```

This means
- You should not declare `statusOutput` or any such variable OUTSIDE the button click function
- This `purchaseTicketForm` function should only return `(*primitives.Form, error)`, the other string previously returned has no use

2019-04-07 01:06 UTC, itswisdomagain commented on terminal/pages/staking.go
> +	var statusOutput string
Please delete this

2019-04-07 01:06 UTC, itswisdomagain commented on terminal/pages/staking.go
> +func purchaseTicketForm(wallet walletcore.Wallet, displayMessage func(message string, error bool)) (*primitives.Form, string, error) {
Return `(*primitives.Form, error)`

2019-04-07 01:06 UTC, itswisdomagain commented on terminal/pages/staking.go
> +		displayMessage(statusOutput, false)
If there is no error, what are you displaying? Please delete this.

2019-04-07 01:06 UTC, itswisdomagain commented on terminal/pages/staking.go
> +	body.AddItem(tview.NewTextView().SetText("Purchase Ticket").SetTextColor(helpers.DecredLightBlueColor), 2, 0, false)
use height 1

2019-04-07 01:06 UTC, itswisdomagain commented on terminal/pages/staking.go
> +		body.AddItem(stakeInfo, 4, 0, true)
use height 3

2019-04-07 01:06 UTC, itswisdomagain commented on terminal/pages/staking.go
> +	body.AddItem(tview.NewTextView().SetText("Stake Info").SetTextColor(helpers.DecredLightBlueColor), 2, 0, false)
use height 1

2019-04-07 01:06 UTC, itswisdomagain commented on terminal/pages/history.go
>  	titleTextView := primitives.NewCenterAlignedTextView("History")
Left align

2019-04-07 01:06 UTC, itswisdomagain commented on terminal/pages/history.go
> +		hintTextView.SetText("(TIP: Use ARROW UP/DOWN to select txn, ENTER to view details, ESC to return to nav menu)")
`navigation menu`, small caps all through, please

2019-04-07 01:06 UTC, itswisdomagain commented on terminal/pages/history.go
> +		hintTextView.SetText("(TIP: Use ARROW UP/DOWN to scroll, BACKSPACE to view History page, ESC to return to nav menu)")
`navigation menu`, small caps all through, please

2019-04-07 01:06 UTC, itswisdomagain commented on terminal/pages/history.go
> +	hintTextView.SetText("TIP: Use ARROW UP/DOWN to select txn, ENTER to view details, ESC to return to Navigation menu")
`navigation menu`, small caps all through, please

2019-04-07 01:06 UTC, itswisdomagain commented on terminal/pages/overview.go
> +func overviewPage(wallet walletcore.Wallet, hintTextView *primitives.TextView, setFocus func(p tview.Primitive) *tview.Application, clearFocus func()) tview.Primitive {
The "BALANCE" and "RECENT ACTIVITY" section titles in this file should be "Balance" and "Recent Activity"

2019-04-07 01:06 UTC, itswisdomagain commented on terminal/pages/overview.go
>  	overviewPage.SetBorderPadding(1, 0, 1, 0)
No page should have padding

2019-04-07 01:06 UTC, itswisdomagain commented on terminal/pages/send.go
> +	body.AddItem(primitives.NewLeftAlignedTextView("SEND"), 2, 0, false)
`Send`

2019-04-07 01:06 UTC, itswisdomagain commented on terminal/pages/send.go
> +	hintTextView.SetText("TIP: Select source account with ARROW DOWN and ENTER. Move around with TAB and SHIFT+TAB. ESC to return to Navigation menu")
`navigation menu`, small letters all through, please

2019-04-07 01:06 UTC, itswisdomagain commented on terminal/pages/staking.go
> +	hintTextView.SetText("TIP: Move around with TAB and SHIFT+TAB. ESC to return to Navigation menu")
`navigation menu`, small letters all through, please

2019-04-07 02:24 UTC, itswisdomagain requested changes

2019-04-07 02:24 UTC, itswisdomagain commented on terminal/pages/receive.go
> +	body.AddItem(primitives.NewLeftAlignedTextView("GENERATE RECEIVE ADDRESS"), 2, 1, false)
Thought we agreed no all-caps for page titles?

2019-04-07 02:24 UTC, itswisdomagain commented on terminal/pages/receive.go
> +	hintTextView.SetText("TIP: Navigate with TAB and SHIFT+TAB, hit ENTER to generate Address. ESC to return to Navigation menu")
Thought we agreed `navigation menu`, small letters all through?

2019-04-07 02:28 UTC, itswisdomagain approved these changes

2019-04-07 02:28 UTC, merged