improved terminal receive page and overview page
raedahgroup/godcr-old pull request #263
Opened 2019-04-07 22:16 UTC by Sirmorrison

fix #262 

![image](https://user-images.githubusercontent.com/27733432/55690538-d9720d00-598a-11e9-8415-7290d6cc85d6.png)

![image](https://user-images.githubusercontent.com/27733432/55690547-ed1d7380-598a-11e9-88f5-4c509f3c71bd.png)

2019-04-08 19:47 UTC, raedah commented
No need to have UTC on every line. Put it in the header  Date UTC

Trailing zeros can be truncated on the amounts. I believe wisdom already did this in the transaction details view.

2019-04-08 19:52 UTC, raedah commented
With detecting the terminal width, we should be able to center the QR code.

2019-04-09 17:53 UTC, itswisdomagain commented
> With detecting the terminal width, we should be able to center the QR code.

If we do this, we might get a weird UI on full screen mode because the account selection widget will be on the far left of the page while the rest of the page content sits in the horizontal middle.

Maybe we should just left align everything?

2019-04-12 08:26 UTC, itswisdomagain commented
I think this page needs a # column, would be especially helpful for wallets with high number of txs in history. Should confirm from @raedah though.
> ![image](https://user-images.githubusercontent.com/27733432/55873249-0428b500-5b87-11e9-91b0-ddb1711b6a5b.png)

Single account shouldn't have this tip. Should be something like `Hit ENTER to copy generated address, ESC to return to navigation menu`.
> ![image](https://user-images.githubusercontent.com/27733432/55842422-6e137100-5b2b-11e9-845d-7f923cb4af68.png)

Multiple account hint should be `Select account with ARROW DOWN and hit ENTER to generate address. Use ESC to return to navigation menu`.
> ![image](https://user-images.githubusercontent.com/27733432/55873180-dcd1e800-5b86-11e9-9131-e85eea58d3da.png)

The receive page should have a "generate new address" button beneath the address qr code and text to skip the previously generated unused address and generate a new one. Use `wallet.GenerateNewAddress()` instead of `wallet.ReceiveAddress()` for that purpose. Should discuss this with @raedah.

2019-04-12 08:52 UTC, itswisdomagain requested changes

2019-04-12 08:52 UTC, itswisdomagain commented on app/walletcore/helper.go
> +	return fmt.Sprintf("%.3f DCR", balance)
Is this a necessary change for this PR?

2019-04-12 08:52 UTC, itswisdomagain commented on app/walletcore/helper.go
> +	return totalBalance.String()
go fmt please

2019-04-12 08:52 UTC, itswisdomagain commented on terminal/pages/history.go
> +var displayedTxHashes []string
- Move this declaration to the top of the file, before the first function in this file
- In the `historyPage` function, clear this slice before transactions are loaded using `displayedTxHashes = []string{}`

2019-04-12 08:52 UTC, itswisdomagain commented on terminal/pages/history.go
> +	currentDate := time.Now().In(loc).Add(1 * time.Hour)
Why are we adding 1 hour? A comment may be necessary here

2019-04-12 08:52 UTC, itswisdomagain commented on terminal/pages/history.go
> +		transactionDate := time.Unix(tx.Timestamp, 0).In(loc).Add(1 * time.Hour)
Why are we adding 1 hour to current time and this time, only to subtract them later? it's like doing (a + 1) - (b + 1) which is essentially equivalent to doing a - b.

2019-04-12 08:52 UTC, itswisdomagain commented on terminal/pages/history.go
> +	timeDifference, _ := time.ParseDuration("24h")
- `_24hours` instead of `timeDifference`, your code in subsequent lines will read better:
`if transactionDuration > _24hours` reads better than `if transactionDuration > timeDifference`

- `transactionDuration` is also a bad name, should be something like `transactionAge`, to show that the variable represents how old a transaction is, which is the time difference between now and when the transaction was created.

- can declare this variable at the top of this file as well: `var _24hours, _= time.ParseDuration("24h")`

2019-04-12 08:52 UTC, itswisdomagain commented on terminal/pages/history.go
> +		transactionDuration := currentDate.Sub(transactionDate)
`transactionAge` instead of `transactionDuration`

2019-04-12 08:52 UTC, itswisdomagain commented on terminal/pages/history.go
> +	   	dateOutput := strings.Split(tx.FormattedTime, " ")
`txDateTime` instead of `dateOutput`

2019-04-12 08:52 UTC, itswisdomagain commented on terminal/pages/history.go
> +	    	historyTable.SetCell(row, 0, tview.NewTableCell(fmt.Sprintln(dateOutput[0])).SetAlign(tview.AlignCenter))
`dateOutput[0]` can be used directly, no need to wrap in `fmt.Sprintln()`

2019-04-12 08:52 UTC, itswisdomagain commented on terminal/pages/history.go
> +	var confirmations int32
There really is no need to declare this variable, you should be able to use `walletcore.DefaultRequiredConfirmations` directly

2019-04-12 08:52 UTC, itswisdomagain commented on terminal/pages/history.go
> +		if txns.Confirmations > confirmations{
- use `walletcore.DefaultRequiredConfirmations` instead of `confirmations`
- should be greater than or equal to

2019-04-12 08:52 UTC, itswisdomagain commented on terminal/pages/overview.go
> +	displayError := func(errorMessage string) {
If both balance and recent activity need to display an error, the error displayed first will be removed in order to add the second error. This is bad. What was wrong with the previous approach?

2019-04-12 08:52 UTC, itswisdomagain commented on terminal/pages/overview.go
>  	tabAndEscInputCapture := func(viewIndex int) func(event *tcell.EventKey) *tcell.EventKey {
This input capture function is longer necessary. Focus should be placed on the recent activity table, and that table alone should listen for esc key presses. Tabs should be ignored

2019-04-12 08:52 UTC, itswisdomagain commented on terminal/pages/overview.go
> +	balanceViews, balanceViewBoxes := renderBalanceSection(overviewPage, wallet, displayError)
These views and boxes were only needed to make moving between fields with tab possible. That's no longer necessary so `renderBalanceSection` and `renderRecentActivity` no longer need to return anything.

Since `renderBalanceSection` has been greatly simplified, you could merge both functions together and put the code here directly instead.

2019-04-12 08:52 UTC, itswisdomagain commented on terminal/pages/overview.go
> +	confirmations = walletcore.DefaultRequiredConfirmations
A number of the review comments from the overview page applies here as well

2019-04-12 08:52 UTC, itswisdomagain commented on terminal/pages/receive.go
> +		qrCode := fmt.Sprintf(qr.ToSmallString(false))
`fmt.Sprintf` is not necessary

2019-04-12 08:52 UTC, itswisdomagain commented on terminal/pages/receive.go
> +		SetLabelColor(helpers.DecredLightBlueColor)
The screenshot doesn't show that this label color reflects. If it doesn't reflect, delete this line.

2019-04-13 10:12 UTC, Sirmorrison commented on terminal/pages/receive.go
> +		SetLabelColor(helpers.DecredLightBlueColor)
it does form colors are default yellow

2019-04-14 06:00 UTC, itswisdomagain approved these changes

2019-04-15 00:55 UTC, ademuanthony submitted a review, later dismissed
few observations

2019-04-15 00:55 UTC, ademuanthony commented on terminal/pages/helpers.go
> +func formatAmountDisplay(amount int64, maxDecimalPlaces int) string {
the display of amount has been advised to be in the format, x.xxxxxxxx DCR on other interfaces. `walletcore.NormalizeBalance` already returns this

2019-04-15 00:55 UTC, ademuanthony commented on terminal/pages/history.go
> +	displayError("Fetching data...")
`Fetching data...` is not an error message

2019-04-15 00:55 UTC, ademuanthony commented on terminal/pages/history.go
> +		return formatAmountDisplay(amount, maxDecimalPlacesForTxAmounts)
we should use `walletcore.NormalizeBalance` to maintain consistency across all the interfaces

2019-04-15 00:55 UTC, ademuanthony commented on terminal/pages/history.go
> +			historyTable.SetCell(row, 1, tview.NewTableCell(tx.Direction.String()).SetAlign(tview.AlignCenter))
I think will be better to have this left aligned

2019-04-15 00:55 UTC, ademuanthony commented on terminal/pages/overview.go
> +		return formatAmountDisplay(amount, maxDecimalPlacesForTxAmounts)
we can use `walletcore.NormalizeBalance` for consistency

2019-04-15 00:55 UTC, ademuanthony commented on terminal/pages/overview.go
>  		row := historyTable.GetRowCount()
`rowCount` i think

2019-04-15 00:55 UTC, ademuanthony commented on terminal/pages/overview.go
> +		historyTable.SetCell(row, 1, tview.NewTableCell(tx.Direction.String()).SetAlign(tview.AlignCenter))
I think this can be Left Aligned

2019-04-15 00:55 UTC, ademuanthony commented on terminal/pages/receive.go
>  	generatedAddress, err := wallet.ReceiveAddress(accountNumber)
You should call `wallet.GenerateNewAddress` instead

2019-04-15 12:50 UTC, itswisdomagain commented on terminal/pages/helpers.go
> +func formatAmountDisplay(amount int64, maxDecimalPlaces int) string {
There is a different requirement from @raedah for terminal and cli.

2019-04-15 12:50 UTC, itswisdomagain commented on terminal/pages/history.go
> +		return formatAmountDisplay(amount, maxDecimalPlacesForTxAmounts)
There is a different requirement from @raedah for terminal and cli.

2019-04-15 12:51 UTC, itswisdomagain commented on terminal/pages/history.go
> +			historyTable.SetCell(row, 1, tview.NewTableCell(tx.Direction.String()).SetAlign(tview.AlignCenter))
The UI has already been approved by @raedah, would not want to make additional changes.

2019-04-15 12:51 UTC, itswisdomagain commented on terminal/pages/overview.go
> +		return formatAmountDisplay(amount, maxDecimalPlacesForTxAmounts)
There is a different requirement from @raedah for terminal and cli.

2019-04-15 12:53 UTC, itswisdomagain commented on terminal/pages/receive.go
>  	generatedAddress, err := wallet.ReceiveAddress(accountNumber)
`GenerateNewAddress` is only when user wants to ignore previously generated but unused addresses to get a new one instead, it's not the default behaviour. The default behaviour is to repeat previously generated address until it is used before a new one is generated. That's what `ReceiveAddress` does.

2019-04-15 13:02 UTC, merged