Receive page design alignment
raedahgroup/godcr-old pull request #266
Opened 2019-04-09 07:21 UTC by ademuanthony

This is a redesign of the' receive page' that normalizes the font and elements alignment

![receive-page-amend](https://user-images.githubusercontent.com/11990092/55780618-46c39200-5aa0-11e9-99ef-b22d0804eb78.PNG)

2019-04-10 00:05 UTC, ademuanthony commented
The 'receive page' has been updated to align the QR code and the address horizontally and to hide the 'generate new address' button in a dropdown

![receive-page-amed p2 - plain](https://user-images.githubusercontent.com/11990092/55842724-b1baaa80-5b2c-11e9-868a-91cd93229623.PNG)

![receive-page-amed p2 -dropped](https://user-images.githubusercontent.com/11990092/55842740-be3f0300-5b2c-11e9-9812-6c3de8b9b65f.PNG)

2019-04-10 01:17 UTC, ademuanthony commented
![receive-page-qr-centered](https://user-images.githubusercontent.com/11990092/55844758-b7b58900-5b36-11e9-91d5-a18c44129bc7.PNG)

2019-04-12 08:14 UTC, itswisdomagain requested changes

2019-04-12 08:14 UTC, itswisdomagain commented on web/views/receive.html
> +                                   {{/*<input class="form-control singleAccountTextView" disabled value="{{ $account.Name }}">*/}}
This comment can go

2019-04-12 08:14 UTC, itswisdomagain commented on web/views/receive.html
> +                               <div class="result-card">
Can use the utility class `text-center` instead. The font-size need not be changed really...

2019-04-12 08:14 UTC, itswisdomagain commented on web/static/app/src/css/style.scss
> +.result-card {
Think we can do without this. The class name isn't very helpful either, doesn't give an immediate idea of where it could be used...

2019-04-12 08:14 UTC, itswisdomagain commented on web/static/app/src/css/style.scss
> +  padding: 10px;
This space is meant to separate this element from the elements before and after it, should be `0 10px` for horizontal padding only.

2019-04-12 08:14 UTC, itswisdomagain commented on web/static/app/src/css/style.scss
> +  margin-left: -60px;
- I'm guessing this is to take care of the padding embedded in the qr image, a comment here would help.
- `margin-left: -4%;` seem to produce a better result across varying screen widths, the current margin looks like this on mobile screen width:
![Screenshot 2019-04-12 at 9 08 47 AM](https://user-images.githubusercontent.com/18400051/56022022-bafd7000-5d02-11e9-894b-1d08169454bc.png)

2019-04-12 08:14 UTC, itswisdomagain commented on web/views/receive.html
> +                                   <div id="result-text" style="margin-top: -25px;">
Is this id used anywhere? styles or js code?

2019-04-12 08:14 UTC, itswisdomagain commented on web/static/app/src/css/style.scss
> +  font-size: 15px;
I see a lot of elements are individually set to use font size as 15px, perhaps this can be done in body instead? Or some other parent element...
the account text and the lead text are other instances I've noticed

2019-04-12 08:14 UTC, itswisdomagain commented on web/static/app/src/css/style.scss
> +.singleAccountTextView {
no longer necessary

2019-04-12 08:14 UTC, itswisdomagain commented on web/views/receive.html
> +                                   <div data-action="click->receive#copyAddressToClipboard" style="margin-top: -20px;"
The margin here and in the next 2 lines, are they really necessary? I took them out and the look wasn't adversely affected imo.
If they are necessary though, comments should be added before each of those lines explaining that the negative margins are applied to reduce/eliminate some extra white space around the qr code image.

2019-04-13 03:05 UTC, itswisdomagain requested changes

2019-04-13 03:05 UTC, itswisdomagain commented on web/views/receive.html
> +                                   {{/* the nagative margin this is to take care of the padding embedded in the qr image*/}}
html comments should be like this
`<!-- comment here -->`

2019-04-13 20:23 UTC, itswisdomagain commented
Just noticed a display issue when there are multiple accounts in wallet. The account drop down appears cut off. Something `z-index` can prolly fix.

![Screen Shot 2019-04-13 at 9 21 31 PM](https://user-images.githubusercontent.com/18400051/56084891-41fd3600-5e32-11e9-8d08-a58c630b7bd4.png)

Also, @raedah once said these dropdowns are too wide and can/should be reduced to simply fit the content adequately.

2019-04-13 20:28 UTC, itswisdomagain commented
Another issue with multiple accounts, this time when you select a different account to generate new address. Ideally, as soon as a different account is selected, the currently displayed address and qr code should be cleared so a user does not mistake it for the newly generated address.

In the following screenshot, the "whew" account doesn't really exist (has a wrong account number) and there was an error trying to generate the address. The error could not be displayed.

![Screen Shot 2019-04-13 at 9 24 28 PM](https://user-images.githubusercontent.com/18400051/56084949-1a5a9d80-5e33-11e9-92b2-b2b7ed1827be.png)

2019-04-14 12:28 UTC, ademuanthony commented
updated

![receive-page-14-4-error-page](https://user-images.githubusercontent.com/11990092/56092821-17a28b80-5eb9-11e9-8205-0f298203281f.PNG)

![receive-page-14-4-overlap-fixed](https://user-images.githubusercontent.com/11990092/56092823-1ec99980-5eb9-11e9-890b-cc6dc5bc5397.PNG)

2019-04-15 17:16 UTC, itswisdomagain requested changes

2019-04-15 17:16 UTC, itswisdomagain commented on web/routes/handlers.go
> +	accounts = append(accounts, accounts...)
I believe this is test code, please delete.

2019-04-15 17:16 UTC, itswisdomagain commented on web/static/app/src/controllers/receive_controller.js
> +      'errorMessage', 'successMessage',
Do we need `successMessage` on this page? We can show success messages using toastr, but error messages need to stay visible on the screen, so we should retain the `errorMessage` element

2019-04-15 17:16 UTC, itswisdomagain commented on web/static/app/src/controllers/receive_controller.js
> +      'account', 'addressContainer', 'address', 'image', 'copyButtonText', 'generateNewAddressButton'
Can split this into 3 lines to semantically differentiate the sections
- account selector widget
- generated address container with qr code, address text and copy button
- generate new address button

The functions in this file should be ordered similarly:
- `getRecieveAddress` for when the account selection changes (see related comment below)
- `copyAddressToClipboard `
- `generateNewAddress`

2019-04-15 17:16 UTC, itswisdomagain commented on web/static/app/src/controllers/receive_controller.js
>      this.generateNewAddressButtonTarget.textContent = 'Generating...'
The button's text was all small letters, should probably stick to that.

2019-04-15 17:16 UTC, itswisdomagain commented on web/static/app/src/controllers/receive_controller.js
> +        _this.generateNewAddressButtonTarget.textContent = 'Generate New Address'
This isn't the exact original button text, it was all small letters.

2019-04-15 17:16 UTC, itswisdomagain commented on web/static/app/src/controllers/receive_controller.js
>      axios.get('/generate-address/' + this.accountTarget.value)
When the account selection changes, we don't need to generate a new address, we should return previously generated address that is unused. The `wallet.ReceiveAddress` method ensures that no new address is generated unless the previously generated address has been used. That method should be used for this scenario.

When user clicks generate new address however, the `wallet.GenerateNewAddress` method should be used to ignore previously unused addresses and return a new one.

We can make this endpoint take a `new` query parameter that can be used the route handler to determine which of the above methods to use.

2019-04-16 03:29 UTC, itswisdomagain approved these changes

2019-04-16 03:30 UTC, merged