implemented http standard menu items
raedahgroup/godcr-old pull request #287
Opened 2019-04-14 09:59 UTC by Sirmorrison

fixes #283

![image](https://user-images.githubusercontent.com/27733432/56091230-1c107980-5ea4-11e9-83ff-83765a83d916.png)

![image](https://user-images.githubusercontent.com/27733432/56091235-2b8fc280-5ea4-11e9-97fe-3a0a967358a8.png)

2019-04-14 12:45 UTC, ademuanthony submitted a review, later dismissed

2019-04-14 12:45 UTC, ademuanthony commented on web/routes/walletloader.go
> +		// currentSyncStatus := routes.blockchain.status()
Why did you remove wallet opening logic

2019-04-14 23:37 UTC, itswisdomagain requested changes

2019-04-14 23:37 UTC, itswisdomagain commented on web/views/accounts.html
> +        .btn-form-group {
I can't see the elements being styled here. Where are the `.btn-form-group` and `.result-card` elements?

2019-04-14 23:37 UTC, itswisdomagain commented on web/routes/routes.go
> +	router.Get("/accounts", routes.accountsPage)
The nav menu order has accounts before security. Let's maintain that here.

2019-04-14 23:37 UTC, itswisdomagain commented on web/routes/handlers.go
> +func (routes *Routes) accountsPage(res http.ResponseWriter, req *http.Request) {
The nav menu order has accounts before security. Let's maintain that here. This `accountsPage` function should come before `securityPage`

2019-04-14 23:37 UTC, itswisdomagain commented on web/views/layout.html
> +                    <li class="nav-item">
We have another nav item for settings just below, this isn't needed.

2019-04-15 17:02 UTC, itswisdomagain approved these changes

2019-04-15 17:04 UTC, merged