Restructure app to allow for multiple entry points
raedahgroup/godcr-old pull request #29
Opened 2018-10-29 13:56 UTC by codemaestro64

This restructures the application creating an abstraction layer such that commands can be called from cli mode and web mode providing the same interface for commands and response

2018-10-29 15:35 UTC, itswisdomagain requested changes
Hi @codemaestro64, please give thoughts to this. To confirm, the major change this PR brings to the table is the caller functionality that allows different command handlers "behave" differently depending on the caller. Am I correct in my deduction?

2018-10-29 15:35 UTC, itswisdomagain commented on main.go
> +	params["caller"] = "cli"
Why is `params` a map? Why not just a simple string that informs the source of the call (aka `caller`)? Do you anticipate other data being passed into `params`?

2018-10-29 15:35 UTC, itswisdomagain commented on main.go
> +			res, err := client.RunCommand("listcommands", nil, params)
Does the `listcommands` handler need to know the "caller"? Currently, the handler for this command returns a Response object with the array of available commands; and this response can be processed by cli/http modules to display proper feedback to the user. Don't see a need to pass params to this handler.

Compare the implementation of the `listcommands` handler in #28

2018-10-29 15:35 UTC, itswisdomagain commented on server/handlers.go
> +	res, err := s.walletClient.RunCommand("accounts", nil, nil)
Currently, all web server calls to `walletClient.RunCommand` passes nil as params. And when this is done, `"caller"` defaults to "cli". If the command handlers always end up using `caller = "cli"`, then `caller` and the additional `params` parameter are not required.

Ideally, if we can find a way to make the command handlers work without knowing the caller, I think it'd make it easier for us to introduce other "callers" going forward without having to modify the implementation of each handler to account for the newly added caller.

Because I suspect the key reason for passing `params` to each handler is to enable the handler know the source of the call and perform its operations accordingly depending on "who" the caller is.

2018-10-29 15:35 UTC, itswisdomagain commented on server/handlers.go
> +	res, err := s.walletClient.RunCommand("balance", opts, nil)
The `opts` array passed here is ignored in the implementation for the balance command handler. See line 191 of `walletrpcclient/walletrpcclient.go`

2018-10-29 15:35 UTC, itswisdomagain commented on server/handlers.go
> -func (s *Server) version(w http.ResponseWriter, req *http.Request) {
Why are we taking this out? Won't hurt to have a page in the web app showing users the current version of dcrwallet?

2018-10-29 15:35 UTC, itswisdomagain commented on walletrpcclient/walletrpcclient.go
> +func (c *Client) RunCommand(command string, args []string, params map[string]interface{}) (*Response, error) {
I want to propose we use consistent variable names for `args`/`opts`. Can we stick to `commandArgs` everywhere so its immediately obvious that this variable holds additional arguments for the command about to be proceed?

2018-10-29 15:35 UTC, itswisdomagain commented on walletrpcclient/cmd.go
> +func (c *Client) cmdListCommands(ctx context.Context) (*Response, error) {
`ctx` is never used. No need to create and pass a context that's never used

2018-10-29 15:35 UTC, itswisdomagain commented on walletrpcclient/walletrpcclient.go
> +func (c *Client) listCommands(args []string, params map[string]interface{}) (*Response, error) {
Since this requires no params to run, can we take off the arguments in the function signature? Compare the implementation of the listcommands handler in #28

2018-10-29 15:35 UTC, itswisdomagain commented on walletrpcclient/walletrpcclient.go
> +			return nil, errors.New("command 'receive' requires at least 1 param. 0 found \nUsage:\n  receive \"accountnumber\"")
I'm thinking of an idea where this function behaves like the send command, displaying a list of accounts and prompting for a selection if no account number is passed. But should **definitely belong in a different PR**, just thought to mention

2018-10-29 15:35 UTC, itswisdomagain commented on walletrpcclient/walletrpcclient.go
> -func (c *Client) walletVersion(ctx context.Context, opts []string) (*Response, error) {
Please let's keep this. Unless there's an advantage to taking it away...

2018-10-30 09:12 UTC, codemaestro64 commented on main.go
> +	params["caller"] = "cli"
depending on the caller, other data can be passed to the called function through the map

2018-10-30 09:13 UTC, codemaestro64 commented on walletrpcclient/walletrpcclient.go
> -func (c *Client) walletVersion(ctx context.Context, opts []string) (*Response, error) {
@raedah  wants it taken off

2018-10-30 09:15 UTC, codemaestro64 commented on server/handlers.go
> +	res, err := s.walletClient.RunCommand("accounts", nil, nil)
all code in the server module are being refactored.

2018-10-30 09:18 UTC, codemaestro64 commented on main.go
> +			res, err := client.RunCommand("listcommands", nil, params)
yes. at some point in development. The listcommands shouldn't function in web ad desktop mode

2018-10-30 09:20 UTC, codemaestro64 commented on walletrpcclient/walletrpcclient.go
> +func (c *Client) listCommands(args []string, params map[string]interface{}) (*Response, error) {
all of those functions have that signature. can't take of the arguments

2018-10-30 09:22 UTC, yaowork commented on server/handlers.go
> +	res, err := s.walletClient.RunCommand("balance", opts, nil)
server module is a WIP

2018-10-30 09:46 UTC, itswisdomagain commented on walletrpcclient/walletrpcclient.go
> -func (c *Client) walletVersion(ctx context.Context, opts []string) (*Response, error) {
Oh. Okay then

2018-10-30 09:53 UTC, codemaestro64 commented on server/handlers.go
> -func (s *Server) version(w http.ResponseWriter, req *http.Request) {
@raedah 's instructions

2018-10-30 12:58 UTC, itswisdomagain commented on walletrpcclient/walletrpcclient.go
> +func (c *Client) listCommands(commandArgs []string, params map[string]interface{}) (*Response, error) {
There's another function like this in this package: `ListSupportedCommands`, and seeing as the arguments here are not used, I recommend taking this off. I guess the reason we have this, is because this function is registered as a command.

I don't think `-l` is a command like `send` is, usually `-abc` are flags/options. Same reason we won't list `-h` as a command. So this function can go, and the code at the bottom of this file that registers this function as a command.

If you run `dcrcli -h`, `-l` is listed there as an option/flag

2018-10-30 12:58 UTC, itswisdomagain commented on walletrpcclient/walletrpcclient.go
> +		if acc, ok := params["accountNumber"]; ok {
Remember my comment earlier:
>Ideally, if we can find a way to make the command handlers work without knowing the caller, I think it'd make it easier for us to introduce other "callers" going forward without having to modify the implementation of each handler to account for the newly added caller

The cli sends command arguments in an array. For this handler, line 129 above reads the account number from the `commandArgs` array at position 0. Can't we maintain that for the web server and any other module that calls the handlers?

The web server already follows this pattern, line 48-49 of `server/handlers.go` uses an array to send arguments to the `balance` command.

Following this line of thought, I'm thinking we create 3 different packages: `core`, `cli` and `server`. The `core` would be like the current `walletrpcclient` package which will primarily be concerned about interacting with the dcrwallet rpc server. The `core` package should have a fixed way it receives arguments for each command and a fixed response it returns.

Both the `cli` and `server` package interact with the `core` package, passing in the required fields/values and processing the response received.

The `cli` package gets user input from the terminal, passes the input received to the `core` package in the format the `core` package understands, receives response from the `core` package and writes messages/prompts/outputs back to the terminal.

The `server` package gets user input from the web app interface (mostly through forms), passes the input received to the `core` package in the format the `core` package understands, receives response from the `core` package and displays outputs to the user in the web page.

This way, we make the `core` package "caller-agnostic" and we can add more "callers" like the desktop interface on the fly.

2018-10-31 11:32 UTC, itswisdomagain requested changes
Really, really nice work. Just a little more refactoring to firmly establish separation of concerns.

2018-10-31 11:32 UTC, itswisdomagain commented on main.go
> +	cli := cli.New()
variable name `cli` clashes with the name of the imported `cli` package

2018-10-31 11:32 UTC, itswisdomagain commented on main.go
> +func cliExecuteCommand(cli *cli.CLI, command string, config *config, args []string) {
this function is completely related to the cli package, that's where it belongs. Access this function by calling cli.ExecuteCommand rather than passing the cli instance into this function

2018-10-31 11:32 UTC, itswisdomagain commented on main.go
> +func noCommandReceived(client *cli.CLI) {
This function too, should go into the cli package,. Access this function by calling cli.NoCommandReceived rather than passing the cli instance into this function

2018-10-31 11:32 UTC, itswisdomagain commented on main.go
>  	if command == "-l" {
while it's okay to check if no command was passed in (aka `len(args) == 0`, I don't think processing **any** cli command should be done in main.go, the cli command (`args[0]`) and any additional command args (`args[1:]`) should be passed to the `cli` package via `cli.ExecuteCommand`

2018-10-31 11:32 UTC, itswisdomagain commented on main.go
> +	if !cli.IsCommandSupported(command) {
same here, checking whether a command is valid or not belongs in the cli package. Anything that has to do with **processing** a cli command should please go in the cli package

2018-10-31 11:32 UTC, itswisdomagain commented on main.go
> +func showAvailableCommands(cli *cli.CLI) {
1. this function belongs in the cli package as I've explained for other similar cases
2. why not just call `cli.RunCommand("listcommands", nil, nil)` directly?

2018-10-31 11:32 UTC, itswisdomagain commented on cli/cli.go
> +func (c *CLI) RunCommand(command string, commandArgs []string, walletrpcclient *walletrpcclient.Client) {
`walletrpcclient` is registered as a property of `CLI`, see the CLI struct definition in line  25 above. CLI.walletrpcclient should be set in `func New()` and then accessed here as `c.walletrpcclient`

2018-10-31 11:32 UTC, itswisdomagain commented on cli/cli.go
> +func (c *CLI) RunCommand(command string, commandArgs []string, walletrpcclient *walletrpcclient.Client) {
alternatively, take off the property declaration in line 25

2018-10-31 11:32 UTC, itswisdomagain commented on cli/cli.go
> +func (c *CLI) printResult(res *response) {
this func does not need to extend CLI as `c` is not used, it can just be an ordinary func in this package

2018-10-31 11:32 UTC, itswisdomagain commented on walletrpcclient/walletrpcclient.go
> +type AccountBalanceResult struct {
I love the introduction of these types! Can we put all type definitions in a different file in this package (walletrpcclienttypes)?

2018-10-31 11:33 UTC, itswisdomagain commented on main.go
> +	cli := cli.New()
I'm thinking you could call the variable `cliInstance` or something

2018-10-31 12:43 UTC, itswisdomagain commented on cli/cli.go
> +	if command == "-l" {
lines 52-62 can be represented in a simpler way:
```

	if command == "-l" {
		command = "listcommands"
	} else if !c.IsCommandSupported(command) {
		c.invalidCommandReceived(command)
		os.Exit(1)
	}
```

2018-10-31 12:47 UTC, itswisdomagain requested changes
Just 2 small changes and we're good. Just semantic corrections

2018-10-31 12:47 UTC, itswisdomagain commented on cli/cli.go
> +	if command == "-l" {
lines 52-62 can be represented in a simpler way:
```

	if command == "-l" {
		command = "listcommands"
	} else if !c.IsCommandSupported(command) {
		c.invalidCommandReceived(command)
		os.Exit(1)
	}
```

2018-10-31 12:47 UTC, itswisdomagain commented on main.go
> +	cli := cli.New(client, AppName)
This variable name clash is still unresolved, `cli` is used as a variable name and as a package name in the same scope.

2018-10-31 13:02 UTC, itswisdomagain approved these changes

2018-10-31 13:02 UTC, merged