recent activities in the overview page are not more than 5
raedahgroup/godcr-old pull request #319
Opened 2019-04-18 10:33 UTC by ademuanthony

Resolves #300 

![image](https://user-images.githubusercontent.com/11990092/56355211-abcc6580-61cd-11e9-8300-699bf06f0997.png)

2019-04-18 21:45 UTC, itswisdomagain requested changes

2019-04-18 21:45 UTC, itswisdomagain commented on web/routes/templates.go
> +			return strings.Split(balanceStr, ".")[0]
The code in lines 47 to 51 are repeated 3 times, please refactor into a function.

Preferably, you can put all 3 functions into one function that returns either a slice
`"splitBalanceIntoParts": func(accounts []*walletcore.Account) []string`

I explain how this slice can be used in template below.

2019-04-18 21:45 UTC, itswisdomagain commented on web/views/overview.html
> +                                <b>{{ totalBalanceWholePart .accounts }}.{{ totalBalance1st2Decimal .accounts }}<span
If using a slice as recommended in a previous comment, this becomes
```
{{ $balanceParts := splitBalanceIntoParts }}
<b>
     {{ index $balanceParts 0 }}.{{ index $balanceParts 1 }}
     <span style="font-size:13px;">{{ index $balanceParts 2 }}</span> DCR
</b>
```

2019-04-18 22:03 UTC, itswisdomagain requested changes

2019-04-18 22:03 UTC, itswisdomagain commented on web/routes/templates.go
> +			spitedParts := strings.Split(balanceStr, ".")
`splitBalance` instead of `spitedParts`

2019-04-18 22:32 UTC, itswisdomagain approved these changes

2019-04-18 23:00 UTC, raedah commented
Two outstanding issue he found.
- font size of the DCR suffix should be the smaller variation.
- case of 0.00000000 should just be 0. Remove trailing zeros for any amount.

2019-04-18 23:10 UTC, itswisdomagain requested changes
New requested changes
https://github.com/raedahgroup/godcr/pull/319#issuecomment-484716863

2019-04-18 23:59 UTC, itswisdomagain requested changes

2019-04-18 23:59 UTC, itswisdomagain commented on web/routes/templates.go
> +			if len(splitBalance[1]) > 2 {
`splitBalance[1]` might produce index out of bounds at this point (if len(splitBalance) == 1)
Move this second if statement into the body of the first if statement

2019-04-18 23:59 UTC, itswisdomagain commented on web/routes/templates.go
> +				balanceParts = append(balanceParts, splitBalance[1][0:2])
This will produce an error if `len(splitBalance[1])` is less than 2. Also remember that `splitBalance[1]` will contain ` DCR` suffix.

2019-04-18 23:59 UTC, itswisdomagain commented on web/routes/templates.go
> +		"splitBalanceIntoParts": func(accounts []*walletcore.Account) (balanceParts []string) {
This function needs to be rewritten and simplified, it's too complicated currently.

2019-04-19 05:21 UTC, ademuanthony commented
Updated

![image](https://user-images.githubusercontent.com/11990092/56408160-0798fc00-626b-11e9-858e-061eb696a137.png)

![image](https://user-images.githubusercontent.com/11990092/56408176-167fae80-626b-11e9-929a-3c3fb6b155d9.png)

![image](https://user-images.githubusercontent.com/11990092/56408205-30b98c80-626b-11e9-931c-c22b51458394.png)

2019-04-20 00:55 UTC, itswisdomagain requested changes

2019-04-20 00:55 UTC, itswisdomagain commented on web/routes/templates.go
> +			balanceParts[1] = "." + splitBalance[1][0:2]
This would fail if `len(splitBalance[1] < 2)`. Cannot extract values from index 0 to 2 (exclusive) if there's only a value at index 0 and no value at index 1.

2019-04-20 01:10 UTC, itswisdomagain approved these changes

2019-04-20 01:10 UTC, merged