[WIP] truncate tx hash
raedahgroup/godcr-old pull request #325
Opened 2019-04-19 05:59 UTC by ademuanthony

2019-04-25 05:35 UTC, Sirmorrison commented
The `fee` table header can be align to the center. its too far left.

![image](https://user-images.githubusercontent.com/27733432/56711889-4116af00-6724-11e9-976d-a55db73b3ec3.png)

2019-04-25 05:40 UTC, Sirmorrison commented
run `go fmt ./...`

2019-04-25 05:55 UTC, Sirmorrison requested changes

2019-04-25 05:55 UTC, Sirmorrison commented on web/routes/templates.go
> +	"github.com/raedahgroup/dcrlibwallet/txhelper"
re-arrange imports

2019-04-25 10:10 UTC, ademuanthony commented
> The `fee` table header can be align to the center. its too far right. Also the `amount` can be aligned a little to the left.
> 
> generally are the headers center, left or right align? hard to tell.
> 
> ![image](https://user-images.githubusercontent.com/27733432/56711889-4116af00-6724-11e9-976d-a55db73b3ec3.png)

The headers are aligned with the content

2019-04-26 20:01 UTC, Sirmorrison requested changes

2019-04-26 20:01 UTC, Sirmorrison commented on web/routes/handlers.go
> +	alTxCount, txCountErr := routes.walletMiddleware.TransactionCount(nil)
this is supposed to be `allTxCount` if am not mistaken

2019-04-26 20:01 UTC, Sirmorrison commented on web/routes/handlers.go
> +		"transactionTotalCount":  alTxCount,
same as above `allTxCount`

2019-04-26 20:01 UTC, Sirmorrison commented on web/routes/handlers.go
> +	if totalTxLoaded < alTxCount {
same as above

2019-04-26 20:01 UTC, Sirmorrison commented on web/routes/handlers.go
> +	filter := txindex.Filter()
camel case `txIndex`

2019-04-26 20:04 UTC, ademuanthony commented on web/routes/handlers.go
> +	filter := txindex.Filter()
this is an imported package name

2019-04-26 20:41 UTC, Sirmorrison commented on web/routes/handlers.go
> +	filter := txindex.Filter()
ok

2019-04-26 21:01 UTC, Sirmorrison requested changes

2019-04-26 21:01 UTC, Sirmorrison commented on web/views/history.html
> +                                {{ index $amountParts 0 }}{{ index $amountParts 1 }}<span>{{ index $amountParts 2 }}</span>
im not sure why you are splitting the tx.Amount but the output im seeing from testing is same as the one you changed. If there isn't any sure reason why please revert to the `{{ amountDcr $txn.Amount }}` same goes for the fees also.

2019-04-26 21:09 UTC, Sirmorrison commented
![image](https://user-images.githubusercontent.com/27733432/56836463-374d9280-686f-11e9-806f-4d3f50d0758c.png)

![image](https://user-images.githubusercontent.com/27733432/56836573-9b705680-686f-11e9-85c5-d9b0c7f5b3f2.png)

i noticed your `amount` and `fees` columns outputs needs to be properly formatted for your filters.  
use the `amountDcr` function where necessary.

2019-04-27 00:12 UTC, Sirmorrison approved these changes

2019-04-27 01:19 UTC, itswisdomagain requested changes

2019-04-27 01:19 UTC, itswisdomagain commented on app/walletcore/helper.go
> +func TransactionTypes() map[wallet.TransactionType]string {
This should probably use `txhelper.FormatTxType` from dcrlibwallet. See https://github.com/raedahgroup/dcrlibwallet/blob/dcrlibwallet-wip/txhelper/types.go#L113

2019-04-27 01:19 UTC, itswisdomagain commented on web/routes/handlers.go
> +	for _, txType := range txTypes {
This should probably use `txhelper.FormatTxType` from dcrlibwallet. See https://github.com/raedahgroup/dcrlibwallet/blob/dcrlibwallet-wip/txhelper/types.go#L113

2019-04-27 01:19 UTC, itswisdomagain commented on web/routes/handlers.go
> +		"accountsCount":          len(accounts),
Not used, can remove.

2019-04-27 01:19 UTC, itswisdomagain commented on web/routes/handlers.go
> +	if transactionType := req.FormValue("trans-type"); transactionType != "" {
`tx-type` instead of `trans-type`

2019-04-27 01:19 UTC, itswisdomagain commented on web/routes/templates.go
> +		"extractDateTime": func(timestamp int64) string {
Can simplify to `"extractDateTime": utils.FormatUTCTime`. See https://github.com/raedahgroup/dcrlibwallet/blob/dcrlibwallet-wip/utils/utils.go#L63.

2019-04-27 01:19 UTC, itswisdomagain commented on web/routes/templates.go
> +		"truncate": func(input string, maxLength int) string {
`text string, maxNumberOfCharacters int`

2019-04-27 01:19 UTC, itswisdomagain commented on web/routes/templates.go
> +			if len(input) <= maxLength {
`if len(input) < maxLength` is fine, quicker to make sense of too.

2019-04-27 01:19 UTC, itswisdomagain commented on web/routes/templates.go
> +		"accountName": func(txn *walletcore.Transaction) string {
Let's move this into a `(tx *walletcore.Transaction) WalletAccountForTx() string` function. Of course, this would have to be in the `walletcore` package, inside the `types.go` file there, below the `Transaction` type declaration.

2019-04-27 01:19 UTC, itswisdomagain commented on web/static/app/src/controllers/history_controller.js
> +    this.transactionCountTarget.setAttribute('data-transactionCount', 0)
`data-tx-count`

2019-04-27 01:19 UTC, itswisdomagain commented on web/static/app/src/controllers/history_controller.js
> +    let transType = this.transactionTypeTarget.value
`txType`

2019-04-27 01:19 UTC, itswisdomagain commented on web/static/app/src/controllers/history_controller.js
> +        console.log(e)
For debugging purposes I believe. This can be removed.

2019-04-27 01:19 UTC, itswisdomagain commented on web/static/app/src/controllers/history_controller.js
> +          if (output.account_numberr === -1 || accountNames.indexOf(output.account_name) !== -1) {
`account_numberr`? See https://github.com/raedahgroup/dcrlibwallet/blob/dcrlibwallet-wip/txhelper/types.go#L109.

In order to use the `tx.account_number` json key specified there, you'll need to update the dcrlibwallet mod version. Reason is, dcrlibwallet previously used a wrong json tag (`previous_account`).

- Run `go get github.com/raedahgroup/dcrlibwallet@dcrlibwallet-wip`
- Then `go mod tidy`

Please test to ensure that txs loaded this way display properly. You can temporarily reduce the number of txs loaded per page in order to trigger an async call to fetch more txs. Remember to restore the default minimum tx per page count.

2019-04-27 01:19 UTC, itswisdomagain commented on web/views/history.html
> +                            <option value="">All Transaction({{ .transactionTotalCount }})</option>
- `All Transactions`
- Also add a space before the bracket.
- This doesn't show fully on your screenshot, may need to increase the width of this element.

2019-04-27 01:19 UTC, itswisdomagain commented on web/views/history.html
> +                            <option value="{{ $txType }}">{{ $txType }}({{ $count }})</option>
Space between tx type and (count)

2019-04-27 01:19 UTC, itswisdomagain commented on web/views/history.html
> +                <table class="table history-table" style="table-layout: fixed">
This style isn't necessary as the class already defines it.

2019-04-27 01:19 UTC, itswisdomagain commented on web/views/history.html
> +                        <th style="width: 115px;text-align: center;">Amount</th>
space between width and text-align properties.

2019-04-27 01:19 UTC, itswisdomagain commented on web/views/history.html
> +                    {{ $accountsCount := .accountsCount}}
Not necessary, remove.

2019-04-27 01:19 UTC, itswisdomagain commented on web/static/app/src/controllers/history_controller.js
> +          let transCount = parseInt(_this.transactionCountTarget.getAttribute('data-transactionCount')) + result.txs.length
Isn't this same as counting the number of rows in the table? Generally a better idea to not store data that can be inferred elsehow.

2019-04-27 01:39 UTC, ademuanthony commented on web/routes/handlers.go
> +	for _, txType := range txTypes {
Here we are trying to loop through all the types, but the suggested function only gives a string representation of a specified transaction type and not a list of all the types

2019-05-01 03:21 UTC, raedah commented
If 0 items are found for a filter type, the line should be hidden and not be a choice.

2019-05-03 02:38 UTC, itswisdomagain requested changes

2019-05-03 02:38 UTC, itswisdomagain commented on app/walletcore/helper.go
> +func TransactionTypes() map[wallet.TransactionType]string {
I believe we can do away with this function. Make it a slice instead:
```
var TransactionTypes = []wallet.TransactionType {
	wallet.TransactionTypeRegular,
	wallet.TransactionTypeCoinbase,
	wallet.TransactionTypeTicketPurchase,
	wallet.TransactionTypeVote,
	wallet.TransactionTypeRevocation,
}
```

I'll add more thoughts on the 2 sites calling this function.

2019-05-03 02:38 UTC, itswisdomagain commented on app/walletcore/types.go
> +			if output.AccountNumber == -1 || isInArray(output.AccountName) {
`isInArray` as a function name begs the question, which array? The function could be renamed to `addWalletAccount` and the function modified to check if the account name already exists, then appending if it doesn't.

This line and similar lines would become (also notice the comment, it's not immediately obvious what `-1` signifies):
```
if output.AccountNumber != -1 {
     // output belongs to this wallet and not an external wallet address
     addWalletAccount(output.AccountName)
}
```

The `isInArray` modified to `addWalletAccount` would look like this:
```
addWalletAccount := func(accountName string) {
	for _, name := range accountNames {
		if name == accountName {
			return
		}
	}
	accountNames = append(accountNames, accountName)
}
```

2019-05-03 02:38 UTC, itswisdomagain commented on app/walletcore/types.go
> +	}
Please add a single line space after this function.

2019-05-03 02:38 UTC, itswisdomagain commented on app/walletcore/types.go
> +}
go fmt

2019-05-03 02:38 UTC, itswisdomagain commented on web/routes/handlers.go
> +	for _, txType := range txTypes {
I see here that what you need is the string representation of each txType, not the `wallet.TransactionType` itself. If you loop over `walletcore.TransactionTypes()`, you can get the string representation by calling `txhelper.FormatTransactionType(txType)`

2019-05-03 02:38 UTC, itswisdomagain commented on web/routes/templates.go
> +	libutils "github.com/raedahgroup/dcrlibwallet/utils"
Whenever an external package clashes with an internal package, I oft prefer to alias the internal package, prefixing with `godcr`. An example of that is `godcrApp` used in `fyne/fyne.go`. I think it's easier to make sense of. Could do same here.

2019-05-03 02:38 UTC, itswisdomagain commented on web/routes/templates.go
> +		"directionImage": func(txn *walletcore.Transaction) (imageFile string) {
I don't see that naming the return variable is necessary.

2019-05-03 02:38 UTC, itswisdomagain commented on web/routes/templates.go
> +			var accountNames []string
This can `return tx. WalletAccountForTx()`

2019-05-03 02:38 UTC, itswisdomagain commented on web/routes/handlers.go
> +	txns, err := routes.walletMiddleware.TransactionHistory(offset, txPerPage, filter)
Please correct the condition of the if statements in lines 295 and 245 of this file to be `pageToLoad <= 0` instead of `pageToLoad < 0`

2019-05-03 02:38 UTC, itswisdomagain commented on web/static/app/src/controllers/history_controller.js
> +      'transactionCountContainer', 'transactionCount', 'transactionTotalCount'
The targets listed here should be ordered the same way they appear on the page. I believe `loadingIndicator` is the last on the page and `transactionType` is the first.

2019-05-03 02:38 UTC, itswisdomagain commented on web/static/app/src/controllers/history_controller.js
> +    if (this.historyTableTarget.innerHTML === '') {
I think this if statement can move to the top of this function, returning before any resizing is done.

2019-05-03 02:38 UTC, itswisdomagain commented on web/static/app/src/controllers/history_controller.js
> +  changeTransactionType () {
This function isn't triggered **to** `changeTransactionType `, it is triggered **on** `transactionTypeFilterChanged`. Function should be renamed.

2019-05-03 02:38 UTC, itswisdomagain commented on web/static/app/src/controllers/history_controller.js
> +    this.transactionCountTarget.setAttribute('data-tx-count', 0)
I don't see this attribute used anywhere; probably don't need to set it.

2019-05-03 02:38 UTC, itswisdomagain commented on web/static/app/src/controllers/history_controller.js
> +      'transactionType',
This could/should be `selectedTransactionTypeFilter` or `selectedTxTypeFilter` for short.

2019-05-03 02:38 UTC, itswisdomagain commented on web/static/app/src/controllers/history_controller.js
> +          if (!result.txs || result.txs.length === 0) {
`result.success` is true but there's either no txs in result or txs count is 0? This shouldn't happen. Why are we writing code for such possibility?

If `result.success` is true, then txs should be returned. Unless there's no tx for the type specified (in which case it shouldn't be on the filter) or the page used in the query does not have data to return (in which case the handler should return an error message, not `result.success = true`; the error would be that there's `no transaction for page  ${x}`

2019-05-03 02:38 UTC, itswisdomagain commented on web/static/app/src/controllers/history_controller.js
> +    const accountName = tx => {
`tx` in bracket `(tx)` might be more readable

2019-05-03 02:38 UTC, itswisdomagain commented on web/static/app/src/controllers/history_controller.js
> +          if (output.account_numberr === -1 || accountNames.indexOf(output.account_name) !== -1) {
- `account_number`
- You can (should) test that this `fetchMoreTxs` function works as it should by temporarily reducing the number of txs to load per page, so that this function is triggered initial load. Remember to reset the number of txs loaded per page.
- The if statement can be made 1 line shorter by using:
```
if (output.account_number !== -1 && accountNames.indexOf(output.account_name) < 0)
```
- You can also use a `Set` instead of an array so you don't need to check if the account name has been previously added, you just add to the set knowing that it will not re-add the value if it has already been added.

2019-05-03 02:38 UTC, itswisdomagain commented on web/static/app/src/controllers/history_controller.js
> +
Can do without this space.

2019-05-03 02:38 UTC, itswisdomagain commented on web/static/app/src/controllers/history_controller.js
> +import { hide, show, splitAmountIntoParts, truncate } from '../utils'
`splitAmountIntoParts` is not used.

2019-05-03 02:38 UTC, itswisdomagain commented on web/routes/handlers.go
> +	txCount, txCountErr := routes.walletMiddleware.TransactionCount(filter)
Should be `allTxCount` since it's not the count of txs being returned but the count of all txs for this filter (and if no filter is specified, then it's the count of all txs in wallet)

2019-05-03 02:38 UTC, itswisdomagain commented on web/routes/handlers.go
> +		data["txCount"] = txCount
Key should be `transactionTotalCount` since the value assigned is not the count of txs being returned but the total count of txs for the given filter.

2019-05-03 02:38 UTC, itswisdomagain commented on web/routes/handlers.go
> +	if transactionType := req.FormValue("tx-type"); transactionType != "" {
The complete list of filters on android history page are `All`, `Sent`, `Received`, `Yourself`, `Staking` and `Coinbase`. `Staking` is a combination of `Ticket`, `Vote` and `Revocation`.

 See https://github.com/decred/dcrandroid/blob/master/app/src/main/java/com/dcrandroid/fragments/HistoryFragment.kt#L223-L260.

2019-05-03 02:38 UTC, itswisdomagain commented on web/routes/handlers.go
> +	transactionCountByType := make(map[string]int, len(txTypes))
The complete list of filters on android history page are `All`, `Sent`, `Received`, `Yourself`, `Staking` and `Coinbase`. `Staking` is a combination of `Ticket`, `Vote` and `Revocation`.

See https://github.com/decred/dcrandroid/blob/master/app/src/main/java/com/dcrandroid/fragments/HistoryFragment.kt#L223-L260.

We'll also need to rename `Transferred` to `Yourself`. This has been done in the latest commit to `dcrlibwallet-wip`, you would need to update the mod version on godcr for this to reflect. Remember to run `go mod tidy` after updating the version with `go get github.com/raedahgroup/dcrlibwallet@dcrlibwallet-wip`.

2019-05-03 02:38 UTC, itswisdomagain commented on web/static/app/src/controllers/history_controller.js
> +          show(_this.transactionCountContainerTarget)
`transactionCountTarget` should be updated as well

2019-05-03 02:38 UTC, itswisdomagain commented on web/routes/handlers.go
> +	transactionCountByType := make(map[string]int, len(txTypes))
I'm concerned about setting the length of this `transactionCountByType` map to `len(txTypes)` as not all tx types may be accounted for. Best to set the capacity instead: `make(map[string]int, 0, len(txTypes))`; or just `make(map[string]int, 0)`

2019-05-03 02:38 UTC, itswisdomagain commented on web/views/history.html
> +                            <td style="text-align: right">{{ amountDcr $txn.Amount}}</td>
- `{{ amountDcr $txn.Amount }}`
- return the trailing space at the next line too

2019-05-03 03:04 UTC, itswisdomagain commented
**These anomalies are observed on page load:**
<img width="332" alt="Screenshot 2019-05-03 at 4 00 03 AM" src="https://user-images.githubusercontent.com/18400051/57117987-07632b00-6d58-11e9-922a-f51d6598d97e.png">
- Direction icons are same
- Date, amount and fee fields getting truncated (why are we using fixed column widths again?)

**When you change the tx filter, these additional anomalies are observed:**
<img width="1032" alt="Screenshot 2019-05-03 at 4 00 19 AM" src="https://user-images.githubusercontent.com/18400051/57118009-35e10600-6d58-11e9-98a8-c600e2330ce2.png">
- tx count report at the top right
- External account listed
- Hash getting `{` at the end instead of `...`

2019-05-03 15:27 UTC, ademuanthony commented on web/static/app/src/controllers/history_controller.js
> +          show(_this.transactionCountContainerTarget)
`transactionCountTarget ` is updated in `displayTxs`

2019-05-06 19:13 UTC, itswisdomagain requested changes
I'm unable to build, getting the following error:
<img width="953" alt="Screenshot 2019-05-06 at 8 11 57 PM" src="https://user-images.githubusercontent.com/18400051/57248831-513f6000-703b-11e9-8b69-83268294a27c.png">

If possible, make the following adjustments:

2019-05-06 19:13 UTC, itswisdomagain commented on app/walletcore/helper.go
> +	var (
This can be inlined

2019-05-06 19:13 UTC, itswisdomagain commented on web/static/app/src/controllers/history_controller.js
> +        // if the user have changed the filter before the result is gottend
`if the user **has** changed the filter before the result is **gotten**`

2019-05-11 14:14 UTC, ademuanthony commented on app/walletcore/helper.go
> +	var (
The variable needs to be initialized immediately

2019-05-13 19:03 UTC, Sirmorrison commented
> 
> 
> If 0 items are found for a filter type, the line should be hidden and not be a choice.

![image](https://user-images.githubusercontent.com/27733432/57647091-05039b00-75ba-11e9-9892-6baf834635d7.png)

Im still getting the filters with 0 items please check

also rebase your PR

2019-05-31 02:01 UTC, itswisdomagain approved these changes

2019-05-31 02:01 UTC, itswisdomagain commented on app/walletcore/helper.go
> +	TransactionFilterSent     = "Sent"
Add an empty line space before this, to show separation of concerns.

2019-05-31 12:12 UTC, Sirmorrison requested changes
![image](https://user-images.githubusercontent.com/27733432/58704601-84f47800-83a4-11e9-976a-283b47da1d8d.png)

* first i noticed that on smaller screens the hash column on the history page is hidden and the table is not scroll-able. what this implies is that a user will not be to view the details of the transaction.

* Also on full screen i noticed the hashes are truncated thereby leaving the too much space on the history table.
we could either reduce the width of the hash column on the history table, or display the full length of the hashes and detect screen width which will truncate the hash on smaller screens rather than hide it. 
![image](https://user-images.githubusercontent.com/27733432/58704968-ad30a680-83a5-11e9-868b-570cdf163cc7.png)

2019-06-08 16:26 UTC, ademuanthony commented
![image](https://user-images.githubusercontent.com/11990092/59149821-7a745700-8a12-11e9-9313-96618655ba00.png)

2019-06-09 02:10 UTC, Sirmorrison commented
![image](https://user-images.githubusercontent.com/27733432/59154124-f39b9a80-8a62-11e9-9580-69bc4a3778f1.png)

i think this error is messing with the output.

![image](https://user-images.githubusercontent.com/27733432/59154169-1da18c80-8a64-11e9-93d5-5aeacce75015.png)

2019-06-11 09:53 UTC, Sirmorrison requested changes

2019-06-11 09:53 UTC, Sirmorrison commented on web/routes/templates.go
> +		"directionImage": func(txn *walletcore.Transaction) string {
i think this will make more sense as `txDirectionImage`

2019-06-13 05:37 UTC, Sirmorrison approved these changes

2019-06-13 05:37 UTC, merged