Terminal navigation
raedahgroup/godcr-old pull request #327
Opened 2019-04-20 01:14 UTC by Sirmorrison

2019-04-22 23:16 UTC, raedah commented
design ack

2019-04-23 03:47 UTC, ademuanthony requested changes
Update the description to show that this PR is a continuation of #334 which resolves #311.
#311 also requires that you should `Show the total count of transactions at the top of the page`. This will require that #330 by @itswisdomagain is completed. We should either add this to the description and create a new issue for it or mark this PR as WIP

2019-04-23 13:47 UTC, itswisdomagain commented
> #311 also requires that you should `Show the total count of transactions at the top of the page`.

This requirement is implemented in #330.

2019-04-23 16:32 UTC, ademuanthony approved these changes

2019-04-23 20:16 UTC, merged