[WIP] add load more button
raedahgroup/godcr-old pull request #328
Opened 2019-04-20 19:23 UTC by codemaestro64

This adds a load more button to the transaction history page of the nuklear interface.It ensures that more history items are only fetched upon user request. 

Fixes #314

2019-04-22 23:17 UTC, raedah commented
Currently a random number of items are being returned on each page. This should be fixed so the number of items returned are consistent.

2019-04-23 04:08 UTC, ademuanthony requested changes
Is infinite scrolling not possible as requested in the #314 being resolved? Please update the description to reflect this.
Also https://github.com/raedahgroup/godcr/pull/328#issuecomment-485585342

2019-04-23 09:30 UTC, codemaestro64 commented
The PR has been updated to display a consistent number of transactions per page.

2019-04-23 12:09 UTC, ademuanthony approved these changes

2019-04-23 13:42 UTC, itswisdomagain requested changes

2019-04-23 13:42 UTC, itswisdomagain commented on nuklear/pagehandlers/sync.go
> +	return
Forgot to remove this.

2019-04-23 19:24 UTC, itswisdomagain approved these changes

2019-04-23 19:29 UTC, merged