Empty imported wallet fix
raedahgroup/godcr-old pull request #33
Opened 2018-11-12 05:15 UTC by Jujhar

Removed imported wallet if empty on flaky basis that system falsely automatically — always — creates an entry of an imported wallet even when no wallet is imported

Fixes #32

2018-11-12 23:05 UTC, itswisdomagain requested changes

2018-11-12 23:05 UTC, itswisdomagain commented on cli/cli.go
> +		if v.AccountName == "imported" && v.Total == 0 {
Why not do this from the `walletrpcclient` package instead? The `Balance()` handler in that package is called multiple times from the web and cli packages. It's called when displaying the balance on both packages, when sending an amount on both interfaces and when generating a receive address on the web interface. Soon enough, it will be called when generating a receive address on the cli interface. And there could be other interfaces.

It would be better to discard the imported account at the source where all the interfaces connect to, that way we won't have to write same/similar code in multiple places to do that.

2018-11-13 02:46 UTC, Jujhar commented on cli/cli.go
> +		if v.AccountName == "imported" && v.Total == 0 {
Updated

2018-11-13 20:03 UTC, itswisdomagain requested changes

2018-11-13 20:03 UTC, itswisdomagain commented on walletrpcclient/walletrpcclient.go
> +	var minusRange = 0  // used to return correct number of wallet entries to make
This is quite unnecessary as you can make a slice in go without knowing the actual length of the slice. More so, this attempt to determine the number of "invalid" accounts to disregard comes with an extra cost - you're making 2 RPCs for each account to get the account balance which introduces redundancy.

You can initialise the `balanceResult` slice without specifying the length, like so:
`balanceResult := make([]AccountBalanceResult, 0, len(accounts.Accounts))`

Then you can run your accounts loop once, get the balance and ignore accounts with name as "imported" and balance equal zero. The code sinppet below should work:

```
balanceResult := make([]AccountBalanceResult, 0, len(accounts.Accounts))

for _, v := range accounts.Accounts {
	req := &pb.BalanceRequest{
		AccountNumber:         v.AccountNumber,
		RequiredConfirmations: 0,
	}

	res, err := c.walletServiceClient.Balance(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("error fetching balance for account: %d :%s", v.AccountNumber, err.Error())
	}

	if v.AccountName == "imported" && dcrutil.Amount(res.Total) == 0 {
		continue
	}

	accountBalance := AccountBalanceResult{
		AccountNumber:   v.AccountNumber,
		AccountName:     v.AccountName,
		Total:           dcrutil.Amount(res.Total),
		Spendable:       dcrutil.Amount(res.Spendable),
		LockedByTickets: dcrutil.Amount(res.LockedByTickets),
		VotingAuthority: dcrutil.Amount(res.VotingAuthority),
		Unconfirmed:     dcrutil.Amount(res.Unconfirmed),
	}

	balanceResult = append(balanceResult, accountBalance)
}
```

Notice also the usage of `continue` not `break` when you want to skip further processing in a loop and jump to the next item in the loop. Also notice there's no need for incrementing the loop index yourself with `i++`

I think with this, we should be good to go.

2018-11-13 20:03 UTC, itswisdomagain commented on walletrpcclient/walletrpcclient.go
> +	var minusRange = 0  // used to return correct number of wallet entries to make
This article and SO answer might help to explain more about go slices
- https://blog.golang.org/go-slices-usage-and-internals
- https://stackoverflow.com/a/28636712

2018-11-14 00:51 UTC, Jujhar commented on walletrpcclient/walletrpcclient.go
> +	var minusRange = 0  // used to return correct number of wallet entries to make
Ok this kind of makes sense did not know you could do 0 like that.

2018-11-14 12:21 UTC, itswisdomagain approved these changes

2018-11-14 12:25 UTC, itswisdomagain commented
For future reference, the `imported` account has its purpose in dcrwallet. It's meant to hold details for accounts a user imports into the wallet.

However, because it's not part of the wallet's account, the wallet cannot generate a receive address for it.

But if a user does import an external account, he should be able to see the balance for such account and possibly create transactions from the imported account.

This PR does ensure that if the imported account's balance is > 0, the account will show up in the account balances section of the interfaces.

2018-11-14 12:25 UTC, merged