[WIP] Iss 308 send page
raedahgroup/godcr-old pull request #333
Opened 2019-04-21 18:31 UTC by ademuanthony

Resolves #308

2019-04-26 20:23 UTC, Sirmorrison requested changes

2019-04-26 20:23 UTC, Sirmorrison commented on nuklear/pagehandlers/transaction_details.go
> +	"fmt"
re-arrange import

2019-04-26 20:23 UTC, Sirmorrison commented on web/routes/handlers.go
>  	"math"
re-arrange import

2019-04-26 20:48 UTC, Sirmorrison approved these changes

2019-05-03 03:39 UTC, itswisdomagain requested changes
Let's work on these changes first, will test and review more afterwards.

2019-05-03 03:39 UTC, itswisdomagain commented on app/conversion/bitrex/bitrex.go
> +		Timeout: time.Second * 2,
2 seconds timeout seems small, no?

2019-05-03 03:39 UTC, itswisdomagain commented on app/utils/utils.go
> +		changeAddresses = append(changeAddresses, destination.Address)
`changeAddresses` and `outputs` are actually not the same.

I see that the new functions required are `EstimateFee` and `EstimateSerializeSize`.

These operations are already quite well handled in `dcrlibwallet`, so what I did was to export a public function that can be used from the `txhelper` package (`txhelper.EstimateTxFeeAndSize`). You'll need to update the dcrlibwallet version in go.mod and run `go mod tidy` to use these new functions.

Usage should be something like `txhelper.EstimateTxFeeAndSize(len(payload.utxos), payload.sendDestinations, payload.changeDestinations)`

2019-05-03 03:39 UTC, itswisdomagain commented on web/routes/handlers.go
> +	// If no input is selected, use all inputs in the account to determine
This comment needs to be updated. The reason we need all inputs is to properly determine the number of inputs to take into account when estimating fee and tx serialize size.

2019-05-03 03:39 UTC, itswisdomagain commented on web/routes/handlers.go
> +	}
Adding an empty line after each if block in this function would be helpful.

2019-05-03 03:39 UTC, itswisdomagain commented on app/walletcore/helper.go
> +			return nil, 0, err
`fmt.Errorf("Invalid account number")`

2019-05-03 03:39 UTC, itswisdomagain commented on app/walletcore/helper.go
> +	for i, accountStr := range destinationAccounts {
`accountNumber` or `accountNumberStr`

2019-05-03 03:39 UTC, itswisdomagain commented on app/walletcore/helper.go
> +	destinationAmounts, sendMaxAmountValues []string, addressFunc func(accountNumber uint32) (string, error)) (
`addressFunc` can be `generateAddress` or `generateAddressFn`

2019-05-03 03:39 UTC, itswisdomagain commented on app/walletcore/helper.go
> +	destinationAccountAddresses := make([]string, len(destinationAccounts))
Append to `destinationAddresses` instead of creating a new `destinationAccountAddresses` slice.

2019-05-03 03:39 UTC, itswisdomagain commented on web/routes/helpers.go
> +	destinationAccounts := req.Form["destination-account"]
`destinationAccountNumbers`, `destination-account-number`

2019-05-31 12:38 UTC, Sirmorrison requested changes
![image](https://user-images.githubusercontent.com/27733432/58705969-a192af00-83a8-11e9-9ca3-7b6790ae5560.png)

![image](https://user-images.githubusercontent.com/27733432/58706011-bbcc8d00-83a8-11e9-99f3-219eca30c8f6.png)

*on the send page? `send to account` column doesn't show the input fields and when you return to `send to address` the input fields are also hidden until the page is refresh.

2019-05-31 12:54 UTC, Sirmorrison requested changes

2019-05-31 12:54 UTC, Sirmorrison commented on web/views/send.html
> +                                            Add another output
` Add another output` should be ` Add another account`

2019-05-31 16:40 UTC, ademuanthony commented on web/views/send.html
> +                                            Add another output
it was changed to output so that the user will not confuse it with creating a new account

2019-06-07 09:03 UTC, Sirmorrison commented on app/utils/utils.go
> +		changeAddresses = append(changeAddresses, destination.Address)
> 
> 
> `changeAddresses` and `outputs` are actually not the same.
> 
> I see that the new functions required are `EstimateFee` and `EstimateSerializeSize`.
> 
> These operations are already quite well handled in `dcrlibwallet`, so what I did was to export a public function that can be used from the `txhelper` package (`txhelper.EstimateTxFeeAndSize`). You'll need to update the dcrlibwallet version in go.mod and run `go mod tidy` to use these new functions.
> 
> Usage should be something like `txhelper.EstimateTxFeeAndSize(len(payload.utxos), payload.sendDestinations, payload.changeDestinations)`

have this request been implemented?

2019-06-07 09:03 UTC, Sirmorrison commented on web/routes/handlers.go
> +	// If no input is selected, use all inputs in the account to determine
> 
> 
> This comment needs to be updated. The reason we need all inputs is to properly determine the number of inputs to take into account when estimating fee and tx serialize size.

this also?

2019-06-07 09:09 UTC, Sirmorrison commented
![image](https://user-images.githubusercontent.com/27733432/59092954-a99fa100-890a-11e9-8e4f-1dc63d7b367d.png)
These issues should be looked at.

![image](https://user-images.githubusercontent.com/27733432/59093517-0b143f80-890c-11e9-96cd-3f6e297b6ec8.png)
I think `add another output` should be `add another account`

2019-06-09 01:48 UTC, Sirmorrison commented
![image](https://user-images.githubusercontent.com/27733432/59153996-124c6200-8a60-11e9-8374-d5cfb1391fa2.png)
I noticed that when i select `custom inputs` it brings out this `change output` at the bottom of the screen.
Now the issue is.. when i select an output say `1` then change my mind not to use `custom input` but `automatic input` instead, it clears everything but i still get this error at the bottom saying `Total change amount percentage must be equal to 100. Current total is 0` which prevents me from sending the fund.

2019-06-09 01:52 UTC, Sirmorrison commented
I also noticed i can send funds to the address of same account... is that a normal something or an issue?

2019-06-10 16:49 UTC, ademuanthony commented
> I also noticed i can send funds to the address of same account... is that a normal something or an issue?

yes

2019-06-11 10:09 UTC, Sirmorrison approved these changes

2019-09-06 14:32 UTC, ademuanthony commented on app/utils/utils.go
> +		changeAddresses = append(changeAddresses, destination.Address)
`changeAddresses` and `output` are used differently here though

2019-09-11 22:43 UTC, itswisdomagain requested changes

2019-09-11 22:43 UTC, itswisdomagain commented on app/rebase.txt
> +delete me again
Please delete

2019-09-11 22:43 UTC, itswisdomagain commented on app/utils/utils.go
> +	"github.com/decred/dcrd/dcrutil"
Organize your imports alphabetically.

2019-09-19 20:06 UTC, itswisdomagain requested changes

2019-09-19 20:06 UTC, itswisdomagain commented on web/routes/handlers.go
> +		data["exchangeRate"] = fmt.Sprintf("%.8f", exchangeRate)
This should be in an else block.

2019-09-20 07:16 UTC, itswisdomagain approved these changes

2019-09-20 07:17 UTC, merged