modified http transcation details page to be same as android
raedahgroup/godcr-old pull request #343
Opened 2019-04-24 02:49 UTC by Sirmorrison

fixes 303

![image](https://user-images.githubusercontent.com/27733432/56629006-e9a11200-6643-11e9-8297-7c283d5737bf.png)

2019-04-24 21:04 UTC, raedah commented
feature ack

2019-04-25 00:07 UTC, ademuanthony requested changes

2019-04-25 00:07 UTC, ademuanthony commented on web/views/transaction_details.html
> +                            {{ $balanceParts := splitAmountIntoParts .tx.Fee }}
`$feeParts` will make more meaning

2019-04-25 10:16 UTC, ademuanthony approved these changes

2019-04-25 20:07 UTC, itswisdomagain requested changes

2019-04-25 20:07 UTC, itswisdomagain commented on web/routes/templates.go
> +		"splitAmountIntoParts": func(value int64) []string {
`splitAmountIntoParts` and `splitBalanceIntoParts` contain duplicated code. I believe we can have a  `splitAmountIntoParts` function in `app/walletcore/helpers.go` and then in the `splitBalanceIntoParts` function, simply calculate the total balance and pass to the `walletcore/helpers.go` function to do the rest.
Then, this `splitAmountIntoParts` function can simply point to the `walletcore/helpers.go` function:
```
"splitAmountIntoParts": walletcore.splitAmountIntoParts,
```

Also rename that `value` parameter to `amount` please.

2019-04-25 20:07 UTC, itswisdomagain commented on web/routes/templates.go
> +		"checkStatus": func(status string) bool {
This can be done in template, don't need a template function, please remove this function. Check below for how to use if in template.

2019-04-25 20:07 UTC, itswisdomagain commented on web/views/transaction_details.html
> +                        <td class="text-right"><p style="border: 1px solid #24E8EF; color: #24E8EF;display: block;width: 6.5rem; float: right"> {{ .tx.Status }}</td>
lines 31 to 36 can be simplified as follows:
```
<td class="text-right {{ if eq .tx.Status "Confirmed" }} confirmed-status {{ else }} pending-status {{ end }}">
    {{ .tx.Status }}
</td>
```

Move those inline styles to `web/static/app/src/css/style.scss`. As you can observe from the code above, the `<td>` cell will get either `confirmed-status` or `pending-status` class. So declare `.confirmed-status` and `.pending-status` selectors in the `style.scss` file and apply the appropriate styles there.

Also, notice I removed the `<p>` element that was inside the `<td>` , don't see why that is necessary. If you want some spacing, use margin or padding. Style however you want, don't use a `<p>` in a `<td>`.

2019-04-26 08:49 UTC, yaowork approved these changes

2019-04-26 11:40 UTC, ademuanthony requested changes

2019-04-26 11:40 UTC, ademuanthony commented on web/routes/templates.go
> +			balance := walletcore.SplitAmountIntoParts(totalBalance)
you can just `return walletcore.SplitAmountIntoParts(totalBalance)`

2019-04-26 11:40 UTC, ademuanthony commented on web/routes/templates.go
> +			balance := walletcore.SplitAmountIntoParts(amountToSplit)
just `return walletcore.SplitAmountIntoParts(amountToSplit)` here

2019-04-26 11:40 UTC, ademuanthony commented on web/views/transaction_details.html
> +
This empty line can be removed

2019-04-26 11:40 UTC, ademuanthony commented on web/views/transaction_details.html
> +                        <td class="text-right">{{ .tx.LongTime }}<span> UTC</span></td>
No need for `<span>`, just `<td class="text-right">{{ .tx.LongTime }} UTC</td>`

2019-04-26 11:40 UTC, ademuanthony commented on web/static/app/src/css/style.scss
> +  padding: 0, 0.1rem, 0, 0.1rem;
`padding: 0 0.1rem 0 0.1rem` or simply `padding: 0 0.1rem`
Remove the commas

2019-04-26 11:40 UTC, ademuanthony commented on web/static/app/src/css/style.scss
> +  padding: 0, 0.1rem, 0, 0.1rem;
`padding: 0 0.1rem 0 0.1rem` or simply `padding: 0 0.1rem`

2019-04-26 11:40 UTC, ademuanthony commented on web/views/transaction_details.html
> +                        <td><P class="text-right {{ if eq .tx.Status "Confirmed" }} confirmed-status {{ else }} pending-status {{ end }}">
`<P>` should be `<p>`.
And if the `text-right` can be moved to the `<td>`, a `<span>` can be used here

2019-04-26 12:48 UTC, ademuanthony requested changes

2019-04-26 12:48 UTC, ademuanthony commented on nuklear/pagehandlers/transaction_details.go
> +	"fmt"
re-arrange import

2019-04-26 12:48 UTC, ademuanthony commented on app/utils/utils.go
> -package utils
restore this package

2019-04-26 12:48 UTC, ademuanthony commented on app/walletcore/helper.go
> +func DecimalPortion(n float64) string {
move to `app/utils`

2019-04-26 12:48 UTC, ademuanthony commented on app/walletcore/helper.go
> +func SplitAmountIntoParts(amount float64) []string {
move to `app/utils`

2019-04-26 20:41 UTC, ademuanthony approved these changes

2019-04-27 00:07 UTC, itswisdomagain requested changes

2019-04-27 00:07 UTC, itswisdomagain commented on app/utils/utils.go
> +}
go fmt

2019-04-27 00:07 UTC, itswisdomagain commented on web/routes/templates.go
> +			amountToSplit = dcrutil.Amount(amount).ToCoin()
- Lines 55 and 56 can simplify to `amountToSplit := dcrutil.Amount(amount).ToCoin()`
- `dcrAmount` instead of `amountToSplit`

2019-04-27 00:07 UTC, itswisdomagain commented on web/views/transaction_details.html
> +                                    <td class="text-right {{ if eq .tx.Status "Confirmed" }} confirmed-status {{ else }} pending-status {{ end }}"><span >{{ .tx.Status }}</span>
Move `<span >{{ .tx.Status }}</span>` to next line to look like:
```
<td ...>
    <span >{{ .tx.Status }}</span>
</td>
```

2019-04-27 00:07 UTC, itswisdomagain commented on web/views/transaction_details.html
> +                                        </tr>
Please format properly. Where does the previous `<td>` and `<tr>` end?

2019-04-27 00:07 UTC, itswisdomagain commented on web/views/transaction_details.html
> +                                                        <p style="margin-bottom: 0.1rem">{{ amountDcr .Amount }} <span>( {{ .AccountName }} )</span></p>
Is the space after the opening bracket and before the closing bracket intentional?
```
<span>( {{ .AccountName }} )</span
```

That produces `( morrison )` in the screenshot of this PR instead of `(morrison)`.

2019-04-27 00:07 UTC, itswisdomagain commented on web/views/transaction_details.html
> +                </html>
Add a new line after this line.

2019-04-27 00:10 UTC, Sirmorrison commented on web/views/transaction_details.html
> +                </html>
Which of the lines? 92, 93, 94?

2019-04-27 00:11 UTC, itswisdomagain commented on web/views/transaction_details.html
> +                </html>
94. The file should end with an empty line.

2019-04-29 14:30 UTC, itswisdomagain approved these changes

2019-04-29 14:30 UTC, merged