display nuklear transaction details on one column
raedahgroup/godcr-old pull request #349
Opened 2019-04-25 14:44 UTC by codemaestro64

This changes the layout of the nuklear transaction details page to display transaction details using a single column instead of two columns. 

This fixes #335 

![Screenshot from 2019-04-25 15-34-42](https://user-images.githubusercontent.com/42093751/56744754-ff602580-6770-11e9-8248-f433cabb2ddc.png)

2019-04-25 20:10 UTC, raedah commented
Details look okay. Placement of the Back button is no good. Can probably just use the same 'bread crumb' style that http uses.

2019-04-26 11:34 UTC, codemaestro64 commented
> Details look okay. Placement of the Back button is no good. Can probably just use the same 'bread crumb' style that http uses.

Use of breadcrumb as been implemented

2019-04-26 17:42 UTC, raedah commented
tested locally, worked fine.

2019-04-26 21:24 UTC, Sirmorrison requested changes

2019-04-26 21:24 UTC, Sirmorrison commented on nuklear/pagehandlers/transaction_details.go
this space is not needed

2019-04-26 21:30 UTC, Sirmorrison commented
![image](https://user-images.githubusercontent.com/27733432/56837477-716c6380-6872-11e9-88fe-2ec4007b73de.png)

the space between the `type` and the `amount` is too much (blue line on screen shot).
and would look nicer if the table items at the bottom half of the tx's aligned with those on the top half (red lines on screenshot).

2019-05-01 22:47 UTC, codemaestro64 commented
updated screenshot

![Screenshot from 2019-05-01 23-42-21](https://user-images.githubusercontent.com/42093751/57048332-7020a980-6c6b-11e9-92d4-26c4b3f40f06.png)

2019-05-02 05:18 UTC, Sirmorrison approved these changes

2019-05-03 03:46 UTC, itswisdomagain requested changes
Inputs need an account name column as well, compare the screenshot from the mobile app:

<img width="300" src="https://user-images.githubusercontent.com/18400051/57118927-54e29680-6d5e-11e9-8281-fcf5fea5228f.jpeg">

Other things to note:
- **Date** not Time
- Show **Status**

2019-05-05 18:14 UTC, codemaestro64 commented
> Inputs need an account name column as well, compare the screenshot from the mobile app:
> 
> <img alt="" width="300" src="https://user-images.githubusercontent.com/18400051/57118927-54e29680-6d5e-11e9-8281-fcf5fea5228f.jpeg">
> 
> Other things to note:
> 
> * **Date** not Time
> * Show **Status**

done

2019-05-06 19:27 UTC, itswisdomagain submitted a review, later dismissed

2019-05-06 19:27 UTC, itswisdomagain commented on nuklear/pagehandlers/transaction_details.go
> +		if handler.selectedTxHash == "" {
`if handler.selectedTxHash == ""`, why are we adding a breadcrumb to the page in the previous line? Don't think this group window should even be created at all if that's the case.

2019-05-06 19:27 UTC, itswisdomagain commented on nuklear/pagehandlers/transaction_details.go
> +	contentWindow.Window.Row(handler.calculateTxDetailsPageHeight()).Static(730)
Why is a row as high as the tx details page created before the breadcrumb? Should it be after the breadcrumb? Or is the breadcrumb placed inside this pretty tall row?

2019-05-06 19:27 UTC, itswisdomagain commented on nuklear/pagehandlers/transaction_details.go
> +	lineHeight := 27
- What is `firstSection` whose height is 460?
- How do we know the height of the first section is 460? Should probably be declared as a constant with a comment explaining how the value was determined. I'd prefer if the height is calculated though, after creating the table, before rendering the table on a window, by calculating `len(table.Rows) * table.RowHeight`. Might need to declare a `table.RowHeight` constant too.

- Going with the previous point, we might no longer need `lineHeight`

2019-05-06 19:27 UTC, itswisdomagain commented on nuklear/pagehandlers/transaction_details.go
> +	outputsHeight := len(handler.selectedTxDetails.Outputs) * lineHeight
I believe there's a row for the "Inputs" and "Outputs" headers; and some spacing between tables.

2019-05-06 19:27 UTC, itswisdomagain commented on nuklear/widgets/breadcrumb.go
> +		if isLastItem {
- `breadcrumb []*Breadcrumb` is a slice, should be `breadcrumbs`
- Instead of checking if `isLastItem`, should probably check if `breadcrumb.action == nil`.

2019-05-07 21:45 UTC, codemaestro64 commented on nuklear/pagehandlers/transaction_details.go
This has been fixed

2019-05-09 07:49 UTC, Sirmorrison commented
![image](https://user-images.githubusercontent.com/27733432/57436287-4c470000-7237-11e9-8a45-ad043e9a4ae9.png)


the issue with the tx alignment doesnt seem resolved from what im see here please take a look and ensure u pushed ur modified codes.

2019-05-09 07:51 UTC, Sirmorrison requested changes
please take a look at the screenshot and notify when done.

Also add the `status` field to the transaction details page is status `confirmed` or `unconfirmed`. Status is part of the tx returned just call it.

![image](https://user-images.githubusercontent.com/27733432/57436668-0fc7d400-7238-11e9-8f0d-756a1549f5cd.png)

2019-05-09 10:36 UTC, codemaestro64 commented
> please take a look at the screenshot and notify when done.
> 
> Also add the `status` field to the transaction details page is status `confirmed` or `unconfirmed`. Status is part of the tx returned just call it.
> 
> ![image](https://user-images.githubusercontent.com/27733432/57436668-0fc7d400-7238-11e9-8f0d-756a1549f5cd.png)

Done

2019-05-09 10:37 UTC, codemaestro64 commented
Updated screenshot 
![Screenshot from 2019-05-09 11-34-08](https://user-images.githubusercontent.com/42093751/57447331-c040d280-724e-11e9-9c72-712f5dbf75e5.png)

2019-05-09 17:38 UTC, Sirmorrison requested changes

2019-05-09 17:38 UTC, Sirmorrison commented on nuklear/pagehandlers/transaction_details.go
> +		widgets.NewColoredLabelTableCell(status, "LC", statusColor),
we have a `handler.selectedTxDetails.Status` in the return values from the call to `renderTransactionDetailsPage()` please make use of it.

2019-05-11 06:07 UTC, Sirmorrison approved these changes

2019-05-11 06:09 UTC, merged