history page fix
raedahgroup/godcr-old pull request #351
Opened 2019-04-25 22:20 UTC by UMichael

This implements the history page for fyne showing all transactions.

2019-04-25 23:17 UTC, ademuanthony requested changes
The application switches (automatically) to the overview page after some time when the history page is launched for the first time.

2019-04-25 23:17 UTC, ademuanthony commented on fyne/pages/history.go
> +	no, err := page.wallet.TransactionCount(nil)
`transactionCount` is a more suitable variable name

2019-04-25 23:17 UTC, ademuanthony commented on fyne/pages/history.go
> +	page.recentActivityTable.AddRowSimple("#", "Date", "Direction", "Amount", "Fee", "Type", "Hash")
Remove the # column.
The header should contain the following in this order
Account, Date (UTC), Type, Direction, Amount, Fee, Status, Hash

2019-04-25 23:17 UTC, ademuanthony commented on fyne/pages/history.go
> +	txns, err := page.wallet.TransactionHistory(-1, int32(no), nil)
We should not load all the transactions at once, this can be very large and can cause the app to crash, we should page the result instead.

2019-04-25 23:17 UTC, ademuanthony commented on fyne/pages/history.go
> +func (page *historyPageLoader) fetchRecentActivity() {
`loadTransactions` is a more understandable name

2019-04-25 23:17 UTC, ademuanthony commented on fyne/pages/history.go
> +	fetchRecentActivityError string
rename this to `loadTransactionsError`

2019-04-25 23:17 UTC, ademuanthony commented on fyne/pages/history.go
> +	recentActivityTable      *widgets.Table
rename to `transactionsTable`

2019-04-25 23:24 UTC, raedah commented on fyne/pages/history.go
> +	txns, err := page.wallet.TransactionHistory(-1, int32(no), nil)
Load time is much faster now with the tx indexing code merged recently. Shouldnt be a problem anymore as long as the gui is able to load and scroll it properly. Nuklear doesnt have the capability to do it, and http may be better with eager loading since it is expected in that interface. Full list may work well on fyne though. Android supports full list scrolling.

2019-04-25 23:28 UTC, raedah commented
Was unable to test this due to frequent crashing.

2019-04-26 01:17 UTC, UMichael commented
> The application switches (automatically) to the overview page after some time when the history page is launched for the first time.

This is not related to this PR please check https://github.com/raedahgroup/godcr/issues/350

2019-04-26 01:21 UTC, UMichael commented on fyne/pages/history.go
> +	page.recentActivityTable.AddRowSimple("#", "Date", "Direction", "Amount", "Fee", "Type", "Hash")
resolved this

2019-04-26 12:25 UTC, ademuanthony requested changes
The app occasionally panics when you try to close it
![image](https://user-images.githubusercontent.com/11990092/56806575-35121680-6824-11e9-8fdd-b612f3541141.png)

Also, confirm the frequent crashing [noted here](https://github.com/raedahgroup/godcr/pull/351#issuecomment-486873105) is not as a result of trying to load a large number of transaction. Cannot confirm this as I have a small number of transactions on my system

I also noticed the app panicking during startup on a few occasions:
![image](https://user-images.githubusercontent.com/11990092/56806846-047eac80-6825-11e9-90d7-528ad3777a0a.png)
![image](https://user-images.githubusercontent.com/11990092/56807150-e06f9b00-6825-11e9-93b7-9dbaa9d52f11.png)
[fyne-26-4-data-race-err.txt](https://github.com/raedahgroup/godcr/files/3121273/fyne-26-4-data-race-err.txt)
This may not be related to this PR, but we need to note it down

2019-04-26 12:25 UTC, ademuanthony commented on app/walletcore/types.go
> +	"strings"
re-arrange import

2019-04-26 12:25 UTC, ademuanthony commented on fyne/pages/history.go
> +	page.transactionTable.AddRowSimple("Account", "Date", "Type", "Direction", "Amount", "Fee", "Status", "Hash")
align Amount and fee to the centre

2019-04-26 12:25 UTC, ademuanthony commented on fyne/pages/history.go
>  			dcrutil.Amount(tx.Amount).String(),
Align to the right

2019-04-26 12:25 UTC, ademuanthony commented on fyne/pages/history.go
>  			dcrutil.Amount(tx.Fee).String(),
Align to the right

2019-04-29 17:04 UTC, UMichael commented on fyne/pages/history.go
>  			dcrutil.Amount(tx.Fee).String(),
fixed

2019-04-29 17:04 UTC, UMichael commented on app/walletcore/types.go
> +	"strings"
fixed

2019-05-02 07:40 UTC, ademuanthony approved these changes

2019-05-03 04:21 UTC, raedah commented
Tested again, crashed, unusable.

2019-05-03 04:54 UTC, itswisdomagain requested changes
Why does this PR include changes to the http interface? See further required changes below:

2019-05-03 04:54 UTC, itswisdomagain commented on app/utils/utils.go
> +//func accountNameFromTransaction()
Please delete unwanted code.

2019-05-03 04:54 UTC, itswisdomagain commented on app/walletcore/types.go
> +func (txn *Transaction) AccountName() string {
See https://github.com/raedahgroup/godcr/pull/325/files#r280646122.

2019-05-03 04:54 UTC, itswisdomagain commented on fyne/pages/history.go
> +	// update main window after fetching recent activity
Comment needs to be updated.

2019-05-03 04:54 UTC, itswisdomagain commented on fyne/pages/history.go
> +	var err error
- Add an empty line space after `page.transactionTable.Clear()` to show some separation of concerns.
- No need to declare `err`, if you make `page.loadTransactionsError` to be of type error, then you can simply do `page.transactionCount, page.loadTransactionsError = page.wallet.TransactionCount(nil)` in the next line.

2019-05-03 04:54 UTC, itswisdomagain commented on fyne/pages/history.go
> +	loadTransactionsError  string
Should be `loadTransactionsError  error`

2019-05-03 04:54 UTC, itswisdomagain commented on fyne/pages/history.go
> +	txns, err := page.wallet.TransactionHistory(-1, int32(page.transactionCount), nil)
- Empty line space before this line 45.
- Offset should be 0, not -1.
- Use limit = 0 to load all transactions instead of `int32(page.transactionCount)`.
- Why are we loading all txs at once though? If we can't load more on scroll, then let's display history in pages. Compare how this is done in nuklear.
- Discussed with @raedah. In a bid to prevent the app crashing trying to load so many transactions, let's load only a few transactions per page and use previous/next buttons to load more on click. Ideally, we should implement a scroll listener to load more txs as the user scrolls but we can start with pagination buttons if fyne doesn't yet support scroll events.

2019-05-03 04:54 UTC, itswisdomagain commented on fyne/pages/history.go
> +	leftAlign := []int{3}
Empty line space before this line 50 please. If your code is all joined together, makes it difficult to read. Use single empty line spaces at appropriate points to show where a particular sub task ends and where another sub task starts.

2019-05-03 04:54 UTC, itswisdomagain commented on fyne/pages/history.go
> +	page.transactionTable.AddRowHeader("Account", "Date", "Type", "Direction", "Amount", "Fee", "Status", "Hash")
`Date` should be `Date (UTC)`. Compare https://user-images.githubusercontent.com/11990092/56841922-7dfbb680-6888-11e9-9ba5-0fea87f29c68.png

2019-05-03 04:54 UTC, itswisdomagain commented on fyne/pages/history.go
> +		page.transactionTable.AddRowWithButtonSupport(tx.Hash,
I see what you're trying to achieve here, really cool attempt, I must say.
A potentially smoother way to achieve this involves creating a new type `TableTextCell` that provides information about the alignment and click handlers for each cell (where necessary). The new type and how to use it can be found in [this gist](https://gist.github.com/itswisdomagain/d9e0c50dcba27342c14dd3ab81f769b6).

This for loop can now be re-written thus:
```
for _, tx := range txns {
	trimmedHash := tx.Hash[:len(tx.Hash)/2] + "..."
	hashClickFn := func() {
		// todo load tx details
	}

	page.transactionTable.AddRowWithTextCells(
		widgets.NewTableTextCell(tx.AccountName(), fyne.TextAlignLeading, fyne.TextStyle{}, nil),
		widgets.NewTableTextCell(tx.LongTime, fyne.TextAlignLeading, fyne.TextStyle{}, nil),
		widgets.NewTableTextCell(tx.Type, fyne.TextAlignLeading, fyne.TextStyle{}, nil),
		widgets.NewTableTextCell(tx.Direction.String(), fyne.TextAlignLeading, fyne.TextStyle{}, nil),
		widgets.NewTableTextCell(dcrutil.Amount(tx.Amount).String(), fyne.TextAlignTrailing, fyne.TextStyle{}, nil),
		widgets.NewTableTextCell(dcrutil.Amount(tx.Fee).String(), fyne.TextAlignTrailing, fyne.TextStyle{}, nil),
		widgets.NewTableTextCell(tx.Status, fyne.TextAlignLeading, fyne.TextStyle{}, nil),
		widgets.NewTableTextCell(trimmedHash, fyne.TextAlignLeading, fyne.TextStyle{}, hashClickFn),
	)
}
```

2019-05-03 04:54 UTC, itswisdomagain commented on fyne/pages/history.go
> +
The empty line spaces in lines 66 and 68 do not separate 1 sub task from another, they can be removed.

2019-05-03 04:54 UTC, itswisdomagain commented on fyne/pages/history.go
> +		var recentActivityObject fyne.CanvasObject
`recentActivityObject`?

2019-05-03 04:54 UTC, itswisdomagain commented on fyne/pages/history.go
> +		if page.loadTransactionsError != "" {
`page.loadTransactionsError != nil`

2019-05-03 04:54 UTC, itswisdomagain commented on fyne/pages/history.go
> +			recentActivityObject = widget.NewLabel(fmt.Sprintf("Error History: %s", page.loadTransactionsError))
`Error loading wallet history: %s`

2019-05-03 04:54 UTC, itswisdomagain commented on fyne/pages/history.go
> +		updatePageOnMainWindow(pageViews)
Can use `recentActivityObject` directly, don't see a need for a view box with vertical orientation holding an empty space at the top and the actual content; no need for the space.

2019-05-03 04:54 UTC, itswisdomagain commented on fyne/widgets/table.go
> +
Empty space at lines 30 and 32 not needed.

2019-05-03 04:54 UTC, itswisdomagain commented on fyne/widgets/table.go
> +func (table *Table) AddRowHeader(texts ...string) {
`headerTexts` instead of `texts`

2019-05-03 04:54 UTC, itswisdomagain commented on fyne/widgets/table.go
> +func (table *Table) AddRowSimple(LeftAlign []int, texts ...string) {
- Empty line space between both functions.
- `AddRowSimple` should no longer need to take a `LeftAlign []int` parameter, can remain the way it was.
- To set text align on some cells, use `AddRowWithTextCells`

2019-05-03 04:54 UTC, itswisdomagain commented on fyne/widgets/table.go
> +func (table *Table) AddRowWithButtonSupport(hash string, buttonColumn int, leftAlign []int, texts ...string) {
We shouldn't need this anymore. Use `AddRowWithTextCells` instead.

2019-05-03 04:54 UTC, itswisdomagain commented on web/static/app/src/css/style.scss
> +.confirmed-status span {
Why are these added in your PR? Did you work on the http interface?

2019-05-06 12:36 UTC, closed without merging