Cli history command navigation
raedahgroup/godcr-old pull request #356
Opened 2019-04-29 14:15 UTC by Sirmorrison

Added next, previous navigation to cli history command.

2019-04-30 03:40 UTC, ademuanthony requested changes

2019-04-30 03:40 UTC, ademuanthony commented on cli/commands/show-transaction.go
> +		validateUserInput := func(userInput string) error {
```
validateUserInput := func(userInput string) error {
     if strings.EqualFold(userInput, "q") || strings.EqualFold(userInput, "h"){
        return nil
    }
    return fmt.Errorf("invalid response, try again")
}
```

2019-04-30 03:40 UTC, ademuanthony commented on nuklear/pagehandlers/transaction_details.go
> +	"fmt"
re-arrange import

2019-04-30 03:40 UTC, ademuanthony commented on cli/commands/show-transaction.go
> +		err = HistoryCommand{}.Run( ctx, wallet)
let us pass the `txHistoryOffset` here and update the `Run` so that the history page will return to the previous state

2019-04-30 03:40 UTC, ademuanthony commented on cli/commands/history.go
> +		} else if strings.EqualFold(userChoice, "n") {
update the comment on line 137, change the `m` to `n`

2019-04-30 03:40 UTC, ademuanthony commented on cli/commands/history.go
>  	var txHistoryOffset = 0
A `txHistoryOffset` field should be added to the `HistoryCommand` struct in line 17 and `ShowTransactionCommandArgs` on line 20 of `show-transaction.go` so that the user can be returned to the previous state of the history page before navigating to the details page.
Line 38 should now use `h.txHistoryOffset` and this value should be passed in `ShowTransactionCommandArgs` on line 142

2019-04-30 22:58 UTC, Sirmorrison commented on cli/commands/show-transaction.go
> +		validateUserInput := func(userInput string) error {
`  return fmt.Errorf("invalid response, try again")`

line 87 takes care of this.

2019-05-01 01:26 UTC, raedah commented
These screenshots dont look good with the hash wrapping.

2019-05-01 16:14 UTC, ademuanthony requested changes

2019-05-01 16:14 UTC, ademuanthony commented on cli/commands/history.go
> +	TxHistoryOffset   int
`int32`

2019-05-01 16:14 UTC, ademuanthony commented on cli/commands/history.go
> +		transactions, err := wallet.TransactionHistory(int32(h.TxHistoryOffset), txPerPage, nil)
Use `int32` on line 19 so that you won't have to do type conversion here

2019-05-01 16:14 UTC, ademuanthony commented on cli/commands/history.go
> +			h.TxHistoryOffset -= int(txPerPage)
Use `int32 ` on line 19 so that you won't have to do type conversion here

2019-05-01 16:14 UTC, ademuanthony commented on cli/commands/show-transaction.go
> +	TxHistoryOffset   int
`int32`

2019-05-02 19:03 UTC, ademuanthony approved these changes

2019-05-03 04:59 UTC, itswisdomagain requested changes
- @Sirmorrison is https://github.com/raedahgroup/godcr/pull/356#issuecomment-488170495 addressed?
- Update your screenshot for first page, it's the same screenshot used for middle page.

I'll review again and test after these changes and questions are addressed.

2019-05-03 04:59 UTC, itswisdomagain commented on cli/commands/history.go
> +	var lastTX int
- `lastTx` instead of `lastTX`
- tx is not an int, do you need to rename this variable?

2019-05-03 04:59 UTC, itswisdomagain commented on cli/commands/history.go
> +	DisplayedTxHashes []string
These properties do not need to be public.

2019-05-03 04:59 UTC, itswisdomagain commented on cli/commands/history.go
> +		transactions, err := wallet.TransactionHistory(h.TxHistoryOffset, txPerPage, nil)
Rename `h` to `history` please.

2019-05-06 19:48 UTC, itswisdomagain submitted a review, later dismissed
First page is asking to enter `p` to show previous page:
<img width="598" alt="Screenshot 2019-05-06 at 8 42 57 PM" src="https://user-images.githubusercontent.com/18400051/57250565-a7160700-703f-11e9-8f2e-25c1ab8d1b21.png">

Too much space after hitting quit:
<img width="512" alt="Screenshot 2019-05-06 at 8 46 36 PM" src="https://user-images.githubusercontent.com/18400051/57250779-24417c00-7040-11e9-9866-5e8025b60fa4.png">

2019-05-06 19:48 UTC, itswisdomagain commented on cli/commands/history.go
> +		lastTx = len(transactions)
Do you mean `fetchedTxCount` or `totalFetchedTxs`? `lastTx` should be a `tx` (type `walletcore.Transaction`), not a number (type `int`).


UPDATE: After seeing more of your code, I think `previousPageTxCount` is more appropriate?

2019-05-06 19:48 UTC, itswisdomagain commented on cli/commands/show-transaction.go
> +		prompt := fmt.Sprintf("Enter (h)istory table, or (q)uit")
Do we need to show this prompt if a user gets here by running `godcr show-transaction abcdefghash`?
If we don't, then you can check if `len(showTxCommand.displayedTxHashes) > 0` to know when a user gets here from the history command.

2019-05-06 19:48 UTC, itswisdomagain commented on cli/commands/show-transaction.go
> +	displayedTxHashes []string
Add `txHistoryOffset` and `displayedTxHashes` to the `ShowTransactionCommand` struct, they are not command arguments.

2019-05-06 20:09 UTC, Sirmorrison commented
> 
> 
> First page is asking to enter `p` to show previous page:
> <img alt="Screenshot 2019-05-06 at 8 42 57 PM" width="598" src="https://user-images.githubusercontent.com/18400051/57250565-a7160700-703f-11e9-8f2e-25c1ab8d1b21.png">
> 
> Too much space after hitting quit:
> <img alt="Screenshot 2019-05-06 at 8 46 36 PM" width="512" src="https://user-images.githubusercontent.com/18400051/57250779-24417c00-7040-11e9-9866-5e8025b60fa4.png">

im not sure the code you re testing but this is my out put
![image](https://user-images.githubusercontent.com/27733432/57252073-3bce3400-7043-11e9-9c85-55b867a0ff73.png)

2019-05-06 20:12 UTC, itswisdomagain commented
@Sirmorrison, I get the previous page prompt on the first page when there's just one page of data to load. Temporarily increase your `txPerPage` number so that your app loads all txs in page 1 - you'll get the issue.

2019-05-07 18:57 UTC, UMichael commented
![image](https://user-images.githubusercontent.com/31141573/57325557-2f5ce080-7102-11e9-95d0-110cf3956202.png)
text overlaps on large string

2019-05-09 09:13 UTC, Sirmorrison commented
> 
> 
> ![image](https://user-images.githubusercontent.com/31141573/57325557-2f5ce080-7102-11e9-95d0-110cf3956202.png)
> text overlaps on large string in amount column

fixed please test and give feed back please

2019-05-13 18:27 UTC, merged