Bundle assets/resource file in go binary
raedahgroup/godcr-old pull request #357
Opened 2019-04-30 12:13 UTC by ademuanthony

Fixes #346 
This PR adds the ability to build the go binaries with the web files included, so it can be distributed as a single binary. 
A `godcr.sh` is added to the root of the project with the following commands
`./godcr.sh build` which simply runs `go build`
`./godcr.sh build-web` which change to the src directory of the web, builds the front-end and returns to the root directory and 
`./godcr.sh deploy` which fetches the `go mod` dependencies, builds the web assets and bundle it all as a single binary file

![image](https://user-images.githubusercontent.com/11990092/56960739-b7af1480-6b49-11e9-8c02-c49c2d814115.png)

2019-05-01 21:03 UTC, raedah commented
I tested it and was able to get it to build. The CSS didnt load correctly for me. I will try again later to see if anything was missed in the build process.

2019-05-03 05:16 UTC, itswisdomagain requested changes
I got a `bash: ./build.sh: Permission denied`. Need to make the file executable by running `chmod +x ./build.sh` (should work on linux) then pushing the file with the updated permissions.

2019-05-03 05:16 UTC, itswisdomagain commented on .gitignore
> +web/static/dist/js/2.bundle.js.map
Could just ignore `web/static/dist/js/*.bundle.js` and `web/static/dist/js/*.bundle.js.map`

2019-05-03 05:16 UTC, itswisdomagain commented on README.md
>  However, to use dcrwallet instead of dcrlibwallet for wallet operations, you'll need a running dcrwallet daemon.
Remove `However`.

2019-05-03 05:16 UTC, itswisdomagain commented on README.md
> +You can also build the http frontend by running `./build.sh web`
There shouldn't be 2 sections on the readme for "building the http frontend", move necessary information here to the section above.

2019-05-03 05:16 UTC, itswisdomagain commented on web/server.go
> +	makeStaticFileServer(router, "/dist", packr.NewBox("./static/dist"))
Can we retain `static`? Or use `public`. `dist` is a developers' term.

2019-05-03 05:16 UTC, itswisdomagain commented on build.sh
> +function buildFe {
`buildFrontEnd`

2019-05-03 05:16 UTC, itswisdomagain commented on build.sh
> +function buildBe {
- `buildBackEnd`
- Space between functions

2019-05-03 05:16 UTC, itswisdomagain commented on build.sh
> +elif [[ "$ACTION" = "web" ]]; then
- This can be simplified to `if action web, then build, else, deploy`. No need for an elseif.
- Is there a scenario where someone will want to run `go build` and `yarn build` without running `packr build`?

2019-05-03 05:25 UTC, itswisdomagain requested changes
I was able to run `./build.sh` successfully and launch the http server, but it seems javascript controllers are not loaded yet. Noticed it especially in the send page. Also the font size is bigger than it used to be. I'm thinking the yarn built files are not being packed by packr.

2019-05-03 05:25 UTC, itswisdomagain commented on README.md
> +* You will also need `packr`. Run `go get github.com/gobuffalo/packr` to get it
`go get -u github.com/gobuffalo/packr/packr`

2019-05-03 05:25 UTC, itswisdomagain commented on web/routes/routes.go
> +		parsedTemplate, err = parsedTemplate.Parse(viewBox.String(layout))
`viewBox.String` deprecated, use `viewBox.FindString` instead.

2019-06-08 05:48 UTC, Jujhar commented
Testing on a linux machine. 

This does not work natively without any parameters (./build.sh) nor with deploy parameter both result to "line 23 packr command not found" even after installing packr via documentation ('go get -u github.com/gobuffalo/packr/packr')

`deploy web` seems to work fine and produce a binary around 35 mb that which can serve assets.

Also note to make into executable if possible and push it back (_chmod +x_)

2019-09-19 09:09 UTC, itswisdomagain requested changes
In addition to the below, we want to keep `web/static/app/yarn.lock` and I expect we'd gitignore the `web/static/dist` folder since it is autogenerated by `yarn build`.

2019-09-19 09:09 UTC, itswisdomagain commented on README.md
> +* You will also need `packr`. Run `go get -u github.com/gobuffalo/packr/v2/packr2` to get it.
You will also need `packr2`

2019-09-19 09:09 UTC, itswisdomagain commented on README.md
> +Note: You use bit bash to run shell commands on windows
```suggestion
Note: Use git bash to run shell commands on windows.
```

2019-09-19 09:09 UTC, itswisdomagain commented on README.md
>  * To run the http interface (`godcr-web`), you'd need to also build the frontend assets:
Need to build and pack the frontend assets. Add bash code for packing the assets.

2019-09-19 09:09 UTC, itswisdomagain commented on web/go.mod
> +	github.com/gobuffalo/packr v1.30.1
Need to `go mod tidy` on this sub-directory. I expect `packr` v1 is no longer used?

2019-09-19 09:09 UTC, itswisdomagain commented on build.sh
> +if [[ "$ACTION" = "web" ]]; then
I'm thinking the arguments can be the interface, and this script modified to enable building for different interfaces. Don't see anything special that `deploy` does, looks just like build to me.

Here's an idea I had for fyne:
```
function buildFyne() {
    echo "packing assets with packr2"
    (cd fyne && packr2)
    echo "building with go build"
    go build ./cmd/godcr-fyne
}

if [[ "$1" = "fyne" ]]; then
    buildFyne
else
    echo "Usage: ./build.sh {interface} e.g. ./build.sh fyne"
fi
```

Could add similar function for building the web interface.

2019-09-19 09:09 UTC, itswisdomagain commented on web/routes/routes.go
> +			fmt.Println(template)
Is this necessary?

2019-09-19 09:09 UTC, itswisdomagain commented on web/routes/routes.go
> +		parsedTemplate, _ = parsedTemplate.Parse(viewContentFunc(utils))
Add comments preceding each of these `Parse` calls.

2019-09-19 09:09 UTC, itswisdomagain commented on web/routes/templates.go
>  func templates() []templateData {
Could just become a string slice, since the map keys and values are the same.

2019-09-19 09:09 UTC, itswisdomagain commented on web/static/app/src/utils.js
> +  import(/* webpackChunkName: "toastr" */ 'toastr').then(({ default: toastr }) => {
These and related changes seem to do with it reducing the bundle size rather than bundling assets. Changes not relating to bundling http assets should go into a different PR.

2019-09-19 13:39 UTC, ademuanthony commented on README.md
>  * To run the http interface (`godcr-web`), you'd need to also build the frontend assets:
`build.sh web` does the packing already

2019-09-19 21:56 UTC, itswisdomagain requested changes
Please restore `web/static/app/yarn.lock`

2019-09-19 21:56 UTC, itswisdomagain commented on build.sh
> +    cd ../ && go build ./cmd/godcr-nuklear
Aside fyne, every other interface will need to `cd ./cmd/godcr-{interface} && go build`.

2019-09-19 21:56 UTC, itswisdomagain commented on README.md
>  `cd ./web/static/app && yarn install && yarn build`.
Will this be sufficient to run the http interface? Isn't running `packr2` necessary?

2019-09-19 21:56 UTC, itswisdomagain commented on README.md
> +Note: Use git bash to run shell commands on windows
Add a period at the end of this sentence.

2019-09-19 21:56 UTC, itswisdomagain commented on README.md
>  * To run the http interface (`godcr-web`), you'd need to also build the frontend assets:
I suppose you'll need to build and pack the frontend assets first **before** building `godcr-web`?

2019-09-19 21:56 UTC, itswisdomagain commented on web/routes/routes.go
> +	viewContentFunc := func(template string) string {
`viewContentFunc` -> `extractTemplateText`, so that `parsedTemplate.Parse(viewContentFunc(tmpl))` becomes `parsedTemplate.Parse(extractTemplateText(tmpl))`

2019-09-19 21:57 UTC, ademuanthony commented on README.md
>  `cd ./web/static/app && yarn install && yarn build`.
yes

2019-09-19 22:09 UTC, ademuanthony commented on README.md
>  * To run the http interface (`godcr-web`), you'd need to also build the frontend assets:
this comment is actually for someone that is trying to run this interface directly without bundling it first

2019-09-20 07:46 UTC, itswisdomagain requested changes

2019-09-20 07:46 UTC, itswisdomagain commented on .gitignore
> +*-packr.go
I think this renders the gitignore in line 8 unnecessary. Should also consider adding `packrd/` and removing line 9.

2019-09-20 07:46 UTC, itswisdomagain commented on web/go.mod
> +	go.etcd.io/bbolt v1.3.3 // indirect
This is causing build problems. I suppose the other indirect imports are also unnecessary.
Replace the contents of this file with what we have on master (https://github.com/raedahgroup/godcr/blob/master/web/go.mod). Then `cd ./web and go mod tidy`.

2019-09-20 07:46 UTC, itswisdomagain commented on go.sum
> -github.com/armon/consul-api v0.0.0-20180202201655-eb2c6b5be1b6/go.mod h1:grANhF5doyWs3UAsr3K4I6qtAmlQcZDesFNEHPZAzj8=
I'm also concerned about the modifications to this file. Please revert to what we have on master: https://github.com/raedahgroup/godcr/blob/master/go.sum

2019-09-20 08:13 UTC, itswisdomagain requested changes

2019-09-20 08:13 UTC, itswisdomagain commented on README.md
> +* To build the distributable bundle, run `./build.sh {interface}` e.g. `./build.sh web` from the root directory.
This appears to general to all interfaces, it should be separated with empty line spaces from the previous section which is strictly for the web interface. Also, this should read `To build the distributable bundle for any interface, run...`

2019-09-20 09:31 UTC, itswisdomagain approved these changes

2019-09-20 09:31 UTC, merged