Replace promptui with stdlib package functions.
raedahgroup/godcr-old pull request #36
Opened 2018-11-13 15:26 UTC by barisere

Fixes #34

2018-11-13 21:30 UTC, itswisdomagain requested changes
Preliminary review. I'll share more thoughts in a bit

2018-11-13 21:30 UTC, itswisdomagain commented on cli/cli.go
>  func (c *CLI) RunCommand(commandArgs []string) {
Nice work for adding comments for these public functions 👍

2018-11-13 21:30 UTC, itswisdomagain commented on cli/prompter.go
> +func (p promptOption) Prompt() (string, error) {
This doesn't make semantic sense, having an action `Prompt()` in an `Option` type. Might be more meaningful to make this function extend `prompter` instead.

2018-11-13 21:30 UTC, itswisdomagain commented on cli/prompter.go
> +		if vErr := p.Validate(input); vErr != nil {
I'm thinking you can reuse the `err` variable declared earlier here, no need to create another variable...

2018-11-13 21:30 UTC, itswisdomagain commented on cli/prompter.go
> +	for _, opt := range p.Options {
Adding a single space before this for loop makes this code a little more readable

2018-11-13 22:21 UTC, itswisdomagain requested changes

2018-11-13 22:21 UTC, itswisdomagain commented on cli/helpers.go
> +	validateInt := func(v string) error {
the validate function above is not complete, and you're not only validating if the input is an integer, you also should check if the int falls within the range of 0 to `len(accounts) - 1`.

2018-11-13 22:21 UTC, itswisdomagain commented on cli/helpers.go
> +		promptItems.Options = append(promptItems.Options, fmt.Sprintf("%3d. %s (%s)",
Please use a separate variable to hold these options and then assign to promptItems same way you did for the validate function above. Makes the code more readable

2018-11-13 22:21 UTC, itswisdomagain commented on cli/helpers.go
>  	if err != nil {
notice a partial repetition of the earlier validate command here. I want to recommend performing validation outside the `prompter.Prompt()` function

Read the input without validating and then validate here. Same thing for other places you need to call `Prompt()`. It'll make more sense to someone reading your code why you're performing the validation when you validate **after** receiving the input

More so, if you validate here, you'd be able to repeat the prompt if the user's input is invalid which is an important requirement (compare the comment on issue #10)

2018-11-13 22:28 UTC, itswisdomagain commented
Nice job @barisere. The code works almost as expected (the only missing requirement is repeating the prompt if a user provides a wrong input)

That said, I believe the code can be easier to interprete if you abstract just a little bit less and don't attempt to plan for features we may never need or scenarios we may never accomplish. I'm sure you know about the [YAGNI principle](https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it)?

Here are some suggestions to improve the code quality. Doing these should take care of most if not all of the review comments I dropped earlier.

- rename `prompter` to `terminal-prompter` or something more descriptive (using descriptive names for files, variables, structs, interfaces, packages etc makes your code a lot more easier to understand)
- remove `Prompt()` function and replace with the following 3 functions (we can add more as the need arises, we don't want to plan for what we may never need)
- first function: `terminalPrompt.RequestInput(message, validateFn)`, displays message, waits for input and validates using the validateFn, if input fails validation, tell user the input was invalid (and why) then repeat prompt
- second function: `terminalPrompt.RequestInput(message, validateFn)`, much like the first function, except it masks the user's input
- third function: `terminalPrompt.RequestSelection(message, options, validateFn)`, display the message, then the options, and wait for input. Before running the provided validate function, first check if the user's selection is within the range of the options provided, if not, show an error message and run prompt again, else, run the validate function

2018-11-14 13:41 UTC, barisere commented
@itswisdomagain I've applied your suggestions. New commits added.

2018-11-14 13:51 UTC, barisere commented
![Current behaviour (with the send command) uses ordinal values to select options](https://user-images.githubusercontent.com/20553476/48486278-599ca800-e81b-11e8-9ec3-7fefb2bc8cb6.png)

Previous behaviour (with the send command) uses arrow navigation to select options.
![Previous behaviour](https://user-images.githubusercontent.com/20553476/48486362-99638f80-e81b-11e8-8505-8bc6d35fc713.png)
![Previous behaviour](https://user-images.githubusercontent.com/20553476/48486740-af258480-e81c-11e8-9f35-0ce22b6e688f.png)

2018-11-14 14:18 UTC, itswisdomagain commented
This looks like good work! See some thoughts below, I haven't looked at the code though. Will do so and leave more thoughts where appropriate
> ![Current behaviour](https://user-images.githubusercontent.com/20553476/48486278-599ca800-e81b-11e8-9ec3-7fefb2bc8cb6.png)

The spacing between the prompt `"Select source account"` and the options seems to suggest a disconnect for me. Look at the previous implementation, you'd notice the prompt message, instruction and the options all form a "paragraph", with no empty line between any of them. 

Whitespaces are generally used to indicate the end of a section and start of another not very related section. If they're not related at all, then the space is bigger, if there's some relationship but not very big, then a single space or no space will do. If they're very related, no need for white space.

I believe the only spacing that would make visual sense is the one after showing an error message, which does not currently exist in your implementation. The prompt message, options, user selection and any error arising from the user's input should be close together

2018-11-14 14:53 UTC, itswisdomagain requested changes
Good improvements made. Just noticed our objective for this PR hasn't really even been met, so you should give attention to that

2018-11-14 14:53 UTC, itswisdomagain commented on cli/helpers.go
> +
why the space though?

2018-11-14 14:53 UTC, itswisdomagain commented on cli/helpers.go
same space here, there are not so many imports, I think doing away with the empty line spacing won't harm readability

2018-11-14 14:53 UTC, itswisdomagain commented on cli/helpers.go
> +			return fmt.Errorf("could not recognize input: not an allowed option")
This error message could be more informative. I'm thinking: `Invalid selection. Please enter a number between 1 and N`

2018-11-14 14:53 UTC, itswisdomagain commented on cli/helpers.go
> +			return fmt.Errorf("%d is not an allowed option", choice)
Same message above would work here as well

2018-11-14 14:53 UTC, itswisdomagain commented on cli/helpers.go
> +	accountItems := map[int]uint32{}
This is a map of account numbers. Wouldn't a more descriptive variable name be `accountNumbers`? When I first saw it, I first thought to my self, what are account items? Do accounts have items? Or is this a map of accountItem objects? Had to defer to your usage of the variable below to determine its purpose

2018-11-14 14:53 UTC, itswisdomagain commented on cli/helpers.go
> +	for idx, v := range accounts {
Forgive my obsession with variable naming, but while you're here, can you use `for index, account : range accounts`? Helps almost anyone familiar with programming generally instantly have an idea of what you're doing

2018-11-14 14:53 UTC, itswisdomagain commented on cli/helpers.go
> +	for idx, v := range accounts {
Or `i` instead of `index`/`idx`

2018-11-14 14:53 UTC, itswisdomagain commented on cli/helpers.go
> +	validateInput := func(value string) error {
We could call this function, `validateAccountSelectionInput` instead

2018-11-14 14:53 UTC, itswisdomagain commented on cli/helpers.go
> +		if choice, err = strconv.Atoi(value); err != nil {
and rename `choice` to `selection`

2018-11-14 14:53 UTC, itswisdomagain commented on cli/helpers.go
> +	validateInput := func(value string) error {
and while at it, we could use `input` instead of `value` as the name of the parameter to the function

2018-11-14 14:53 UTC, itswisdomagain commented on cli/helpers.go
> +	var result string
this declaration is unnecessary

2018-11-14 14:53 UTC, itswisdomagain commented on cli/helpers.go
> +	emptyValidator := func(v string) error {
Instead of having to create an empty validator, why not pass nil to the `terminalprompt.RequestInputSecure` function and in the function's handler, check if the validateFn is nil before attempting to call it

2018-11-14 14:53 UTC, itswisdomagain commented on cli/helpers.go
> +	emptyValidator := func(v string) error {
Or you could create a public `EmptyValidator` function in `terminalprompt` and whenever you don't need to perform custom validation, you call that function. All the function does could be to check if the input is not null/empty.  But please don't space trim inputs. "  " (double spaces) may be a valid input in some scenarios

2018-11-14 14:53 UTC, itswisdomagain commented on cli/terminalprompt/terminalprompt.go
> +	"golang.org/x/crypto/ssh/terminal"
Surprised I'm just seeing this. The aim of this PR effort is to remove external dependencies for the use cases we have here. Adding this new dependency invalidates our efforts

2018-11-14 21:44 UTC, barisere commented
I've made changes to reflect your suggestions. Please take a look.

2018-11-17 06:58 UTC, itswisdomagain requested changes
Much better, seeing as everything now works with standard libraries. There's a key concern though. Trying to cancel the send command before it gets to the wallet passphrase stage doesn't cancel. The fix to this is mentioned in one of the comments. While at it, give attention to the other matters.

2018-11-17 06:58 UTC, itswisdomagain commented on cli/helpers.go
> +	accountNumbers := map[int]uint32{}
`accountNumbers` is redundant and unnecessary. You can always use `accounts[selection].AccountNumber` to get account number after selection

2018-11-17 06:58 UTC, itswisdomagain commented on cli/helpers.go
> +		errWrongInput := fmt.Errorf("Error: input must be between %d and %d", minAllowed, maxAllowed)
What if `len(accounts) == 1`? The error message would read: `"Error: input must be between 1 and 1"`. Not exactly grammatically correct.

@raedah suggested proceeding with the default account if there's no other account. In line with that, if `len(accounts) == 1` , this `getSendSourceAccount` function should return `accounts[0]. AccountNumber`

2018-11-17 06:58 UTC, itswisdomagain commented on cli/terminalprompt/getinput.go
> +	text, err := reader.ReadString('\n')
This can be replaced with the `ReadLine` function of bufio reader:
`inputBytes, _, err := reader.ReadLine()`

Then your return statement can convert the bytes to string without needing to trim:
`return string(inputBytes), nil`

2018-11-17 06:58 UTC, itswisdomagain commented on cli/terminalprompt/getinput.go
> +	text, err := reader.ReadString('\n')
I'm thinking that doing this will render the `skipEOFError` function in `terminalprompt.go` obsolete? If so, that function should go. I really don't see it's use case but will appreciate some enlightenment if it's useful

2018-11-17 06:58 UTC, itswisdomagain commented on cli/cli.go
> +		// finished their clean up.
if we don't exit here and the current process does not capture SIGINT and exits, then the program keeps running even after user tries to terminate

I understand the issue this present. For now, let's take off this SIGINT listener, as it doesn't perform any cleanup work. The implication is that if a user attempts to cancel and there is no SIGINT listener, the program will simply exit. If there is a SIGINT listener like we have in `getPasswordInput`, then that listener has to exit the process manually, which it does currently.

Capturing SIGINT without exiting will only keep the program running if there is no other SIGINT listener that exits the program. To reproduce this error, run `dcrcli send` and ^C before getting to the part where it asks for wallet passphrase

2018-11-17 06:58 UTC, itswisdomagain commented on cli/cli.go
> +		// finished their clean up.
While testing this, also remove the SIGINT listener in `getPasswordInput` and confirm if it's even needed. Testing on a Mac terminal works fine without the listener - the terminal's echo setting is automatically restored. If we can confirm this behaviour across windows cmd prompt and linux terminal, we can safely take this out. Until then, having the listener in that function is fine.

2018-11-17 06:58 UTC, itswisdomagain commented on cli/terminalprompt/terminalprompt.go
> +func skipEOFError(value string, err error) (string, error) {
Reconfirm the necessity of this function. I think the program works fine without it. More so when you use `reader.ReadLine` to get user input as pointed out in an earlier comment

2018-11-17 06:58 UTC, itswisdomagain commented on cli/terminalprompt/terminalprompt.go
> +	var label = message + "\n"
label may make more sense as `prompt` or `promptMessage`

2018-11-17 06:58 UTC, itswisdomagain commented on cli/terminalprompt/getinput.go
> +	fmt.Println()
Introducing a new line after reading user input may not be best for displaying messages directly related to the user input, such as validation error messages.

Compare the 2 screenshots below, the first has an empty line space after reading input, the second does not. Do you agree that the error message sitting closer to the user input, makes the error message easier to understand? Especially if the user were to get distracted from his terminal and comes back to see the error message.

![screenshot 2018-11-17 at 7 09 27 am](https://user-images.githubusercontent.com/18400051/48657882-942f5c00-ea38-11e8-8241-d9cac43130b1.png)
![screenshot 2018-11-17 at 7 08 37 am](https://user-images.githubusercontent.com/18400051/48657871-461a5880-ea38-11e8-8a4f-6c0da42aa6f2.png)

If you agree, then take off `fmt.Println()` and use it only where appropriate such as **after** reading a valid input and before prompting for the next information

2018-11-17 06:58 UTC, itswisdomagain commented on cli/terminalprompt/getinput.go
>  	text, err := reader.ReadString('\n')
This can also be replaced with `ReadLine`

2018-11-17 09:35 UTC, barisere commented on cli/terminalprompt/getinput.go
> +	text, err := reader.ReadString('\n')
> I'm thinking that doing this will render the `skipEOFError` function in `terminalprompt.go` obsolete? If so, that function should go. I really don't see it's use case but will appreciate some enlightenment if it's useful

`skipEOFError` will remain necessary, because the underlying function is `ReadSlice` which returns `EOF` if it encounters it.
`EOF` is returned if the user enters `Ctrl+D` (on Linux). That should be treated equivalent to pressing `Enter` (it means the user is done entering data).

2018-11-17 09:46 UTC, barisere commented on cli/terminalprompt/getinput.go
> +	text, err := reader.ReadString('\n')
> This can be replaced with the `ReadLine` function of bufio reader:
> `inputBytes, _, err := reader.ReadLine()`
> 
> Then your return statement can convert the bytes to string without needing to trim:
> `return string(inputBytes), nil`

I'm wary of the second return value from `ReadLine`. If it's set, it means that there was a `bufio.ErrBufferFull` error, and you should retry for the next fragment of the line. If we are expecting long inputs that can fill the input buffer, and would like to continue until the rest of the line is read, then `ReadLine` is okay. But I think that is not the case. In fact, `ReadString` may be just okay here.

2018-11-17 09:55 UTC, barisere commented on cli/terminalprompt/terminalprompt.go
> +func skipEOFError(value string, err error) (string, error) {
See my reply here: https://github.com/raedahgroup/dcrcli/pull/36#discussion_r234402626

2018-11-17 10:01 UTC, barisere commented on cli/terminalprompt/getinput.go
>  	text, err := reader.ReadString('\n')
See https://github.com/raedahgroup/dcrcli/pull/36#discussion_r234402626

2018-11-17 10:20 UTC, barisere commented on cli/cli.go
> +		// finished their clean up.
On Linux my terminal setting was not restored when I removed the SIGINT listener.

2018-11-17 20:50 UTC, itswisdomagain commented on cli/terminalprompt/getinput.go
> +	text, err := reader.ReadString('\n')
That's fine then

2018-11-17 20:51 UTC, itswisdomagain commented on cli/cli.go
> +		// finished their clean up.
I figured!

2018-11-17 21:08 UTC, itswisdomagain approved these changes

2018-11-17 21:09 UTC, merged