Refactor fyne
raedahgroup/godcr-old pull request #360
Opened 2019-05-02 16:33 UTC by codemaestro64

This refactors code on the fyne interface. It improves performance, and simplifies code for adding other pages to the interface. 

It adds the following pages to the main UI. 

- Sync Page 
- Transaction Details Page

It also fixes the crash issue on fyne stated in #324. 

It should be noted that, the fyne library does not currently support scrolling.

![Screenshot from 2019-05-02 17-10-18](https://user-images.githubusercontent.com/42093751/57091114-57160800-6d00-11e9-8430-b56805c1e406.png)
![Screenshot from 2019-05-02 17-10-32](https://user-images.githubusercontent.com/42093751/57091116-57ae9e80-6d00-11e9-987f-38c2e149672f.png)
![Screenshot from 2019-05-02 17-11-12](https://user-images.githubusercontent.com/42093751/57091118-57ae9e80-6d00-11e9-9504-a9af5053ce17.png)

2019-05-02 21:52 UTC, ademuanthony requested changes
The overview page is randomly rendered automatically from the other pages. Since this PR is refactoring the interface, I think this issue should also be addressed here.

2019-05-02 21:52 UTC, ademuanthony commented on fyne/pages/transaction_details.go
> +
this empty line can be deleted

2019-05-09 10:39 UTC, codemaestro64 commented
> The overview page is randomly rendered automatically from the other pages. Since this PR is refactoring the interface, I think this issue should also be addressed here.

Other than rendering the Overview page from the sync page (which is intended), i don't experience this

2019-05-17 07:41 UTC, itswisdomagain commented
#### Window content does not auto-resize to fill available window space when window is resized.
Look closely enough, you'll see the initial window size having a slightly different background.
<img width="1392" alt="Screenshot 2019-05-17 at 8 11 23 AM" src="https://user-images.githubusercontent.com/18400051/57909706-758d0f00-787b-11e9-89b5-73541b208981.png">

#### Re @ademuanthony's comment:
> The overview page is randomly rendered automatically from the other pages. Since this PR is refactoring the interface, I think this issue should also be addressed here.

You can reproduce the issue by starting the app, waiting for sync to complete and the overview page to be loaded, then switch to any other page, turn off your internet for a while (will cause the wallet to lose connection to peers), turn your internet back on (will re-connect to peers, which will re-trigger the sync callbacks and cause the syncCompleted method to be re-called). It's when this method is recalled, that the window "resets" to the overview page. I believe this to also be the cause of #358.

#### Overview page -> Recent activity table -> Hash not properly aligned vertically.
<img width="908" alt="Screenshot 2019-05-17 at 8 18 42 AM" src="https://user-images.githubusercontent.com/18400051/57910183-8c803100-787c-11e9-8e49-5ceb4f134772.png">

2019-08-02 22:25 UTC, closed without merging