Fyne refactored code base
raedahgroup/godcr-old pull request #365
Opened 2019-05-09 07:19 UTC by UMichael

![image](https://user-images.githubusercontent.com/31141573/57434262-84980f80-7232-11e9-9b7f-0ea5c2e43416.png)
 added theme preference in settings

![image](https://user-images.githubusercontent.com/31141573/57434494-0851fc00-7233-11e9-9572-b916e18061ae.png)
added overview page

![image](https://user-images.githubusercontent.com/31141573/57434536-1c95f900-7233-11e9-97bc-8d5ff1717ad9.png)
added history page with pagination support

fixed all issues below
#358 , #324 #277 #272

2019-05-17 08:07 UTC, itswisdomagain commented
#### Initial windows size is quite small
Also, the nav menu black text should be white font color in this theme.
<img width="565" alt="Screenshot 2019-05-17 at 8 48 54 AM" src="https://user-images.githubusercontent.com/18400051/57912592-9ad14b80-7882-11e9-87f8-2dd0efb04cb2.png">

#### Peer count on sync window and nav menu do not update simultaneously.
<img width="1392" alt="Screenshot 2019-05-17 at 8 50 14 AM" src="https://user-images.githubusercontent.com/18400051/57912695-e84db880-7882-11e9-9f85-4a8581efcb72.png">

#### Peer count on nav menu is temporarily invisible(?) when you switch to a page
<img width="1392" alt="Screenshot 2019-05-17 at 8 56 26 AM" src="https://user-images.githubusercontent.com/18400051/57912738-04515a00-7883-11e9-966d-41eca22ae2fc.png">

2019-05-17 11:21 UTC, itswisdomagain requested changes
These are required changes for now.

Also, 
- Window should have a set minimum size, the initial window size on page load is too small.
- Windows can no longer be resized beyond a the minimum size required to display a page's content. This means that the minimum window size for the history page for example is quite big. User should be able to resize even further.

2019-05-17 11:21 UTC, itswisdomagain commented on fyne/fyne.go
> +	window.SetContent(pages.Menu(pages.ShowSyncWindow(walletMiddleware, window, fyneApp), window, fyneApp))
Can we
- create the nav menu views once (in this `LaunchFyne` function)
- set the window content once (in this `LaunchFyne` function)

Changing between pages should not need to re-create the nav menu or change the entire window content; just the relevant area of the window (the section for displaying page content) should be updated.

2019-05-17 11:21 UTC, itswisdomagain commented on fyne/fyne.go
> +	window.SetContent(pages.Menu(pages.ShowSyncWindow(walletMiddleware, window, fyneApp), window, fyneApp))
Also, this line 14 is too congested, could have been simplified thus:
```
syncWindow := pages.ShowSyncWindow(walletMiddleware, window, fyneApp)
pageContent := pages.Menu(syncWindow, window, fyneApp)
window. SetContent(pageContent)
```

2019-05-17 11:21 UTC, itswisdomagain commented on fyne/pages/sync.go
> +var Wallet godcrApp.WalletMiddleware
This feels a lot like a bad idea. Should not make the wallet publicly accessible from anywhere. Instead, the wallet should be passed to whatever function requires it to maintain the principle of least responsibility. Compare how this is done in other interfaces.

2019-05-17 11:21 UTC, itswisdomagain commented on fyne/pages/sync.go
> +		//wait for sync to be done before calling overview
Why are we using a goroutine and a sleeping forloop to determine when sync is done and when to load overview page? This is a potentially long running background operation that **needlessly** consumes extra computing power.

There is a sync progress callback that tells us when sync is done, why can't we load overview then and there, rather than here.

To be specific, you make `SyncDone = true` in line 78. Why not display the overview page there as well, thereby eliminating the need for this separate goroutine that does nothing else other than display overview page when `SyncDone == true`.

2019-05-17 11:21 UTC, itswisdomagain commented on fyne/pages/sync.go
> +		for{
This is another terrible, terrible idea. An **infinite forloop** in a separate goroutine to update the number of peers and best block height? This is a long running background operation that **needlessly** consumes extra computing power.

Similar work is done for the http interface (websocket is used to send the updates to the browser). You'd notice there that updates are only sent to the UI when peer count changes and when there's a new block.

The function that sends updates via websocket is here: https://github.com/raedahgroup/godcr/blob/master/web/routes/websocket.go#L63. Do a thorough analysis of when and where that function is called, you'll find that is isn't called randomly but only when there's actually new information.

For example, that function is called here: https://github.com/raedahgroup/godcr/blob/master/web/routes/walletloader.go#L75, when there is update from the sync operation. It's worth noting that this sync operation update is received when there is a change to the number of connected peers.

2019-05-17 11:21 UTC, itswisdomagain commented on fyne/pages/sync.go
> +				PeerConn.Text = strconv.Itoa(int(info.PeersConnected)) + " Peer Connected"
I see 2 issues with this statement:
- `PeerConn` is a property of the nav menu but being accessed from a `sync.go` file. Would be ideal to group `PeerConn`, `BlkHeight` and other related items into a `NavMenu` struct.
- `PeerConn` is obviously a package-wide variable. Can we reduce the scope? We certainly don't want any and every file in this package to be able to access this variable otherwise someone could add a code tomorrow in some other file that sets `PeerConn == nil` and we might not easily be able to detect that this is a wrong step. It'd be easier to detect foul usage if `PeerConn` was placed in a `NavMenu` struct, so we'd have `navMenu.PeerConn = nil`. `PeerConn == nil` may not raise attention but `navMenu.PeerConn = nil` likely will - we'd wonder why someone is modifying the nav menu from a different file. However, we should not even make it possible for anyone to update the nav menu from anywhere. Limit the scope, only provide necessary access to functions that need it. See https://en.wikipedia.org/wiki/Principle_of_least_privilege

2019-05-17 11:21 UTC, itswisdomagain commented on fyne/pages/sync.go
> +	widget.Refresh(reportLabel)
From `fyne.io/fyne/widget`:
> // Refresh instructs the containing canvas to refresh the specified widget.

At this point, `reportLabel` is just freshly created and not added to any container yet, why are we refreshing it?

2019-05-17 11:21 UTC, itswisdomagain commented on fyne/pages/sync.go
> +	infoButton = widget.NewButton("Tap to view informations", func() {
`Tap to view information` not `Tap to view informations`

2019-05-17 11:21 UTC, itswisdomagain commented on fyne/pages/sync.go
> +			infoButton.SetText("Tap to hide informations")
This does not follow the pattern in the rest of godcr or in the decred mobile apps. Please re-check.

2019-05-17 11:21 UTC, itswisdomagain commented on fyne/pages/sync.go
> +			reportLabel.Hide()
Shouldn't you hide before refreshing? Make me wonder if the call to `widget.Refresh(reportLabel)` is necessary, we can probably do without it.

2019-05-17 11:21 UTC, itswisdomagain commented on fyne/pages/sync.go
> +		reportLabel.SetText(strings.TrimSpace(stringReport.String()))
Setting text in this label always even when it is hidden is not a memory-efficient move. We're talking bytes, yes, but the writing memory-efficient code should be a practice.

2019-05-17 11:21 UTC, itswisdomagain commented on fyne/pages/sync.go
> +		netType := wallet.NetType()
There's a difference between `wallet` and `walletMiddleware`. If the type of the variable is `app.WalletMiddleware`, variable name should be `walletMiddleware`. Just semantics, but it helps code readers make accurate inference just by looking at the variable name.

2019-05-17 11:21 UTC, itswisdomagain commented on fyne/pages/sync.go
> +		fyne.NewContainerWithLayout(layout.NewFixedGridLayout(infoButton.MinSize()), infoButton),
What happens if you use `infoButton` directly instead of wrapping in a `NewFixedGridLayout`?

2019-05-17 11:21 UTC, itswisdomagain commented on fyne/widgets/tables.go
>  	return &Table{}
Rename this file back to `table.go`. Objects should be named in singular terms, not plural. `Class person` not `Class persons`. And of course, if the class name is `person`, it should go into a `person.go` file, not `persons.go`.

2019-05-17 11:21 UTC, itswisdomagain commented on fyne/widgets/tables.go
> -func (table *Table) AddRowSimple(texts ...string) {
We should keep this method, if there's ever a need to add row items that are plain strings, no formatting.

2019-05-17 11:21 UTC, itswisdomagain commented on go.mod
> +	fyne.io/fyne v1.0.1
Need to run `go mod tidy` to remove previous version from `go.sum`

2019-05-17 11:21 UTC, itswisdomagain commented on fyne/pages/menu.go
> +func Menu(object fyne.CanvasObject, win fyne.Window, App fyne.App) fyne.CanvasObject {
- This function name can be improved, it does not ONLY create the menu, it creates the entire app window: the menu and the main content.
- The `object` should be properly renamed to better describe what is to be passed in.
- `win` should be `window`, `App` should be `app` or `fyneApp`.

2019-05-17 11:21 UTC, itswisdomagain commented on fyne/pages/menu.go
> +	PeerConn  *canvas.Text
- Are these needed outside this package? If not, should be `peerConn` and `blkHeight`
- These variable names can be improved, seeing `PeerConn` somewhere (without seeing the type) could lead someone to think that the variables stores peer connection, `BlkHeight` sounds like a number, representing the height of a particular block. `numberOfConnectedPeersLabel` and `bestBlockHeightLabel` are more descriptive.

2019-05-17 11:21 UTC, itswisdomagain commented on fyne/pages/menu.go
> +func PageNotImplemented(win fyne.Window, App fyne.App) fyne.CanvasObject {
Why is `PageNotImplemented` in `menu.go`?

2019-05-17 11:21 UTC, itswisdomagain commented on fyne/pages/menu.go
> +//Menu outputs CanvasObjects "widgets" in vertical formats
- There should be a single space after the second slash, before the start of a comment proper: `// Menu outputs...`
- If a comment starts with capital letter, it should end with punctuation.

2019-05-17 11:21 UTC, itswisdomagain commented on fyne/pages/menu.go
> +				window.SetContent(Menu(OverviewPage(window, App), window, App))
Why calling `window.SetContent` twice in quick succession with different contents? Does the first content ever display for longer than a split second?

2019-05-17 11:21 UTC, itswisdomagain commented on fyne/pages/menu.go
> +			//return
Remove unwanted code.

2019-05-17 11:21 UTC, itswisdomagain commented on fyne/pages/overview.go
> +	noOfTxns, _ := Wallet.TransactionCount(nil)
No need to count tx in wallet BEFORE fetching the top 5 txs if there are txs to fetch. Proceed to fetch the top 5, if you do so and the number of txs returned from the fetch is 0, then you know there's no tx in wallet.

2019-06-05 07:28 UTC, ademuanthony commented on app/walletcore/types.go
> +			if output.AccountNumber == -1 || isInArray(output.AccountName) {
please add a comment for the `-1`

2019-06-05 07:28 UTC, ademuanthony commented on app/walletcore/types.go
> +			if input.AccountNumber == -1 || isInArray(input.AccountName) {
please add a comment for the `-1`

2019-06-05 07:28 UTC, ademuanthony commented on fyne/pages/history.go
> +	"github.com/raedahgroup/godcr/fyne/widgets"
An empty line above this line will be fine

2019-07-29 01:30 UTC, closed without merging