added no activity and no transaction textviews to overview and history page
raedahgroup/godcr-old pull request #368
Opened 2019-05-16 20:21 UTC by Sirmorrison

fixes #326
![image](https://user-images.githubusercontent.com/27733432/57884372-5c0aa980-7820-11e9-94cb-965072e8f850.png)

![image](https://user-images.githubusercontent.com/27733432/57884432-7e9cc280-7820-11e9-8b91-68e1aefd5448.png)

2019-05-16 22:58 UTC, UMichael commented
![image](https://user-images.githubusercontent.com/31141573/57892257-2ffa2300-7836-11e9-82a6-9b0d9c47539f.png)
Try removing unwanted space to make it readable, or make them all decimals

2019-05-16 23:18 UTC, Sirmorrison commented
> ![image](https://user-images.githubusercontent.com/31141573/57892257-2ffa2300-7836-11e9-82a6-9b0d9c47539f.png)
> Try removing unwanted space to make it readable, or make them all decimals

Please create an issue for this and share the link. Will be looked at in a separate PR this issue doesn't align with issue been addressed in this PR.

2019-05-17 00:09 UTC, metaclips approved these changes
This has been reviewed and works

2019-05-17 00:32 UTC, metaclips approved these changes

2019-05-18 02:12 UTC, itswisdomagain requested changes

2019-05-18 02:12 UTC, itswisdomagain commented on terminal/pages/history.go
> +			if error && message != "" {
- You only need to set the text (`messageTextView.SetText`) if `message != ""`
- If error, you use error color. If the next message is not error, the previously set error color will remain. Add an else statement to use a different color if not error.

2019-05-18 02:12 UTC, itswisdomagain commented on terminal/pages/history.go
> +			body.AddItem(messageTextView, 2, 0, false)
You should only re-add `messageTextView` if `message != ""`

2019-05-18 02:12 UTC, itswisdomagain commented on terminal/pages/overview.go
> +	if len(txns) == 0 {
Add an empty line space before this if statement.

2019-05-18 02:12 UTC, itswisdomagain commented on terminal/pages/overview.go
>  		overviewPage.AddItem(statusTextView, 2, 0, false)
No need to add the the textview at this point since no text is being displayed. Why was the "Fetching data..." text removed?

2019-05-18 02:12 UTC, itswisdomagain commented on terminal/pages/overview.go
> +			overviewPage.AddItem(noTxnsTextview, 2, 0, false)
Similar to when an error occurs in line 68 above, do not create another textview, simply update `statusTextView`.

2019-05-18 02:12 UTC, itswisdomagain commented on terminal/pages/overview.go
> +	statusTextView.SetText("Fetching data...")
You're setting the "Fetching data..." text after the top 5 txs have been fetched?

2019-05-18 02:12 UTC, itswisdomagain commented on terminal/pages/sync.go
> -		tviewApp.QueueUpdateDraw(func() {
Why is this taken off `tviewApp.QueueUpdateDraw`? This `afterSyncing` function is called from a separate goroutine, tview recommends using `QueueUpdateDraw` when manipulating views from goroutines.

2019-05-18 02:12 UTC, itswisdomagain commented on terminal/pages/sync.go
> +		return
`return` is unnecessary.

2019-05-18 03:27 UTC, Sirmorrison commented on terminal/pages/overview.go
>  		overviewPage.AddItem(statusTextView, 2, 0, false)
> "F

it was not removed, It was moved downwards because we cannot be displaying fetching data when there is actually no data to fetch

2019-05-18 15:25 UTC, itswisdomagain requested changes

2019-05-18 15:25 UTC, itswisdomagain commented on cli/commands/history.go
> -			Detailed:          true,
Why are these changes from #369 reflecting here? Please undo changes not relating to this PR.

2019-05-31 01:32 UTC, ademuanthony approved these changes

2019-05-31 01:56 UTC, itswisdomagain approved these changes

2019-05-31 01:58 UTC, merged