Removed detailed flag from transaction details command
raedahgroup/godcr-old pull request #369
Opened 2019-05-16 22:24 UTC by Sirmorrison

fixes  #274
![image](https://user-images.githubusercontent.com/27733432/57890920-68e3c900-7831-11e9-80b5-3b45ccf1044d.png)

![image](https://user-images.githubusercontent.com/27733432/57890951-7f8a2000-7831-11e9-80d0-3c7793990d5d.png)

2019-05-18 01:52 UTC, itswisdomagain requested changes

2019-05-18 01:52 UTC, itswisdomagain commented on cli/commands/helpers.go
> +func maxDecimalPlaces(amounts []int64) (maxDecimalPlaces int) {
Always aim to avoid code duplication. These same functions exist in `terminal/pages/helpers.go`, move that file to godcr utils package and modify terminal and cli to call the functions from there.

2019-05-18 01:52 UTC, itswisdomagain commented on cli/commands/show-transaction.go
> +
Unnecessary empty line space.

2019-05-18 01:52 UTC, itswisdomagain commented on cli/commands/show-transaction.go
> +	// var prompt string
This should probably be deleted?

2019-05-18 01:52 UTC, itswisdomagain commented on cli/commands/show-transaction.go
> +	if len(showTxCommand.displayedTxHashes) > 0 {
Why does show `showTxCommand` have a `displayedTxHashes` property? Should probably rename to `historyCommandDisplayedTxHashes`

2019-05-18 01:52 UTC, itswisdomagain commented on cli/commands/show-transaction.go
> +		displayedTxHashes = displayedTxHashes[:len(displayedTxHashes)-(len(displayedTxHashes)-int(showTxCommand.txHistoryOffset))]
Why does `showTxCommand.displayedTxHashes` have so much data that we need to trim it before sending to `HistoryCommand`? We don't do anything else with `showTxCommand.displayedTxHashes`, do we?

2019-05-18 15:18 UTC, itswisdomagain requested changes

2019-05-18 15:18 UTC, itswisdomagain commented on cli/commands/show-transaction.go
> +	ut "github.com/raedahgroup/godcr/app/utils"
What's `ut`? If you're reading code and you see `ut.DoSomething`, what would you conclude `ut` is?

2019-05-18 15:18 UTC, itswisdomagain commented on cli/commands/show-transaction.go
> +	historyCommand                  bool
`historyCommand` should be a "command" not a bool. Perhaps `returnToHistoryCommand` or `shouldReturnToHistory` are better variable names.

2019-05-18 15:18 UTC, itswisdomagain commented on cli/commands/show-transaction.go
> +	txHistoryOffset                 int32
- `historyCommandTxDisplayOffset`.
- You can put these history command related data into a struct:
```
type ShowTransactionCommand struct {
...
...
historyCommandData struct {
    offset int32
    displayedHashes []string
}
```

Then you can check `if showTxCommand.historyCommandData != nil` to determine whether or not to go back to history command.

2019-05-18 15:18 UTC, itswisdomagain commented on cli/commands/show-transaction.go
> +		transactionOutput.WriteString(fmt.Sprintf("  %s \t %s\n", inputAmount, input.PreviousOutpoint))
You're writing `input` data to a `transactionOutput` object? Tells me the `transactionOutput` variable is badly named - it obviously does not hold "transaction output" alone.

You should have a `txDetailsOutput` variable that you use for the entire writing, including when writing the basic info.

2019-05-21 18:45 UTC, itswisdomagain submitted a review, later dismissed
If I load history, pick a tx to see details, return to history, pick another tx to view details and return and keep cycling like that 3 or more times, a number of empty line spaces get printed to the terminal when I finally hit `q` to quit.

2019-05-21 18:45 UTC, itswisdomagain commented on cli/commands/show-transaction.go
> +type HistoryCommandData struct {
This doesn't need to be exported. `historyCommandData` is just fine.

2019-05-21 18:45 UTC, itswisdomagain commented on cli/commands/history.go
> +		displayedTxHashes := history.displayedTxHashes[:len(history.displayedTxHashes)-(len(history.displayedTxHashes)-int(history.txHistoryOffset))]
Pay close attention to this computation.
You're saying trim `history.displayedTxHashes` starting from 0 to X, where
`X = len(history.displayedTxHashes) - (len(history.displayedTxHashes) - int(history.txHistoryOffset))`
which is same as saying
`X = len(history.displayedTxHashes) - len(history.displayedTxHashes) + int(history.txHistoryOffset)`
which is same as saying
`X = int(history.txHistoryOffset)`

So this line can be simplified to:
`displayedTxHashes := history.displayedTxHashes[:int(history.txHistoryOffset)]`

2019-05-31 00:46 UTC, ademuanthony approved these changes

2019-05-31 00:49 UTC, ademuanthony requested changes
![image](https://user-images.githubusercontent.com/11990092/58674121-45973e80-8346-11e9-8c52-18d8cebfac8a.png)
 The empty spaces as noted in an earlier review is still not resolved

2019-06-04 14:22 UTC, ademuanthony approved these changes

2019-06-04 14:26 UTC, merged