Terminal account page
raedahgroup/godcr-old pull request #377
Opened 2019-05-31 11:27 UTC by Sirmorrison

added account page to terminal ui.
Fixes issues #374

2019-06-06 15:14 UTC, ademuanthony requested changes
Unable to view account details
![image](https://user-images.githubusercontent.com/11990092/59044476-1ae14480-8876-11e9-90c0-80883274c039.png)

2019-06-06 15:14 UTC, ademuanthony commented on main.go
> +func enterTerminalMode(ctx context.Context, walletMiddleware app.WalletMiddleware, appConfig *config.Config) {
I think you only need `*config.Settings`, this function can accept just that and have it passed down below

2019-06-06 23:36 UTC, Sirmorrison commented on main.go
> +func enterTerminalMode(ctx context.Context, walletMiddleware app.WalletMiddleware, appConfig *config.Config) {
It gives a type error. `cannot use Application (type *config.Config as type *config.Settings in argument to enterTerminalMode`

2019-06-06 23:41 UTC, Sirmorrison commented
> Unable to view account details
> ![image](https://user-images.githubusercontent.com/11990092/59044476-1ae14480-8876-11e9-90c0-80883274c039.png)

Resolved.

2019-06-08 15:26 UTC, ademuanthony requested changes

2019-06-08 15:26 UTC, ademuanthony commented on main.go
> +		enterTerminalMode(ctx, walletMiddleware, appConfig)
you should pass `appConfig.Settings` here and change the parament for the `enterTerminalMode` to accept `config.Settings` as suggested in an earlier comment

2019-06-10 16:48 UTC, ademuanthony requested changes

2019-06-10 16:48 UTC, ademuanthony commented on main.go
> +func enterTerminalMode(ctx context.Context, walletMiddleware app.WalletMiddleware, appConfig config.Settings) {
`appConfig` should be `settings` or `appSettings`

2019-06-11 04:13 UTC, ademuanthony requested changes

2019-06-11 04:13 UTC, ademuanthony commented on terminal/pages/accounts.go
> +		var accountExist bool
this variable can be renamed to `accountIsHidden` I guess

2019-06-11 09:36 UTC, ademuanthony approved these changes

2019-06-12 18:26 UTC, merged