fixed issues with overview page rendering
raedahgroup/godcr-old pull request #382
Opened 2019-06-10 19:55 UTC by Sirmorrison

fixed #381 

fixed issues with overview page always rendering from other pages on interfaces rendering overview page on launch like terminal and fyne.

2019-06-11 04:32 UTC, ademuanthony requested changes

2019-06-11 04:32 UTC, ademuanthony commented on fyne/sync.go
> +			}else{
This else block can be removed

2019-06-11 04:32 UTC, ademuanthony commented on terminal/pages/sync.go
> +			}else{
this `else` block can be removed

2019-06-11 04:32 UTC, ademuanthony commented on terminal/pages/sync.go
> +	var syncCompleted bool
I guess this variable is tracking whether the main page has been loaded or not. Please rename

2019-06-11 04:32 UTC, ademuanthony commented on fyne/sync.go
> +	var syncCompleted bool
I guess this variable is tracking whether the main page has been loaded or not. Please rename

2019-06-11 04:48 UTC, Sirmorrison commented on fyne/sync.go
> +	var syncCompleted bool
Its tracking is sync was completed. Reason is after sync is completed the process starts again in background.

2019-06-12 18:24 UTC, ademuanthony approved these changes

2019-06-12 18:24 UTC, merged