Terminal ui transaction filter
raedahgroup/godcr-old pull request #383
Opened 2019-06-18 13:56 UTC by Sirmorrison

Fixes #378 
Added transaction filter to terminal history page.

2019-09-05 01:45 UTC, itswisdomagain requested changes
Will continue review after these.

2019-09-05 01:45 UTC, itswisdomagain commented on cli/commands/history.go
> +		fmt.Println(len(history.displayedTxHashes))
I bet this isn't needed.

2019-09-05 01:45 UTC, itswisdomagain commented on terminal/pages/history.go
> +			txCount, txCountErr = wallet.TransactionCount(nil)
Should check if `txCountErr` is not nil here and `break` or `return` from this loop instead of continuing to count txs for other filters, similar to what is done in lines 73 to 76

2019-09-05 01:45 UTC, itswisdomagain commented on terminal/pages/history.go
> +		txCount, txCountErr := wallet.TransactionCount(walletcore.BuildTransactionFilter(filter))
Using `:=` here means you're creating and assigning to new variables and not the variables declared before the loop. Is this intentional?

2019-09-05 01:45 UTC, itswisdomagain commented on terminal/pages/history.go
> +			continue
This means `transactionCountByFilter[index]` will be empty.
Assuming there are 5 filters, line 63 above creates a `transactionCountByFilter` slice with 5 items. By default, each item's value is "".
Assume again that the filter at index 4 returns 0 count, transactionCountByFilter[4] will remain "". I'm pretty sure that's not what's intended.

You should use `append` instead.

2019-09-05 06:07 UTC, barisere requested changes
Several functions are defined within the `historyPage` function. Extract those that can stand alone (such as `displayMessage`) into function definitions at the top level. This should shorten the length of the `historyPage` function. The rationale for this is that the `historyPage` function should return the view primitive, and its helper functions can stand alone. The `displayMessage` function can become
```go
func displayMessage(tviewApp *tview.Application, message string, kind MessageKind) {
    // ...
}
```
See whether similar refactoring can be done for other functions, where necessary.

Also rebase your commits onto master, then see whether you can follow the changes made in #412. The entry point for building the CLI binary should be in the _cmd_ directory. The resulting binary should be named _godcr-tui_.

2019-09-05 06:07 UTC, barisere commented on terminal/pages/history.go
> +		txCount, txCountErr := wallet.TransactionCount(walletcore.BuildTransactionFilter(filter))
This will be executed even if the previous `if` block executes. Is that intended?

2019-09-05 06:07 UTC, barisere commented on terminal/pages/history.go
>  				if error {
`error` is also the name of a built-in interface. I suggest you rename the parameter to `isError`
Also, considering that this is a function, passing a boolean at its call site will be cryptic. An alternative is to use a type to describe the error condition instead. 
```go
type MessageKind string
const (
	ErrorMessage MessageKind = "error"
	InfoMessage MessageKind = "info"
)

displayMessage := func(message string, kind MessageKind) {
	// this function may be called from a goroutine, use tviewApp.QueueUpdateDraw
	tviewApp.QueueUpdateDraw(func() {
		historyPage.RemoveItem(messageTextView)
		if message != "" && kind == ErrorMessage {
			// other stuff
		}
	})
}
```

2019-09-05 06:07 UTC, barisere commented on terminal/pages/history.go
> +		selectedFilter = selectedFilterAndCount[0]
As a more idiomatic Go style, the previous three lines can be collapsed into the following.
```go
selectedFilter, lastSelectedFilter := strings.Split(filterAndCount, " ")[0], selectedFilter
```

2019-09-05 06:07 UTC, barisere commented on terminal/pages/history.go
> +func fetchAndDisplayTransactions(txOffset int, wallet walletcore.Wallet, filter *txindex.ReadFilter, historyTable *tview.Table, tviewApp *tview.Application, displayMessage func(string, bool)) {
The function signature is quite long. Break the parameter list onto several lines.
```go
func fetchAndDisplayTransactions(txOffset int,
	wallet walletcore.Wallet,
	filter *txindex.ReadFilter,
	historyTable *tview.Table,
	tviewApp *tview.Application,
	displayMessage func(string, bool)) {}
```

2019-09-14 23:39 UTC, Sirmorrison commented on terminal/pages/history.go
> +		selectedFilter = selectedFilterAndCount[0]
doesn't work as expected.

2019-09-14 23:41 UTC, Sirmorrison commented on terminal/pages/history.go
> +		txCount, txCountErr := wallet.TransactionCount(walletcore.BuildTransactionFilter(filter))
yes.

2019-09-18 08:32 UTC, barisere commented on terminal/pages/history.go
> +		selectedFilter = selectedFilterAndCount[0]
How is it expected to work? I tried it and it works as I expect.

2019-09-18 08:33 UTC, barisere commented on terminal/pages/history.go
> +func fetchAndDisplayTransactions(txOffset int, wallet walletcore.Wallet, filter *txindex.ReadFilter, historyTable *tview.Table, tviewApp *tview.Application, displayMessage func(string, bool)) {
Please take a look at this function signature, it's gotten even longer. It can be written on at least two lines.
```go
func fetchAndDisplayTransactions(txOffset int, wallet walletcore.Wallet, filter *txindex.ReadFilter,
	historyTable *tview.Table, tviewApp *tview.Application, displayMessage func(string, bool)) {
        // stuff here
}
```

2019-09-18 08:38 UTC, barisere commented on terminal/pages/history.go
>  				if error {
@Sirmorrison You may have missed this. Please attend to it.

2019-09-18 08:43 UTC, barisere requested changes
Previous reviews have not been attended to completely. Please go through the comments above and resolve any issue left.

2019-09-21 20:21 UTC, Sirmorrison commented
> ```go
> func displayMessage(tviewApp *tview.Application, message string, kind MessageKind) {
>     // ...
> }
> ```

The reason for the inline function used for the displayMessage().. is so as to have access to the historyPage primitive.

2019-09-21 20:45 UTC, Sirmorrison commented on terminal/pages/history.go
> +		selectedFilter = selectedFilterAndCount[0]
Your approach yields the following results from the screenshots below. The idea is to clear the table before adding new data. But your approach doesn't seem be doing that.

<img width="557" alt="image" src="https://user-images.githubusercontent.com/27733432/65378933-00fa2f00-dcb8-11e9-87c5-051b6b055a14.png">

<img width="564" alt="image" src="https://user-images.githubusercontent.com/27733432/65378944-21c28480-dcb8-11e9-9f47-138c92e1877f.png">

<img width="557" alt="image" src="https://user-images.githubusercontent.com/27733432/65378957-43bc0700-dcb8-11e9-8435-45fff76349d7.png">

what I want Is seen in the screenshots below.
<img width="562" alt="image" src="https://user-images.githubusercontent.com/27733432/65378999-f7bd9200-dcb8-11e9-88b1-9531c76b29d6.png">

<img width="564" alt="image" src="https://user-images.githubusercontent.com/27733432/65378992-de1c4a80-dcb8-11e9-92cf-04dffb85276c.png">

<img width="566" alt="image" src="https://user-images.githubusercontent.com/27733432/65379001-0c018f00-dcb9-11e9-9f13-a9a1351e9496.png">

2019-09-21 22:52 UTC, barisere approved these changes
LGTM

2019-09-23 09:24 UTC, itswisdomagain requested changes
Will review again after these.

2019-09-23 09:24 UTC, itswisdomagain commented on terminal/pages/history.go
> +	type MessageKind string
This isn't properly formatted. Also, the following enum pattern is better as the values for the constants are not needed:

```
type messageKind string
const (
	ErrorMessage messageKind = iota
	InfoMessage messageKind
)
```

2019-09-23 09:24 UTC, itswisdomagain commented on terminal/pages/history.go
> +				if message != "" && kind == ErrorMessage {
the preceding if statement already checks if `message != ""`

2019-09-23 09:24 UTC, itswisdomagain commented on terminal/pages/history.go
>  	titleTextView := primitives.NewLeftAlignedTextView(historyPageTitle)
Can inline the `"History"` text instead of using a `historyPageTitle` variable.

2019-09-23 09:24 UTC, itswisdomagain commented on terminal/pages/history.go
> +	filters := walletcore.TransactionFilters
Use `walletcore.TransactionFilters` directly please.

2019-09-23 09:24 UTC, itswisdomagain commented on terminal/pages/history.go
> +	var transactionCountByFilter []string
A count should be a slice of numbers not string. Rename your variable, this slice does not actually hold counts, it holds texts.

2019-09-23 09:24 UTC, itswisdomagain commented on terminal/pages/history.go
>  	if txCountErr != nil {
All cases of `txCountErr != nil` are already handled in the for loop above. This if statement is guaranteed to always return false, and is thus unneeded.

2019-09-23 09:24 UTC, itswisdomagain commented on terminal/pages/history.go
> +	var txCountErr error
These 2 variables do not need to be declared outside the for loop as they're really not needed outside the loop.

2019-09-23 09:24 UTC, itswisdomagain commented on terminal/pages/history.go
> +	txDropdown := primitives.NewForm(false)
`txFilterDropdown`

2019-09-23 09:24 UTC, itswisdomagain commented on terminal/pages/history.go
> +		filter = walletcore.BuildTransactionFilter(selectedFilter)
You do recognize that those 2 lines above is same as `filter := walletcore.BuildTransactionFilter(selectedFilter)`.

2019-09-23 09:24 UTC, itswisdomagain commented on terminal/pages/history.go
> +			if selectedFilter != lastSelectedFilter {
This check should happen whether selected filter is all or not. Regardless of what selected filter is, if it's the same as the last selected filter, nothing should happen.

2019-09-23 09:24 UTC, itswisdomagain commented on terminal/pages/history.go
> +		lastSelectedFilter = selectedFilter
Swap this line with the preceding line. The `selectedFilterAndCount` is created to be used in line 125. There shouldn't be any line of code separating the creation of that variable and it's usage.

2019-09-23 09:24 UTC, itswisdomagain commented on terminal/pages/history.go
> +		totalTxCount, txCountErr = wallet.TransactionCount(filter)
`totalTxCount`? What if filter is sent filter? Would this still return totalTxCount? Why do you even count the transactions for this filter? I don't see you using the count anywhere.

2019-09-23 21:38 UTC, Sirmorrison commented on terminal/pages/history.go
> +		totalTxCount, txCountErr = wallet.TransactionCount(filter)
<img width="117" alt="image" src="https://user-images.githubusercontent.com/27733432/65464868-d2648b80-de52-11e9-9d49-7996bfb39767.png">


the reason we count is for the dropdown.

2019-09-23 21:44 UTC, Sirmorrison commented on terminal/pages/history.go
> +			if selectedFilter != lastSelectedFilter {
It does regardless of the filter. Only thing is the `fetchAndDisplayTransactions()` parameter takes a `nil` filter instead of an actual filter as seen in line 141.

2019-09-23 21:47 UTC, Sirmorrison commented on terminal/pages/history.go
> +	var txCountErr error
They are used outside the loop.

2019-09-23 21:51 UTC, Sirmorrison commented on terminal/pages/history.go
> +	type MessageKind string
<img width="568" alt="image" src="https://user-images.githubusercontent.com/27733432/65465596-9c280b80-de54-11e9-850e-cfefd80066da.png">

I get this error.

2019-09-24 15:37 UTC, itswisdomagain commented on terminal/pages/history.go
> +			if selectedFilter != lastSelectedFilter {
You first check if the selected filter is all BEFORE checking if the selected filter is the last selected filter. That should not be so.

2019-09-24 15:40 UTC, itswisdomagain commented on terminal/pages/history.go
> +	var txCountErr error
I didn't say they are not used outside. I said they are not REALLY NEEDED outside the loop.

2019-09-24 15:41 UTC, itswisdomagain commented on terminal/pages/history.go
> +	type MessageKind string
When you reply to a message without applying the suggestions, DO NOT resolve the conversation so I can easily see your reply. `type messageKind string` -> `type messageKind uint32`

2019-09-24 15:44 UTC, itswisdomagain requested changes

2019-09-24 15:44 UTC, itswisdomagain commented on terminal/pages/history.go
> +		totalTxCount, txCountErr = wallet.TransactionCount(filter)
Look again. Do you really use that `totalTxCount` variable? Does that variable really hold the count for all transactions or for a set of transactions based on the filter selected?

2019-09-26 14:32 UTC, itswisdomagain requested changes
Will review again after these.

2019-09-26 14:32 UTC, itswisdomagain commented on terminal/pages/history.go
> +	// var txCountErr error
Please remove.
Also no need for an empty line space between the declaration of `transactionCountByFilter` and this loop.
And again, I believe a previous review comment advised renaming the `transactionCountByFilter` variable. It does not hold COUNTS!!! If it did, the type would be `[]int` not `[]string`.

2019-09-26 14:32 UTC, itswisdomagain commented on terminal/pages/history.go
> +			totalTxCount = txCount
There's no `continue` or `break` here. What this means is, if the filter is "All', the `wallet.TransactionCount` method will be called twice. Obviously not good.

Instead of calling it twice, call it once (below) and use do the following after calling the tx count function:
```
if filter == "All" {
      totalTxCount = txCount
}
```

2019-09-26 14:32 UTC, itswisdomagain commented on terminal/pages/history.go
> +			displayMessage(fmt.Sprintf("Cannot load history page. Error getting total transaction count: %s", txCountErr.Error()), ErrorMessage)
This is not an error getting TOTAL transaction count. Replace with
```suggestion
			displayMessage(fmt.Sprintf("Cannot load history page. Error getting transaction count for filter %s: %s", filter, txCountErr.Error()), ErrorMessage)
```

Also, reading this line of code makes it obvious that the variable `ErrorMessage` is poorly named. Rename to `MessageKindError`

2019-09-26 14:32 UTC, itswisdomagain commented on terminal/pages/history.go
> +		lastSelectedFilter = selectedFilter
You should first check if `lastSelectedFilter == selectedFilter` and return if so before making this assignment. Doing this check early on prevents making any further attempt to load txs for the newly selected filter.

2019-09-26 14:32 UTC, itswisdomagain commented on terminal/pages/history.go
> +		_, txCountErr := wallet.TransactionCount(filter)
I see absolutely no reason to count the txs for this filter only to see if an error will occur. Remove please.

2019-09-26 14:32 UTC, itswisdomagain commented on terminal/pages/history.go
> +			}else{
go fmt please
Always go fmt before committing.

2019-09-26 21:39 UTC, Sirmorrison commented on terminal/pages/history.go
> +		lastSelectedFilter = selectedFilter
This is a cyclic process. there is not need checked if they are same. line 127 does the checks that is needed.

2019-09-30 08:48 UTC, itswisdomagain requested changes
There are probably more changes to be requested, but I'm unwilling to review further as there's been too many changes yet to be made. I'm taking up this PR to complete properly.

2019-09-30 08:48 UTC, itswisdomagain commented on terminal/pages/history.go
> +	InfoMessage messageKind = iota
Did I really need to specifically mention this? `InfoMessage` -> `MessageKindInfo`

2019-09-30 08:48 UTC, itswisdomagain commented on terminal/pages/history.go
> +	// page title
This comment is really unnecessary.

2019-09-30 08:48 UTC, itswisdomagain commented on terminal/pages/history.go
> +	if totalTxCount == 0 {
This check can be moved to after line 72. There's no point doing anything further if totalTxCount is 0.

2019-09-30 08:48 UTC, itswisdomagain commented on terminal/pages/history.go
> +	// tx filter
Unnecessary comment. Variable names already tell us what's going on here.

2019-09-30 08:48 UTC, itswisdomagain commented on terminal/pages/history.go
> +	var selectedTxFilter *txindex.ReadFilter
This isn't needed aside the loop, at least it SHOULDN'T be. Move it to inside the loop.

2019-09-30 08:48 UTC, itswisdomagain commented on terminal/pages/history.go
> +		filteredTxCount, txCountErr := wallet.TransactionCount(selectedTxFilter)
This isn't the selected tx filter. At this point, no selection has been made. Rename the variable please.

2019-09-30 08:48 UTC, itswisdomagain commented on terminal/pages/history.go
> +			displayMessage(fmt.Sprintf("Cannot load history page. Error getting transaction count for filter %s: %s", selectedTxFilter, txCountErr.Error()), MessageKindError)
`selectedTxFilter` -> `filter`

2019-09-30 08:48 UTC, itswisdomagain commented on terminal/pages/history.go
> +	SetSelectable(true, false)
The indenting in lines 109 to 110 are off.

2019-09-30 08:48 UTC, itswisdomagain commented on terminal/pages/history.go
> +	// filter dropDown sleection options
- typo
- also don't know what this comment describes

2019-09-30 08:48 UTC, itswisdomagain commented on terminal/pages/history.go
> +		lastSelectedFilter = selectedFilter
In my comment here https://github.com/raedahgroup/godcr/pull/383/files?file-filters%5B%5D=.go#r328647081, I said you should FIRST check and return. Check early. I did not say the check wasn't done below, I said the check should be done earlier. This isn't implemented and there's no good reason for not implementing it.

2019-09-30 08:48 UTC, itswisdomagain commented on terminal/pages/history.go
> +			}else{
You still have not done go fmt

2019-09-30 08:48 UTC, itswisdomagain commented on terminal/pages/history.go
> +		if event.Key() == tcell.KeyEscape || event.Key() == tcell.KeyBackspace || event.Key() == tcell.KeyBackspace2 {
Do we clear focus on backspace? iirc, we only do so on escape key press.

2019-09-30 08:48 UTC, itswisdomagain commented on terminal/pages/history.go
> +		if event.Key() == tcell.KeyEscape || event.Key() == tcell.KeyBackspace || event.Key() == tcell.KeyBackspace2 {
My previous comment applies here as well.

2019-09-30 08:48 UTC, itswisdomagain commented on terminal/pages/history.go
> -	displayedTxHashes = []string{}
Why is this removed?

2019-09-30 08:48 UTC, itswisdomagain commented on terminal/pages/history.go
> +		// show a loading text at the bottom of the table so user knows an op is in progress
Add an empty line space here because this function parameters list extends beyond 1 line. The extra line makes it easy to tell where the function signature stops and where the function body begins.

2019-09-30 10:05 UTC, itswisdomagain approved these changes

2019-09-30 10:06 UTC, merged