Nuklear ui tx filter[WIP]
raedahgroup/godcr-old pull request #384
Opened 2019-06-19 09:01 UTC by Sirmorrison

2019-09-05 13:52 UTC, barisere requested changes

2019-09-05 13:52 UTC, barisere commented on nuklear/widgets/dropDown.go
> +		if filterSelector.txCountErr != nil {
This technique is returning an error implicitly. The function signature does not indicate the possibility of an error, so the caller has to be aware of the `FilterSelector.txCountErr` property. Can you make the error condition explicit?

2019-09-11 22:35 UTC, itswisdomagain requested changes
I'll review again after this important change is addressed.

2019-09-11 22:35 UTC, itswisdomagain commented on nuklear/pagehandlers/history.go
> +			go handler.fetchTransactions(filter)
Wallet operations should not be performed directly from the `Render` function, use the `BeforeRender` function instead. `Render` should only be for drawing/rendering views on the window; it is called repeatedly whenever there's a slight action such as moving the mouse. As a matter of fact, a single mouse move could cause the `Render` function to be called multiple times in a second.

The only safe places to call wallet functions is in `BeforeRender` and in event listeners such as button click event listeners.

2019-09-23 08:57 UTC, itswisdomagain requested changes
Will review again after these.

2019-09-23 08:57 UTC, itswisdomagain commented on nuklear/pagehandlers/history.go
> +	txCountErr               error
go fmt

2019-09-23 08:57 UTC, itswisdomagain commented on nuklear/pagehandlers/history.go
> +	handler.filterSelectorWidget, handler.txCountErr = widgets.FilterSelectorWidget(wallet, nil)
This call is rendered obsolete by similar function call in line 57. Please delete.

2019-09-23 08:57 UTC, itswisdomagain commented on nuklear/pagehandlers/history.go
> +	handler.filterSelectorWidget, handler.txCountErr = widgets.FilterSelectorWidget(wallet, func(int){
Why is the error returned from the `widgets.FilterSelectorWidget` function assigned to `txCountErr`? The relattionship between tx count and FilterSelectorWidget (if such a relationship even exists) is not immediately obvious.

Should probably rename `txCountErr` to `filterSelectorErr`.

2019-09-23 08:57 UTC, itswisdomagain commented on nuklear/pagehandlers/history.go
> +			handler.filter = filter
Rename `filter` and `handler.filter` to `selectedTxFilter` and `handler.selectedTxFilter` respectively. Also rename `selectedFilter` and `handler.selectedFilter` to `currentFilterText` and `handler.currentFilterText` respectively.

2019-09-23 08:57 UTC, itswisdomagain commented on nuklear/pagehandlers/history.go
> +		handler.totalTxCount = totalTxCount
Does the `totalTxCount` count change? `handler.totalTxCount` is already assigned in line 50; don't see why it needs to be returned by `filterSelectorWidget.GetSelectedFilter()`.

2019-09-23 08:57 UTC, itswisdomagain commented on nuklear/pagehandlers/history.go
> +			handler.fetchHistoryError = err
`err` isn't an history fetch error, is it?

2019-09-23 08:57 UTC, itswisdomagain commented on nuklear/pagehandlers/history.go
> +	handler.clearTxDetails()
You want to clear tx details before calling `fetchTransactions`. Restore this `handler.clearTxDetails()` call to after line 45.

2019-09-23 08:57 UTC, itswisdomagain commented on nuklear/pagehandlers/history.go
> +
This space is unnecessary. The next set of lines directly relate to the preceding line.

2019-09-23 08:57 UTC, itswisdomagain commented on nuklear/pagehandlers/history.go
> +			contentWindow.DisplayErrorMessage("Error loading history", handler.fetchHistoryError)
How is a tx **COUNT** error same as an error loading history? Oh by the way, you're referencing `handler.fetchHistoryError` in the if statement body but your if statement checked for `handler.txCountErr != nil`

2019-09-23 08:57 UTC, itswisdomagain commented on nuklear/widgets/accountselector.go
> +	} else if len(accountSelector.accounts) != 1 {
Why is this change necessary?

2019-09-23 08:57 UTC, itswisdomagain commented on nuklear/widgets/dropDown.go
> +	filter                   string
`selectedFilter`

2019-09-23 08:57 UTC, itswisdomagain commented on nuklear/widgets/dropDown.go
> +	selectionChanged         func(int)
The `int` is not needed obviously, can just use a simple `func()`.

2019-09-23 08:57 UTC, itswisdomagain commented on nuklear/widgets/dropDown.go
> +	filterSelector.transactionCountByFilter = make([]string, len(filterSelector.filters))
The empty line spaces at lines 41 and 43 can be deleted without hurting readability.

2019-09-23 08:57 UTC, itswisdomagain commented on nuklear/pagehandlers/history.go
> +	filter               *txindex.ReadFilter
Shouldn't need to save this variable in this struct. Only save the selected filter text and whenever you need the readfilter, you call `walletcore.BuildTransactionFilter()`

2019-09-23 08:57 UTC, itswisdomagain commented on nuklear/widgets/dropDown.go
> +		filterSelector.txCount, filterSelector.txCountErr = wallet.TransactionCount(walletcore.BuildTransactionFilter(filter))
Each time this loop runs, `filterSelector.txCount` is re-assigned. The final value of `filterSelector.txCount` is the value set by the last loop run. I believe this variable does not need to be a property of the `filterSelector` struct, but can be a local variable used here and here alone.

2019-09-23 08:57 UTC, itswisdomagain commented on nuklear/widgets/dropDown.go
> +	transactionCountByFilter []string
Why is a transaction COUNT slice a string slice instead of a number slice? Probably need to rename your variable.

2019-09-23 10:43 UTC, Sirmorrison commented on nuklear/pagehandlers/history.go
> +	handler.filterSelectorWidget, handler.txCountErr = widgets.FilterSelectorWidget(wallet, nil)
Not exactly... Line 47 generates the initial receive address on the first user account. The call on line 57 only comes to effect only after the dropdown option is selected or changed.

2019-09-23 20:55 UTC, Sirmorrison commented on nuklear/pagehandlers/history.go
> +	filter               *txindex.ReadFilter
`filter` this is just a variable stored here oh not the filters themselves.

2019-09-24 15:46 UTC, itswisdomagain commented on nuklear/pagehandlers/history.go
> +	filter               *txindex.ReadFilter
I did not debate that with you. Please read my comment again and apply accordingly.

2019-09-24 15:55 UTC, itswisdomagain requested changes
Looking better but still some changes. I also replied to some comments from the previous review. Please take a look.

2019-09-24 15:55 UTC, itswisdomagain commented on nuklear/pagehandlers/history.go
> +	filterSelectorErr       error
- go fmt please
- move this `filterSelectorErr` property close to the `filterSelectorWidget` property. Doesn't that just make more sense?

2019-09-24 15:55 UTC, itswisdomagain commented on nuklear/pagehandlers/history.go
> +	selectedTxFilter      	*txindex.ReadFilter
I've mentioned in a previous review that this does not need to be stored. Only `currentFilterText` needs to be stored.

2019-09-24 15:55 UTC, itswisdomagain commented on nuklear/pagehandlers/history.go
> +	handler.filterSelectorWidget, handler.filterSelectorErr = widgets.FilterSelectorWidget(wallet, func(){
This code in line 57 does not fetch filtered data. It sets up the filter widget. Update your comment.

2019-09-24 15:55 UTC, itswisdomagain commented on nuklear/pagehandlers/history.go
> +		_, selectedTxFilter, currentFilterText, err := handler.filterSelectorWidget.GetSelectedFilter()
`handler.filterSelectorWidget.GetSelectedFilter` should only return `currentFilterText, err` or just `currentFilterText` even.

2019-09-24 15:55 UTC, itswisdomagain commented on nuklear/pagehandlers/history.go
> +		handler.filterSelectorWidget.Render(contentWindow)
`handler.filterSelectorWidget` may be nil if line 57 returns an error. You should check that it is not nil before rendering it here.

2019-09-24 15:55 UTC, itswisdomagain commented on nuklear/pagehandlers/history.go
> +			handler.filterSelectorErr = err
This is not an error with the filter selector. If this code here executes, then it means the filter has been successfully rendered on the page. This sub-function only gets triggered if a user selects an item from the filter dropdown. This is probably more related to `fetchHistoryError` since the next thing after a user selects an item from the filter is an attempt to load transactions for the selected filter item.

2019-09-25 02:18 UTC, Sirmorrison commented on nuklear/pagehandlers/history.go
> +			handler.filterSelectorErr = err
https://github.com/raedahgroup/godcr/pull/384#discussion_r327695663

already resolves this as no error is returned.

2019-09-26 14:44 UTC, itswisdomagain requested changes

2019-09-26 14:44 UTC, itswisdomagain commented on nuklear/pagehandlers/history.go
> +	totalTxCount 			int
go fmt please

2019-09-26 14:44 UTC, itswisdomagain commented on nuklear/pagehandlers/history.go
> +			handler.fetchHistoryError = err
Again you mark a comment as resolved without actually resolving it or commenting on it. Please go back to https://github.com/raedahgroup/godcr/pull/384/files#r327002260

2019-09-26 14:44 UTC, itswisdomagain commented on nuklear/pagehandlers/history.go
> +		if currentFilterText != handler.currentFilterText {
Empty line space before this.

2019-09-26 14:44 UTC, itswisdomagain commented on nuklear/pagehandlers/history.go
> +		refreshWindowDisplay()
This should only be called after the transactions are fetched, i.e. from inside the `handler.fetchTransactions` method. Please remove from here.

If you need to refresh the display, that should be after line 63 where you clear the previous list of transactions.

2019-09-26 14:44 UTC, itswisdomagain commented on nuklear/pagehandlers/history.go
> +			handler.filterSelectorWidget.Render(contentWindow)
How does `handler.fetchHistoryError` relate to `handler.filterSelectorWidget`?

2019-09-26 14:44 UTC, itswisdomagain commented on nuklear/pagehandlers/history.go
> +			contentWindow.AddWrappedLabel("No Transactions to display yet", widgets.CenterAlign)
Transactions -> transactions

2019-09-26 14:44 UTC, itswisdomagain commented on nuklear/widgets/dropDown.go
> +		filterSelector.txCountErr = txCountErr
This assignment is unncessary. Just return the error!

2019-09-26 14:44 UTC, itswisdomagain commented on nuklear/widgets/dropDown.go
> +			txCount, txCountErr := wallet.TransactionCount(nil)
If filter is all, you call `wallet.TransactionCount` twice. This is unnecessary. See the similar comment on your other PR #383.

2019-09-26 14:44 UTC, itswisdomagain commented on nuklear/widgets/dropDown.go
> +		filterSelector.transactionFilter[index] = fmt.Sprintf("%s (%d)", filter, txCount)
You should ignore 0 count filters. This is done better in #383

2019-09-26 14:44 UTC, itswisdomagain commented on nuklear/widgets/dropDown.go
> +	rowColumns[1] = filterSelectorWidth
lines 64 to 66 can be simplified to 
```
rowColumns := []int {
     window.LabelWidth("filter"),
     filterSelectorWidth,
}
```

By the way, those are not columns! Please use proper variable names!

2019-09-26 14:44 UTC, itswisdomagain commented on nuklear/widgets/dropDown.go
> +	transactionFilter []string
- `transactionFilters`, this is a collection of items, not a single item
- what's the difference between `filters` and `transactionFilters`?
- go fmt

2019-09-26 20:21 UTC, Sirmorrison commented on nuklear/widgets/dropDown.go
> +	rowColumns := []int {
here

2019-09-30 18:08 UTC, itswisdomagain approved these changes

2019-09-30 18:08 UTC, merged