Nuklear receive page
raedahgroup/godcr-old pull request #386
Opened 2019-06-25 00:45 UTC by Sirmorrison

fixes #385
Improved nuklear ui receive page by generating receive address automatically when wallet account is only one and generate receive address for the first wallet account automatically when wallet account is more than on.

![image](https://user-images.githubusercontent.com/27733432/60060883-a9651b00-96ea-11e9-97ea-c8157bd09c91.png)

![image](https://user-images.githubusercontent.com/27733432/60060941-e16c5e00-96ea-11e9-9590-ded1b394696f.png)

2019-06-25 12:41 UTC, ademuanthony submitted a review, later dismissed
The sync is not working in nuklear mode.
Please check

2019-09-05 01:21 UTC, itswisdomagain requested changes

2019-09-05 01:21 UTC, itswisdomagain commented on nuklear/pagehandlers/receive.go
> +			handler.generatedAddress, handler.generateAddressError = handler.wallet.ReceiveAddress(handler.accountNumber)
Should not call `handler.wallet.ReceiveAddress` directly in the `Render` method. Reason is `Render` is invoked multiple times per second. I believe this if statement should rather go into `BeforeRender`.

Then you'd need to figure out a way to listen for dropdown selection change event on the account selection widget, and place the following code in the selection change event listener:
```
handler.accountNumber = handler.accountSelectorWidget.GetSelectedAccountNumber()
handler.generatedAddress, handler.generateAddressError = handler.wallet.ReceiveAddress(handler.accountNumber)
window.Master().Changed()
```
```

2019-09-05 01:21 UTC, itswisdomagain commented on nuklear/widgets/tablecell.go
> +}
Add an extra line at the end of this file

2019-09-05 01:21 UTC, itswisdomagain commented on terminal/pages/receive.go
> +		formButton.AddButton("new address.", func() {
Please remove these changes that obviously do not relate to this PR. Create a new PR if these changes are important.

2019-09-05 01:38 UTC, Sirmorrison commented on terminal/pages/receive.go
> +		formButton.AddButton("new address.", func() {
its was just to change the casing from all caps to lower casing. Too small for a PR.

2019-09-05 01:40 UTC, itswisdomagain commented on terminal/pages/receive.go
> +		formButton.AddButton("new address.", func() {
why are you changing it?

2019-09-05 01:41 UTC, Sirmorrison commented on terminal/pages/receive.go
> +		formButton.AddButton("new address.", func() {
requested.

2019-09-11 22:29 UTC, itswisdomagain requested changes
This looks significantly better. There are 2 issues still:

- Selecting a different account from the account selection dropdown does not generate and display a receive address for the new selection.
- Clicking "new address" to force generate a new address also does not use the current account selection in the dropdown.

2019-09-11 22:29 UTC, itswisdomagain commented on nuklear/pagehandlers/receive.go
> +				window.Master().Changed()
This doesn't look properly indented.

2019-09-11 22:29 UTC, itswisdomagain commented on go.mod
> -require github.com/raedahgroup/godcr/cmd/godcr-fyne v0.0.0-00010101000000-000000000000 // indirect
There shouldn't be any changes to the `go.mod` and `go.sum` files in the project root dir. I suspect this change would cause a build error when trying to build fyne from the project root using `go build ./cmd/godcr-fyne`.

Currently, fyne doesn't build because of a dcrlibwallet mod version issue. That will soon be resolved on master and you'd need to rebase this PR. Then we can properly test the above assertion.

2019-09-11 22:29 UTC, itswisdomagain commented on nuklear/pagehandlers/receive.go
> +			handler.generatedAddress, handler.generateAddressError = handler.wallet.GenerateNewAddress(handler.accountNumber)
`handler.accountNumber` is only set once, in `BeforeRender` when the page is navigated to - this initial value is always the account number of the first account in the wallet. This value does not change when the account dropdown selection changes, so clicking this label to generate a new address never uses the current selection in the dropdown.

2019-09-23 09:10 UTC, itswisdomagain requested changes
I do not see the code that causes the account selection widget to be displayed on the receive page. Am I missing something?

2019-09-23 09:10 UTC, itswisdomagain commented on go.mod
> -require github.com/raedahgroup/godcr/cmd/godcr-fyne v0.0.0-00010101000000-000000000000 // indirect
Please undo the changes to this file.

2019-09-23 09:10 UTC, itswisdomagain commented on nuklear/pagehandlers/receive.go
> +	handler.accounts, handler.generateAddressError = wallet.AccountsOverview(walletcore.DefaultRequiredConfirmations)
`widgets.AccountSelectorWidget` already calls `wallet.AccountsOverview`. I'm not okay with having that function called twice: here (line 38) and in the `AccountSelectorWidget`. Find a way to merge them. Specifically, why do we need to have information of the accounts here?

2019-09-23 09:10 UTC, itswisdomagain commented on nuklear/pagehandlers/receive.go
> +	}
Modify lines 40-48 thus:

Note the following:
- No need for `handler.accountNumber` or `handler.accounts`.
- The selection changed func no longer needs an int parameter.

```
// first setup account selector widget
handler.accountSelectorWidget = widgets.AccountSelectorWidget("Account:", false, false, wallet, func() {
	handler.generatedAddress, handler.generateAddressError = handler.wallet.ReceiveAddress(handler.accountSelectorWidget.GetSelectedAccountNumber())
	refreshWindowDisplay()
})

// generate address for first account in wallet
handler.generatedAddress, handler.generateAddressError = handler.wallet.ReceiveAddress(handler.accountSelectorWidget.GetSelectedAccountNumber())
```

2019-09-23 09:10 UTC, itswisdomagain commented on nuklear/pagehandlers/receive.go
> +			window.Master().Changed()
Other pages, iirc, use a `handler.refreshDisplay()` function. That is probably better.

2019-09-23 09:10 UTC, itswisdomagain commented on nuklear/pagehandlers/receive.go
> +		window.Master().Changed()
Calling master changed will only cause this Render function to be called again. When it is called again, this master changed function will also be re-called and you get an endless cycle of repainting the window. Please remove this.

2019-09-24 16:00 UTC, itswisdomagain requested changes

2019-09-24 16:00 UTC, itswisdomagain commented on go.sum
> +github.com/raedahgroup/dcrlibwallet v1.1.1-0.20190917220221-47d626dfbe08/go.mod h1:6AGgglq9BB0twJnZnHvfH8hIQrbw6yBJSPp9QI+hBk0=
Can't tell why this change is necessary. Or even why any change to this file is necessary. Please undo.

2019-09-24 16:00 UTC, itswisdomagain commented on nuklear/pagehandlers/receive.go
> +	accountNumber         uint32
`accounts` and `accountNumber` are not used, are they?

2019-09-24 16:00 UTC, itswisdomagain commented on nuklear/pagehandlers/receive.go
> +		refreshWindowDisplay()
use `handler.refreshWindowDisplay()`

2019-09-24 16:00 UTC, itswisdomagain commented on nuklear/pagehandlers/receive.go
> +			handler.generatedAddress, handler.generateAddressError = handler.wallet.GenerateNewAddress(handler.accountNumber)
`handler.accountSelectorWidget.GetSelectedAccountNumber()` instead of `handler.accountNumber`

2019-09-24 16:00 UTC, itswisdomagain commented on nuklear/widgets/tablecell.go
> +type LinkLabelCell struct {
Is there a `label.go` file in this package? This should be there not here, this has no relation with a table. It could preferably be in a `linklabel.go` file instead.

2019-09-25 02:32 UTC, Sirmorrison commented on go.sum
> +github.com/raedahgroup/dcrlibwallet v1.1.1-0.20190917220221-47d626dfbe08/go.mod h1:6AGgglq9BB0twJnZnHvfH8hIQrbw6yBJSPp9QI+hBk0=
I didn't change it. I just build and the app did its thing.

2019-09-30 18:13 UTC, itswisdomagain requested changes

2019-09-30 18:13 UTC, itswisdomagain commented on nuklear/widgets/accountselector.go
> +	"github.com/aarzilli/nucular/label"
Is this import used? If so, need to order it properly, but I can't find where it is used.

2019-09-30 19:00 UTC, Sirmorrison commented on nuklear/widgets/accountselector.go
> +	"github.com/aarzilli/nucular/label"
used inlines 94 and 97.

2019-09-30 19:44 UTC, itswisdomagain approved these changes

2019-09-30 19:45 UTC, merged