Added interactive receive prompt
raedahgroup/godcr-old pull request #39
Opened 2018-11-16 17:42 UTC by Jujhar

Passing no parameters to `./dcrcli receive` brings up interactive console to select account to generate receive address for previously displayed error.

Fixes #38

2018-11-17 02:55 UTC, Jujhar commented
Please hold off on merging for a bit until I update and follow up.
Raedah wants third party plugin Promptui removed from system.

2018-11-17 07:15 UTC, itswisdomagain requested changes
This looks good, just some improvements required.

2018-11-17 07:15 UTC, itswisdomagain commented on cli/cli.go
> +	if recieveAddress == "" {
Shouldn't this be an else? `if len(commandArgs) == 0`, prompt user to select an account, **`else`**, use the value present in `commandArgs[0]`. Pretty straight forward.

2018-11-17 07:15 UTC, itswisdomagain commented on cli/cli.go
> +		recieveAddress = fmt.Sprint(sourceAccount)
This is unnecessary, what we actually need for receiveAddress is a `uint32` which is what we already get from the `getSendSourceAccount` function.

You should instead make a direct assignment of the result of the `getSendSourceAccount` function to `receiveAddress`

Then there'd be no need for the string parsing in line 183. Instead, you should parse the string in the else block where you read the argument passed in; and assign the result of the parsing to `receiveAddress`

2018-11-17 07:17 UTC, itswisdomagain commented
After taking another look and conferring with @raedah, you do not need to worry about removing the promptui dependency. That's already done in a separate PR that will get merged soon. After that PR is merged and promptui removed, your code will still work fine, so you can safely proceed to just making the corrections above for now.

2018-11-17 17:27 UTC, Jujhar commented
Ready to go I think.

2018-11-17 20:48 UTC, itswisdomagain requested changes
Just these little code cleanup.

2018-11-17 20:48 UTC, itswisdomagain commented on cli/cli.go
> +		recieveAddress = sourceAccount
I think you can straight-forward assign `recieveAddress` in line 170 instead of using a new "temporary" variable `sourceAccount`

2018-11-17 20:48 UTC, itswisdomagain commented on cli/cli.go
> +	r, err := c.walletrpcclient.Receive(uint32(recieveAddress))
This conversion to uint32 is unnecessary. `recieveAddress` was declared in line 164 above as unit32 already.

2018-11-17 21:13 UTC, itswisdomagain commented on cli/cli.go
> +		x, err := strconv.ParseUint(commandArgs[0], 0, 32)
Shouldn't you use base 10 for this conversion? Like:
`x, err := strconv.ParseUint(commandArgs[0], 10, 32)`

2018-11-19 20:41 UTC, Jujhar commented
Updated and tested.

2018-11-20 03:42 UTC, itswisdomagain requested changes
This looks good @Jujhar! Please rebase your branch with master and fix merge conflicts. Or it might be easier/faster to update your local master branch by merging with this remote master branch, creating a new branch off the updated master and then re-introducing your changes.

Either ways, while doing that, do you mind giving some attention to these minor issues?

2018-11-20 03:42 UTC, itswisdomagain commented on cli/cli.go
> +		recieveAddress, err = getSendSourceAccount(c.walletrpcclient)
If you do `recieveAddress, err := getSendSourceAccount(c.walletrpcclient)`, there'd be no need for the declaration of the err variable in the preceding line.

2018-11-20 03:42 UTC, itswisdomagain commented on cli/cli.go
> +
Maybe take off the whitespaces in lines 175 and 177?

2018-11-20 15:54 UTC, Jujhar commented on cli/cli.go
> +		recieveAddress, err = getSendSourceAccount(c.walletrpcclient)
That would make recieveAddress a new variable and we want to use the one located a step up the scope (line 164)

2018-11-23 21:54 UTC, Jujhar commented
Updated and tested.
Interactive prompt is removed but selection (if more than one account is present) is possible through inputting a number.

2018-11-29 18:52 UTC, itswisdomagain approved these changes

2018-11-29 23:37 UTC, merged