separate entry point for each user interface
raedahgroup/godcr-old pull request #412
Opened 2019-09-03 21:42 UTC by itswisdomagain

2019-09-03 22:54 UTC, barisere requested changes
The new `godcr-web` binary fails with the following error when run from `$GOPATH/bin`.
```
➜  godcr git:(pr412_separate_entrypoints) godcr-web 
The following wallets were found...
(1) /Users/barisere/Library/Application Support/Dcrwallet/mainnet
(2) /Users/barisere/Library/Application Support/Dcrwallet/testnet3
(C)reate a new wallet.
(R)estore wallet from seed.
Select the wallet to use for this session: 2
2019/09/03 23:48:23 error loading templates: open ../../web/views/error.html: no such file or directory
```
We may need to use a tool such as [Packr](https://github.com/gobuffalo/packr) to isolate the built binary from the filesystem. This will enable us ship only binaries for the web UI, just as it is for other interfaces.

2019-09-03 22:58 UTC, barisere requested changes
`godcr-nuklear` no longer launches the GUI as expected.
```
➜  godcr git:(pr412_separate_entrypoints) godcr-nuklear 
The following wallets were found...
(1) /Users/barisere/Library/Application Support/Dcrwallet/mainnet
(2) /Users/barisere/Library/Application Support/Dcrwallet/testnet3
(C)reate a new wallet.
(R)estore wallet from seed.
Select the wallet to use for this session: 2
```

2019-09-03 22:59 UTC, itswisdomagain commented on README.md
> +Exporting `GO111MODULE` directly in CLI does not work and
Don't know who added this to the readme, doesn't sound very accurate. Will need someone running Windows OS to confirm this.

2019-09-03 23:00 UTC, barisere requested changes
`godcr-fyne` launches the GUI, then crashes on start because it cannot find its assets. Again, [Packr](https://github.com/gobuffalo/packr) can help us here.
```
➜  godcr git:(pr412_separate_entrypoints) godcr-fyne 
The following wallets were found...
(1) /Users/barisere/Library/Application Support/Dcrwallet/mainnet
(2) /Users/barisere/Library/Application Support/Dcrwallet/testnet3
(C)reate a new wallet.
(R)estore wallet from seed.
Select the wallet to use for this session: 2
2019/09/03 23:58:21 overview png file missing open ../../fyne/pages/png/overview.png: no such file or directory
```

2019-09-03 23:15 UTC, barisere commented on README.md
> +Exporting `GO111MODULE` directly in CLI does not work and
I've seen that elsewhere too. I think it's because of the difference in handling of environment variables between *nix and Windows.

2019-09-03 23:57 UTC, itswisdomagain commented
@barisere the 3 issues you identified above are all related to the interfaces not being able to find the required assets. Related issue https://github.com/raedahgroup/godcr/issues/239.

2019-09-04 01:48 UTC, Sirmorrison requested changes

2019-09-04 01:48 UTC, Sirmorrison commented on cmd/godcr-cli/log.go
> +		fmt.Fprintf(os.Stderr, "failed to create log directory: %v\n", err)
`Failed`

2019-09-04 01:48 UTC, Sirmorrison commented on cmd/godcr-cli/log.go
> +		fmt.Fprintf(os.Stderr, "failed to create file rotator: %v\n", err)
`Failed`

2019-09-04 01:48 UTC, Sirmorrison commented on cmd/godcr-fyne/fyne.go
> +		fmt.Fprintf(os.Stderr, "unexpected command or flag in %s mode: %s\n",
`Unexpected`

2019-09-04 01:48 UTC, Sirmorrison commented on cmd/godcr-nuklear/log.go
> +		fmt.Fprintf(os.Stderr, "failed to create log directory: %v\n", err)
`Failed`

2019-09-04 01:48 UTC, Sirmorrison commented on cmd/godcr-nuklear/log.go
> +		fmt.Fprintf(os.Stderr, "failed to create file rotator: %v\n", err)
`Failed`

2019-09-04 01:48 UTC, Sirmorrison commented on cmd/godcr-terminal/log.go
> +		fmt.Fprintf(os.Stderr, "failed to create log directory: %v\n", err)
`Failed`

2019-09-04 01:48 UTC, Sirmorrison commented on cmd/godcr-terminal/log.go
> +		fmt.Fprintf(os.Stderr, "failed to create file rotator: %v\n", err)
`Failed`

2019-09-04 01:48 UTC, Sirmorrison commented on cmd/godcr-terminal/terminal.go
> +		fmt.Fprintf(os.Stderr, "unexpected command or flag in %s mode: %s\n",
`Unexpected`

2019-09-04 01:48 UTC, Sirmorrison commented on cmd/godcr-web/log.go
> +		fmt.Fprintf(os.Stderr, "failed to create log directory: %v\n", err)
same as above.

2019-09-04 07:56 UTC, Sirmorrison commented
<img width="426" alt="image" src="https://user-images.githubusercontent.com/27733432/64236166-bcb61300-cef1-11e9-80f2-d0fbea58dcd8.png">

unused import error on cli.

2019-09-04 08:36 UTC, Sirmorrison approved these changes

2019-09-04 08:37 UTC, Sirmorrison commented
PR looks good for fyne interface.

2019-09-04 09:08 UTC, merged