[WIP] Add utilities to fetch transactions
raedahgroup/godcr-old pull request #42
Opened 2018-11-25 15:07 UTC by codemaestro64

This adds functions that fetches transactions of a wallet. 

The following are yet to be implemented:

1. CLI interface 
2. Pagination on the web ui

2018-11-29 17:59 UTC, codemaestro64 commented
ready for merge

2018-11-30 19:50 UTC, raedah commented
Pagination is not part of any current spec. Do not over engineer.

2018-12-01 06:11 UTC, itswisdomagain requested changes
You have the core concept, but work isn't (well) done yet. Focus is on displaying individual **transactions**, not **inputs/outputs**.

What information should be displayed for each transaction? The hash, transaction date, amount (sum of all output amounts), maybe from and to addresses, fee and any other potentially relevant info. Compare the Transactions section of the decred block explorer (https://testnet.dcrdata.org/block/00000000bbfafc943e01935d0bb9ae2bf2df204b0c12a8ba9a4cab908f2b6e7c?ind=3) for a clue.

And remember to keep it simple. We do not need plenty info, no need to attempt to extract every possible information. For example, I don't think we need the **details** of the inputs and outputs for each transaction, so the `TransactionSummary`, `TransactionInput` and `TransactionOutput` structs could be removed. We can instead display **number** of inputs and outputs.

2018-12-01 06:11 UTC, itswisdomagain commented on walletrpcclient/walletrpcclient.go
> +func (c *Client) FetchHeaders() (*FetchHeadersResult, error) {
This function is never called. Why do we have it? If it doesn't relate to this PR (fetching transactions), let's do without it. If it does, please explain it's relevance.

If taking off this function, the following will have to be removed as well, as they'd become obsolete:
- `FetchHeadersResult` struct in line 23 of `walletrpcclient/types.go`
-  `c.walletLoaderServiceClient` defined in line 18 and assigned in line 30 of `walletrpcclient/walletrpcclient.go`

2018-12-01 06:11 UTC, itswisdomagain commented on walletrpcclient/types.go
> +type FetchHeadersResult struct {
This might be unnecessary. Refer to my comment on line 215 of `walletrpcclient/walletrpcclient.go`

2018-12-01 06:11 UTC, itswisdomagain commented on walletrpcclient/walletrpcclient.go
> +	walletLoaderServiceClient pb.WalletLoaderServiceClient
This might be unnecessary. Refer to my comment on line 215 of `walletrpcclient/walletrpcclient.go`

2018-12-01 06:11 UTC, itswisdomagain commented on walletrpcclient/walletrpcclient.go
> +	c.walletLoaderServiceClient = pb.NewWalletLoaderServiceClient(conn)
This might be unnecessary. Refer to my comment on line 215 of `walletrpcclient/walletrpcclient.go`

2018-12-01 06:11 UTC, itswisdomagain commented on walletrpcclient/helpers.go
> +func getSummary(blockDetails *BlockDetails) []*TransactionSummary {
This is unnecessary and problematic. What you're doing here is digging deep into each transaction to extract the inputs and outputs.

Then in the web and cli interface, this extracted info is what you display. You're displaying the individual inputs and outputs across all the transactions instead of the transactions themselves.

I'm confident we don't need this. Even if we need to display the individual inputs and outputs in a transaction, it shouldn't be on the transactions page. More so, the decred block explorer site provides this info already so instead of adding another feature here to show individual inputs and outputs, we could just link to the transaction detail page of dcrd explorer (an example: https://testnet.dcrdata.org/tx/3cb931653122a5cbd4ca0874b676ecbd6be3d5178ef587af87a1dc49c044c380)

If you agree that focus should be on **transactions** not **inputs/outputs**, then `MinedTransactions` and `UnminedTransactions` fields in `GetTransactionsResult` would be sufficient. `MinedTransactions` is of type `BlockDetails` which has `Transactions` field, which is an array of `TransactionDetails`. `UnminedTransactions` is itself an array of `TransactionDetails`.

2018-12-04 07:52 UTC, itswisdomagain commented
This is what we currently have for the transactions page on the web interface:
<img width="1280" alt="screen shot 2561-12-04 at 8 49 54 am" src="https://user-images.githubusercontent.com/18400051/49426708-a253db00-f7a1-11e8-9f73-b03bda13652e.png">

Similar to what we have on cli:
<img width="700" alt="screen shot 2561-12-04 at 8 51 49 am" src="https://user-images.githubusercontent.com/18400051/49426790-e21ac280-f7a1-11e8-98c4-14898aefb92e.png">

2018-12-08 17:01 UTC, itswisdomagain commented
We're making progress! Please remember to include screenshots when you update subsequently to give a visual appraisal of what was done. Here's what I capture:

<img width="1280" alt="screen shot 2561-12-08 at 5 50 10 pm" src="https://user-images.githubusercontent.com/18400051/49688410-bedd7380-fb11-11e8-9c10-4913aee435e3.png">

The progress I observe is the table now displays `transaction hash`, `total amount` and `transaction date`

2018-12-08 17:01 UTC, itswisdomagain commented
Immediate observation is that the hash displayed are not transaction hashes but block hashes. With the implication that the amount displayed is the total amount mined in the block which usually will contain a number of other transactions not related to the querying wallet. Same thing with the dates.

The [`dcrwallet` rpc doc](https://github.com/decred/dcrwallet/blob/master/rpc/documentation/api.md#gettransactions) explains that the `getTransactions` call returns `mined_transactions` and `unmined_transactions`

`mined_transactions` is a `BlockDetails` object, that's not what we're looking for exactly. We're looking for `TransactionDetails` objects, which `BlockDetails` contains in `BlockDetails. transactions `.
`unmined_transactions` is itself an array of `TransactionDetails` objects, so yes we need it.

We should now have access to 2 arrays of `TransactionDetails` objects; in `mined_transactions.transactions` and `unmined_transactions`.

If you loop through both arrays, you can get the `hash`, `timestamp` directly from each `TransactionDetails` object. The `TransactionDetails` object also has `outputs` property. If you loop through this property, you can get the total amount in involved in the transaction. There we have what we need, `hash`, `date` and `amount` for each **transaction** belonging to the wallet.

Remember to loop through both `mined_transactions.transactions` and `unmined_transactions`

2018-12-08 17:09 UTC, itswisdomagain commented
Another thing I notice is that each `Output` object in `TransactionDetails.credits` has a boolean property `internal` that informs whether that particular output returned to the wallet. If this property is true, the amount in that output should not be included in the total transaction amount.

2018-12-12 19:33 UTC, closed without merging