Pack fyne icons into godcr-fyne binary
raedahgroup/godcr-old pull request #424
Opened 2019-09-04 21:23 UTC by barisere

This PR packs the images needed by the fyne interface into the release binary. To do this we currently have to first run `packr2` in the `fyne` directory, then run `go build` in the `cmd/godcr-fyne` directory.
This is a partial solution to #423.

2019-09-05 00:44 UTC, itswisdomagain requested changes
Need to include in your PR description and in readme that the `packr` cli utility needs to be installed using `go get -u github.com/gobuffalo/packr/v2/packr2`.

Also need to add `fyne/fyne-packr.go` and `fyne/packrd/` to gitignore.

Please while you're here, delete this dead code that made it's way into master.

2019-09-05 00:44 UTC, itswisdomagain commented on fyne/go.mod
>  replace github.com/raedahgroup/godcr/fyne => ./
This replace directory would likely no longer be needed. I was quite surprised when I noticed that without it, fyne wouldn't build. Now I realize it was because of the incorrect module name at the top of this file.

2019-09-05 00:44 UTC, itswisdomagain commented on fyne/icons.go
> +	"github.com/gobuffalo/packr/v2"
Separate with a space. Likely github imports first, space then fyne imports (g beore f alphabetically)

2019-09-05 00:44 UTC, itswisdomagain commented on fyne/display.go
> +		panic(err)
Should not panic. Use the `app. displayLaunchErrorAndExit` instead.

2019-09-05 00:44 UTC, itswisdomagain commented on fyne/icons.go
> +// var overviewIcon = &fyne.StaticResource{
These can be deleted.

2019-09-05 01:31 UTC, itswisdomagain requested changes
Running `./godcr-fyne` from `./cmd/godcr-fyne` after building (`cd ./cmd/godcr-fyne && go build && ./godcr-fyne`) gives this error: 
`panic: stat /Users/itswisdomagain/go/src/github.com/raedahgroup/godcr/fyne/overview.png: no such file or directory`

When I run `./godcr-fyne` from the project root after building (`go build ./cmd/godcr-fyne && ./godcr-fyne`), I get:
`panic: stat /Users/itswisdomagain/go/src/github.com/raedahgroup/godcr/overview.png: no such file or directory`

2019-09-05 06:23 UTC, barisere commented on fyne/icons.go
> +	"github.com/gobuffalo/packr/v2"
Generally, standard library >> GitHub >> custom domains?

2019-09-09 15:04 UTC, ademuanthony commented
I am unable to build the project
```go: github.com/raedahgroup/dcrlibwallet@v1.1.1-0.20190904121310-90259892e503: unknown revision 90259892e503
go: error loading module requirements
```

2019-09-10 09:09 UTC, barisere commented
@ademuanthony the revision 90259892e503 was somehow erased from the dcrlibwallet history. I think someone force-pushed. I've replaced it with a compatible revision, at least the interfaces look the same and they're from close dates.
Try rebuilding, you may need to delete your local sources and pull this PR afresh.

2019-09-11 20:07 UTC, itswisdomagain commented
This PR should be set to fix/resolve #423 rather than be a partial solution. See https://github.com/raedahgroup/godcr/issues/423#issuecomment-530544179

2019-09-11 21:31 UTC, itswisdomagain requested changes
I see changes to some go.mods and go.sums. The resulting effect is that it is no longer possible to build other interfaces aside fyne.

Also please include the new build steps in your PR description so we don't need to go searching for how to test the features introduced in your PR.

2019-09-11 21:31 UTC, itswisdomagain commented on README.md
> +* To build/install godcr-fyne, you need to install Packr also:
`you need to install Packr first`

2019-09-11 21:31 UTC, itswisdomagain commented on README.md
> +cd cmd/godcr-fyne && go build .
It's also possible to build/install without changing the cwd using `go build ./cmd/godcr-fyne` or `go install ./cmd/godcr-fyne`.

2019-09-11 21:31 UTC, itswisdomagain commented on Makefile
> +.POSIX:
Thought we were going with using a shell script?

2019-09-11 21:36 UTC, itswisdomagain requested changes
`fyne/fyne-packr.go` and `fyne/packrd/packed-packr.go` are generated when `packr2` is run. Those should be gitignored.

2019-09-12 00:08 UTC, itswisdomagain requested changes
There are a couple of unused icons, let's take them out and only (re) introduce them when they will be needed in order to avoid forgetfully leaving stuff in the branch that we never use.

2019-09-12 00:08 UTC, itswisdomagain commented on fyne/display.go
> +		app.displayLaunchErrorAndExit(fmt.Sprintf("An error occured while load app icons: %s", err))
while **loading** app icons

2019-09-12 09:18 UTC, itswisdomagain requested changes

2019-09-12 09:18 UTC, itswisdomagain commented on README.md
> +(cd cmd/godcr-fyne && go install)
This would fail without running `packr2` first.
Also, should be able to run `go install ./cmd/godcr-fyne` from the root dir.

2019-09-12 09:18 UTC, itswisdomagain commented on fyne/icons.go
> +	decredDarkIcon  = "decredDark.png"
These and others like it that are not used should be removed along with the png files.

2019-09-12 12:11 UTC, barisere commented on README.md
> +cd cmd/godcr-fyne && go build .
For `godcr-fyne`, this is temporarily not possible, until the dependencies on dcrlibwallet are synced. For the other binaries it is possible.

2019-09-13 06:24 UTC, itswisdomagain requested changes
https://github.com/raedahgroup/godcr/pull/424/commits/1888dbac8b5a346a4b79475e77d1cd9d7b2d1575 cleared the go mod changes that do not relate to this PR. This PR now builds as documented in the project's readme. Any further changes to the modules setup should be done in a different PR.

For now, just the readme and build.sh files need some corrections to the build instructions and this should be good to merge.

2019-09-13 12:05 UTC, itswisdomagain approved these changes

2019-09-13 12:07 UTC, merged