Create and restore page
raedahgroup/godcr-old pull request #428
Opened 2019-09-16 19:42 UTC by metaclips

This PR implements create and restore wallet page of Godcr-fyne.
<img width="518" alt="Screenshot 2019-09-16 at 7 47 50 PM" src="https://user-images.githubusercontent.com/31141573/64987713-b183bf80-d8c1-11e9-80ff-9821516d99df.png">
<img width="522" alt="Screenshot 2019-09-16 at 7 47 33 PM" src="https://user-images.githubusercontent.com/31141573/64987724-b8123700-d8c1-11e9-95db-1cfa17719daa.png">
<img width="523" alt="Screenshot 2019-09-16 at 7 52 23 PM" src="https://user-images.githubusercontent.com/31141573/64987734-bd6f8180-d8c1-11e9-8288-d2b3ec12cfd6.png">
<img width="522" alt="Screenshot 2019-09-16 at 7 53 00 PM" src="https://user-images.githubusercontent.com/31141573/64987746-c3fdf900-d8c1-11e9-9db9-19b19740213e.png">

Due to #427 to view wallet page create a Godcr folder in AppDir and add create a config.db file in it.

2019-09-24 08:46 UTC, itswisdomagain requested changes

2019-09-24 08:46 UTC, itswisdomagain commented on cmd/godcr-fyne/go.mod
> +	github.com/raedahgroup/godcr/fyne v0.0.0-20190913120727-97da9d1ad9b8
Undo this change. Run `go mod tidy` afterwards.

2019-09-24 08:46 UTC, itswisdomagain commented on fyne/assets/wordlist.txt
> +aardvark
We'll need to move this to dcrlibwallet, it's information that is shared across the various wallet apps.

2019-09-24 08:46 UTC, itswisdomagain commented on fyne/fyne.go
> +func (app *fyneApp) displayLaunchErrorAndExit(errorMessage string) {
Why is this moved away from the `display.go` file? If it must be on this file, it should appear below the `LaunchUserInterface` function.

2019-09-24 08:46 UTC, itswisdomagain commented on fyne/go.mod
> +	fyne.io/fyne v1.0.2-0.20190912194812-5b44bfe4c1aa
Why this change?

2019-09-24 08:46 UTC, itswisdomagain commented on fyne/fyne.go
> +	menu.MenuPage()
Is there a menu page? The menu is but a part of every page, it's not a page of it's own. It's still not clear why the previous codebase was changed and menu moved to pages.go.

2019-09-24 12:53 UTC, metaclips commented on fyne/go.mod
> +	fyne.io/fyne v1.0.2-0.20190912194812-5b44bfe4c1aa
we both discussed about using fyne develop branch, there's an issue which which can't be resolved on masters https://github.com/fyne-io/fyne/issues/443

2019-09-26 21:42 UTC, itswisdomagain requested changes
This looks better than previously. More cleanup required before we get to testing.

2019-09-26 21:42 UTC, itswisdomagain commented on fyne/assets/icons_test.go
> +			AccountsIcon, HistoryIcon, OverviewIcon, ReceiveIcon, SendIcon, StakeIcon, DecredLogo, Reveal, Conceal, Checkmark, CreateNewWallet, RestoreWallet, Wordlist}
Don't really need to test for all icons that are used. Can test with just a few icons to confirm that icon assets can be retrieved if the icons exist in the directory.

2019-09-26 21:42 UTC, itswisdomagain commented on fyne/assets/icons.go
> +	StakeIcon       = "stake.png"
Stake or Staking?

2019-09-26 21:42 UTC, itswisdomagain commented on fyne/assets/icons.go
> +	DecredLogo      = "decred.png"
It's always a good idea to arrange code in the order of usage. `DecredLogo` and the rest of the assets relating to the welcome page should be at the top. There should be a single empty line to separate those from the set of assets used on the nav menu.

2019-09-26 21:42 UTC, itswisdomagain commented on fyne/assets/icons.go
> +var imageBox = packr.New("icons", "../../fyne/assets")
uhmm, isn't this same as `../assets`?

2019-09-26 21:42 UTC, itswisdomagain commented on fyne/display.go
> +	fyne.CurrentApp().Settings().SetTheme(theme.LightTheme())
Undo this theme setting. Setting up godcr/fyne to use themes belongs in a different PR please.

2019-09-26 21:42 UTC, itswisdomagain commented on fyne/display.go
> -	app.tabMenu.SelectTabIndex(0)
Why is this removed?

2019-09-26 21:42 UTC, itswisdomagain commented on fyne/display.go
> +	icons, err := assets.GetIcons(assets.OverviewIcon, assets.HistoryIcon, assets.SendIcon, assets.ReceiveIcon, assets.AccountsIcon, assets.StakeIcon)
This is quite a long line of code, can split into 2 lines.

2019-09-26 21:42 UTC, itswisdomagain commented on go.mod
> +require github.com/raedahgroup/godcr/cmd/godcr-fyne v0.0.0-00010101000000-000000000000 // indirect
Prefer to have require statements before replace statements in go.mods.

2019-09-26 21:42 UTC, itswisdomagain commented on fyne/widgets/clickableIcon.go
> +package widgets
Camel case file names is quite unusual, not sure I've seen it in any go project before. Snake casing works but I've seen all the words just joined together in small letters as one word. `clickableIcon.go` -> `clickable-icon.go` or `clickableicon.go`

2019-09-26 21:42 UTC, itswisdomagain commented on fyne/widgets/clickableIcon.go
> +func NewClickableIcon(res fyne.Resource, shadow fyne.Resource, OnTapped func()) *ClickableIcon {
It's quite customary to have this kind of function immediately below the type declaration before defining methods on the type.

2019-09-26 21:42 UTC, itswisdomagain commented on fyne/pages/createAndRestore.go
> +func shannonEntropy(data string) (entropy float64) {
This will need to be moved to dcrlibwallet/master.

2019-09-26 21:42 UTC, itswisdomagain commented on fyne/pages/createAndRestore.go
> +func (app *AppInterface) createSpendingPasswordPopup(seed string) {
This would need to be a separate, re-usable component that can be used from multiple pages.

2019-09-26 21:42 UTC, itswisdomagain commented on fyne/pages/createAndRestore.go
> +func (app *AppInterface) passwordTab(popup *widget.PopUp, seed string) fyne.CanvasObject {
There's no pin tab anymore, this will likely need to be renamed.

2019-09-26 21:42 UTC, itswisdomagain commented on fyne/pages/createAndRestore.go
> +type AppInterface struct {
Is this meant to be used by all parts of the app? If so, this should go in a different file. I don't see any reason why the type or properties need to be public.

2019-09-27 08:30 UTC, itswisdomagain submitted a review, later dismissed

2019-09-27 08:30 UTC, itswisdomagain commented on fyne/pages/createAndRestore.go
> +	icons, err := assets.GetIcons(assets.Wordlist, assets.Checkmark)
`icons`?
I see we also need to rename `assets.GetIcons` to `assets.Get`, as we're not just returning icons.

2019-09-27 08:47 UTC, itswisdomagain commented
`dcrlibwallet.ShannonEntropy` and `dcrlibwallet.PGPWordList` are added in this dcrlibwallet version: `github.com/raedahgroup/dcrlibwallet v1.1.1-0.20190927084226-1b67c344bb10`

2019-09-29 16:55 UTC, metaclips commented on fyne/pages/createAndRestore.go
> +type AppInterface struct {
most pages need to be accessed as methods

2019-09-29 16:56 UTC, metaclips commented on fyne/display.go
> -	app.tabMenu.SelectTabIndex(0)
Default selected tab index is 0 on start

2019-10-16 10:20 UTC, barisere commented
@metaclips 
I got the following error log.
```
2019/10/16 10:59:54 Fyne error:  Settings watch error:
2019/10/16 10:59:54   Cause: lstat /Users/barisere/Library/Preferences/fyne: no such file or directory
2019/10/16 10:59:54   At: /Users/barisere/go/pkg/mod/fyne.io/fyne@v1.0.2-0.20190912194812-5b44bfe4c1aa/app/settings.go:125
```
Can we prevent this error condition, or handle in a better way? Ensuring the directory/file exists at startup may be appropriate.
@itswisdomagain what do you think?

Also, typing thirty-three words into the boxes in the "restore wallet" section is not a smooth experience. Can we make this easier for the user? I suggest allowing the user to paste the entire phrase from their clipboard, and we break it up into words. They can then verify the words before proceeding.

2019-10-24 07:00 UTC, metaclips commented
The fyne preference setting error would be fixed on a different PR as it's not related to this PR

2019-11-05 21:38 UTC, Sirmorrison requested changes

2019-11-05 21:38 UTC, Sirmorrison commented on fyne/assets/icons.go
> +// Get returns a map from the names of the icons passed as arguments to
`Get` or `GetIcons`? line 37 still uses `GetIcons()`

2019-11-05 21:38 UTC, Sirmorrison commented on fyne/assets/icons.go
> +
Please remove the empty line.

2019-11-05 21:38 UTC, Sirmorrison commented on fyne/fyne.go
>  	"fyne.io/fyne/app"
Please move to line 6. rearrange imports.

2019-11-05 21:38 UTC, Sirmorrison commented on fyne/pages/createAndRestore.go
> +	greenBar.SetMinSize(fyne.NewSize(312, 56))
move in-between 35 and 36

2019-11-05 21:38 UTC, Sirmorrison commented on fyne/pages/createAndRestore.go
> +	blueBar.SetMinSize(fyne.NewSize(312, 56))
Move to line 37 just after `blueBar`

2019-11-05 21:38 UTC, Sirmorrison commented on fyne/pages/createAndRestore.go
> +	restoreLabel := canvas.NewText("Restore an existing wallet", color.White)
`restoreWalletLabel` sounds better.

2019-11-05 21:38 UTC, Sirmorrison commented on fyne/pages/createAndRestore.go
> +	createLabel := canvas.NewText("Create a new wallet", color.White)
`createWalletLabel` sounds better.

2019-11-05 21:38 UTC, Sirmorrison commented on fyne/pages/createAndRestore.go
> +	createWallet := widgets.NewClickableBox(widget.NewVBox(
`createWalletWidget`

2019-11-05 21:38 UTC, Sirmorrison commented on fyne/pages/createAndRestore.go
> +	restoreWallet := widgets.NewClickableBox(widget.NewVBox(
`restoreWalletWidget`

2019-11-05 21:38 UTC, Sirmorrison commented on fyne/pages/createAndRestore.go
> +	createWallet := widgets.NewClickableBox(widget.NewVBox(
Also properly indent parameters for easy readability.

2019-11-05 21:38 UTC, Sirmorrison commented on fyne/pages/createAndRestore.go
> +	restoreWallet := widgets.NewClickableBox(widget.NewVBox(
Also properly indent parameters for easy readability.

2019-11-05 21:38 UTC, Sirmorrison commented on fyne/pages/createAndRestore.go
> +	image := canvas.NewImageFromResource(icons[assets.DecredLogo])
`image`? what image are we talking about? please rename.

2019-11-05 21:38 UTC, Sirmorrison commented on fyne/pages/createAndRestore.go
> +	createAndRestoreButtons := widget.NewVBox(
Also properly indent parameters for easy readability.

2019-11-05 21:38 UTC, Sirmorrison commented on fyne/pages/createAndRestore.go
> +	godcrLabel := canvas.NewText("Welcome to", color.Black)
`godcrLabel` this does not hold `godcr` looks more like a phrase. Please rename as appropriate.

2019-11-05 21:38 UTC, Sirmorrison commented on fyne/pages/createAndRestore.go
> +	godcrLabel.TextSize = 24
Move to Just after `godcrlabel` (line 72)

2019-11-05 21:38 UTC, Sirmorrison commented on fyne/pages/createAndRestore.go
> +
Remove space.

2019-11-05 21:38 UTC, Sirmorrison commented on fyne/pages/createAndRestore.go
> +		widget.NewHBox(image, layout.NewSpacer()),
`image` please check review above.

2019-11-05 21:38 UTC, Sirmorrison commented on fyne/pages/createAndRestore.go
> +	page := widget.NewVBox(
`page`? which Page are we talking about?

2019-11-05 21:38 UTC, Sirmorrison commented on fyne/pages/createAndRestore.go
> +			index := i
`index := i` why doing this? instead `for index := start; index < stop; index++{}` works just fine.
you re doing one thing twice.
`wordlist[index]` and `wordlist[i]` yet `index` and `i` are carrying same values.

2019-11-05 21:38 UTC, Sirmorrison commented on fyne/pages/createAndRestore.go
> +
Remove space.

2019-11-05 21:38 UTC, Sirmorrison commented on fyne/pages/createAndRestore.go
> +		vertical := widget.NewVBox()
`vertical`? please rename.

2019-11-05 21:38 UTC, Sirmorrison commented on fyne/pages/createAndRestore.go
> +		horizontalTextBoxes.Append(vertical)
Line space.

2019-11-05 21:38 UTC, Sirmorrison commented on fyne/pages/display.go
> +package pages
any specific reason why you moved `display.go` to `pages`? As this is against what was intended.

2019-11-05 21:38 UTC, Sirmorrison commented on fyne/pages/display.go
> +
remove space.

2019-11-05 21:38 UTC, Sirmorrison commented on fyne/pages/display.go
> +
remove space.

2019-11-05 22:23 UTC, metaclips commented on fyne/pages/display.go
> +package pages
If wallet doesn’t exist and users have to create a wallet before accessing tabmenu content this would cause issues as tabmenu was defined in fyne package and cant be called from create and restore wallet page after the wallet has been created.

2019-11-05 22:37 UTC, metaclips commented on fyne/pages/createAndRestore.go
> +			index := i
No. This would cause a panic. Variable i is stored on the stack and since the loop ends before the 
https://github.com/raedahgroup/godcr/blob/1e29c57160b45493fdd2a6f17795cf3b51eb585a/fyne/pages/createAndRestore.go#L128 call is made, using the variable i in that function would cause an out of range error.

2019-11-07 06:28 UTC, Sirmorrison requested changes

2019-11-07 06:28 UTC, Sirmorrison commented on fyne/pages/createAndRestore.go
> +	restoreWalletLabel := canvas.NewText("Restore an existing wallet", color.White)
move this to line 54.

2019-11-07 06:28 UTC, Sirmorrison commented on fyne/pages/createAndRestore.go
> +
remove space.

2019-11-07 06:28 UTC, Sirmorrison commented on fyne/pages/createAndRestore.go
> +	welcomeLabel := canvas.NewText("Welcome to", color.Black)
`welcomeTextLabel`

2019-11-07 06:28 UTC, Sirmorrison commented on fyne/pages/createAndRestore.go
> +		var popup *widget.PopUp
`popup` what does this popup holds? please lets explicitly define it.

2019-11-07 06:28 UTC, Sirmorrison commented on fyne/pages/createAndRestore.go
> +	wordlistDropdown := func(start, stop, textboxIndex int, val string) {
`val` do you mean `value`? please rename... what string value are you passing into the function?.

2019-11-07 06:28 UTC, Sirmorrison commented on fyne/pages/createAndRestore.go
> +		popup = widget.NewPopUpMenu(fyne.NewMenu("", menuItem...), app.Window.Canvas())
`popup`

2019-11-07 06:28 UTC, Sirmorrison commented on fyne/pages/spendingpassword.go
> +	var popup *widget.PopUp
`popup` lets be explicit with the variable name. What does the popup hold?

2019-11-07 06:28 UTC, Sirmorrison commented on fyne/pages/spendingpassword.go
> +		log.Println("could not generate seed", err.Error())
`log.Println("Could not generate seed", err.Error())`

2019-11-13 01:31 UTC, beansgum requested changes
1. Create button works with a mismatched password. It's disabled at initial startup and enabled once both passwords are correct but do not get disabled if I alter the confirm password field.

The rest looks fine.

2019-11-13 01:31 UTC, C-ollins commented on fyne/pages/createAndRestore.go
> +		widget.NewLabelWithStyle("Enter your seed phrase in the correct order.", fyne.TextAlignCenter, fyne.TextStyle{Monospace: true}),
This text style should not be monospace.

2019-11-13 06:24 UTC, Sirmorrison commented
Just as mentioned above, when a user inputs correct passwords, the create button is active as should be. But the issue is.. when i delete one of the password values, the create button is still active and it creates the wallet instead of setting the create button to inactive.

![image](https://user-images.githubusercontent.com/27733432/68738386-7a423e00-05e6-11ea-8597-04c247b77f92.png)

2019-11-13 06:28 UTC, Sirmorrison commented
Again to restore wallet, user need seed phrase but not seed phrase was generated when the wallet was created. wondering how wallet will be restored or i'm i missing something?

2019-11-13 15:31 UTC, metaclips commented on fyne/pages/spendingpassword.go
> +		if seed == "" {
@Sirmorrison for restore wallet, the seed phrase is passed  after being verified, if no seed phrase was passed as in case of create new wallet, a seed is generated automaticall

2019-11-13 16:21 UTC, Sirmorrison commented on fyne/pages/spendingpassword.go
> +		if seed == "" {
So what this means is we really dont need seed phrase to restore wallet.

2019-11-13 16:40 UTC, metaclips commented on fyne/pages/spendingpassword.go
> +		if seed == "" {
on restore wallet page, seeds are verified here https://github.com/metaclips/godcr/blob/663cdb33d9ee87062a002eaf20277114da7f0a14/fyne/pages/createAndRestore.go#L151
 if verified, the verified seed is passed in app.createSpendingPasswordPopup(seed) method and this page 
![](https://user-images.githubusercontent.com/31141573/65283147-6a4e3680-db2e-11e9-87b8-6e7960d268b0.png)
 is shown that allows users create spending password when the create button is clicked on it verifies if a Seed was passed, if passed it restores the wallet.
https://github.com/metaclips/godcr/blob/663cdb33d9ee87062a002eaf20277114da7f0a14/fyne/pages/spendingpassword.go#L126

2019-11-13 19:04 UTC, metaclips commented on fyne/pages/createAndRestore.go
> +		widget.NewLabelWithStyle("Enter your seed phrase in the correct order.", fyne.TextAlignCenter, fyne.TextStyle{Monospace: true}),
Fixed. Thanks.

2019-11-18 04:58 UTC, beansgum approved these changes

2019-11-18 04:59 UTC, merged