Reset style
raedahgroup/godcr-old pull request #43
Opened 2018-11-29 09:45 UTC by codemaestro64

2018-11-29 23:44 UTC, itswisdomagain commented
Before:
<img width="1280" alt="screen shot 2561-11-30 at 12 42 17 am" src="https://user-images.githubusercontent.com/18400051/49259234-d85b2d00-f438-11e8-876b-aeb9fcb97ec6.png">

After:
<img width="1280" alt="screen shot 2561-11-30 at 12 40 40 am" src="https://user-images.githubusercontent.com/18400051/49259233-d7c29680-f438-11e8-9f2a-ea50e30767ba.png">

Does this represent the changes made @codemaestro64? Please share more screenshots if there's more...

2018-11-30 06:21 UTC, codemaestro64 commented
@itswisdomagain it does. Changes made as per @raedah 's request.

2018-11-30 20:12 UTC, raedah commented
remove icons

2018-12-01 06:13 UTC, itswisdomagain commented
When done with the requested changes, edit the title to remove [WIP] so I or anyone else available can take it up for review

2018-12-07 04:57 UTC, itswisdomagain commented
@codemaestro64, it'd help to upload screenshots after making changes so we can have a visual rep of what was changed. Here's the latest changes I've noticed:

<img width="1280" alt="screen shot 2561-12-07 at 5 55 57 am" src="https://user-images.githubusercontent.com/18400051/49628535-e84cb100-f9e4-11e8-99ff-cc47d6006160.png">

<img width="1280" alt="screen shot 2561-12-07 at 5 57 04 am" src="https://user-images.githubusercontent.com/18400051/49628537-f26eaf80-f9e4-11e8-8a45-6c90759f59a3.png">

2018-12-07 07:12 UTC, itswisdomagain requested changes
All looks good, just remove the `run.sh` file from git and move the `public` folder to inside the `web` folder (related items should stay together, yeah?)

then update `web.server.go` line 34 to use the new path for the public directory like so:
`filesDir := filepath.Join(workDir, "web/public")`

2018-12-07 07:12 UTC, itswisdomagain commented on run.sh
> +#!/bin/bash
I suppose this is for your personal use, add this file to gitignore and remove it from git history

2018-12-07 07:45 UTC, itswisdomagain approved these changes

2018-12-07 07:45 UTC, merged