Send page input validation
raedahgroup/godcr-old pull request #431
Opened 2019-09-19 12:43 UTC by ademuanthony

This is a split of the #333 
This part worked on input validation and custom input panel toggling

![image](https://user-images.githubusercontent.com/11990092/65244530-ae1b4e80-dae2-11e9-9f5b-254f0843bde6.png)

Users can choose custom input and have the panel collapsed
![image](https://user-images.githubusercontent.com/11990092/65244907-7b258a80-dae3-11e9-8174-4c9312f18a6c.png)

2019-09-19 13:16 UTC, itswisdomagain requested changes

2019-09-19 13:16 UTC, itswisdomagain commented on web/routes/handlers.go
> +		data["error"] = fmt.Errorf("error in parsing request: %s", err.Error())
should return after this

2019-09-19 13:16 UTC, itswisdomagain commented on web/routes/handlers.go
> +		data["error"] = "Address cannot be empty"
cannot -> should not

2019-09-19 13:16 UTC, itswisdomagain commented on web/routes/routes.go
>  	router.Get("/max-send-amount", routes.maxSendAmount)
Add an empty line space before and after the route registrations relating to the send page:
```

router.Get("/send", routes.sendPage)
router.Post("/validate-address", routes.validateAddress)
router.Get("/max-send-amount", routes.maxSendAmount)
router.Post("/send", routes.submitSendTxForm)

```

The routes and their handlers should be registered in the order they will be triggered from the frontend to help a reader of this code better understand the flow. In line with that, the methods should be ordered:

validateAddress
maxSendAmount
submitSendTxForm

2019-09-19 15:11 UTC, itswisdomagain requested changes

2019-09-19 15:11 UTC, itswisdomagain commented on web/static/app/src/controllers/send_controller.js
> +    const editedAddress = event.currentTarget
`editedAddressField`

2019-09-19 15:11 UTC, itswisdomagain commented on web/static/app/src/controllers/send_controller.js
> +      'useCustom', 'toggleCustomInputPnl', 'customInputToggleButton', 'fetchingUtxos', 'utxoSelectionProgressBar', 'customInputsTable', 'utxoCheckbox',
Of these added targets, the only one I see used is `customInputToggleButton`. The others can be removed here and in the html file.

2019-09-19 15:11 UTC, itswisdomagain commented on web/static/app/src/controllers/send_controller.js
> +    const button = event.currentTarget
Can use `event.currentTarget` directly at lines 65 and 68 instead of creating a variable. Also check if it's possible to use `$(this)` instead.

2019-09-19 15:11 UTC, itswisdomagain commented on web/static/app/src/controllers/send_controller.js
> +      $('#custom-inputs').slideDown()
Not sure what is going on here. If it's open, open again?

2019-09-19 16:58 UTC, ademuanthony commented on web/static/app/src/controllers/send_controller.js
> +    const button = event.currentTarget
`this` here is the stimolus controller class

2019-09-20 08:45 UTC, itswisdomagain commented
#333 is merged, this is no longer necessary.

2019-09-20 08:45 UTC, closed without merging