terminal ui: use dcrlibwallet/master
raedahgroup/godcr-old pull request #432
Opened 2019-09-20 21:27 UTC by itswisdomagain

2019-09-28 20:40 UTC, Sirmorrison reviewed
<img width="566" alt="image" src="https://user-images.githubusercontent.com/27733432/65822011-4cbb5400-e235-11e9-84af-acfbcfd41788.png">

Interface doesn't load completely on launch of the terminal interface until a options selected.

2019-09-29 18:36 UTC, Sirmorrison requested changes

2019-09-29 18:36 UTC, Sirmorrison commented on terminal/pages/overview.go
> +		statusCell := tview.NewTableCell(fmt.Sprintf("%12s", status)).
Line space between 153 and 154.

2019-09-29 18:36 UTC, Sirmorrison commented on terminal/pages/receive.go
> +		commonPageData.hintTextView.SetText("TIP: Select PreferredAccount and hit ENTER to generate Address, \n" +
`PreferredAccount` should be `Preferred Account`

2019-09-30 08:26 UTC, itswisdomagain commented on terminal/pages/overview.go
> +		statusCell := tview.NewTableCell(fmt.Sprintf("%12s", status)).
The entire lines 149 to 154 are related, don't see why you want a separation of concerns. They are all related to the status to be displayed on the status cell on the table.

2019-09-30 19:16 UTC, Sirmorrison approved these changes

2019-09-30 19:22 UTC, Sirmorrison requested changes

2019-09-30 19:22 UTC, Sirmorrison commented on cmd/godcr-terminal/terminal.go
> +	terminal.LaunchUserInterface(appDisplayName, defaultAppDataDir, "testnet3")
Why are we hard coding the netType? `testnet3`

2019-09-30 19:34 UTC, itswisdomagain commented on cmd/godcr-terminal/terminal.go
> +	terminal.LaunchUserInterface(appDisplayName, defaultAppDataDir, "testnet3")
It's a temporary stuff, will fix for all interfaces in a subsequent PR.

2019-09-30 19:37 UTC, Sirmorrison requested changes

2019-09-30 19:37 UTC, Sirmorrison commented on terminal/pages/overview.go
> +	listener.updateUI(report)
line space.

2019-09-30 19:37 UTC, Sirmorrison commented on terminal/pages/overview.go
> +	listener.updateUI(report)
line space

2019-09-30 19:37 UTC, Sirmorrison commented on terminal/pages/overview.go
> +	listener.overviewPage.RemoveItem(listener.peerCountTextView)
line space.

2019-09-30 19:49 UTC, Sirmorrison approved these changes
Tested and looks good.

2019-09-30 19:51 UTC, Sirmorrison requested changes
merge conflict please resolve.

2019-10-01 08:20 UTC, Sirmorrison approved these changes

2019-10-01 13:25 UTC, merged