Implemented Fyne receive page.
raedahgroup/godcr-old pull request #437
Opened 2019-10-02 23:53 UTC by Sirmorrison

![](https://user-images.githubusercontent.com/31141573/65394667-a250b600-dd88-11e9-99b2-f13c694200ef.png)

<img width="805" alt="image" src="https://user-images.githubusercontent.com/27733432/66089486-6d5a1580-e577-11e9-9bbe-a2581d87e13b.png">

<img width="807" alt="image" src="https://user-images.githubusercontent.com/27733432/66089502-8236a900-e577-11e9-8c9f-405d3dde9efe.png">

<img width="804" alt="image" src="https://user-images.githubusercontent.com/27733432/66089523-9e3a4a80-e577-11e9-8e54-69761ecf3556.png">

<img width="801" alt="image" src="https://user-images.githubusercontent.com/27733432/66089533-aeeac080-e577-11e9-8f03-1e4e964bbc00.png">

<img width="806" alt="image" src="https://user-images.githubusercontent.com/27733432/66089575-e0638c00-e577-11e9-993b-ab675ce71fff.png">

2019-10-10 06:39 UTC, Sirmorrison commented on fyne/pages/receive.go
> +		checkmarkIcon := widget.NewIcon(theme.ConfirmIcon())
from here.

2019-10-16 09:43 UTC, barisere commented
@Sirmorrison please provide instructions on how to test the changes in this PR. I built the program and ran it, but I could not figure out how to get to the receive page. I got only the following screen.
<img width="479" alt="Screen Shot fyne interface not implemented" src="https://user-images.githubusercontent.com/20553476/66907685-a5466b80-f001-11e9-8c13-f1e4af7b4661.png">

2019-10-16 09:44 UTC, barisere requested changes
@Sirmorrison please provide instructions on how to test the changes in this PR. I built the program and ran it, but I could not figure out how to get to the receive page. I got only the following screen.
<img width="479" alt="Screen Shot fyne interface not implemented" src="https://user-images.githubusercontent.com/20553476/66907685-a5466b80-f001-11e9-8c13-f1e4af7b4661.png">

2019-10-22 11:17 UTC, Sirmorrison commented
This is because you don't have any wallet account. You will need to create a wallet before you will be able to test this PR.

2019-10-22 12:59 UTC, barisere commented
> This is because you don't have any wallet account. You will need to create a wallet before you will be able to test this PR.

No, I do. I had a wallet account before we changed direction on the fyne UI.
@Sirmorrison

2019-10-24 07:02 UTC, metaclips commented
@barisere yes, it seems dcrlibwallet-wip branch and dcrlibwallet master branch detect/creates wallet in different ways

2019-10-24 17:26 UTC, Sirmorrison commented
About the bug notice from the generate new address feature, It is a bug from dcrlibwallet  at it returns the initial wallet address and when generated again, returns a new address.
/Users/macbookair/Desktop/Screenshot 2019-10-24 at 6.19.35 PM.png/Users/macbookair/Desktop/Screenshot 2019-10-24 at 6.20.38 PM.png

2019-10-24 17:28 UTC, Sirmorrison commented
About the bug notice from the generate new address feature, It is a bug from dcrlibwallet at it returns the initial wallet address and when generated again, returns a new address.

2019-10-26 20:28 UTC, metaclips commented
https://user-images.githubusercontent.com/27733432/66244031-8ccf7a80-e6fe-11e9-9e8c-c21a77054790.png
we should instead increase the height of the popup instead of the width

2019-10-26 21:00 UTC, metaclips requested changes
Spendable label text and amount color shouldn't be in black.

2019-10-26 21:00 UTC, metaclips commented on fyne/pages/receive.go
> +const pageTitleText = "Receive DCR"
Do we need this? receivingDecredHint and pageTitleText variables are only used in the ReceivePageContent function, there is really no use making it a package level variable.

2019-10-26 21:00 UTC, metaclips commented on fyne/pages/receive.go
> +func ReceivePageContent(dcrlw *dcrlibwallet.LibWallet, window fyne.Window, tabmenu *widget.TabContainer) fyne.CanvasObject {
why are we declaring a struct outside a function and also passing function parameters in ReceivePageContent? only widgets that needs to be updated and refreshed by other functions should be defined outside the ReceivePageContent function.

2019-10-26 21:00 UTC, metaclips commented on fyne/pages/receive.go
> +	generateAddress := func(generateNewAddress bool) {
Can we move this to generateAddressAndQrCode?

2019-10-26 21:00 UTC, metaclips commented on fyne/pages/receive.go
> +		accountsView := widget.NewHBox(
accountsView? can we be more explicit?

2019-10-26 21:00 UTC, metaclips commented on fyne/pages/receive.go
> +		accountWidget := widgets.NewClickableBox(accountsView, func() {
we should probably change the variable name to something better.

2019-10-26 21:00 UTC, metaclips commented on go.sum
>  github.com/decred/dcrd/rpcclient v1.0.1/go.mod h1:tApXK3wwrAQtz7lcXeeqBwuktUZesvrFfvhAdedYqdM=
go mod tidy

2019-10-26 21:20 UTC, metaclips commented
Can we make popup width same as the account selector so as to allow uniformity?

2019-11-01 00:34 UTC, metaclips commented
https://user-images.githubusercontent.com/27733432/67986619-bb704080-fc2b-11e9-9461-61c5b2fef594.png

We should right align balance label and left align account name and spendable label.

2019-11-01 00:41 UTC, metaclips commented
![IMAGE 2019-11-01 01:40:44](https://user-images.githubusercontent.com/31141573/67995022-9fc76300-fc48-11e9-8fa1-4fa41b85c8a8.jpg)
We should right align balance label with the checkmark icon and left align account name and spendable label.

2019-11-04 07:00 UTC, Sirmorrison commented
> ![image](https://user-images.githubusercontent.com/31141573/67995053-ba014100-fc48-11e9-9117-a3da55c9c9f9.png)
> 
> We should right align balance label with the checkmark icon and left align account name and spendable label.

icons cannot be aligned left or right.

2019-11-04 11:00 UTC, metaclips commented
Account dropdown content isn't correctly aligned, I think to do this we'll need to implement tables, this would be treated on a different PR.

2019-11-04 11:11 UTC, metaclips approved these changes
Tested locally and approved by me.

2019-11-04 18:41 UTC, merged