Fyne send page Implementation
raedahgroup/godcr-old pull request #457
Opened 2019-11-27 00:40 UTC by metaclips

This PR implements send page and adds custom button widget and Box layout with varied space sizes to godcr-fyne, solves https://github.com/raedahgroup/godcr/issues/451

<img width="1680" alt="Screenshot 2019-11-27 at 01 26 24" src="https://user-images.githubusercontent.com/31141573/69683639-d496d080-10b5-11ea-8e2f-58f14c4f5ba8.png">
<img width="1680" alt="Screenshot 2019-11-27 at 01 26 42" src="https://user-images.githubusercontent.com/31141573/69683648-dcef0b80-10b5-11ea-8e37-d0f31ee59d19.png">
<img width="1680" alt="Screenshot 2019-11-27 at 01 26 54" src="https://user-images.githubusercontent.com/31141573/69683663-e5474680-10b5-11ea-8947-c3217822d5f4.png">
<img width="1680" alt="Screenshot 2019-11-27 at 01 27 21" src="https://user-images.githubusercontent.com/31141573/69683672-ea0bfa80-10b5-11ea-9a68-67db4a485dcb.png">
<img width="1680" alt="Screenshot 2019-11-27 at 01 27 41" src="https://user-images.githubusercontent.com/31141573/69683922-ce552400-10b6-11ea-8960-2e94e982494f.png">
<img width="1680" alt="Screenshot 2019-11-27 at 01 27 55" src="https://user-images.githubusercontent.com/31141573/69683687-01e37e80-10b6-11ea-994d-ebc56bfe7be1.png">
<img width="1680" alt="Screenshot 2019-11-27 at 01 28 15" src="https://user-images.githubusercontent.com/31141573/69683697-07d95f80-10b6-11ea-835a-5b03cf525349.png">

2019-11-30 21:55 UTC, C-ollins commented on fyne/pages/send.go
> +		if sendToAccountLabel.Text == "Send to account" {
Use a boolean for this instead

2019-11-30 23:11 UTC, beansgum requested changes
The following issues need attention.
1. There're a lot of numbers(dimensions) in this file, move `send.go` into its own folder `pages/send/send.go` and also create a new file it `dimensions.go` and declare all your dimensions in it as constants.
2. A global string file should be created to house all the strings used, in this project. Place all strings in the file as constants and import the file wherever strings are needed.
3. Estimates should not be shown if destination address input contains an invalid address.
4. The window size should be the same as the page size.
5. The page title should not be in italics.
6. Put a border around the account selector and remove the line from "From" and "To".
7. Most of the colors used do not match the mockup.

2019-11-30 23:11 UTC, beansgum commented on fyne/pages/send.go
> +		if sendToAccountLabel.Text == "Send to account" {
Use a boolean for this instead.
`if selfSendingToAccountGroup.Hidden {`

2019-11-30 23:11 UTC, beansgum commented on fyne/pages/send.go
> +			amountErrorLabel.Text = "Not enough funds (or not connected)."
This error message should be used only for `insufficient_funds` error and "(or not connected)" should be added only if wallet is not synced. Some other errors can also be thrown here.

2019-11-30 23:11 UTC, beansgum commented on fyne/pages/send.go
> +func sendPageContent(multiWallet *dcrlibwallet.MultiWallet, window fyne.Window) (pageContent fyne.CanvasObject) {
The entire send page was created in this function, it should be broken down into smaller reusable functions to reduce the possibility of running into a bug. I'd suggest a function each for source account, destination account/address, amount input + fee estimates & lastly total cost + balance after sending.

2019-11-30 23:11 UTC, beansgum commented on fyne/pages/send.go
> +		transactionAuthor.AddSendDestination(temporaryAddress, 0, true)
This same estimation is repeated on Lines 116 & 117, a function should handle estimation.

2019-11-30 23:11 UTC, C-ollins commented on fyne/pages/send.go
> +			if err.Error() == "insufficient_balance" {
Use the dcrlibwallet reference here. `dcrlibwallet.ErrInsufficientBalance`

2019-11-30 23:11 UTC, C-ollins commented on fyne/pages/send.go
> +				if err.Error() == "invalid_passphrase" {
`dcrlibwallet.ErrInvalidPassphrase`

2019-12-21 00:52 UTC, beansgum approved these changes

2019-12-21 00:54 UTC, merged