Overview 446
raedahgroup/godcr-old pull request #461
Opened 2019-12-10 23:32 UTC by oshorefueled

This PR replaces total balance and recent transactions dummy data on overview page with live data. Closes issue #446 
<img width="647" alt="Screenshot 2019-12-11 at 12 30 54 AM" src="https://user-images.githubusercontent.com/15804688/70578311-9a492b00-1bad-11ea-8c83-cdec3928f354.png">

2019-12-12 13:53 UTC, Sirmorrison requested changes

2019-12-12 13:53 UTC, Sirmorrison commented on fyne/pages/overview.go
> +	"time"
Re arrange imports.
"fmt"
.
.
"time"

"fyne.io/fyne"
.
.
.
"fyne.io/fyne/widget"

"github.com/decred/dcrd/dcrutil"
.
.
.
"github.com/raedahgroup/godcr/fyne/widgets"

2019-12-12 17:40 UTC, Sirmorrison requested changes

2019-12-12 17:40 UTC, Sirmorrison commented on fyne/pages/overview.go
> +		ov.walletIds = ov.multiWallet.OpenedWalletIDsRaw()
i think just `Overview.app = app` will perform same action. I really dont see the need for line 35.

2019-12-12 17:40 UTC, Sirmorrison commented on fyne/pages/overview.go
>  type Overview struct {
why is `Overview` a global variable? i think it should be `overview`

2019-12-12 17:40 UTC, Sirmorrison commented on fyne/pages/overview.go
> +	tb, err := totalBalance(ov)
`tb`? please be explicit.

2019-12-12 17:40 UTC, Sirmorrison commented on fyne/pages/overview.go
> +		timeDate := time.Unix(txn.Timestamp, 0).Format("2006-01-02")
`dcrlibwallet.ExtractDateOrTime(txn.Timestamp)`

2019-12-12 17:40 UTC, Sirmorrison commented on fyne/pages/overview.go
> +}
`dcrlibwallet.TransactionDirectionName(txn.Direction)` covers for this if im not mistaking.

2019-12-12 17:40 UTC, Sirmorrison commented on fyne/pages/overview.go
> +			transactionDirection(txn.Direction), status, timeDate))
`dcrlibwallet.TransactionDirectionName(txn.Direction)`

2019-12-12 17:40 UTC, Sirmorrison commented on fyne/pages/overview.go
>  }
add empty line here.

2019-12-12 17:40 UTC, Sirmorrison commented on fyne/pages/overview.go
> +	}
everything here can be moved to `recentTransactionBox ()` since it isn't used anywhere else and its just 3 lines.

```
  status := "Pending"
  confirmations := overview.multiWallet.GetBestBlock().Height - txn.BlockHeight + 1
  if tx.BlockHeight != -1 && confirmations > dcrlibwallet.DefaultRequiredConfirmations {
         status = "Confirmed"
 }
`

2019-12-12 22:44 UTC, oshorefueled commented on fyne/pages/overview.go
> +		ov.walletIds = ov.multiWallet.OpenedWalletIDsRaw()
`ov := &Overview{}` initializes an empty Overview pointer to variable "ov". How would 
`Overview.app` work? It's not a valid go statement.

> i think just `Overview.app = app` will perform same action. I really dont see the need for line 35.

2019-12-12 23:11 UTC, oshorefueled commented on fyne/pages/overview.go
> +	tb, err := totalBalance(ov)
Golang permits the use of short variables, especially when they're local variables, just like I did within the "balance" method. From the code, you can tell that "tb" simply means "totalBalance". You can check this link for more info on that. https://github.com/golang/go/wiki/CodeReviewComments#variable-names

2019-12-12 23:31 UTC, oshorefueled commented on fyne/pages/overview.go
> +	}
> everything here can be moved to `recentTransactionBox ()` since it isn't used anywhere else and its just 3 lines.
> 
> ```
>   status := "Pending"
>   confirmations := overview.multiWallet.GetBestBlock().Height - txn.BlockHeight + 1
>   if tx.BlockHeight != -1 && confirmations > dcrlibwallet.DefaultRequiredConfirmations {
>          status = "Confirmed"
>  }
> `
> ```

When writing clean code, you should try your possible best to make your functions do just one thing. It makes it easy to know what part of the code does what. Also if I were to add another feature sometime in the future that needs a transaction status, I can simply reuse the function.

2019-12-13 05:59 UTC, Sirmorrison requested changes

2019-12-13 05:59 UTC, Sirmorrison commented on fyne/pages/overview.go
>  	"image/color"
move under "time"

2019-12-13 06:31 UTC, Sirmorrison commented
![image](https://user-images.githubusercontent.com/27733432/70774431-93234800-1d7a-11ea-857b-19b9bd861d2b.png)


i get this panic while trying to run your PR.

2019-12-15 09:48 UTC, beansgum approved these changes

2019-12-15 09:49 UTC, merged