implement exit page
raedahgroup/godcr-old pull request #468
Opened 2019-12-25 11:13 UTC by metaclips

<img width="654" alt="Screenshot 2019-12-25 at 12 12 47" src="https://user-images.githubusercontent.com/31141573/71444216-e8167500-270f-11ea-907e-25536a642b53.png">
Fixes #467

2019-12-25 13:26 UTC, oshorefueled commented
The app successfully exits when I click "Yes" on the exit popup. However, when I click "No" on a page other than the overview page, the popup disappears but takes me to the overview page. The app should remain on the same page after clicking the "No" button.

2019-12-25 13:28 UTC, oshorefueled requested changes

2019-12-25 13:28 UTC, oshorefueled commented on fyne/pages/exit.go
> +		fmt.Println("Exited fyne")
This should be logged

2019-12-25 13:33 UTC, metaclips commented
> The app successfully exits when I click "Yes" on the exit popup. However, when I click "No" on a page other than the overview page, the popup disappears but takes me to the overview page. The app should remain on the same page after clicking the "No" button.

What would be shown on exit page if the popup closes?  Showing an empty page on clicking No doesn't really seem right to be honest.

2019-12-25 13:46 UTC, oshorefueled commented
> > The app successfully exits when I click "Yes" on the exit popup. However, when I click "No" on a page other than the overview page, the popup disappears but takes me to the overview page. The app should remain on the same page after clicking the "No" button.
> 
> What would be shown on exit page if the popup closes? Showing an empty page on clicking No doesn't really seem right to be honest.

ideally, the popup should not be a page, but just a popup capable of being visible on any page. But in a case where this isn't possible as a result of fyne's limitations, you can just go back to the previous page. It should give the same effect as if the user never left the page.

2020-01-07 10:54 UTC, oshorefueled approved these changes

2020-01-07 10:54 UTC, merged