./dcrcli help - WIP
raedahgroup/godcr-old pull request #63
Opened 2018-12-16 02:58 UTC by ademuanthony

Added a './dcrcli help [command]' command that shows general help message or specific help message when called with the optional [command] param

2018-12-17 20:25 UTC, itswisdomagain requested changes

2018-12-17 20:25 UTC, itswisdomagain commented on cli/handlers.go
> +		res.result = append(res.result, []interface{}{additionalHelp})
aside from `header` and `additionalHelp`, the rest of the help message content can be printed by calling `PrintHelp(c.appName)`, to avoid code repetition.

also, there's a new idea suggested in #54 (https://github.com/raedahgroup/dcrcli/issues/54#issuecomment-447550604), that proposes that command handlers no longer return a response object, thus allowing each command the freedom to display their output messages as best appropriate.

for now, this command could return nil for `res` and do all the needed printing here.

2018-12-17 20:25 UTC, itswisdomagain commented on cli/commands.go
> +		{"history", "show your transaction history", "", transactionHistory},
I think the usage here is `dcrcli history`

2018-12-17 20:25 UTC, itswisdomagain commented on cli/commands.go
> +		{"history", "show your transaction history", "", transactionHistory},
something I've noticed about the `usage` for all commands is, it's basically same as concatenating the app name `dcrcli` with the command name `send` (for example)

if we can "construct" the usage from what we already have, there might be no need to have a separate property for it in the `command` struct

2018-12-17 20:25 UTC, itswisdomagain commented on cli/commands.go
> +		{"history", "show your transaction history", "", transactionHistory},
In line with #53, what I think might be worth introducing is a boolean `experimental` property, and also a means to track information about required and optional command arguments that may be used with each command.

An example is the receive command. That command accepts an account number argument by default. e.g `dcrcli receive 0`. If no argument is passed, the user is prompted to select an account.
I'm thinking the extended help for the receive command should indicate that this command works with an optional argument.

2018-12-17 20:29 UTC, itswisdomagain commented on cli/commands.go
> +		{"history", "show your transaction history", "", transactionHistory},
The arguments to a command could also be a flag (for boolean arguments) such as `-l/--list` or `-e/--extended` for the use case presented in #49

2018-12-17 21:40 UTC, ademuanthony commented on cli/commands.go
> +		{"history", "show your transaction history", "", transactionHistory},
I was thinking it may be easier to provide the usage since some commands may require addition args, options/flags and may even have sub-commands in future

2018-12-18 08:23 UTC, itswisdomagain requested changes
Took my first real dive into this PR. Here are some thoughts to consider...

2018-12-18 08:23 UTC, itswisdomagain commented on cli/commands.go
> +		{"history", "show your transaction history", "", transactionHistory},
You're right, it may be easier. Not sure though. But I'm inclined to go that way (for now). With this approach, command usages will need to provide information on required/optional options/flags, such as the `receive` command explained above. So maybe we can start with that, let's make the usage description for the receive command show it's optional argument.

Also, history command does not have any usage text yet...

2018-12-18 08:23 UTC, itswisdomagain commented on cli/handlers.go
> +		header := "Dcrcli is a command-line utility that interfaces with Dcrwallet rpc's methods.\n"
We've preferred not hardcoding the app name since it could (will likely) change in the future, there should be another way to use the "foolproof" app name stored in the `cli` struct

2018-12-18 08:23 UTC, itswisdomagain commented on cli/handlers.go
> +		header := "Dcrcli is a command-line utility that interfaces with Dcrwallet rpc's methods.\n"
Also, dcrwallet rpc is just one possible means by which dcrcli interfaces with a decred wallet. Another mode of interfacing is in the works, we should probably adjust this help text accordingly, you know, not limit it to just dcrwallet rpc.

2018-12-18 08:23 UTC, itswisdomagain commented on cli/handlers.go
> +		additionalHelp := "\nUse \"dcrcli help <command>\" for more information about a command."
Same comment about hardcoded app name applies here also

2018-12-18 08:23 UTC, itswisdomagain commented on cli/handlers.go
> +		PrintHelp("")
calling `HelpMessage()` gives you the string representation of the current help information, that might be more readable in this context, seeing as `header` and `additionalHelp` are declared then printed.

It'd aid readability to also have something like `help := HelpMessage()` after `header` and before `additionalHelp`

2018-12-18 08:23 UTC, itswisdomagain commented on cli/handlers.go
> +				found = true
`found` is not necessary, to know if the command was found later, you can check if `command == nil`
also, you should `break` once you find the command you're looking for, really no need to keep the loop going

2018-12-18 08:23 UTC, itswisdomagain commented on cli/handlers.go
> +		cmdText := commandArgs[0]
`cmdText` might be better called `cmdName`, line 218 helps with this line of thought

2018-12-18 08:23 UTC, itswisdomagain commented on cli/handlers.go
> +		return &response{}, nil
This return is unnecessary in my opinion
if you do not return anything here, the program continues to after the if/else block and just returns, thus using the named return variables, which will be nil (and that's fine, to be expected)

the only change this would require is a change to line 83 of `cli.go` (`RunCommand` fn), there should be a check if `res != nil` before a print is attempted. Other PRs already do this check in recognition of the fact that command handlers would no longer need to return a response, since each handler would ideally (going forward) print their own successful responses and only return an error otherwise for the `RunCommand` fn to handle.

Once all handlers have been modified to print their own success messages, we'd revisit the signature of the `handler` struct to remove the first return object.

2018-12-18 08:23 UTC, itswisdomagain commented on cli/handlers.go
> +		res = &response{
In line with one of the comments above, let's print the "success" message here directly, and return nil for `res`

2018-12-18 08:23 UTC, itswisdomagain commented on cli/handlers.go
> +		res = &response{
A thought.... can we do without the empty line space for usage text?
<img width="377" alt="screen shot 2561-12-18 at 9 18 41 am" src="https://user-images.githubusercontent.com/18400051/50140767-1c0dbd80-02a6-11e9-9e79-cad7e857c46e.png">

Put it in 1 line like `Usage: dcrcli receive` instead? I don't think it hurts readability but if you think otherwise, we should leave it as is.

2018-12-18 08:23 UTC, itswisdomagain commented on cli/help.go
> +		columns: []string{prefix + "dcrcli [OPTIONS] <command> [<args...>]\n\nAvailable commands:"},
`prefix` was supposed to hold the app name where necessary, to prevent hardcoding the app name. hardcoding it yet, produces this effect when you run `dcrcli -h`
<img width="395" alt="screen shot 2561-12-18 at 9 21 31 am" src="https://user-images.githubusercontent.com/18400051/50140905-70b13880-02a6-11e9-851f-c135eb065b6c.png">

2018-12-18 11:19 UTC, ademuanthony commented on cli/handlers.go
> +				found = true
I cannot do `command == nil` as `command` is not nullable

2018-12-19 12:39 UTC, itswisdomagain commented
The area in red looks off...
![screenshot 2018-12-19 at 1 36 23 pm](https://user-images.githubusercontent.com/18400051/50220645-3376a480-0393-11e9-80fa-f67e0893ea4c.png)

2018-12-19 12:43 UTC, itswisdomagain commented
Would it hurt readability to take off the empty line space?
![screenshot 2018-12-19 at 1 39 13 pm](https://user-images.githubusercontent.com/18400051/50220806-9bc58600-0393-11e9-83c5-92a22fe0fba5.png)

Also, the receive usage text can benefit from the pattern established above. Instead of `Usage: dcrcli receive [<args...>]`, how about being more specific about what "args..." is/are like `Usage: dcrcli receive [account number]` or `Usage: dcrcli receive [account]`

I prefer the latter, as I also want to suggest we allow users enter account names OR account numbers. dcrwallet rpc has a method to retrieve account number using account name. And users would/may find it easier to remember account name than account number. Will create a separate issue for that with @raedah's approval.

2018-12-19 12:51 UTC, itswisdomagain commented
There's a concept of short and long description for each command. I think (hope) @barisere's research into supporting command options (amongst other things) will bring this to life.

It'd come in quite handy for this use case, showing the short description when listing all the commands in response to the `dcrcli help` command, while showing the long description when responding to `dcrcli help [command]`

Something like the `send` command would especially benefit from this. When a user requests "detailed" help for the `send` command, it would be "helpful" to mention that the command would require certain information progressively, such as the source/sending account, amount to send, address(es) to send to and the private passphrase for the wallet.

2018-12-19 12:58 UTC, itswisdomagain requested changes

2018-12-19 12:58 UTC, itswisdomagain commented on cli/handlers.go
> +		additionalHelp := "\nUse \"dcrcli help <command>\" for more information about a command."
`additionalHelp` still uses hardcoded app name

2018-12-19 12:58 UTC, itswisdomagain commented on cli/handlers.go
> +				found = true
Now that you mention it, we should make `supportedCommands()` return `[]*command`. Using a pointer really makes more sense.

Then you can make type of command `*command` and then you can perform a nil check

2018-12-19 20:07 UTC, ademuanthony commented
> There's a concept of short and long description for each command. I think (hope) @barisere's research into supporting command options (amongst other things) will bring this to life.
> 
> It'd come in quite handy for this use case, showing the short description when listing all the commands in response to the `dcrcli help` command, while showing the long description when responding to `dcrcli help [command]`
> 
> Something like the `send` command would especially benefit from this. When a user requests "detailed" help for the `send` command, it would be "helpful" to mention that the command would require certain information progressively, such as the source/sending account, amount to send, address(es) to send to and the private passphrase for the wallet.

Should we add this to the command struct and use it to kind add full documentation for each command? Like to try and explain all the options and args (both required and optional ones) for each command

2018-12-19 20:17 UTC, ademuanthony commented
![help-screen-211912](https://user-images.githubusercontent.com/11990092/50245708-7a848a00-03d3-11e9-8fb5-8b5f556346f0.png)

2018-12-20 05:18 UTC, itswisdomagain requested changes

2018-12-20 05:18 UTC, itswisdomagain commented on cli/handlers.go
> +		writeHelpMessage(fmt.Sprintf("Usage: \n%s", c.appName), writer)
Could use a single space after app name, the output currently jams it all up

2018-12-20 05:18 UTC, itswisdomagain commented on cli/handlers.go
> +			return nil, fmt.Errorf("Invalid command, %s", cmdName)
comma or colon, I think colon
`invalid command: received`, instead of `invalid command, recieved`

2018-12-20 05:18 UTC, itswisdomagain commented on cli/handlers.go
> +			return nil, fmt.Errorf("Invalid command, %s", cmdName)
comma or colon, I think colon
`invalid command: received`, instead of `invalid command, received`

2018-12-20 06:15 UTC, ademuanthony commented
![072012-help](https://user-images.githubusercontent.com/11990092/50267284-07a4fe80-0427-11e9-807e-1cfb19f7d9b5.png)

2018-12-20 10:40 UTC, itswisdomagain commented
> Should we add this to the command struct and use it to kind add full documentation for each command? Like to try and explain all the options and args (both required and optional ones) for each command

Yes please. Also, the current short descriptions might need some work. For example, @raedah pointed out how unhelpful the description for the balance command is:
`balance | show your balance`
That could probably be `shows total balance for each account in wallet`, long description could go on to say, `also shows spendable balance if different from total balance. Use -e/--extensive to view a more detailed balance breakdown`

_forgive this coming late, I wrote the comment hours ago with the other review but somehow did not hit the comment button_

2018-12-21 09:00 UTC, ademuanthony commented
Resolved conflict

2018-12-22 08:31 UTC, itswisdomagain requested changes
1 small mixup in the latest changes. Also remember to give attention to my last comment about better short and long descriptions for each command

2018-12-22 08:31 UTC, itswisdomagain commented on cli/commands.go
> +		{"send-custom", "send a transaction, manually selecting inputs from unspent outputs", "dcrcli send-custom", customSend, false},
This ought to be experimental. Probably made the mistake when fixing conflicts

2018-12-22 08:54 UTC, itswisdomagain commented
We can borrow some of your recent work on #64, wrt providing a "better" way to access the `AppName` and thus stick to the principle of least privileges, passing on `walletrpcclient` to the command handlers and not the entire `cli` struct.

When that PR is merged, this change would become inevitable. Why not we do it now?

2018-12-22 09:45 UTC, itswisdomagain commented
Should we put this PR on pause? There's some interesting work going on with #71 that would alter how the commands are currently structured and probably make it easier for the command-specific help command to work as expected. @ademuanthony please take a look at that PR and share your thoughts

2018-12-22 12:43 UTC, ademuanthony commented
> Should we put this PR on pause? There's some interesting work going on with #71 that would alter how the commands are currently structured and probably make it easier for the command-specific help command to work as expected. @ademuanthony please take a look at that PR and share your thoughts

The work going on at [71](https://github.com/raedahgroup/dcrcli/pull/71) will change a lot of things. 
I think we should pause this until that is done

2018-12-25 11:12 UTC, itswisdomagain commented
The PR (#71) that was blocking this has been completed and merged. Work on this can continue. When it's ready for review, rename the PR to remove the [WIP] label

The changes in #71 includes detailed help message printing with `dcrcli -h` and command-specific help message printing with `dcrcli <command> -h`. After conferring with @raedah, this PR remains relevant: the goal as mentioned in issue #51 is to introduce a new command `dcrcli help`. The expected behaviour of this new command would be similar to `dcrcli -h` and `dcrcli <command> -h`

**Next steps for this PR**
- **Regarding `dcrcli help`**, I think the output of `dcrcli -h` is okay as is, so `dcrcli help` can simply trigger that functionality.
- **Regarding `dcrcli help <command>`**, the similar syntax (`dcrcli <command> -h`) isn't exactly there yet. This PR _may_ not need to alter the functionality of `dcrcli <command> -h`, it probably should instead focus on achieving the concept expressed below for `dcrcli help <command>`

**Expected behaviour for `dcrcli help <command>`**
- [From this comment](https://github.com/raedahgroup/dcrcli/pull/63#issuecomment-448583095):
`dcrcli help <command>` should clearly show the kind of arguments `<command>` works with. For example, `dcrcli help receive` should show `Usage: dcrcli receive [account]`

- [From this comment](https://github.com/raedahgroup/dcrcli/pull/63#issuecomment-448585542):
`dcrcli help <command>` should include additional information that describe how the command works. For example, `dcrcli help send` should mention that `the command would require certain information progressively, such as the source/sending account, amount to send, address(es) to send to and the private passphrase for the wallet`

- [From this comment](https://github.com/raedahgroup/dcrcli/pull/63#issuecomment-448952265):
`dcrcli help <command>` should give information about flags/options that `<command>` works with. For example, `dcrcli help balance` should show `Usage: dcrcli balance [-d/--detailed]`. It should go on to explain what `-d/--detailed` does: `Display detailed account balance report`

PS: The behaviour depicted above are not hard and fast rules, just how I imagine/expect a verbose help message to appear. Alternative/supplementary ideas are definitely welcome

2018-12-25 12:47 UTC, barisere commented
>     * **Regarding `dcrcli help <command>`**, the similar syntax (`dcrcli <command> -h`) isn't exactly there yet. This PR _may_ not need to alter the functionality of `dcrcli <command> -h`, it probably should instead focus on achieving the concept expressed below for `dcrcli help <command>`
> 
> 
> **Expected behaviour for `dcrcli help <command>`**
> 
>     * [From this comment](https://github.com/raedahgroup/dcrcli/pull/63#issuecomment-448583095):
>       `dcrcli help <command>` should clearly show the kind of arguments `<command>` works with. For example, `dcrcli help receive` should show `Usage: dcrcli receive [account]`

```
$ ./dcrcli -C dcrcli.conf receive -h
Usage:
  dcrcli [OPTIONS] receive [account]
To view application options, use 'dcrcli -h'
```
[OPTIONS] is printed because the top-level application options are still relevant for running the command. The last line of the message tells the user how to view those options.
>     * [From this comment](https://github.com/raedahgroup/dcrcli/pull/63#issuecomment-448585542):
>       `dcrcli help <command>` should include additional information that describe how the command works. For example, `dcrcli help send` should mention that `the command would require certain information progressively, such as the source/sending account, amount to send, address(es) to send to and the private passphrase for the wallet`

The additional information you speak of can be placed in the `long-description` struct tag of the command. If you add `long-description` tag to `BalanceCommand` as follows, you get that additional information in the help output for `balance`.
```go
type CliCommands struct {
	Balance    BalanceCommand    `command:"balance" description:"show your balance" long-description:"Voluptate sunt consectetur eiusmod nulla tempor et amet non nostrud nulla consequat cillum aute laborum"`
	// other commands
}
```
```
$ ./dcrcli -C dcrcli.conf balance -h
Usage:
  dcrcli [OPTIONS] balance [balance-OPTIONS]

Voluptate sunt consectetur eiusmod nulla tempor et amet non nostrud nulla consequat cillum aute laborum

[balance command options]
      -d, --detailed  Display detailed account balance report
To view application options, use 'dcrcli -h'
```
Observe that the long description is shown for command-specific help, while the short description is shown for the top-level (overview) help.
It may be a good idea to make the short description the first sentence of the long description.
>     * [From this comment](https://github.com/raedahgroup/dcrcli/pull/63#issuecomment-448952265):
>       `dcrcli help <command>` should give information about flags/options that `<command>` works with. For example, `dcrcli help balance` should show `Usage: dcrcli balance [-d/--detailed]`. It should go on to explain what `-d/--detailed` does: `Display detailed account balance report`
> 
See the output of `$ ./dcrcli -C dcrcli.conf balance -h` above. The information about flags/options are included in the help output.

2018-12-30 11:38 UTC, itswisdomagain commented
@ademuanthony regarding this https://github.com/raedahgroup/godcr/pull/86#issuecomment-450521416:

> Though the circular dependency still continues for my current use case as I want to reference the CliRoot in the cli package in commands; whereas the cli package already references the commands package.
> 
> So I am thinking, what if the commands are moved to the cli package, seeing that that is the main component in that package, it may not be that bad to have it at the root.
> It may look like we will lose the organization that the current structure provides, but with the current convention of adding 'Command' suffix to the command names, I think it makes sense enough to have cli.SendCommand

Can you the share the code snippet where you use `CliRoot` in the `cli` package. I had similar circular dependency issue while working on #88, may be able to offer some assistance

2018-12-31 16:00 UTC, ademuanthony commented
I have continued this work at https://github.com/raedahgroup/godcr/pull/98

2018-12-31 16:54 UTC, closed without merging