WIP - detect if dcrcli.conf is not configured
raedahgroup/godcr-old pull request #64
Opened 2018-12-17 02:02 UTC by ademuanthony

fixes [#50](https://github.com/raedahgroup/dcrcli/issues/50)
If the config file is not found and the user did not pass Dcrwallet credentials in command line options, propose to guide the user in creating a new config file and do same if the user accepts, else quit the application

2018-12-17 20:14 UTC, barisere requested changes
You've done good work here. Let's tie up loose edges so we can merge this PR.

2018-12-17 20:14 UTC, barisere commented on config.go
> +				fmt.Fprintln(os.Stderr, fmt.Sprintf(`The config file, %s is missing and you did not pass the Dcrwallet RCP credetial in command line options.\n`, preCfg.ConfigFile))
Using backticks around the string creates an unescaped string literal. This makes the "\n" appear in the output stream literally.
Using `fmt.Fprintln` causes two lines to be printed in the output stream when the backticks are corrected to quotation marks.
Replace the backticks with quotation marks, and remove the "\n" at the end of the string as follows.
```go
fmt.Fprintln(os.Stderr, fmt.Sprintf("The config file, %s is missing and you did not pass the Dcrwallet RCP credetial in command line options.", preCfg.ConfigFile))
```
Also, the prompt message reads better as follows.
```go
fmt.Fprintln(os.Stderr, fmt.Sprintf("The config file (%s) is missing, and you did not pass dcrwallet RCP credentials in command line options.", preCfg.ConfigFile))
```

2018-12-17 20:14 UTC, barisere commented on config.go
> +	promtMsg := "Do you want to create the configuration file now? y|yes or n|no"
Options for command line input are usually shown in brackets. Line 178 would read better as follows.
```go
promtMsg := "Do you want to create the configuration file now? [y or yes / n or no]"
```
Compare with the prompt from an `apt` command.
```
Do you want to continue? [Y/n]
```

2018-12-17 20:14 UTC, barisere commented on config.go
> +			return nil, nil, fmt.Errorf("error receiving input: %s", err.Error())
You can use the helper function declared on line 175 on line 189.
```go
if err != nil {
	return nil, nil, inputErr(err)
}
```

2018-12-17 20:14 UTC, barisere commented on config.go
> +		if strings.Trim(rpcAddress, "\n") == "" {
The return value of `terminal.RequestInput` is already stripped of the ending "\n", so you can simply compare the value as follows.
```go
if rpcAddress == "" {
```
Do same for lines 200 and 208.

2018-12-17 20:14 UTC, barisere commented on config.go
> +
Hard-coding the content of the configuration file will result in more maintenance burden than necessary.
@itswisdomagain what other approach would be cleaner and more maintainable?

2018-12-17 20:14 UTC, barisere commented on config.go
> +		return config, nil, errors.New("Please set dcrcli.conf manually to use Dcrcli")
How about using the `appName` argument we already have access to?
```go
// return config, nil, errors.New("Please set dcrcli.conf manually to use Dcrcli")
return config, nil, fmt.Errorf("Please set config file manually to use %s", appName)
```

2018-12-17 20:14 UTC, barisere commented on config.go
> +	return config, nil, errors.New("Invalid optin args")
"optin" is probably a typo. Please verify that.

2018-12-17 20:14 UTC, barisere commented on cli/terminalprompt/terminalprompt.go
> +		if validate == nil {
Thanks for adding these checks :slightly_smiling_face:

2018-12-17 21:02 UTC, ademuanthony commented on config.go
> +
I agree,
How will the app be distributed? 
If the sample-dcrcli.conf will always be available, then we can use it

2018-12-17 21:03 UTC, ademuanthony commented on config.go
> +				fmt.Fprintln(os.Stderr, fmt.Sprintf(`The config file, %s is missing and you did not pass the Dcrwallet RCP credetial in command line options.\n`, preCfg.ConfigFile))
I don't know how I missed this

2018-12-18 07:33 UTC, itswisdomagain requested changes

2018-12-18 07:33 UTC, itswisdomagain commented on config.go
> +		// Todo load config from dcrwallet
Seeing  as we're leaving this for later, it'd help to include why this "step" should be done, something like "load config from dcrwallet to auto collect the values below instead of requesting user input"...

2018-12-18 07:33 UTC, itswisdomagain commented on config.go
> +			rpcAddress = "localhost:19111"
default variables should be defined where you have line 19-23

2018-12-18 07:35 UTC, itswisdomagain requested changes

2018-12-18 07:35 UTC, itswisdomagain commented on cli/terminalprompt/terminalprompt.go
> +		if validate == nil {
This is nice. Let's go all the way by removing `EmptyValidator` declared in line 12, and replace all its usages with `nil`

2018-12-18 07:36 UTC, itswisdomagain commented on config.go
> +
I'll get this PR's code and take it for a spin later today. I agree with both of you, a better, cleaner way would definitely be preferred. I'll share more thoughts later

2018-12-18 14:30 UTC, barisere commented on config.go
> +
Can we set this at build time?
```sh
go build -ldflags "-X main.sampleConfig=`cat sample-dcrcli.conf`"
```
Instead of filling in the values for rpc address, username, and password, we can append the necessary configuration lines to the `sampleConfig` variable and write it to disk.
Setting the build flag will be done on every build. This means we will use a build tool such as Make to ensure the build steps are followed.

2018-12-19 14:25 UTC, itswisdomagain commented on config.go
> +
2 thoughts here. Both came as a result of thinking about these 2 questions: 
- Do we really need a pre-existing sample config file?
- How would a regular user "create" his config file if there was no option to auto-generate one for the user?

Answers:
- No, the `sample-dcrcli.conf` is for development purposes (I believe), it does not get included in the release build
- Taking `dcrd` binary as an example, without building from source or having the source code (which is not necessary to run `dcrd`), how would you prepare the config file? `dcrd -h` tells you the configurable options and also tells you where the program expects to find the default config file. What I'd do is create a file in that location and set values for only the options I'm interested in as I can see from the output of the `dcrd -h` command.

These thoughts led to these options. The premise is that, in order to prepare the config file content, we don't need to have some sample file or base text stored somewhere to "edit":

Option 1:
Create the file content **_using just the information_** we've collected from the user or from parsing dcrwallet config. Right now, that would look something like this:
```
var conf []string

rpcAddress, err := terminalprompt.RequestInput(fmt.Sprintf("Wallet RPC server (%s)", defaultRpcAddress), nil)
if err != nil {
	return nil, nil, inputErr(err)
}
if rpcAddress == "" {
	conf = append(conf, fmt.Sprintf("walletrpcserver=%s", defaultRpcAddress))
} else {
	conf = append(conf, fmt.Sprintf("walletrpcserver=%s", rpcAddress))
}
```

Progressively append each option to the `conf` slice as you get it. Then join the slice using `strings.Join(conf, "\n")` and write that to the default config file location. Some/most of the comments in sample-dcrcli.conf aren't relevant anyways. `dcrcli -h` already explains what each option is for.

Option 2:
Assuming, we want to generate a more complete config file, even if we have to comment out the options that we do not want to set values for at the moment. And we also would love to include some comments about each of these options in the file, so that when a user goes to edit subsequently, he wouldn't feel lost or need to run back to `dcrcli -h` to catch his breath.

We can, at runtime, get all the available options (their long name and descriptions) and use that to create a more robust content for the config file. The code below gives the idea:
```
group := preParser.Groups()[0]
for _, option := range group.Options() {
	fmt.Println(option.LongName, option.Description)
}
```

2018-12-19 19:40 UTC, barisere commented on config.go
> +
@itswisdomagain the downside to option 1 is that the configuration file generated for the user will be missing essential information for further customization.
The downside to option 2 is that the content of the generated configuration file may not match the sample-dcrcli.config file. Users (including developers) may come across that file and be confused for a moment what the differences mean. I hope we can avoid that.

A third option is to generate the configuration instead of hard-coding it in the sample file. That way, the code is the single source of truth and will serve both the developers and the users.
The technique is as follows.
We'll use the `text/template` package to define the format of the file. Then we define a command, `configure`, that will write out the sample configuration using either user-supplied values for the fields or default values where no input was provided by the user.
Running the `configure` command becomes the first step after downloading the binary. We can even provide a helper script that does that automatically as part of the installation step.

I'll make a demo of this option tomorrow and ask for feedback.

2018-12-20 12:34 UTC, itswisdomagain commented on config.go
> +
I think this is what's holding this PR. @ademuanthony working on this?

2018-12-21 02:40 UTC, ademuanthony commented
Add a new handler; 'dcrcli configure' that will create the dcrcli.conf file for the user.
![config-file-032112](https://user-images.githubusercontent.com/11990092/50321430-28299300-04d1-11e9-8060-0bccbab093bd.png)

the file is now generated using the 'text/template' package and the sample config is now removed leaving the string holding the template as the single source of truth for the configuration file.

2018-12-22 09:35 UTC, itswisdomagain requested changes
Getting this auto-config thing to work smoothly is not proving as straightforward as we'd like but we'll get it. Some more thoughts on what _could_ be done better

2018-12-22 09:35 UTC, itswisdomagain commented on cli/commands.go
> +		{"configure", fmt.Sprint("help in properly setting up %s", AppName()), configure, false},
This should be `fmt.Sprintf`

2018-12-22 09:35 UTC, itswisdomagain commented on cli/commands.go
> +		{"configure", fmt.Sprint("help in properly setting up %s", AppName()), configure, false},
Also, I'm thinking `config` instead of `configure` for command name, it's shorter and descriptive/informative still

2018-12-22 09:35 UTC, itswisdomagain commented on cli/helpers.go
> +func AppName() string {
The introduction of this function is nice! It also means we no longer need to have `appName` property in the `cli` struct, nor pass `appName` as a parameter to the `cli.New` function.

With this current code changes, the only usage of `cli.appName` is in line 97 of `cli.go` and that can easily be updated to call this function instead of referring to the `appName` property of `cli`. Making that change would also mean that the function `invalidCommandReceived` can be simplified, no longer attached to the `cli` struct as it would be no longer needed.

2018-12-22 09:35 UTC, itswisdomagain commented on cli/handlers.go
> +	promtMsg := "Do you want to create the configuration file now? [y or yes / n or no]"
The user issued the command to create a config file, I'm sure there really is no need to ask this.

This question would only make sense if the user were trying to perform some other action and we notice there is no config and want to _suggest_ that the user creates one

2018-12-22 09:35 UTC, itswisdomagain commented on cli/handlers.go
> +func configure(_ *rpcclient.Client, _ []string) (resp *response, err error) {
I want to recommend moving this function to config.go. I'll mention my reasons in some comments below

2018-12-22 09:35 UTC, itswisdomagain commented on cli/handlers.go
> +func configure(_ *rpcclient.Client, _ []string) (resp *response, err error) {
If we do this though, it'll be difficult to register this as a command in `commands.go`. We can create a config flag for it, say `--init` and that may not be totally bad seeing as this is not an action many users will perform more than once

2018-12-22 09:35 UTC, itswisdomagain commented on cli/handlers.go
> +		rpcAddress, err = terminalprompt.RequestInput(fmt.Sprintf("Wallet RPC server (%s)", defaultRpcAddress), nil)
There's no indication to the user that
- the text in brackets are default values
- not providing any input means accepting the default value

2018-12-22 09:35 UTC, itswisdomagain commented on cli/handlers.go
> +		confText :=
I'd suggest putting this in a `conf.tmpl` file instead, but we'd be faced with the issue of including the file with the built binary when building. To keep this file clean, I want to suggest putting this in a `dcrcli.conf.go` file, that returns this text template or that holds a function, accepting the user inputs as parameters and feeding them into a string and returning the final output (similar to what you did previously, difference is, it's going into a different file to make things cleaner and we no longer have the sample conf file to avoid confusion)

2018-12-22 09:35 UTC, itswisdomagain commented on cli/handlers.go
> +		f, err := os.Create(defaultConfigFile)
2 issues here:
- first, the default config file is already declared in `config.go`, you can't import it here, and we should try to avoid repetition as much as possible, which is one reason I recommended moving this function to `config.go`
- second, if a user specifies a different config file location via the `-C/--configfile` option, your code will ignore that, simply because you don't have access to that info in this context. You would have access to that info if this code was in `config.go`, then instead of using the default config file, you'd use `config.ConfigFile` which would point to the user specified value or the default as the case may be

![screenshot 2018-12-22 at 10 15 56 am](https://user-images.githubusercontent.com/18400051/50372657-b76a9f80-05d2-11e9-879f-93810d6cf148.png)

2018-12-22 09:35 UTC, itswisdomagain commented on cli/handlers.go
> +		tmpl := template.New("main")
Won't a better template name be "config" instead of "main"?

2018-12-22 09:35 UTC, itswisdomagain commented on cli/handlers.go
> +	} else if input == "no" || input == "n" {
To make the code a little easier to read, in these circumstances, you could just check for this condition first and return, then you won't need an else block

2018-12-22 09:35 UTC, itswisdomagain commented on config.go
> +	"github.com/btcsuite/go-flags"
usually external imports are kept separated at the bottom... any specific reason you brought this here?

2018-12-22 09:35 UTC, itswisdomagain commented on config.go
> +		} else {
The return statement above makes this else unnecessary, you can just write the code here, knowing it will only execute if the if statement fails validation, because if it passes validation, it'll return before getting to execute the code here

2018-12-22 09:35 UTC, itswisdomagain commented on config.go
> +			isConfigureCommand := func(args []string) bool {
The logic here can be used to invoke the `configure` function (assuming we agree to bring the function to this file instead of `handlers.go`)

2018-12-22 09:35 UTC, itswisdomagain commented on main.go
> +	errConfigNotFound = errors.New("config not found")
This is only used once, any need to create a variable for it?

2018-12-22 09:35 UTC, itswisdomagain commented on main.go
> +		fmt.Println(fmt.Sprintf("The config file (%s) is missing, and you did not pass dcrwallet RCP credentials in command line options.", defaultConfigFile))
As per the comment on #50 
> instructions would be displayed to set edit the config file or to specify the appropriate rpc command line options (-h)

My interpretation of that information is that, if no config file is found, rpc options not set, the user should be informed of 2 alternative options he can take
- set/create the config file using the appropriate command
- pass rpc credentials by following the instructions set in `dcrcli -h`

The second option is not currently offered to the user

2018-12-22 13:30 UTC, ademuanthony commented on main.go
> +	errConfigNotFound = errors.New("config not found")
it is referenced in config.go 158 and main.go 50 and 53

2018-12-22 15:23 UTC, ademuanthony commented
I have added an --init flag and moved the configure func to config.go.
The user can now set the config by calling 'dcrcli --init' or accepting the auto-create suggestion during startup 
![init-for-config](https://user-images.githubusercontent.com/11990092/50375999-b8b5bf80-0606-11e9-9bc6-7a8f20c5f7f1.png)

2018-12-23 15:45 UTC, itswisdomagain requested changes
We're close! Minor changes left...

2018-12-23 15:45 UTC, itswisdomagain commented on config.go
> +	ServerAddress      = "127.0.0.1:7778"
Let's use `defaultHTTPServerAddress` instead, btw, `ServerAddress` doesn't need to be public. We can/should make `defaultHTTPServerAddress` = `127.0.0.1:7778`

2018-12-23 15:45 UTC, itswisdomagain commented on config.go
> +	ServerAddress      = "127.0.0.1:7778"
Also, we don't need to automatically save a value for `serveraddress` to `dcrcli.conf`. The program is designed such that if there is no value set in config, the default value would be used.

If we must save a value for this option to `dcrcli.conf`, we should request it from the user. But I don't think that is relevant, we probably should just stick to having a default value to use if user doesn't manually supply one.

2018-12-23 15:45 UTC, itswisdomagain commented on config.go
> +	if preCfg.Init {
What if the file already exists and user passes the `--init` flag? I think a warning is in order before the existing config file is overwritten.

2018-12-23 15:45 UTC, itswisdomagain commented on config.go
> +		if preCfg.WalletRPCServer == "" || preCfg.RPCUser == "" || preCfg.RPCPassword == "" {
When I run ` dcrcli -c="localhost:19111" -u="rpcuser" -p="rpcpass"`, I still get the error about missing config fie (true) and not passing dcrwallet RPC credentials in command line options (false)

2018-12-23 15:45 UTC, itswisdomagain commented on config.go
> +				fmt.Println(err)
This should behave as though `--init` flag was passed, **exit** after running `configure`.

Currently, if I get to this point and say yes, it creates the config, prints out `The config file has been set successfully` but also proceeds to print out the following message which is a little confusing:
```
available cmds:  balance, send, receive, history
experimental:  send-custom
```

2018-12-23 15:45 UTC, itswisdomagain commented on config.go
> +
Can we maintain the pattern below and remove this empty line space?

2018-12-23 15:45 UTC, itswisdomagain commented on config.go
> +		ServerAddress string
As mentioned in an earlier comment, saving this to `dcrcli.conf` is unnecessary - the app will not break if this value is not set in config.

There are a couple of other config options that are needed but have default values like `RPCCert` and `NoDaemonTLS`. Their absence in `dcrcli.conf` or in the command-line options won't cause the app to break. Don't see a need to ask the user to supply such information when initialising a conf file.

If we want to ask the user to supply them, then let's make them behave like `WalletRPCServer`, `RPCUser` and `RPCPassword` config options (no default values). They must be provided either in command-line options or saved in `dcrcli.conf`. if none of the above is done, then the user should be prompted to create a config file or pass those values.

If we're using default values, let's keep using default values until a user on his own goes to set a different value in `dcrcli.conf` or passes a different value in command-line options

2018-12-23 15:45 UTC, itswisdomagain commented on main.go
>  	config, args, err := loadConfig(appName)
This is the only use of `appName` in this function. We can do without it. `loadConfig` is able to access `cli.AppName()` directly where needed. It currently does so in line 167 of config.go

2018-12-23 16:32 UTC, itswisdomagain commented
We'll need to update readme, the part about configuring dcrcli using the sample config file.

2018-12-24 16:42 UTC, barisere requested changes
If the configuration directory (~/.dcrcli) does not exist, the program should create it before writing the configuration file. Currently, it does not check whether the directory exists.
```
$ ./dcrcli --init
Wallet RPC server (default = localhost:19111): 
RPC username (default = rpcuser): 
RPC password (default = rpcpass): error in creating config file: open /home/barisere/.dcrcli/dcrcli.conf: no such file or directory
```

2018-12-24 16:48 UTC, barisere reviewed
Currently, the program does not offer a default when asking the user whether to create the configuration file immediately.
```
$ ./dcrcli
The config file (/home/barisere/.dcrcli/dcrcli.conf) is missing, and you did not pass dcrwallet RPC credentials in command line options.
Please run 'dcrcli --init' to create the config file or pass RPC credentials by following the instructions set in 'dcrcli -h'
Do you want to create the config file now? (y/n): 
```
The output of the last line of the prompt should be
```
Do you want to create the config file now? (Y/n): 
```
That indicates that "Y" is the default, so the user can simply hit enter and have the process continue. With the current implementation, the process aborts if the user does not provide an input.
Also check for wrong input. Validate that the input is either "Y" or "N", and it should be case-insensitive.

2018-12-24 16:57 UTC, barisere commented on config.go
> +		if preCfg.WalletRPCServer == "" || preCfg.RPCUser == "" || preCfg.RPCPassword == "" {
@ademuanthony That happens because the command line options have not been parsed at this point. Parse the command line arguments first (`parser.Parse`), before parsing the configuration file.

2018-12-24 17:06 UTC, barisere requested changes

2018-12-24 17:06 UTC, barisere commented on config.go
> +		if preCfg.WalletRPCServer == "" || preCfg.RPCUser == "" || preCfg.RPCPassword == "" {
The absence of those properties does not mean that the configuration file is missing. As @itswisdomagain noted, those properties can be provided via command line options.
I have an idea what the solution may be. First, parse the command line options as I suggested in [my previous comment](https://github.com/raedahgroup/dcrcli/pull/64/files#r243846517). Then add an `else` branch to the `if` block on line 155. The `else` branch should run only if there was an `*os.PathError` and the properties you check for on line 161 are empty; i.e., the configuration file is missing, and the associated options were not provided on the command line.

2018-12-24 22:53 UTC, itswisdomagain commented
I just came into a shocking revelation. RPC username (`config.RPCUser`) and RPC password (`config.RPCPassword`) are currently not used in connecting to dcrwallet daemon. The `New` function of `walletrpcclient.go` only uses Wallet RPC server address (`config.WalletRPCServer`) in connecting to dcrwallet daemon.

The only exception to this is when the user specifies `config.NoDaemonTLS` to be false and a connection to dcrwallet daemon is attempted over tls. Then RPC server certificate (`config.RPCCert`) is used together with the server address in establishing a connection to dcrwallet daemon.

This means that the only info we need to run `dcrcli` effectively is the Wallet RPC server address. If we're creating a config file out of necessity, then the only necessary data to request from the user is  Wallet RPC server address. Pretty much makes the whole conf creation process pointless. Why run through so much code just for a single value that we can ask the user to supply via command-line options?

It gets even exciting. The behaviour for dcrwallet is such that if a user does not set a gRPC address to use for incoming connections, `localhost:9111` or `localhost:19111` is automatically used for mainnet and testnet respectively. If we were to borrow such similar behaviour, we may not even need to worry ourselves whether or not there is a conf file or if the user provided the wallet rpc address via command-line options. If either of those possibilities occur, we use the default address for testnet or mainnet.

The only potential problem with using this default value is - what if the value isn't correct? What if the user set a different dcrwallet listen address? That problem wouldn't really solved by asking the user to specify an address instead of using the default address. The user may still specify an incorrect address. This is a whole other problem that gave birth to issue #77. This PR does not confirm if an rpc server address is valid or not. That's for a different PR in response to #77.

This PR is slowly becoming unnecessary work. I'll create a different PR very soon to remove the unused rpc username and password options from config.go; and also use a default rpc address if none is provided. When that PR gets merged, one is left asking, is there ever a scenario where we'll need to ask a user to create a `dcrcli.conf` file to continue using the app? Maybe. Maybe not.

My recommendation at this point is, we change this PR's direction. The goal should now be to create a conf file whenever necessary by running `dcrcli --init`. When a user runs that command, he should be prompted to provide values for all the available dcrcli options, or accept the default values. Then the conf file is created.

2018-12-25 08:04 UTC, barisere commented on README.md
> +The configuration file, dcrcli.conf will be created in your `appdata` folder (default is `~/.dcrcli` on Linux, `%localappdata%\Dcrcli` on Windows). See the output of `dcrcli -h` for a list of all opt
What is the default `appdata` folder on Mac?

2018-12-25 08:06 UTC, barisere commented on README.md
> +dcrcli --init
You can prepend this with a "$" to indicate that it's a command to run at the terminal.
```
$ dcrcli --init
```

2018-12-25 08:55 UTC, itswisdomagain commented on README.md
> +The configuration file, dcrcli.conf will be created in your `appdata` folder (default is `~/.dcrcli` on Linux, `%localappdata%\Dcrcli` on Windows). See the output of `dcrcli -h` for a list of all opt
Great question. That's one of the changes that the readme needs.
For Mac: `~/Library/Application Support/Dcrcli/dcrcli.conf`

2018-12-25 12:28 UTC, itswisdomagain requested changes

2018-12-25 12:28 UTC, itswisdomagain commented on config.go
> +	Init              bool   `long:"init" description:"Create the config file"`
PR #60 introduces a new flag (`--createwallet`) for creating wallet (if it doesn't exist already) before using dcrcli. I initially used `--init` for that use case but decided `init` was a little ambiguous and not very descriptive.

I want to suggest using a more descriptive flag here, say `--createconfig` or `--config`. `--config` might not work since it could be confused with `--configfile` used for specifying a config file path.

2018-12-25 15:29 UTC, barisere commented
@itswisdomagain `--init` works, for me. It follows a familiar pattern in CLIs such as `git` and `npm`. I would even prefer it as a command.
To create the configuration for running dcrcli:
```
$ dcrcli init [app_directory]
```
But that's just me being familiar with other tools that use this style.

2018-12-27 13:30 UTC, itswisdomagain commented
@barisere I think in those cases, `init` is required to use the app, so it makes sense. In our case, `init` isn't required and does not perform the function of getting the app ready for use. It's just a utility function, as the user can create the conf file without using `init`

2018-12-27 16:10 UTC, barisere commented
@ademuanthony Please address https://github.com/raedahgroup/dcrcli/pull/64#pullrequestreview-187716940.
The configuration directory should be created if it does not already exist.
```
$ ./dcrcli --init
Wallet RPC server (default = localhost:19111):
RPC username (default = rpcuser):
RPC password (default = rpcpass): error in creating config file: open /home/barisere/.dcrcli/dcrcli.conf: no such file or directory
```
Also move the error message to its own line.

2018-12-27 16:22 UTC, barisere requested changes
When the creation of the configuration file succeeds, the output is as follows.
```
$ ./dcrcli --init -C ./dcrcli.conf.new
Wallet RPC server (default = localhost:19111):
RPC username (default = rpcuser):
RPC password (default = rpcpass):

The config file has been set successfully

```
The blank lines are not necessary, and the absolute path to the file written is displayed to the user.
An output like the following looks fine to me. What do you think about it?
```
$ ./dcrcli --init -C ./dcrcli.conf.new
Wallet RPC server (default = localhost:19111):
RPC username (default = rpcuser):
RPC password (default = rpcpass):
The config file has been written to /home/barisere/code/go/src/github.com/raedahgroup/dcrcli/dcrcli.conf.new
```

2018-12-27 16:45 UTC, barisere commented
I notice we're simply logging whatever error occurs to the console. I suggest we log them to a file as well, and let the users know about the file. That way, the history of errors does not get lost, and we can get easily introduce telemetry if we want to. The main benefit is being able to go look at detailed error output (including stack traces if necessary) in the log file, and knowing where to start looking for problems. If a user reports an error, we can request the log file for richer context.
@ademuanthony @itswisdomagain

2018-12-27 17:03 UTC, barisere requested changes
When the configuration file is created, the default `rpccert` field should be an actual path on the user's filesystem. Currently it is hard-coded.
Compare
```
 ; Specify dcrwallet's RPC certificate, or disable TLS for the
 ; rpccert=/home/me/.dcrwallet/rpc.cert
```
vs
```
; Specify dcrwallet's RPC certificate, or disable TLS for the
; rpccert=/home/barisere/.dcrwallet/rpc.cert
```

2018-12-27 20:12 UTC, itswisdomagain commented
> I notice we're simply logging errors to the console. I suggest we log them to a file as well, and let the users know about the file. That way, the history of errors does not get lost, and we can get easily introduce telemetry if we want to. The main benefit is being able to go look at detailed error output (including stack traces if necessary) in the log file, and knowing where to start looking for problems. If a user reports an error, we can request the log file for richer context.
> @ademuanthony @itswisdomagain

Yes! Yes! A new issue should be created for this and addressed in a separate PR. Will need permission from @raedah first though

2018-12-29 02:34 UTC, itswisdomagain requested changes

2018-12-29 02:34 UTC, itswisdomagain commented on README.md
> +The configuration file, dcrcli.conf will be created in your `appdata` folder (default is `~/.dcrcli` on Linux, `%localappdata%\Dcrcli` on Windows). See the output of `dcrcli -h` for a list of all opt
Instead of saying 
> See the output of `dcrcli -h` for a list of all options"

I think a more relevant information to display here is 

> To use a different app data folder, use `dcrcli --init -C="path/to/desired/app/data/folder"`

2018-12-29 02:34 UTC, itswisdomagain commented on README.md
> +The configuration file, dcrcli.conf will be created in your `appdata` folder (default is `~/.dcrcli` on Linux, `%localappdata%\Dcrcli` on Windows). See the output of `dcrcli -h` for a list of all opt
The **Using dcrcli** section below should come above this **Configuration** section. That section (**Using dcrcli**) should mention using
- `dcrcli [options] <command> [args...]` to run a command
- `dcrcli -h` to view general program help, application options and available commands
- `dcrcli <command> -h` to view help information for a particular command

2018-12-29 02:34 UTC, itswisdomagain commented on config/config.go
> +	ServerAddress      = "127.0.0.1:7778"
This isn't relevant, we already have `defaultHTTPServerAddress`

2018-12-29 02:34 UTC, itswisdomagain commented on config/config.go
> +	Init              bool   `long:"init" description:"Create the config file"`
In line with [this comment](https://github.com/raedahgroup/dcrcli/pull/64#issuecomment-449858448) and [this reply](https://github.com/raedahgroup/dcrcli/pull/64#issuecomment-450151078), I want to re-recommend this flag be renamed.

It's okay if git and npm uses `init`, you can't use those programs without first issuing that command, "init" makes sense.

In our case, "init" isn't a pre-requirement to use the program, so it's quite misleading... What this does _isn't_ setting up the program for use, but instead creating a config file on-demand - at any time the user says he wants to create one. I think `--config` is appropriate

2018-12-29 02:34 UTC, itswisdomagain commented on config/config.go
> +	var rpcAddress, rpcUsername, rpcPassword string
The `rpcUsername` and `rpcPassword` values are not used in the dcrcli program. They should be completely removed from the list of config options and this function should not request values for them from the user.

2018-12-29 02:34 UTC, itswisdomagain commented on config/config.go
> +	var rpcAddress, rpcUsername, rpcPassword string
Since those 2 options are no longer required, it doesn't make sense for a user to run `dcrcli --init` or `dcrcli --config` just to set `rpcAddress`. I think it'd be appropriate to prompt user to provide values for all or most of the application options. One exception would be the `ConfigFile` option (only makes sense in command-line options).

Then use the values provided to create the config file.

2018-12-29 02:34 UTC, itswisdomagain commented on config/config.go
> +		ServerAddress: ServerAddress,
We should not directly save a default/static value to config file. Before doing so, the user should be prompted for a value to use with the option of retaining the default value

2018-12-29 02:34 UTC, itswisdomagain commented on config/dcrcli.config.go
> +
We need to remember to update this file as more application options/flags are added. For example, we now have UseTestNet (`; testnet=1`)

2018-12-30 14:16 UTC, ademuanthony commented on config/config.go
> +	var rpcAddress, rpcUsername, rpcPassword string
should we remove the config flag entirely and just request the address from the user at the point of loading the config options in the program?

2018-12-30 20:35 UTC, itswisdomagain commented on config/config.go
> +	var rpcAddress, rpcUsername, rpcPassword string
Remove the config/init flag? No. We've done too much work here already to throw it away.

We also should not request the address from the user. To connect to dcrwallet, the dcrwallet cert file path is also needed but we don't request that from the user either. If the user doesn't set a value in config or in command-line options, we use the default. That's currently what we're doing for the wallet rpc server address as well.

2018-12-30 20:38 UTC, itswisdomagain commented
I'm gonna close this PR @ademuanthony and @barisere. The issue this PR took to solve is outdated and irrelevant. But the work done so far, isn't completely unusable. We'll channel it into a more relevant issue.

I'll create the new issue and reference this PR. However, this PR should not be re-opened for the new issue. A new PR should be created. Most of the code changes here can and should be retained though.

2018-12-30 20:53 UTC, closed without merging