Fixed issue 53 - Simplify output of ./dcrcli
raedahgroup/godcr-old pull request #66
Opened 2018-12-18 06:42 UTC by Quadriyanney

Simplified the output of ./dcrcli based on specifications in issue 53.

2018-12-18 06:56 UTC, Quadriyanney commented
![screenshot from 2018-12-18 07-54-16](https://user-images.githubusercontent.com/13119278/50137091-64bf7980-029a-11e9-98e2-a9e28dc07f27.png)

2018-12-18 06:57 UTC, Quadriyanney commented
![screenshot from 2018-12-18 07-57-18](https://user-images.githubusercontent.com/13119278/50137148-989a9f00-029a-11e9-8b99-293443a21d8e.png)

2018-12-18 07:07 UTC, itswisdomagain commented
Hi @Quadriyanney, this is the desired output according to the issue #53 

<img width="678" alt="screen shot 2561-12-18 at 8 05 54 am" src="https://user-images.githubusercontent.com/18400051/50137581-dd730580-029b-11e9-8008-649ea62daaec.png">

Yours is a little different, yeah?

2018-12-18 07:11 UTC, Quadriyanney commented
Thought the "usage" part is supposed to show first, I could remove it tho

2018-12-18 07:14 UTC, itswisdomagain requested changes

2018-12-18 07:14 UTC, itswisdomagain commented on cli/writer.go
> +	var availableCommands []interface{}
You really should not modify this `printResult` function. It is used by other commands to display their individual outputs after successful execution of each command.

You should instead, just go ahead to print what you want, directly in the `writeHelpMessage` function and that function would also no longer need to call this `printResult` function. 

This `printResult` function formats output in a certain uniform way, which we are trying to do without, allowing different commands and actions to display output in different ways to best fit the command output, rather than following a general format. This function may go soon when all commands are able to present their own message internally, as part of their execution. Refer to [this comment on issue 54](https://github.com/raedahgroup/dcrcli/issues/54#issuecomment-447550604) for additional context.

2018-12-18 07:17 UTC, Quadriyanney commented on cli/writer.go
> +	var availableCommands []interface{}
Okay, I'll work on that

2018-12-18 07:50 UTC, Quadriyanney commented
![screenshot from 2018-12-18 08-49-45](https://user-images.githubusercontent.com/13119278/50139401-e5ce3f00-02a1-11e9-8a88-73fb215e8cd8.png)

2018-12-18 07:56 UTC, itswisdomagain commented
Notice a discrepancy with `dcrcli -h` with these changes:
<img width="833" alt="screen shot 2561-12-18 at 8 51 56 am" src="https://user-images.githubusercontent.com/18400051/50139521-4493b880-02a2-11e9-890b-d2f44b71ee05.png">

Previously, it looked like:
<img width="610" alt="screen shot 2561-12-18 at 8 49 35 am" src="https://user-images.githubusercontent.com/18400051/50139540-4f4e4d80-02a2-11e9-8ec5-28564547d004.png">

I'm guessing you can immediately figure out where the discrepancy is coming from and apply a fix.

While at it, also rebase your branch with `raedahgroup/dcrcli master`, and fix conflicts

2018-12-19 06:16 UTC, Quadriyanney commented
![screenshot from 2018-12-19 07-15-22](https://user-images.githubusercontent.com/13119278/50202298-e5937980-035d-11e9-8517-1c0bfee26f9d.png)

2018-12-19 12:31 UTC, itswisdomagain requested changes
This looks much more like it. Way to go!
Take a look at these few suggestions and we should be good.

2018-12-19 12:31 UTC, itswisdomagain commented on cli/help.go
> +	writeSimpleHelpMessage(stderrTabWriter)
the `appName` parameter to this function is no longer needed

2018-12-19 12:31 UTC, itswisdomagain commented on cli/help.go
> +	var experimentalCommands []interface{}
We know what kind of data we're storing in these slices (`string`), why not use that instead of `interface{}`?

2018-12-19 12:31 UTC, itswisdomagain commented on cli/help.go
> +	fmt.Fprintln(w, fmt.Sprintf(experimentalRowStr, experimentalCommands...))
If you use `[]string` above, you can avoid having to loop over both slices again and just print out the desired output like so:

```
fmt.Fprintln(w, "available cmds: ", strings.Join(availableCommands, ", "))
fmt.Fprintln(w, "experimental: ", strings.Join(experimentalCommands, ", "))
```

2018-12-19 13:16 UTC, itswisdomagain commented on cli/help.go
> +	writeSimpleHelpMessage(stderrTabWriter)
Just confirmed, this function (as it was) is used in other places. Don't think it's a good idea to alter it, may be better to create a different function for this use case instead.

A good example of an affected use case is when you pass an invalid option/flag to dcrcli such as `dcrcli -l`. The output for such cases is different now from what used to be.

2018-12-19 15:26 UTC, Quadriyanney commented on cli/help.go
> +	writeSimpleHelpMessage(stderrTabWriter)
I don't really get this

2018-12-19 15:29 UTC, Quadriyanney commented on cli/help.go
> +	var experimentalCommands []interface{}
Okay

2018-12-19 16:32 UTC, Quadriyanney commented
![screenshot from 2018-12-19 17-13-46](https://user-images.githubusercontent.com/13119278/50233616-1a322000-03b4-11e9-946f-9725f7236a56.png)

2018-12-20 10:54 UTC, itswisdomagain approved these changes

2018-12-20 10:55 UTC, merged