Refactor commands to use the go-flags package properly.
raedahgroup/godcr-old pull request #71
Opened 2018-12-19 18:41 UTC by barisere

Commands and subcommands can now be used in a simpler way.

2018-12-20 04:57 UTC, itswisdomagain commented
Some observations from preliminary testing:
- Running `dcrcli` without a command shows a message that doesn't appear customizable. Compare #53 
- There's a funny behaviour when using an unknown option/flag. Some examples to illustrate:
- `dcrcli -n` (unknown flag) doesn't show any message or perform any action. The program just exits
- `dcrcli -n=abc` (unknown option) shows a message to specify a command, ignoring the invalid option passed
- `dcrcli send -n` does nothing, while `dcrcli send -n=abc` finally says something expected: "unknown flag `n'"

I think 1 primary trigger for this refactor is to enable us use command options, can you provide an example to that effect? Use the receive command, let's assume it accepts an "AccountNumber" option, type uint32, short "n", long "account". This option is only useful when executing the receive command. I'm eager to see how this plays out

2018-12-20 15:08 UTC, barisere commented
> Some observations from preliminary testing:
> 
>     * Running `dcrcli` without a command shows a message that doesn't appear customizable. Compare #53
> 
>     * There's a funny behaviour when using an unknown option/flag. Some examples to illustrate:
> 
>     ...

Can you check those again? The behaviour has changed.

> I think 1 primary trigger for this refactor is to enable us use command options, can you provide an example to that effect? Use the receive command, let's assume it accepts an "AccountNumber" option, type uint32, short "n", long "account". This option is only useful when executing the receive command. I'm eager to see how this plays out

Oops, I used the `send` command instead. Assume the `send` command has a sub command, `custom`, that only prints "Custom send called" and the address passed as a flag. The flag has a short form "-a" and a long form "--address". We create this command as follows.
```go
// file: cli/commands.go

type SendCommand struct {
	Custom CustomSend `command:"custom"`
}

type CustomSend struct {
	Address string `short:"a" long:"address"`
}

func (c CustomSend) Execute(args []string) error {
	fmt.Println("Custom send called")
	fmt.Println("address value:", c.Address)
	return nil
}
```
We register the command as follows.
```go
// file: cli/app.go

type AppCommands struct {
	Send       SendCommand       `command:"send" description:"send a transaction" subcommands-optional:"optional"`
	// other fields
}

var DcrcliCommands AppCommands
```
And we parse it as follows.
```go
// file: main.go

cli.Setup(client)
parser := flags.NewParser(&cli.DcrcliCommands, flags.Default)
if _, err := parser.Parse(); err != nil {
	// handle error
}
```
Below is help output when running the compiled code.
```
$ ./dcrcli -C ./dcrcli.conf send custom --help
Usage:
  dcrcli [OPTIONS] send custom [custom-OPTIONS]

Application Options:
  -v, --version          Display version information and exit
  -C, --configfile=      Path to configuration file
  -u, --rpcuser=         RPC username
  -p, --rpcpass=         RPC password
  -w, --walletrpcserver= Wallet RPC server to connect to
  -c, --rpccert=         RPC server certificate chain for validation
  -s, --serveraddress=   Address and port of the HTTP server.
      --http             Run in HTTP mode.
      --nodaemontls      Disable TLS

Help Options:
  -h, --help             Show this help message

[custom command options]
      -a, --address=
```
When we run the `custom` subcommand without the address flag, the output is as follows.
```
$ ./dcrcli -C ./dcrcli.conf send custom 
Custom send called
address value:
```
When we run the `custom` subcommand with the address flag set, the output is as follows.
```
$ ./dcrcli -C ./dcrcli.conf send custom --address=TsfDLrRkk9ciUuwfp2b8PawwnukYD7yAjGd
Custom send called
address value: TsfDLrRkk9ciUuwfp2b8PawwnukYD7yAjGd
```
If we use the flag without providing an argument, the following error is shown.
```
$ ./dcrcli -C ./dcrcli.conf send custom --address
expected argument for flag `-a, --address'

$ ./dcrcli -C ./dcrcli.conf send custom -a
expected argument for flag `-a, --address'
```
That's mostly it.

2018-12-22 13:45 UTC, itswisdomagain requested changes
This looks like great improvement. 1 other immediate cause for concern is this:
- `config.go` is not restricted to just cli-related usages, it shouldn't belong in the `cli` package

I have an idea, want to try it out on your branch and see how it goes

2018-12-22 13:45 UTC, itswisdomagain commented on cli/commands.go
> +func (b BalanceCommand) Execute(args []string) error {
I see a lot of repetition with these Execute methods. I expect there should be a way to prevent that. I have something in mind, but want to test it out first. Might commit my changes to this branch if it pays off

2018-12-22 13:45 UTC, itswisdomagain commented on main.go
> +	// Errors here will be owing to unknown flags and commands, which are not of interest at this point.
Why are they not of interest?

2018-12-22 16:57 UTC, itswisdomagain commented on main.go
> +	// Errors here will be owing to unknown flags and commands, which are not of interest at this point.
I think I get why now

2018-12-23 13:43 UTC, itswisdomagain requested changes
Feedback from testing, haven't really paid another attention to the code. I believe this PR comes with changes to the behaviour of running `dcrcli` (i.e. without commands), `dcrcli -h` and `dcrcli <command> -h`. Those were scenarios I tested for in getting the feedback below.

A fourth use case I simulated in my head but I know this PR also introduces changes regarding, is command-specific options. According to my simulation, this should work well (for the most part). The exception, a pointed below, is when using a command-specific option when running in cli mode. Since commands are limited to cli mode, command-specific options should throw an error when parsing if the user is running on http mode.

I believe the the identified issues below are fixable. An adjusted version of this PR demonstrates potential ways of fixing some of the identified issues. Reference links are provided in such cases.

2018-12-23 13:43 UTC, itswisdomagain commented on main.go
> +	if _, err := parser.Parse(); err != nil {
When no command is passed, this produces the following output:
`Please specify one command of: balance, history, receive, send or send-custom`

The current output (based on #53 and #66) is:
```
available cmds:  balance, send, receive, history
experimental:  send-custom
```

The latter should be preferred.

2018-12-23 13:43 UTC, itswisdomagain commented on main.go
> +		parser.WriteHelp(os.Stderr)
Not critical but if this can be improved, we should. Compare dcrcli current help output to that of this PR:

dcrcli currently:
![screenshot 2018-12-23 at 2 05 20 pm](https://user-images.githubusercontent.com/18400051/50383911-a0ed4280-06bd-11e9-9bec-545207beaa88.png)

with this PR:
![screenshot 2018-12-23 at 2 05 31 pm](https://user-images.githubusercontent.com/18400051/50383913-a34f9c80-06bd-11e9-8321-216a2af0a859.png)

Notice the presense of `[<args...>]` in the usage text that's no longer included with this PR.

Also notice that commands are currently displayed before options, I think it's more user-friendly that way - showing commands before options, but I may be wrong. When I run the help command of any app, it's rarely because I want to see the app options that I can configure but because I want to see which of the supported commands I need at the moment to achieve something. More often than not, I'm looking for a command, not an option

2018-12-23 13:43 UTC, itswisdomagain commented on main.go
> +		parser.WriteHelp(os.Stderr)
Still on help message displays, this PR does a neat job of introducing command-specific help with the `dcrcli <command> -h` syntax. But the message displayed is too verbose, I believe. Can we make it more concise? It should actually provide "details" about how the command functions and the optional arguments and flags it works with.

![screenshot 2018-12-23 at 2 24 03 pm](https://user-images.githubusercontent.com/18400051/50384021-a6975800-06be-11e9-9af7-2970f4837b9f.png)

In a bid to achieve similar objectives set forth in issue #51, PR #63 has begun heading in the desired direction I believe. [This comment](https://github.com/raedahgroup/dcrcli/pull/63#issuecomment-448585542) and [this comment](https://github.com/raedahgroup/dcrcli/pull/63#issuecomment-448952265) mention possible ways to achieve the objective of displaying relevant messages for command-specific help requests.

By the way, that PR is on pause because it expects this PR will somewhat make it easier to achieve the goal. Can it? Will it?

2018-12-23 13:43 UTC, itswisdomagain commented on main.go
> +	parser := flags.NewParser(&commands, flags.HelpFlag)
This is potentially problematic. Regardless of whether the user wants to run in web or cli mode, this code parses command-line options assuming we're running on cli. The following scenario highlights how this could be problematic:

Say the cli balance command uses a flag (`-e/--extended` | compare #62), and a user runs the following:
Scenario 1: `dcrcli send -e` -> error, unknown flag `e`
Scenario 2: `dcrcli balance -e` -> valid, `e` is a valid flag for the `balance` **cli** command
Scenario 3: `dcrcli balance -e --http` -> valid, because `e` is a valid flag for the `balance` command but this should ideally fail because `e` is an invalid flag for any command in http mode. http mode does not even support cli commands by the way.

The ideal behaviour for the Scenario 3 would have been to return an error that the flag `e` is unsupported in http mode. If this parser was created with just `&cfg` and not `&commands`, this flag would have been rejected

2018-12-23 13:48 UTC, itswisdomagain commented on main.go
> +	if _, err := parser.Parse(); err != nil {
Did something here that might help. Might.
https://github.com/itswisdomagain/dcrcli/blob/pr71-update/main.go#L32

2018-12-23 13:52 UTC, itswisdomagain commented on main.go
> +	parser := flags.NewParser(&commands, flags.HelpFlag)
Parsing twice is one work-around. First parse is as basic as possible, does not include cli commands and command-specific options. This parse too would not throw error if it encounters an invalid option because such option may actually be a valid command-specific option if we're running in cli.
Compare https://github.com/itswisdomagain/dcrcli/blob/pr71-update/main.go#L14

First parse helps us know what mode we're running on, so second parse can be more thorough, including commands and command-specific options if running in cli and the reverse if not.
Compare https://github.com/itswisdomagain/dcrcli/blob/pr71-update/main.go#L39 and https://github.com/itswisdomagain/dcrcli/blob/pr71-update/main.go#L50

2018-12-23 16:33 UTC, itswisdomagain commented
We'll need to update the *Using dcrcli* section of the readme

2018-12-23 19:52 UTC, barisere commented on main.go
> +	if _, err := parser.Parse(); err != nil {
The closes I could get is this.
```
$ ./dcrcli -C dcrcli.conf 
Available Commands:  balance, beta, history, receive, send, send-custom
```
I could not access the command data struct, so the experimental flag could not be used.

2018-12-23 20:41 UTC, barisere commented on main.go
> +		parser.WriteHelp(os.Stderr)
> Not critical but if this can be improved, we should. Compare dcrcli current help output to that of this PR:
> 
> dcrcli currently:
> ![screenshot 2018-12-23 at 2 05 20 pm](https://user-images.githubusercontent.com/18400051/50383911-a0ed4280-06bd-11e9-9bec-545207beaa88.png)
> 
> with this PR:
> ![screenshot 2018-12-23 at 2 05 31 pm](https://user-images.githubusercontent.com/18400051/50383913-a34f9c80-06bd-11e9-8321-216a2af0a859.png)
> 
> Notice the presense of `[<args...>]` in the usage text that's no longer included with this PR.

If the command has positional arguments, then [args] or <args> is displayed, depending on whether the arguments are required or not.
```
$ ./dcrcli -C dcrcli.conf receive -h
Usage:
  dcrcli [OPTIONS] receive [account]

Application Options:
  -v, --version          Display version information and exit
  -C, --configfile=      Path to configuration file
  -u, --rpcuser=         RPC username
  -p, --rpcpass=         RPC password
  -w, --walletrpcserver= Wallet RPC server to connect to
  -c, --rpccert=         RPC server certificate chain for validation
  -s, --serveraddress=   Address and port of the HTTP server.
      --http             Run in HTTP mode.
      --nodaemontls      Disable TLS

Help Options:
  -h, --help             Show this help message
```

> Also notice that commands are currently displayed before options, I think it's more user-friendly that way - showing commands before options, but I may be wrong. When I run the help command of any app, it's rarely because I want to see the app options that I can configure but because I want to see which of the supported commands I need at the moment to achieve something. More often than not, I'm looking for a command, not an option

I couldn't find a way around this. It's not quite configurable with `go-flags`.

2018-12-23 20:46 UTC, barisere commented on main.go
> +	parser := flags.NewParser(&commands, flags.HelpFlag)
`--http` is a switch. Because it is also a top-level option, we encounter it immediately after the first parse. So, the program switches to web mode if the `--http` flag is encountered; every other command is ignored.
The current order of priority is as follows.
- -v displays the version information and exits. Every other flag or command is ignored.
- -h/--help
- --http

2018-12-23 21:51 UTC, itswisdomagain commented on main.go
> +	if _, err := parser.Parse(); err != nil {
This is close...

I just remembered a suggestion/request from @raedah that might help. Making reference to the output of `dcrcli -h`:

> send-custom cmd can be separated from the basic cmds in a more advanced sections, ..so we are creating categories

To expatiate, the idea is to separate commands into category, such that when displaying `dcrcli -h`, commands such as `send-custom` would not appear under the **Available commands** section but under a new section **Advanced commands**

If we're able to achieve separating the commands into categories/sections, I think this PR will be able to achieve the desired output for running `dcrcli` without any command

2018-12-23 21:53 UTC, itswisdomagain commented on main.go
> +		parser.WriteHelp(os.Stderr)
All good. Getting the first part to work is priceless

2018-12-23 22:35 UTC, itswisdomagain commented
For reference purposes, here are the objectives of (or issues affected by) this PR:

- command-specific options
**Reference issue**: #49, also [this comment](https://github.com/raedahgroup/dcrcli/pull/63#discussion_r242304719)
**Status**: Green (feature fully supported by this PR)
**More info**: Once this PR is merged, work on #62 can continue

- experimental commands distinction when running dcrcli without commands
**Reference issue**: #53
**Status**: Yellow (partly supported)
**More info**: Requirement is fully implemented in #66,  but works quite differently in this PR
**Way forward**: Leave as is. A new issue ([described here](https://github.com/raedahgroup/dcrcli/pull/71#discussion_r)) should be created and fixed in a different PR. Fixing that issue would make it possible for this requirement to be fully implemented.

- command-specific help
**Reference issue**: #51, also [this comment](https://github.com/raedahgroup/dcrcli/pull/63#issuecomment-448585542) and [this other comment](https://github.com/raedahgroup/dcrcli/pull/63#issuecomment-448952265)
**Status**: Red (support for this feature/requirement is not solid enough)
**More info**: This PR does a neat job of introducing command-specific help with the `dcrcli <command> -h` syntax. But the message displayed is too verbose. It should be more concise, providing "details" about how the command functions and the optional arguments and flags it works with. Similar work being done in #63 cannot continue with what we have at the moment
**Way forward**: Make all commands have long description tags in `app.go`. #63 then uses a parser to get the long description for each command and displays that when `dcrcli help <command>` is issued. `dcrcli help` in #63 should produce the same output as `dcrcli -h` in this PR. Remove support for command-specific help via `dcrcli <command> -h` in this PR or have `dcrcli <command> -h` display what it currently displays AND include instruction to use `dcrcli help <command>` to get detailed help for the command. For this PR, `dcrcli help <command>` may just print a dummy message awaiting complete implementation in #63

_PS: I haven't reviewed the code yet, this "overview" may take a different outlook after I review the code_

2018-12-23 23:26 UTC, itswisdomagain requested changes
Got around to reviewing the code. Some thoughts...

2018-12-23 23:26 UTC, itswisdomagain commented on cli/app.go
> +	Send       SendCommand       `command:"send" description:"send a transaction" subcommands-optional:"optional"`
`subcommands-optional` tag not necessary, must be left-over code from an experiment with subcommands...

2018-12-23 23:26 UTC, itswisdomagain commented on cli/app.go
> +var DcrcliCommands AppCommands
I see this is only used in line 87 of `main.go`, you can use `&cli.AppCommands{}` in lieu of this variable, rendering this unnecessary.

Also, I think the contents of this file would make more sense in `commands.go`, preferably at the top, and then keep the individual command structs  at the bottom

I also recommend moving the Execute methods to `handlers.go`. So that instead of having different handler functions for each command and calling these functions in Execute, we can perform all command execution in the `Execute` method of the command struct. This also has the added advantage of making any command-specific options readily accessible in the handler function (aka Execute)

2018-12-23 23:26 UTC, itswisdomagain commented on cli/cli.go
> +type response struct {
Permit me to saddle you with this requirement. This type should go. All commands should handle displaying appropriate responses after successful execution. Compare [this comment](https://github.com/raedahgroup/dcrcli/issues/54#issuecomment-447550604). You may not want to stress too much about how to display the successful output for different commands, just print what is currently printed. Other PRs building off related issues will revise the successful message printing for each command. Examples are #49, #54 and #55

As provided for by the signature of `Execute` in `goflags.Commander`, commands should only return an error which is printed to the terminal.

2018-12-23 23:26 UTC, itswisdomagain commented on cli/commands.go
> +	res, err := normalSend(walletClient, args)
As mentioned in an earlier comment, the code in `normalSend` should come here. No need to call another handler function, this particular pattern is repeated across all Execute methods in this file, causing avoidable repetition.

Also, assuming `SendCommand` supports some command-specific options, we can have access to such option here seamlessly (`s.option`). Passing such options to the `normalSend` handler will be another stress that can be avoided.

2018-12-23 23:26 UTC, itswisdomagain commented on cli/commands.go
> +	res, err := normalSend(walletClient, args)
This comment applies to all `Execute` methods in this file. Also, it might make sense to put these in `handlers.go`, leaving `commands.go` as a file that describes the supported commands and `handler.go` as the file that actually perform the actions for each command.

2018-12-23 23:26 UTC, itswisdomagain commented on cli/core/config.go
> +	defaultLogDir              = filepath.Join(defaultAppDataDir, defaultLogDirname)
`defaultLogDir`, `defaultLogFilename` and `defaultLogDirname` have no use and can be deleted

2018-12-23 23:26 UTC, itswisdomagain commented on main.go
> +	sort.Strings(commands)
Don't see a need for sort. The commands are listed in the order in which they're defined in the `AppCommands` struct. If there's a particular order of listing commands we prefer, it should be reflected there

2018-12-23 23:26 UTC, itswisdomagain commented on main.go
> +		fmt.Println(appVersion)
When you call `loadConfig` above, a check is made for the version flag and handled accordingly, this is never true and this code never runs. If you agree this code can go safely, then `appVersion` will have just one usage (in the `loadConfig` function), it might no longer make sense to keep the value in a global variable

2018-12-23 23:26 UTC, itswisdomagain commented on cli/core/config.go
> +package core
This file does not belong in `cli`, it applies to the entire app, not just `cli` interface. We can move the `core` package to the root of the project without causing issues

2018-12-23 23:26 UTC, itswisdomagain commented on cli/core/config.go
> +func AppName() string {
Love having this here. `AppName()` is not a cli-only thing, it should be accessible to any interface package and should not reside in the `cli` package

2018-12-23 23:26 UTC, itswisdomagain commented on main.go
> +func enterCliMode(config *core.Config, client *walletrpcclient.Client) {
`config` is not used here

2018-12-23 23:26 UTC, itswisdomagain commented on main.go
> +	parser := flags.NewParser(&cli.DcrcliCommands, flags.Default&(^flags.PrintErrors))
The flag options here is equivalent to `flags.HelpFlag | flags.PassDoubleDash` (which I think is more readable). Compare https://godoc.org/github.com/jessevdk/go-flags#Default

2018-12-23 23:26 UTC, itswisdomagain commented on main.go
> +		fmt.Println("Running in http mode")
Maybe move this to the `enterHTTPMode` function? That function currently has only 1 line of code, makes you _almost_ wonder why that single line of code isn't just use directly here

2018-12-23 23:26 UTC, itswisdomagain commented on main.go
> +func loadConfig() (*core.Config, *flags.Parser, error) {
Can we put these and the related functions in `config.go` instead? And invoke the needed functions using `core.Fn`?

2018-12-24 14:24 UTC, barisere commented on cli/app.go
> +	Send       SendCommand       `command:"send" description:"send a transaction" subcommands-optional:"optional"`
Yes, a leftover. Removed.

2018-12-24 14:50 UTC, barisere commented on cli/cli.go
> +type response struct {
I think this should be done in a different PR. Take the `balance` handler: #49 will change the way the output is displayed. Same for the others. Since they're working on the output messages also, we can let them do it, or do it ourselves in a separate PR. Doing it now will require that I change the output myself (even if I do not handle formatting, I get to unnecessarily mess with what they're doing).

2018-12-24 16:49 UTC, itswisdomagain commented on cli/cli.go
> +type response struct {
Okay

2018-12-24 20:52 UTC, itswisdomagain requested changes
We're making progress. Just some code cleanups

2018-12-24 20:52 UTC, itswisdomagain commented on cli/commands/app.go
> +package commands
I love this file/folder structure! I think `commands.go` will be a better name for this file.

2018-12-24 20:52 UTC, itswisdomagain commented on cli/commands/history.go
> +func transactionHistory(walletrpcclient *walletrpcclient.Client) (*cli.Response, error) {
Do we need this function? It's pretty much straight forward like in `balance.go`. Usually the heavyweight lifting is done in the `walletrpcclient` package and these `Execute` functions just call the appropriate functions in `walletrpcclient` and display the result. By the time we do away with the `cli.Response` struct, the code here will even be much more simpler, just call `transactions, err := walletrpcclient.GetTransactions()` and then print the result to terminal without creating a `response` object

2018-12-24 20:52 UTC, itswisdomagain commented on cli/commands/balance.go
> +	walletrpcclient := cli.WalletClient
Why create a variable for this? It's only used in the next line

2018-12-24 20:52 UTC, itswisdomagain commented on cli/commands/history.go
> +func (h HistoryCommand) Execute(_ []string) error {
In `Execute()` of `balance.go`, `args` is not used but the variable name was maintained. I think I like that as it gives some meaning to the function. If we however want to use `_` for cases where `args` isn't used, we should make it uniform for all command `Execute` methods. I prefer keeping `args` though, but purely a personal preference

2018-12-24 20:52 UTC, itswisdomagain commented on cli/commands/receive.go
> +func (r ReceiveCommand) Execute(_ []string) error {
Seeing as we can define command arguments (both optional and required) in the command struct, will we ever need the `args` parameter of the `Execute` function?

2018-12-24 20:52 UTC, itswisdomagain commented on cli/commands/receive.go
> +	walletrpcclient := cli.WalletClient
Also do not see a need for this variable creation. We can surely just use `cli.WalletClient` directly

2018-12-24 20:52 UTC, itswisdomagain commented on config/config.go
> +
are these spaces necessary?

2018-12-24 20:52 UTC, itswisdomagain commented on main.go
> +
The spaces here, needed?

2018-12-24 20:52 UTC, itswisdomagain commented on main.go
> +	config, parser, err := config.LoadConfig()
Variable 'config' collides with imported package name

2018-12-24 20:52 UTC, itswisdomagain commented on main.go
> +	if config == nil {
There's never a scenario where `err == nil` and `config == nil`. If `config == nil`, then `err != nil`. If `err != nil`, then this code will never be executed

2018-12-24 20:52 UTC, itswisdomagain commented on main.go
> +		enterHTTPMode(config, client)
What's actually required by `enterHTTPMode` is the string value of `config.HTTPServerAddress`.  Maybe pass that only instead of the entire config?

2018-12-24 20:52 UTC, itswisdomagain commented on main.go
> +		commands := supportedCommands(parser)
Variable 'commands' collides with imported package name

2018-12-24 20:52 UTC, itswisdomagain commented on main.go
> +func enterCliMode(client *walletrpcclient.Client) {
This function could use some spacing and comments (especially as it is not immediately obvious how the cli interface processes and handles commands)

2018-12-24 20:52 UTC, itswisdomagain commented on main.go
> +		fmt.Fprintln(os.Stderr, "Available Commands: ", strings.Join(commands, ", "))
Can we make `supportedCommands` return the joined string instead? The function isn't really used anywhere else so we can modify it to return what we actually need rather than it returning something and then we perform some other operation on the returned value.

Alternatively, we can just modify the `supportedCommands` function to print out the message and return nothing. The command can also be renamed accordingly.

2018-12-24 20:52 UTC, itswisdomagain commented on cli/cli.go
> +func IsFlagErrorType(err error, errorType flags.ErrorType) bool {
I think this function belongs in `config.go`. It is not only called by cli-related operations

2018-12-24 20:52 UTC, itswisdomagain commented on walletrpcclient/walletrpcclient.go
> +func (c *Client) AccountNumber (accountName string) (uint32, error) {
I'm wondering why I'm seeing this as a change seeing as it is already merged into master. Did you rebase?

2018-12-24 21:27 UTC, barisere commented on walletrpcclient/walletrpcclient.go
> +func (c *Client) AccountNumber (accountName string) (uint32, error) {
Yes.

2018-12-24 22:03 UTC, barisere commented on cli/commands/receive.go
> +func (r ReceiveCommand) Execute(_ []string) error {
We may never need it, but I think keeping it is fine.

2018-12-24 22:06 UTC, barisere commented on main.go
> +		fmt.Fprintln(os.Stderr, "Available Commands: ", strings.Join(commands, ", "))
Supported commands are a list of commands, so a `[]string` is appropriate.

2018-12-24 22:31 UTC, itswisdomagain commented on main.go
> +		fmt.Fprintln(os.Stderr, "Available Commands: ", strings.Join(commands, ", "))
The motivation for this requirement is that `supportedCommands` isn't used or needed anywhere else. However, the function would likely find use soon (in #63) so let's leave it as is

2018-12-24 22:58 UTC, barisere commented
The help message for command-specific help has been shortened. Here's what it looks like now.
```
$ ./dcrcli -C dcrcli.conf send -h
Usage:
  dcrcli [OPTIONS] send
```
```
$ ./dcrcli -C dcrcli.conf receive -h
Usage:
  dcrcli [OPTIONS] receive [account]
```
If that is acceptable, then command-specific help has been covered as required, leaving us with experimental commands to grok.

2018-12-24 23:35 UTC, itswisdomagain commented
> @itswisdomagain The help message for command-specific help has been shortened. Here's what it looks like now.
> 
> ```
> $ ./dcrcli -C dcrcli.conf send -h
> Usage:
>   dcrcli [OPTIONS] send
> ```
> ```
> $ ./dcrcli -C dcrcli.conf receive -h
> Usage:
>   dcrcli [OPTIONS] receive [account]
> ```

To a very large extent, it does. The associated issue #51 recommended creating a new command `dcrcli help` to do what `dcrcli -h` does and `dcrcli help <command>` to do what `dcrcli <command> -h` does now.

Let's retain this, it's a welcome change. We might need to clean it up (I'm thinking, add a message below the command usage text that says how to see the options, something like `use dcrcli -h to view command options`), but we'll have to discuss this with @raedah and then PR #63 can continue from there.

2018-12-25 00:35 UTC, itswisdomagain requested changes

2018-12-25 00:35 UTC, itswisdomagain commented on main.go
> +	if parser.Active == nil {
If you use `else if` here, the return in the preceding `if` block would be unnecessary

2018-12-25 01:19 UTC, itswisdomagain approved these changes

2018-12-25 01:20 UTC, merged