Updated send and receive outputs
raedahgroup/godcr-old pull request #72
Opened 2018-12-20 00:05 UTC by Jujhar

Regarding the smaller QR size unless you want to display PNG in the command line via importing another PNG rendering library the size cannot be changeable pretty much any way as if you select a pixel on the output you will see it as being one unit of black or white. API does not support resizing this type of textual character output. (practically it only supports PNG and Image size change which is not what we are outputting) (Ref https://godoc.org/github.com/skip2/go-qrcode)

Fixes #54

2018-12-20 10:58 UTC, itswisdomagain commented
Is there another qr code library that does what we want - print smaller images of qr code to terminal?

2018-12-20 11:25 UTC, itswisdomagain requested changes
2 other observations aside from those pointed underneath:
- there are still "blank lines in the output when re-asking the question"
- if an information is not specified (say an address), it may be better to exit the command; but if re-requesting for the input, it would make sense to say "try again" at the end of the invalid input message

![screenshot 2018-12-20 at 12 20 00 pm](https://user-images.githubusercontent.com/18400051/50282183-3be1e480-0452-11e9-9d7c-5989dd2323e8.png)

2018-12-20 11:25 UTC, itswisdomagain commented on cli/handlers.go
> +  text, _ := reader.ReadString('\n')
there's a utility pacakge `terminalprompt` that handles getting user input and performing validation on the input. For example, in this case, anything that's not y, yes, n or no should be regarded as invalid

Your current code doesn't do so, it treats anything not "n" as "yes", not safe

2018-12-20 11:25 UTC, itswisdomagain commented on cli/handlers.go
> +		return &response{}, nil
what happens if you return nil instead of &response{}?

2018-12-20 11:25 UTC, itswisdomagain commented on cli/handlers.go
> +	fmt.Println("sent txid %s", result.TransactionHash)
I'm thinking this may read better:
`sent. txid: %s`

2018-12-20 11:25 UTC, itswisdomagain commented on cli/handlers.go
> +	fmt.Println(res)
You could as well do `fmt.Printf("%s\n%s\n", r.Address, qr.ToString(true))`. It's one-liner but can't say if it's more readable. Leaving that to your discretion...

2018-12-21 00:29 UTC, Jujhar commented on cli/handlers.go
> +		return &response{}, nil
Compiles but runtime error

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x8a57da]

2018-12-23 01:56 UTC, Jujhar commented
Changed to terminalprompt and found as marginlly smaller QR output as this one has no outside padding.

Not sure how to remove those blank lines any ideas?
 A part of me feels like those are fine and Radeah was talking about double extra lines rather than just one.

2018-12-23 16:01 UTC, itswisdomagain commented on cli/handlers.go
> +		return &response{}, nil
> Changed to terminalprompt and found a marginlly smaller QR output as this one has no outside padding.

Not small enough. You had another idea of using a graphics library, discuss that with @raedah 

> Not sure how to remove those blank lines any ideas?

Look into the `terminalprompt` package

> A part of me feels like those are fine and Radeah was talking about double extra lines rather than just one.

Nah. The blank lines have no use

2018-12-23 16:01 UTC, itswisdomagain commented
> Changed to terminalprompt and found a marginlly smaller QR output as this one has no outside padding.

Not small enough. You had another idea of using a graphics library, discuss that with @raedah 

> Not sure how to remove those blank lines any ideas?

Look into the `terminalprompt` package

> A part of me feels like those are fine and Radeah was talking about double extra lines rather than just one.

Nah. The blank lines have no use

2018-12-23 16:02 UTC, itswisdomagain commented on cli/handlers.go
> +		return &response{}, nil
That's because `RunCommand` in `cli.go` in line 83 uses the return value as is. You should return nil and in main.go, check if res is nil before attempting to print. Your main.go should look like this:

```
if res != nil {
     printResult(tabWriter(os.Stdout), res)
}
```

2018-12-23 16:04 UTC, itswisdomagain commented
I'm putting this PR as WIP. After discussing with @raedah on how to deal with the mighty qrcode image on terminal, and fixing other issues highlighted, remove the [WIP] label

2018-12-30 02:45 UTC, Jujhar commented
Fixed and ready to go.

![qr-code-72](https://user-images.githubusercontent.com/5521110/50543912-d8665e00-0b99-11e9-8fcb-373c256a0b6f.png)

2018-12-30 02:50 UTC, Jujhar commented
Updating to add optional QR display via additional prompt.

2018-12-30 20:17 UTC, itswisdomagain commented
@Jujhar rebase your PR branch with master, fix conflicts and then push. Ensure you give attention to ALL previous review comments (there's a comment about using `nil` instead of `&response{}` that you haven't attended to)

When you've done that, rename this PR to remove the [WIP] flag, we don't want to spend time reviewing the code yet until those are done.

2018-12-30 21:59 UTC, Jujhar commented on cli/handlers.go
> +		return &response{}, nil
No longer an issue

2018-12-31 14:18 UTC, itswisdomagain requested changes

2018-12-31 14:18 UTC, itswisdomagain commented on cli/commands/helpers.go
> +			if (address == "") {
This check should be done before line 60. There's no need to attempt to validate an empty address

2018-12-31 14:18 UTC, itswisdomagain commented on cli/commands/helpers.go
> +			if (input == "") {
Always check for empty input before trying to "process" the input. This check should be done before line 90

2018-12-31 14:18 UTC, itswisdomagain commented on cli/commands/receive.go
> +	confirm, _ := terminalprompt.RequestInput("Would you like to a generate QR code? (y/n) ", validateConfirm)
If `validateConfirm` doesn't do anything, you can simply pass nil here instead.

2018-12-31 14:18 UTC, itswisdomagain commented on cli/commands/receive.go
> +	fmt.Printf("%s\n", receiveResult.Address)
`fmt.Println(receiveResult.Address)`

2018-12-31 14:18 UTC, itswisdomagain commented on cli/commands/receive.go
> +	if confirm == "Yes" || confirm == "yes" {
Do case-insensitive comparison using `strings.EqualFold(confirm, "yes")`
Also, no need to assign `confirm = "y"` only to check the value of confirm again in the next line. Unnecesary.
Do all your comparison here:
`if strings.EqualFold(confirm, "yes") || strings.EqualFold(confirm, "y")`, then display the qrcode

2018-12-31 14:18 UTC, itswisdomagain commented on cli/commands/send.go
> +	}
The comments above apply to this file as well

2018-12-31 19:45 UTC, Jujhar commented
Done

2018-12-31 20:17 UTC, itswisdomagain requested changes
In the `receive.go` and `send.go` files, you're not validating the requested "y/n" input properly. Compare how [similar validation is done here](https://github.com/raedahgroup/godcr/blob/master/cli/runner/walletloader.go#L77-L96)

Take note of the other comments below, rebase your PR branch with master and `go fmt ./...` your code when done before pushing.

2018-12-31 20:17 UTC, itswisdomagain commented on cli/commands/helpers.go
> +			return errors.New("That is did a valid amount. Try again.")
Typo here

2018-12-31 20:17 UTC, itswisdomagain commented on cli/commands/helpers.go
> +			return errors.New("That is did a valid amount. Try again.")
Also, the message here should not be "invalid amount", but "Amount not specified" like was done in the address validate function

2018-12-31 20:17 UTC, itswisdomagain commented on cli/commands/helpers.go
>  			return fmt.Errorf("error parsing amount: %s", err.Error())
This should be "Invalid amount. Try again"

2018-12-31 20:17 UTC, itswisdomagain commented on cli/commands/send.go
> +	fmt.Println("sent. txid %s", result.TransactionHash)
This should be `fmt.Printf("Sent. Txid %s", result.TransactionHash)` or `fmt.Println("Send. Txid", result.TransactionHash)`

2018-12-31 23:26 UTC, Jujhar commented on cli/commands/helpers.go
> +			return errors.New("That is did a valid amount. Try again.")
That was not part of my code but updated

2019-01-01 00:06 UTC, Jujhar commented
Alright updated again.

2019-01-01 00:13 UTC, itswisdomagain requested changes

2019-01-01 00:13 UTC, itswisdomagain commented on cli/commands/send.go
> +	if confirm != "y" {
Instead of checking `if confirm != "y"` here, you can check `if strings.EqualFold(confirm, "n")` in line 96 and cancel the operation there instead.

Also note that the `validateConfirm` function will not accept "yes" or "no", only "y" or "n"

2019-01-01 00:13 UTC, itswisdomagain commented on cli/commands/send.go
> +		fmt.Printf("Operation cancelled\n")
`fmt.Println("Operation cancelled")`

2019-01-01 00:13 UTC, itswisdomagain commented on cli/commands/helpers.go
>  			return fmt.Errorf("error parsing amount: %s", err.Error())
This isn't resolved

2019-01-01 00:30 UTC, Jujhar commented
Fixed

2019-01-01 00:57 UTC, itswisdomagain requested changes
Last changes. While at it, run `go mod tidy` to remove references to unused imports in `go.mod` and `go.sum`

2019-01-01 00:57 UTC, itswisdomagain commented on cli/commands/send.go
> +	confirm, err := terminalprompt.RequestInput("Are you sure? (y/N) ", validateConfirm)
As seen here https://github.com/raedahgroup/godcr/issues/54#issuecomment-446785257, there is no default option for this prompt. User must enter "y" or "n" to proceed. This prompt should not have a capital option (capital options imply that if the user does not enter any value, it's assumed they accept the option in capital)

This should be "Are you sure? (y/n)". The space at the end of that message isn't needed as well

2019-01-01 00:57 UTC, itswisdomagain commented on cli/commands/send.go
> +		if userResponse == "" || strings.EqualFold("Y", userResponse) || strings.EqualFold("n", userResponse) {
This validate function should not accept empty string values ("") since there is no default option. User must enter "y" or "n". See comment below for more

2019-01-01 00:57 UTC, itswisdomagain commented on cli/commands/receive.go
> +	confirm, err := terminalprompt.RequestInput("Would you like to generate a QR code? (y/N) ", validateConfirm)
The trailing space at the end of this prompt message is not needed

2019-01-01 00:57 UTC, itswisdomagain commented on cli/commands/send.go
> +	fmt.Println("You are about to send %f DCR to %s", sendAmount, destinationAddress)
`fmt.Printf("You are about to send %f DCR to %s\n", sendAmount, destinationAddress)`

2019-01-01 01:19 UTC, itswisdomagain approved these changes

2019-01-01 01:27 UTC, itswisdomagain requested changes

2019-01-01 01:27 UTC, itswisdomagain commented on cli/commands/send.go
> +		fmt.Println("Operation cancelled")
Just `Canceled` would do. And I think it's safe to stick with American English (one L in Canceled, instead of 2)

2019-01-01 01:27 UTC, itswisdomagain commented on cli/commands/send.go
> +	confirm, err := terminalprompt.RequestInput("Are you sure? (y/n) ", validateConfirm)
Remove the trailing space at the end of this prompt message

2019-01-01 01:38 UTC, itswisdomagain approved these changes

2019-01-01 01:39 UTC, merged