update readme
raedahgroup/godcr-old pull request #74
Opened 2018-12-20 10:26 UTC by Sirmorrison

updated readme by adding links to installing and running dcrcli dependencies
Closes #58

2018-12-20 12:01 UTC, itswisdomagain requested changes
Some thoughts

- Each bulleted point displays in one line, appropriate punctuation is necessary.
- Sounds like you offer 2 alternative methods of getting the needed binaries, but didn't indicate that EITHER needs to be done and not BOTH
- Lastly, the requirements section of the readme might need updating, what binaries do we **need**: `dcrwallet`, `dcrd`, `dcrctl`? some? all?

2018-12-20 12:01 UTC, itswisdomagain commented on README.md
> +click on assets and download the package that best suite your device.
"best suite your device" doesn't really sound like it, it might read better: "download the package for your operating system"

2018-12-20 12:01 UTC, itswisdomagain commented on README.md
> +follow this guild to install, setup and run drcd, dcrwallet,dcrctl executable files
typo: "guild" -> "guide"

2018-12-20 12:01 UTC, itswisdomagain commented on README.md
> +$ go install or GO111MODULE=on go install   (if you are building from within `GOPATH`)
nice

2018-12-20 18:25 UTC, Sirmorrison commented
resolved

2018-12-24 16:34 UTC, itswisdomagain requested changes

2018-12-24 16:34 UTC, itswisdomagain commented on README.md
> +* Download dcrd and dcrwallet from [here](https://github.com/decred/decred-binaries/releases)
Add a period at the end of this statement. Makes this bulleted point more readable

2018-12-24 16:34 UTC, itswisdomagain commented on README.md
> + to install, setup and run drcd, dcrwallet on your machine.
**dcrd and dcrwallet** instead of **dcrd, dcrwallet**

2018-12-24 16:34 UTC, itswisdomagain commented on README.md
> +$ go install or GO111MODULE=on go install   (if you are building from within `GOPATH`)
You can also run `go build` instead of `go install`, find out the difference between both commands and update this section accordingly.

We want new contributors to know that `go install` isn't the only way to produce a binary from this source code

2018-12-24 21:53 UTC, Sirmorrison commented on README.md
> +$ go install or GO111MODULE=on go install   (if you are building from within `GOPATH`)
Can't be explaining the difference between build and install on a project readme nah. Besides golang doc uses install and explains why.

2018-12-24 23:43 UTC, itswisdomagain commented on README.md
> +$ go install or GO111MODULE=on go install   (if you are building from within `GOPATH`)
Wasn't really asking you to "explain the difference" in the readme. Nonetheless, it's a potentially minor something, so we can leave as is

2018-12-24 23:55 UTC, itswisdomagain requested changes
1 more change for now. Will invite someone else to confirm that the changes introduced in this PR takes care of issue #58

2018-12-24 23:55 UTC, itswisdomagain commented on README.md
> +$ go install or GO111MODULE=on go install   (if you are building from within `GOPATH`)
remove multiple spaces before the opening bracket, should just be a single space

2018-12-29 02:40 UTC, itswisdomagain requested changes
Last couple changes

2018-12-29 02:40 UTC, itswisdomagain commented on README.md
> +* Clone this repo to somewhere on your computer. Please set the `GO111MODULE=on` environment variable if you are building from within `GOPATH`.
"Please" is a little over the top, don't you think? Previous statements have been pretty direct, do this, do that. No need to start begging now

2018-12-29 02:40 UTC, itswisdomagain commented on README.md
>  $ cd ~/src/dcrcli
I have issues with this clone syntax. It assumes there is a `~/src` folder. Let's simplify things here:
```
$ git clone https://github.com/raedahgroup/dcrcli
$ cd dcrcli 
```

2018-12-29 02:42 UTC, itswisdomagain commented
PR #64 will continue work on issue #58 by updating the **Running dcrcli** section of the readme

2018-12-29 03:07 UTC, itswisdomagain requested changes

2018-12-29 03:07 UTC, itswisdomagain commented on cli/handlers.go
> +
What does this change have to do with this PR?

2018-12-29 14:08 UTC, itswisdomagain approved these changes

2018-12-29 14:08 UTC, merged