fixed dcrcli window build error
raedahgroup/godcr-old pull request #79
Opened 2018-12-24 17:05 UTC by Sirmorrison

fixed undefined syscall error will building on windows

2018-12-24 17:32 UTC, barisere requested changes
This PR does not fix the issue in a way that preserves the current functionality of the program.
The lines @Sirmorrison  commented out served to allow users type in sensitive information such as passphrases without revealing them on the command line. This is similar to input masking, where a particular character, say "*", is displayed instead of each character of the input text. It's a basic security measure for requesting sensitive information at the terminal: someone else looking at the screen cannot easily tell what the user is typing.
An acceptable solution to this issue is to find a way to either disable terminal echo, or mask terminal input, on Windows. This PR cannot be merged, with this approach.

2018-12-24 21:03 UTC, itswisdomagain requested changes
I haven't tested the PR to see if it'll build or run correctly. Looking at the code changes, it doesn't matter if it builds or runs correctly. There are unacceptable codes in this PR that have to be removed first before further consideration can be granted.

2018-12-24 21:03 UTC, itswisdomagain commented on cli/terminalprompt/getinput.go
> +	//"os/signal"
Soo many commented code on this file! If a code isn't needed, delete the code rather than comment it out. We certainly don't want unused code on the master branch, which means even if this PR accomplished it's objective, we can't merge it to master.

2018-12-24 21:03 UTC, itswisdomagain commented on cli/terminalprompt/getinput.go
> +	"golang.org/x/crypto/ssh/terminal"
There was a time we used this and other similar libraries to collect sensitive info (e.g. password) from terminal. But the use of an external library for this requirement was discouraged. Before we can consider using an external library here, we have to be sure there's no other way to solve the issue at hand

2018-12-25 00:20 UTC, itswisdomagain commented
I'm gonna make this a [WIP] PR. Once you have something that solves this problem in an acceptable manner, remove the [WIP] "flag"

2018-12-30 00:54 UTC, itswisdomagain requested changes

2018-12-30 00:54 UTC, itswisdomagain commented on go.mod
> +	golang.org/x/crypto v0.0.0-20180808211826-de0752318171
Remove this from your go.mod. Maybe run `go mod tidy` to cleanup your go.mod and go.sum files

2018-12-30 00:54 UTC, itswisdomagain commented on cli/terminalprompt/getinput.go
This empty space can be done without

2018-12-30 00:54 UTC, itswisdomagain commented on cli/terminalprompt/getinput.go
> +	if on{
go fmt this file: `go fmt ./cli/terminalprompt/getinput.go`

2018-12-30 00:54 UTC, itswisdomagain commented on cli/terminalprompt/getinput.go
> +	var cmdToExecute string
This is actually an argument, not a command. In line 71, the actual command is `stty` while the second parameter is the argument to the `stty` command. Rename this variable to `sttyCmdArg` or `sttyEchoArg`.

2018-12-30 01:57 UTC, itswisdomagain approved these changes

2018-12-30 01:59 UTC, itswisdomagain commented
@barisere can you confirm that the changes made in this PR produce the expected behaviour on linux? As mentioned here (#92), this PR on windows command prompt doesn't produce the desired password masking behaviour but @raedah agrees it can be left that way for now to allow us focus on more important tasks

2018-12-30 02:41 UTC, barisere commented
> @barisere can you confirm that the changes made in this PR produce the expected behaviour on linux? As mentioned here (#92), this PR on windows command prompt doesn't produce the desired password masking behaviour but @raedah agrees it can be left that way for now to allow us focus on more important tasks

The behaviour on Linux did not change, as expected.

2018-12-30 02:42 UTC, barisere approved these changes

2018-12-30 10:50 UTC, merged