Transaction Details View for CLI.
raedahgroup/godcr-old pull request #83
Opened 2018-12-27 13:09 UTC by barisere

Partial solution to #69

2018-12-27 13:19 UTC, barisere commented
Here's the current output of the `get-transaction` command.
```
$ ./dcrcli -t -C dcrcli.conf get-transaction c3b6b67284ab25208008838e6cbb965c0da1fd33f57e14257b24d00579487ff2
Transaction       c3b6b67284ab25208008838e6cbb965c0da1fd33f57e14257b24d00579487ff2 
Confirmations     17194                                                            
Included in block f27f487905d0247b25147ef533fda10d5c96bb6c8e8308802025ab8472b6b6c3 
Type              REGULAR                                                          
Total sent        200 DCR                                                          
Time              Wed Nov 28, 2018 9:13PM                                          
Size              3.4 kB                                                           
Fee               0.003407 DCR                                                     
Rate              0.00100948 DCR/kB
```

[Compare this output to that on decred explorer](https://testnet.dcrdata.org/tx/c3b6b67284ab25208008838e6cbb965c0da1fd33f57e14257b24d00579487ff2). The block has displayed here is incorrect (it looks like a byte-reversed copy of the transaction hash). Is it possible that dcrwallet is returning incorrect data?
The time shown in this output is approximate. That may be because `time.Unix` accepts two arguments, but the second argument (the nanoseconds) was not provided.

2018-12-28 08:36 UTC, barisere commented
Here's how the current output of `get-transaction --detailed` looks.
```
$ ./dcrcli -t -C dcrcli.conf get-transaction --detailed dac27eb8b0238fb3a69b19dcb9254f865ae6df6d7ef7ecbd1bdc828ed0c6ed45
Transaction       dac27eb8b0238fb3a69b19dcb9254f865ae6df6d7ef7ecbd1bdc828ed0c6ed45 
Confirmations     35                                                               
Included in block 45edc6d08e82dc1bbdecf77e6ddfe65a864f25b9dc199ba6b38f23b0b87ec2da 
Type              REGULAR                                                          
Total sent        0.000253 DCR                                                     
Time              Fri Dec 28, 2018 7:54AM                                          
Size              0.3 kB                                                           
Fee               0.000253 DCR                                                     
Rate              0.00100396 DCR/kB                                                

Inputs                                                             
74448f25f85bb8a49c5b84695f3f95e9f8deaf96fe8edc5069f5cce2379400d2:0 0.998494 DCR 

Outputs                             
TsdCKdRnJ354Y7sHhRdbbGs3SrBP4qfXCbR pubkeyhash 0.997241 DCR (internal) 
TsfMhvoGbn7RVq3zKUJ9obE8ut7JFrnGwgT pubkeyhash 0.001 DCR 
```

2018-12-30 11:19 UTC, itswisdomagain requested changes
Preliminary review. Will do a deep dive shortly and provide more feedback

2018-12-30 11:19 UTC, itswisdomagain commented on cli/commands/commands.go
> +	GetTransaction GetTransactionCommand `command:"get-transaction" description:"show details of a transaction"`
I think `show-transaction` makes more sense for the command name. It's also what @raedah suggested in #69

2018-12-30 11:19 UTC, itswisdomagain commented on cli/commands/get-transaction.go
> +		Hash string `positional-arg-name:"transaction hash" required:"yes"`
`TxHash`, to differentiate from other hashes like `BlockHash`

2018-12-30 11:19 UTC, itswisdomagain commented on cli/commands/get-transaction.go
> +func (g GetTransactionCommand) Execute(args []string) error {
Maybe use `getTransactionCommand` instead of `g` so lines 20 and 39 become more readable...

2018-12-30 11:19 UTC, itswisdomagain commented on walletrpcclient/helpers.go
> +			FormattedTime: time.Unix(txDetail.Timestamp, 0).UTC().Format("Mon Jan 2, 2006 3:04PM"),
Why UTC? Could be misleading to a user especially since "UTC" isn't appended to this formatted time. The previous code shows the time as it is on the running user's PC. But I see how this can be a problem when running an http server in utc+2 and users access the page from a different timezone.

For cli mode, we should use local pc timezone in formatting the time. In web mode, we use utc but append "utc" to the formatted time so user doesn't get confused. I think this should be done in a separate PR, will create an issue for it. `FormattedTime` will need to be removed from this core package, allowing the `cli` and `web` packages do their own formatting.

For now, revert to what we had

2018-12-30 11:19 UTC, itswisdomagain commented on walletrpcclient/types.go
> +type GetTransactionResponse struct {
How about `TransactionDetail` or `DetailedTransaction`, seeing as this is an extension of the basic transaction info. Or, we could rename `Transaction` to `BasicTransactionInfo` call this `TransactionInfo`. Something descriptive of the info this type holds but without the using the `<command>Response` format.

2018-12-30 11:19 UTC, itswisdomagain commented on walletrpcclient/types.go
> +	Value            dcrutil.Amount `json:"value"`
`Value` or `Amount`, which is better?

2018-12-30 11:19 UTC, itswisdomagain commented on walletrpcclient/walletrpcclient.go
> +
can do without the space

2018-12-30 18:21 UTC, itswisdomagain requested changes

2018-12-30 18:21 UTC, itswisdomagain commented on walletrpcclient/walletrpcclient.go
> +	isTestNet           bool
This variable is only used in `chainCfgParams` function to determine the `*chaincfg.Params` object to use. Replace this with `activeNet *chaincfg.Params` instead. Assign the correct value in `New`. Remove the `chainCfgParams` function.

If at any other time, we need to know if we're running testnet, we can do `client.activeNet.Name != "mainnet"`. We do a reverse check for mainnet, because there are 2 possible testnets - testnet and testnet3.

2018-12-30 18:21 UTC, itswisdomagain commented on walletrpcclient/walletrpcclient.go
> +		return nil, err
When an invalid hash is used with this command, the error isn't very helpful. Could instead `return nil, fmt.Errorf("invalid hash: %s\n%s", transactionHash, err.Error())` since `chainhash.NewHashFromStr` only produces an error if the hash string is invalid, but the error it returns in itself is not always helpful.

2018-12-30 18:21 UTC, itswisdomagain commented on walletrpcclient/walletrpcclient.go
> +	getTxResponse, err := c.walletServiceClient.GetTransaction(context.Background(), getTxRequest)
Not all invalid transaction hashes are caught by `chainhash.NewHashFromStr`, from what I notice, any hash string starting with "d" but not longer than 64bytes is seen as valid by that function. But when you send the hash byte to dcrwallet rpc, it causes the running dcrwallet daemon to close and you get the error `rpc error: code = Unavailable desc = transport is closing`

This is potentially very problematic because it would require that the user restart dcrwallet to continue using godcr. Perhaps dcrwallet should have done a better job of handling such errors without causing the program to panic we should see if there's something we can do to prevent this, perhaps revalidate the hash before sending to dcrwallet rpc.

Here's a screenshot of the error trace printed on dcrwallet terminal window, it might help to look into dcrwallet code to find the cause of the problem and figure a way to prevent it:
![screenshot 2018-12-30 at 6 24 54 pm](https://user-images.githubusercontent.com/18400051/50549628-58ef9200-0c60-11e9-8b32-4faba11303bf.png)

2018-12-30 18:21 UTC, itswisdomagain commented on walletrpcclient/walletrpcclient.go
> +	txInfos, err := c.processTransactions([]*pb.TransactionDetails{getTxResponse.GetTransaction()})
In `helpers.go`, create a new function `processTransaction` to deal with 1 transaction and modify `processTransactions` to call the new function

2018-12-30 18:21 UTC, itswisdomagain commented on walletrpcclient/walletrpcclient.go
> +func inputsFromMsgTxIn(txIn []*wire.TxIn) []TxInput {
This function and the next should go into `helpers.go`

2018-12-30 18:21 UTC, itswisdomagain commented on walletrpcclient/walletrpcclient.go
> +		scriptClass, addrs, _, err := txscript.ExtractPkScriptAddrs(output.Version, output.PkScript, chainParams)
Don't think we need `scriptClass`. Not really necessary to show as much detail as is displayed on explorer

2018-12-30 18:21 UTC, itswisdomagain commented on walletrpcclient/types.go
> +	PreviousOutpoint wire.OutPoint  `json:"previousOutpoint"`
Examine usages of this variable and simplify its type. I don't think we need the `wire.OutPoint` type

2018-12-30 18:21 UTC, itswisdomagain commented on cli/commands/get-transaction.go
> +	basicOutput := "Transaction\t%s\t\n" +
`Hash` instead

2018-12-30 18:21 UTC, itswisdomagain commented on cli/commands/get-transaction.go
> +	basicOutput := "Transaction\t%s\t\n" +
The extra tab (`\t`) at the end of each line before `\n` isn't needed. It causes anomaly in small-width terminal windows:
![screenshot 2018-12-30 at 6 18 27 pm](https://user-images.githubusercontent.com/18400051/50549931-7a537c80-0c66-11e9-986a-98ccf3d0b40a.png)

2018-12-30 18:21 UTC, itswisdomagain commented on cli/commands/get-transaction.go
> +		"Total sent\t%s\t\n" +
Not all transactions are sent transactions. It would be nice to use `Amount sent`, `Amount received` or `Amount transferred` for the different transaction directions.

2018-12-30 18:21 UTC, itswisdomagain commented on cli/commands/get-transaction.go
> +		"Time\t%s\t\n" +
dcrandroid uses `Date`, am not sure which will send the message across faster to the user

2018-12-30 18:21 UTC, itswisdomagain commented on cli/commands/get-transaction.go
> +	basicOutput = fmt.Sprintf(basicOutput, transaction.Hash, transaction.Confirmations, transaction.BlockHash,
break each value into a line of its own so we can easily tally it with the field name above

2018-12-30 18:21 UTC, itswisdomagain commented on cli/commands/get-transaction.go
> +		detailedOutput.WriteString("\nInputs\t\n")
same comment about trailing tab space

2018-12-30 18:21 UTC, itswisdomagain commented on cli/commands/get-transaction.go
> +			detailedOutput.WriteString(fmt.Sprintf("%s\t%s\t\n", input.PreviousOutpoint, input.Value))
same comment about trailing tab space

2018-12-30 18:21 UTC, itswisdomagain commented on cli/commands/get-transaction.go
> +			detailedOutput.WriteString(fmt.Sprintf("%s\t%s\t%s", out.Address, out.ScriptClass, out.Value.String()))
same comment about trailing tab space

2018-12-30 18:21 UTC, itswisdomagain commented on cli/commands/get-transaction.go
> +		detailedOutput.WriteString("\nOutputs\t\n")
same comment about trailing tab space

2018-12-30 18:21 UTC, itswisdomagain commented on cli/commands/get-transaction.go
> +			detailedOutput.WriteString("\t\n")
same comment about trailing tab space

2018-12-30 18:26 UTC, itswisdomagain commented
Regarding the output of the detailed command, I particularly like the simplicity of dcrandroid:
![screenshot 2018-12-27 at 9 45 39 pm](https://user-images.githubusercontent.com/18400051/50550025-4416fc80-0c68-11e9-93b7-41d2dd50be3e.png)

For Inputs, we should probably display amounts first. It's more friendly to the eyes.
For outputs, `Amount  Address (internal/external)` does it as well.

Also, for `detailed` view, title the first section:
```
General Info
Hash        dac27eb8b0238fb3a69b19dcb9254f865ae6df6d7ef7ecbd1bdc828ed0c6ed45 
Confirmations     35                                                               
Included in block 45edc6d08e82dc1bbdecf77e6ddfe65a864f25b9dc199ba6b38f23b0b87ec2da 
Type              REGULAR                                                          
Total sent        0.000253 DCR                                                     
Time              Fri Dec 28, 2018 7:54AM                                          
Size              0.3 kB                                                           
Fee               0.000253 DCR                                                     
Rate              0.00100396 DCR/kB                                                

Inputs                                                             
74448f25f85bb8a49c5b84695f3f95e9f8deaf96fe8edc5069f5cce2379400d2:0 0.998494 DCR 

Outputs                             
TsdCKdRnJ354Y7sHhRdbbGs3SrBP4qfXCbR pubkeyhash 0.997241 DCR (internal) 
TsfMhvoGbn7RVq3zKUJ9obE8ut7JFrnGwgT pubkeyhash 0.001 DCR 
```

2018-12-30 19:50 UTC, barisere commented on walletrpcclient/walletrpcclient.go
> +	getTxResponse, err := c.walletServiceClient.GetTransaction(context.Background(), getTxRequest)
I cannot reproduce this error. Looking at the code for `NewHashFromString`, I understand that it allows strings shorter than 64 characters. But the special case of a string starting with "d" crashing dcrwallet is weird.
```
$ ./godcr -t -C ../dcrcli.conf show-transaction d970a25cbe7421f9371180baa1
rpc error: code = NotFound desc = wallet.TransactionSummary(00000000000000000000000000000000000000d970a25cbe7421f9371180baa1): item does not exist
```
The above does not crash dcrwallet. dcrwallet logs the following error.
```
2018-12-30 20:44:15.418 [ERR] GRPC: Unary method /walletrpc.WalletService/GetTransaction invoked by 127.0.0.1:55700 errored: rpc error: code = NotFound desc = wallet.TransactionSummary(00000000000000000000000000000000000000d970a25cbe7421f9371180baa1): item does not exist
```

2018-12-30 21:35 UTC, itswisdomagain commented on walletrpcclient/walletrpcclient.go
> +	getTxResponse, err := c.walletServiceClient.GetTransaction(context.Background(), getTxRequest)
Ah. Maybe it's been fixed and I'm using an older version of dcrwallet

2018-12-30 21:53 UTC, itswisdomagain approved these changes

2018-12-30 21:56 UTC, merged