Make packages commands and config disjoint
raedahgroup/godcr-old pull request #86
Opened 2018-12-28 15:48 UTC by barisere

@ademuanthony discovered that a circular dependency occurred between cli/commands and config packages, while he was working on another PR. I noticed that before, but I managed to sidestep it for a while.
This PR makes those packages disjoint. config package now handles only the top-level application options and configuration. Both the `config.Config` type and the `commands.CliCommands` type are mediated by a third type, `AppRoot`, in the cli package.

I also removed a dependency on a global variable that provided the wallet rpc client to the commands. That dependency is now injected at runtime. A consequence of this change is that the `Execute` methods on the commands is now a noop in any command that requires a wallet rpc client, but because it is required for `go-flags` to identify the type as a `Commander`, it cannot be removed yet. The alternative is to provide our own routing of arguments to commands, which is still some more code. I'm fine with a three-line, noop method copied around, because it does nothing more than satisfying `go-flags`. If we ever replace `go-flags`, all those methods will disappear easily.

2018-12-28 23:18 UTC, itswisdomagain requested changes
Very neat work. Some changes here and there

2018-12-28 23:18 UTC, itswisdomagain commented on cli/cli.go
> +type CommandHandler func(flags.Commander, []string) error
This can be private

2018-12-28 23:18 UTC, itswisdomagain commented on cli/cli.go
> +			return fmt.Errorf("unsupported command")
According to the go-flags doc, `command == nil` isn't a case of unsupported command
> The command passed into CommandHandler may be nil in case there is no command to be executed when parsing has finished.

2018-12-28 23:18 UTC, itswisdomagain commented on cli/commands/balance.go
> +// Execute is a stub method to satisfy the commander interface, so that
Here's a thought. To avoid having this method stub on all commands implementing `WalletCommandRunner`, you can create a `CommanderStub` struct in `commands.go` and make such commands embed `CommanderStub` in their definition.

In commands.go,
```
// CommanderStub implements `flags.Commander` using a noop Execute method to satisfy the commander interface
// Commands embedding this struct would ideally implement `WalletCommandRunner` so that their `Run` method can
// be invoked by the custom command handler which will inject the necessary dependencies to run the command.
type CommanderStub struct {}
func (c CommanderStub) Execute(args []string) error {
	return nil
}
```

Then in files like this (balance.go), the command struct becomes
```
type BalanceCommand struct {
	*CommanderStub
        ....
}
```

2018-12-28 23:18 UTC, itswisdomagain commented on cli/cli.go
> +func DefaultCommandHandler(client *walletrpcclient.Client) CommandHandler {
This could better be called `CommandHandlerWrapper` seeing as it is a wrapper around the actual handler for each command.

2018-12-28 23:18 UTC, itswisdomagain commented on cli/commands/commands.go
> +// WalletCommandRunner defines an optional interface that application commands dependent on
"optional" isn't really necessary, interfaces by default are optional
also, application commands dependent on walletrpcclient.Client do need to implement this interface, so it isn't optional for such commands, it is "optional" for other commands, but then aren't all interfaces optional?

2018-12-28 23:18 UTC, itswisdomagain commented on cli/commands/receive.go
> +
The space can be done without

2018-12-28 23:18 UTC, itswisdomagain commented on cli/termio/writer.go
> +type Response struct {
Every other thing in this file and (ideally in this package), strictly has to do with terminal input/output. This? Not really. It's sort of a bridge between command handlers and terminal output.

2 thoughts:
- Put this in the commands package
- Or do away with it all together, let the `PrintResult` function take `columns []string` and `result [][]interface{}`

I prefer the second approach, it's more readable. We could even change the function to `PrintTabularResult` and the parameters to `column` and `rows`. Now that's more descriptive of what this function actually does.

2018-12-28 23:18 UTC, itswisdomagain commented on config/config.go
> +	return config, parser, nil
All return paths return `config`, `parser` and `err`. Maybe you could use named return parameters. _Could_

2018-12-28 23:18 UTC, itswisdomagain commented on main.go
> +	"github.com/raedahgroup/dcrcli/cli"
IDE did this no doubt. This import can return to where it was...

2018-12-28 23:18 UTC, itswisdomagain commented on cli/cli.go
> +type AppRoot struct {
`App` signifies the entire dcrcli program, including the web and other interfaces. This struct defines cli-only properties, a better name can be used

2018-12-29 00:10 UTC, itswisdomagain commented
This just came to mind:
In main.go, `config.LoadConfig()` will reject cli command-specific flags/options as unknown. Example is `dcrcli balance -d`

2 possible solutions:
- `config.LoadConfig()` should use `AppRoot` as the first argument to `flags.NewParser`. The function would then need to register a noop command handler on `parser` to prevent commands from being executed during the initial config parsing. One problem with this approach is that, you'll likely run into the circular dependency issue once again. Another caveat of this approach is that, if http mode is enabled, cli-only flags/options will be allowed to roam free if used "aimlessly" with the associated cli command. An example is `dcrcli balance -d --http`. Don't know about you, but I think a user running such command is confused and needs to be reminded that there is a difference between cli mode and http mode.

- Use `flags.HelpFlag|flags.IgnoreUnknown` as second argument to `flags.NewParser`. This has the advantage of deferring unknown flag errors to be handled by the cli command parser in `enterCliMode` of main.go. But it also means that if http mode is enabled, unknown options will be permitted to roam free. To circumvent that caveat, http mode should trigger another parsing that does not ignore unknown flags/options and does not include cli commands. Doing this second parsing for http mode has the added advantage of reminding a "confused" user of the cli/http mode difference if a user passes a cli-only flag. For example, `dcrcli balance -d --http` will give an error `-d` is an unknown option. Of course, that message can be better, we should also tell the user that commands are not accepted/allowed in http mode. We can do that if we modify `config.LoadConfig()` to also return `args`. In http mode, if `len(args) > 0`, a command was passed, we should remind the user that http mode don't work with commands.

The following is how I expect `config.LoadConfig()` to appear using the second possibility:
```
func LoadConfig(ignoreUnknownOptions bool) (Config, *flags.Parser, []string, error) {
	// load defaults first
	config := defaultConfig()

	var parserOptions flags.Options
	if ignoreUnknownOptions {
		parserOptions = flags.HelpFlag|flags.IgnoreUnknown
	} else {
		parserOptions = flags.HelpFlag
	}
	parser := flags.NewParser(&config, parserOptions)

	args, err := parser.Parse()
	if err != nil && !IsFlagErrorType(err, flags.ErrHelp) {
		return config, parser, args, err
	}

	if config.ShowVersion {
		return config, parser, args, fmt.Errorf(AppVersion())
	}

	// Load additional config from file
	err = flags.NewIniParser(parser).ParseFile(config.ConfigFile)
	if err != nil {
		if _, ok := err.(*os.PathError); !ok {
			return config, parser, args, fmt.Errorf("Error parsing configuration file: %v", err.Error())
		}
		return config, parser, args, err
	}

	// Parse command line options again to ensure they take precedence.
	args, err = parser.Parse()
	if err != nil && !IsFlagErrorType(err, flags.ErrHelp) {
		return config, parser, args, err
	}

	return config, parser, args, nil
}
```

2018-12-29 02:52 UTC, barisere commented on cli/cli.go
> +			return fmt.Errorf("unsupported command")
If the command passed into `CommandHandler` is nil, it means we registered a command that does not satisfy the `CommandHandler` interface. it's something we should catch early. For now, what error message can be used?

2018-12-29 02:59 UTC, barisere commented on cli/commands/balance.go
> +// Execute is a stub method to satisfy the commander interface, so that
How did I miss that? Thank you :slightly_smiling_face:

2018-12-29 03:18 UTC, barisere commented on main.go
> +	"github.com/raedahgroup/dcrcli/cli"
IDE :man_facepalming:

2018-12-29 03:43 UTC, barisere commented on config/config.go
> +	return config, parser, nil
That would be convenient, but it tends to produce an inconsistent style and obscure the return values of the function at the return site.
```go
func LoadConfig() (config Config, parser *flags.Parser, err error) {
	// load defaults first
	config = defaultConfig()

	parser = flags.NewParser(&config, flags.HelpFlag)

	_, err = parser.Parse()
	if err != nil && !IsFlagErrorType(err, flags.ErrHelp) {
		return
	}

	if config.ShowVersion {
		return config, parser, fmt.Errorf(AppVersion())
	}

	// Load additional config from file
	err = flags.NewIniParser(parser).ParseFile(config.ConfigFile)
	if err != nil {
		if _, ok := err.(*os.PathError); !ok {
			return config, parser, fmt.Errorf("Error parsing configuration file: %v", err.Error())
		}
		return
	}

	// Parse command line options again to ensure they take precedence.
	_, err = parser.Parse()
	if err != nil && !IsFlagErrorType(err, flags.ErrHelp) {
		return
	}

	return
}
```
At some points we simply return, at some points we say what we're returning, and at the final return it's not clear what the return values should be, especially that err should be nil. Thus, you have to keep the code trace in your head at every point to know what each return value will be (debugger mode). I think named returns can make readability worse.

2018-12-29 16:14 UTC, barisere commented
https://github.com/raedahgroup/dcrcli/pull/86#issuecomment-450446124
@itswisdomagain I've addressed this in my latest commits.

2018-12-29 20:53 UTC, itswisdomagain commented on cli/cli.go
> +			return fmt.Errorf("unsupported command")
"Invalid command" is good. From your explanation, the command is actually supported but not properly defined. If the command is not supported, the program won't even get to this point. Would it?

2018-12-29 21:31 UTC, ademuanthony commented
Great effort.
Though the circular dependency still continues for my use case as I want to reference the `AppRoot` in the `cli` package in `commands`; whereas the `cli` package already references the `commands` package.

So I am thinking, what if the commands are moved to the `cli` package, seeing that that is the main component in that package, it may not be that bad to have it at the root.
It may look like we will lose the organization that the current structure provides, but with the current convention of adding 'Command' suffix to the command names, I think it makes sense enough to have `cli.SendCommand`

2018-12-29 22:08 UTC, itswisdomagain requested changes

2018-12-29 22:08 UTC, itswisdomagain commented on cli/cli.go
> +type CommandHandler func(flags.Commander, []string) error
Looks like you missed this... `CommandHandler` should be private, it isn't used outside this file and I don't suppose we'll need to create an instance of this type outside this package, would we?

2018-12-29 22:08 UTC, itswisdomagain commented on cli/cli.go
> +			return fmt.Errorf("unsupported command")
Since this only occurs for commands not properly defined, "command is not execution-ready" sounds more appropriate. Unsupported commands would not even get to this point. So the user should know that the command is actually supported (we registered it on the parser afterall and it shows in `dcrcli -h`) but for some reason the command isn't ready for execution. A command that is actually ready for execution would implement `Commander`.

2018-12-29 22:08 UTC, itswisdomagain commented on cli/termio/helpers.go
> +package termio
Forgot to mention this previously. I think this file belongs in the `commands` package. The functions here exist for the sole purpose of assisting the process of executing one or more commands. `termio` is just 1 of the packages that this file uses in performing its functions.

2018-12-29 22:08 UTC, itswisdomagain commented on config/config.go
> -	if config.ShowVersion {
We should retain the behaviour of handling `-v` cases in this function. Not in `main.go`. Moving this handler to `main.go` does not provide any advantage. Rather, main.go refers back to this file to get the version info to be displayed.

My estimation is, you moved this handler from here to ensure that errors arising from invalid flags/options are handled before attempting to print help information. If so, that goal is not achieved because before handling `-v` cases in main.go, the previous line explicitly instructs `config.ParseConfig` to ignore unknown flags/options.

I recommend that we can continue to simply check for `-v` presence after first command-line options parsing, display version info and exit without even parsing the config file. If we want to bother ourselves with catching invalid flags/options, we would run into trouble with command-specific flags/options that will be seen as invalid when running `config.LoadConfig()`

2018-12-29 22:08 UTC, itswisdomagain commented on main.go
> +			fmt.Println("cannot use --http with a command")
`args` returned from `config.LoadConfig(true)` contains all elements encountered that are not valid config options. This would include commands, yes, since commands are not part of the config struct used in `config.LoadConfig` but it could also contain command-specific flags/options, invalid flags/options and any other random unexpected text encountered while parsing.

For example, `args` returned for
- `dcrcli balance --http` would contain "balance", a valid command but not expected in http mode
- `dcrcli -b --http` would contain "-b", an entirely unknown option
- `dcrcli balance -d --http` would contain "balance and -d", both valid command and valid command-flag respectively but unexpected in http mode
- `dcrcli hey --http` would contain "hey", an entirely unexpected, random text
- `dcrcli -t balance -d hey -http` would contain "balance, -d and hey" as unknown "options"

To accurately deal with all possibilities above and other similar possibilities, this message displayed to the user should be more informative. I thought of `fmt.Printf("unexpected command, argument, flag or option: '%s'\n", strings.Join(args, ", "))`. For the scenarios above, the message would be
- unexpected command, argument, flag or option: 'balance'
- unexpected command, argument, flag or option: '-b'
- unexpected command, argument, flag or option: 'balance, -d'
- unexpected command, argument, flag or option: 'hey'
- unexpected command, argument, flag or option: 'balance, -d, hey'

2018-12-29 22:22 UTC, ademuanthony commented on cli/cli.go
> +type CliRoot struct {
Since we are already in the `cli` package, I am thinking `Root` maybe a sufficient name for the struct

2018-12-29 23:06 UTC, itswisdomagain commented on cli/cli.go
> +type CliRoot struct {
I think `Root` doesn't exactly sound like a good name. But then...

2018-12-30 00:39 UTC, barisere commented on cli/cli.go
> +			return fmt.Errorf("unsupported command")
We shouldn't let commands that are unavailable show up in the help message. How about letting the user know we've messed something up, and asking them to report it to us.
> the command <command name\> was not properly setup. Please report this bug at https://github.com/raedahgroup/godcr/issues.

2018-12-30 02:27 UTC, itswisdomagain requested changes

2018-12-30 02:27 UTC, itswisdomagain commented on dcrcli.conf
> +[Application Options]
Remove this file

2018-12-30 02:27 UTC, itswisdomagain commented on config/config.go
> +	ShowVersion       bool   `short:"v" long:"version" description:"Display version information and exit. Every other flag or command is ignored."`
"Every other" should be "Any other'

2018-12-30 02:49 UTC, barisere commented on dcrcli.conf
> +[Application Options]
[PR 64](https://github.com/raedahgroup/godcr/pull/64) should take care of this. From when PR 64 gets merged, that file will not be needed again. But this PR makes no assumption about that file.

2018-12-30 11:29 UTC, itswisdomagain approved these changes

2018-12-30 11:29 UTC, merged