./godcr help
raedahgroup/godcr-old pull request #98
Opened 2018-12-31 15:57 UTC by ademuanthony

fixes [51](https://github.com/raedahgroup/dcrcli/issues/51).
Added a './dcrcli help [command]' command that shows general help message or specific help message when called with the optional [command] param
This is a replacement for [PR 63](https://github.com/raedahgroup/godcr/pull/63) in which I had some issue and have to take the work to another branch
![help-reworked](https://user-images.githubusercontent.com/11990092/50563432-1049de80-0d1d-11e9-8abe-02ec62ecdd8a.png)

Individual command
![help-rewored-single](https://user-images.githubusercontent.com/11990092/50563442-20fa5480-0d1d-11e9-8d76-233638b8957b.png)

2018-12-31 16:13 UTC, barisere requested changes
Nice work @ademuanthony, it's almost done. Let's see...

2018-12-31 16:13 UTC, barisere commented on cli/commands/help.go
> +	fmt.Printf("To view application options, use '%s help'\n", config.AppName())
Use `appName` instead of calling `config.AppName`.
Also, this function is equivalent to that in main. Delete the one in main, and use this one there.

2018-12-31 16:33 UTC, barisere commented on cli/commands/help.go
> +	PrintCommandHelp(config.AppName(), targetCommand)
`package commands` should not depend on `package config`. That was the purpose of the work we did splitting them. The current app name is registered on the parser as `parser.Name`, use that instead.

2018-12-31 19:08 UTC, itswisdomagain requested changes
Below are a few ways the code could be improved.

Also, the help message displayed for specific commands is not detailed enough yet. I think only balance command has help sufficient info.

Compare https://github.com/raedahgroup/godcr/pull/63#issuecomment-449841140 and https://github.com/raedahgroup/godcr/pull/63#issuecomment-449847773 for what's expected.

2018-12-31 19:08 UTC, itswisdomagain commented on cli/commands/commands.go
> +	Help            HelpCommand            `command:"help" description:"show help for a command"`
`godcr help` doesn't show help for any command, `godcr help <command>` does. This description should be updated. Also, the description should let users know they can run `godcr help <command-name>` for command-specific help. They shouldn't need to run `godcr help -h` before the see the optional command name argument.

2018-12-31 19:08 UTC, itswisdomagain commented on cli/commands/help.go
> +	helpParser := flags.NewParser(nil, flags.HelpFlag)
There's a function performing practically the same thing as this in `cli.go`. Bring that function to this file and have `cli.go` invoke the function moved here

2018-12-31 19:08 UTC, itswisdomagain commented on cli/commands/help.go
> +	helpParser.WriteHelp(os.Stderr)
The output of this command shouldn't go to `Stderr`, it's a valid command. Display the output as you would for any other command - to `Stdout`. That's what's done in the version of this code in `cli.go`

2018-12-31 19:18 UTC, barisere requested changes
@ademuanthony you force-pushed your last commit, erasing the entire history of the previous commits published on this PR. This erases the context of the previous reviews, making it hard to track the progress of this PR. The merge conflict you had was trivial, by inspection. You should avoid force-pushing and erasing history as much as possible. It's usually problematic.

2018-12-31 19:18 UTC, barisere commented on cli/runner/parsercommand.go
> +package runner
Why is this package necessary?

2018-12-31 19:18 UTC, barisere commented on cli/runner/parsercommand.go
> +func (w ParserCommand) Execute(args []string) error {
This stub is not different from `CommanderStub` in cli/commands/commands.go. Why do we have it here?

2018-12-31 19:18 UTC, barisere commented on cli/runner/parsercommand.go
> +	Run(ctx context.Context, parser *flags.Parser, args []string) error
What would the use of `ctx` be? There's no need of a context here.

2018-12-31 20:35 UTC, ademuanthony commented on cli/runner/parsercommand.go
> +package runner
this was already in the master. I was only making my branch to work with what was already on the ground.

2018-12-31 20:45 UTC, ademuanthony commented on cli/runner/parsercommand.go
> +func (w ParserCommand) Execute(args []string) error {
CommanderStub in no longer in the master. We now have WalletCommand

2018-12-31 20:46 UTC, ademuanthony commented on cli/runner/parsercommand.go
> +	Run(ctx context.Context, parser *flags.Parser, args []string) error
I can't see it being useful
Will remove it

2018-12-31 21:09 UTC, barisere commented on cli/runner/parsercommand.go
> +package runner
I wouldn't know, because of the force-push. We can make changes anyway.

2018-12-31 21:11 UTC, barisere commented on cli/runner/parsercommand.go
> +func (w ParserCommand) Execute(args []string) error {
Wow, and that slipped by without a review. :unamused:

2018-12-31 21:50 UTC, barisere requested changes

2018-12-31 21:50 UTC, barisere commented on cli/commands/help.go
> +*/
I guess the problem this comment speaks of has been resolved. Can it be removed?

2018-12-31 21:50 UTC, barisere commented on cli/commands/receive.go
> +}*/
Can this comment be removed?

2018-12-31 21:50 UTC, barisere commented on cli/commands/commands.go
> +	Help            HelpCommand            `command:"help" description:"application help. You can run 'help <command-name>' for command-specific help."`
Let's use the following message.
> run 'help' for general help, or 'help <command-name>' for command-specific help.

2018-12-31 22:45 UTC, barisere approved these changes

2018-12-31 22:47 UTC, barisere commented
To take advantage of the work done in this PR, the descriptions (both long and short) on the commands should be updated, but this should be done in a separate pull request.
@itswisdomagain what do you think? Can this be merged?

2019-01-01 00:05 UTC, itswisdomagain requested changes
We're close, but the critical objective of this PR hasn't been satisfactorily met.

2019-01-01 00:05 UTC, itswisdomagain commented on cli/commands/help.go
> +func (h HelpCommand) Run(ctx context.Context, parser *flags.Parser, args []string) error {
We don't need context, you can adjust the definition of the `Run` method in `ParserCommandRunner` interface to remove this parameter

2019-01-01 00:05 UTC, itswisdomagain commented on cli/commands/commands.go
> +	Help            HelpCommand            `command:"help" description:"shows application help, run 'help' for general help 'help <command-name>' for command-specific help."`
You already explained that this command "shows application help" (maybe that can be "shows general application help")
No need to repeat that info by saying "run 'help' for general application help", the next info should be "run `help <command-name> for command-specific help

This can be simplified to:

> Shows general application help. Run `help <command-name>` to get help message for a specific command

2019-01-01 00:05 UTC, itswisdomagain commented on cli/commands/help.go
> +func PrintCommandHelp(appName string, command *flags.Command) {
We can improve this function's behaviour.
Currently,
![screenshot 2019-01-01 at 12 01 26 am](https://user-images.githubusercontent.com/18400051/50568846-743dc880-0d58-11e9-833e-4c415304ccf7.png)

The long description should be shown first, before usage. I think we can remove the reference to app options in the usage text for simplicity, having 2 [options] in the usage text can be confusing.

**This is a desired output:**
```
$ godcr balance -h
Show total balance for each account in wallet. Also shows spendable balance if different from total balance
Usage: godcr balance [args] [options]

Arguments:
account-name (required)       Name of account to generate balance for
account-number                Account number of account to generate balance for

Options
-d, --detailed                Display detailed account balance report

Use godcr -h to view application options
```

Achieving this would mean not using the parser.WriteHelp method but rather using `command. ShortDescription ` and `command. LongDescription` for short and long descriptions (no need to include short description in long description anymore), `command.Options` to get the [command options](https://godoc.org/github.com/jessevdk/go-flags#Option) (might be nil), `command.Args()` to get the [command arguments](https://godoc.org/github.com/jessevdk/go-flags#Arg) (might be nil also)

2019-01-01 10:41 UTC, ademuanthony commented
![help-detailed](https://user-images.githubusercontent.com/11990092/50572168-3a051300-0dba-11e9-859a-54ebb7f7c978.png)

2019-01-01 11:04 UTC, itswisdomagain requested changes
This is neat! Some thoughts

2019-01-01 11:04 UTC, itswisdomagain commented on cli/commands/help.go
> +	if len(command.LongDescription) > 0 {
We can avoid repeating the short description text in the long description and instead combine both when printing the description message for the command. That way, commands without long description will show just the short description and repetition is avoided.

`fmt.Printf("%s. %s\n")` does the trick

With this approach, we have to ensure now and going forward, that the both short and long descriptions for commands do not end with a period. Also, both descriptions should start with the first letter of the first word capitalized.

2019-01-01 11:04 UTC, itswisdomagain commented on cli/commands/help.go
> +		usageText += " [options]"
Always append the `[options]` text because even commands without command-specific options can still make use of general app options. That's why every command help message ends with instruction to view general app options. If there are command-specific options, then they are listed before the instruction to view general app options

2019-01-01 11:04 UTC, itswisdomagain commented on cli/commands/commands.go
> +	Balance         BalanceCommand         `command:"balance" description:"Shows total balance for each account in wallet" long-description:"Shows total balance for each account in wallet. Also shows sp
The long description should no longer include text from the short description (see comment below). Also information about command args and options can be omitted as these are well defined in the "Arguments" and "Options" section of the command's help message

2019-01-01 11:04 UTC, itswisdomagain commented on cli/commands/commands.go
> +	Help            HelpCommand            `command:"help" description:"Shows general application help. Run help <command-name> to get help message for a specific command"`
I think we should stick to active verbs for command short descriptions: "Show ..." instead of "Shows". It also tallies with the patterns above.

2019-01-01 11:04 UTC, itswisdomagain commented on cli/commands/help.go
> +			fmt.Println(fmt.Sprintf("%s %s%s %s", arg.Name, required, generateWhiteSpace(len(arg.Name), longestNameLength), arg.Description))
You can use tabs (`\t`) with the TabWriter in `termio/writer/go`

2019-01-01 11:05 UTC, itswisdomagain commented
> To take advantage of the work done in this PR, the descriptions (both long and short) on the commands should be updated, but this should be done in a separate pull request.

Yes, separate PR, to ensure thoroughness.

2019-01-01 12:03 UTC, ademuanthony commented on cli/commands/help.go
> +			fmt.Println(fmt.Sprintf("%s %s%s %s", arg.Name, required, generateWhiteSpace(len(arg.Name), longestNameLength), arg.Description))
I am unable to use the TabWriter due to formatting issues;
the extra space between the header and the body of the table is not desirable for my use case.

2019-01-01 13:34 UTC, itswisdomagain requested changes

2019-01-01 13:34 UTC, itswisdomagain commented on cli/commands/help.go
> +	fmt.Println()
Create the `tabWriter` earlier in this function and use it for all printing. When done, call `tabWriter.flush()`. Use `tabWriter` as variable name, it better describes the purpose the writer serves.

```
tabWriter := termio.StdoutWriter
fmt.Fprintf(tabWriter, "%s. %s\n", command.ShortDescription, command.LongDescription)
fmt.Fprintln(tabWriter)
```

2019-01-01 13:34 UTC, itswisdomagain commented on cli/commands/help.go
> +	options := command.Options()
This declaration and assignment can move to line 75, just before it's usage

2019-01-01 13:34 UTC, itswisdomagain commented on cli/commands/help.go
> +	fmt.Println()
```
fmt.Fprintln(tabWriter, usageText)
fmt.Fprintln(tabWriter)
```

2019-01-01 13:34 UTC, itswisdomagain commented on cli/commands/help.go
> +		longestNameLength := 0
This variable and the following loop is are longer necessary

2019-01-01 13:34 UTC, itswisdomagain commented on cli/commands/help.go
> +		writer := termio.StdoutWriter
Use the `tabWriter` created at the top of the function

2019-01-01 13:34 UTC, itswisdomagain commented on cli/commands/help.go
> +		fmt.Println()
Don't flush `tabWriter` yet, `fmt.Fprintln(tabWriter)`

2019-01-01 13:34 UTC, itswisdomagain commented on cli/commands/help.go
> +	if options != nil && len(options) > 0 {
I'm having some troubles reading the code in this if block, compare this snippet, more readable?
```
if options != nil && len(options) > 0 {
	fmt.Fprintln(tabWriter, "Options:")

	for _, option := range options {
		var optionUsages []string
		if option.ShortName != 0 {
			optionUsages = append(optionUsages, fmt.Sprintf("-%c", option.ShortName))
		}
		if option.LongName != "" {
			optionUsages = append(optionUsages, fmt.Sprintf("--%s", option.LongName))
		}
		optionText := strings.Join(optionUsages, ", ")

		fmt.Fprintf(tabWriter, "%s \t %s", optionText, option.Description)
	}

	fmt.Fprintln(tabWriter)
}
```

2019-01-01 13:34 UTC, itswisdomagain commented on cli/commands/help.go
> +	fmt.Println(fmt.Sprintf("Use %s -h to view application options", appName))
```
fmt.Fprintf(tabWriter, "Use %s -h to view application options\n", appName)
tabWriter.Flush()
```

2019-01-01 14:10 UTC, ademuanthony commented on cli/commands/help.go
> +	if options != nil && len(options) > 0 {
the current version tries to indent the options, giving 2 whitespaces for those with short and 4 for those without. This is an attempt to stay consistent with the output of parser.WriteHelp
It is not nesecary?

2019-01-01 20:46 UTC, itswisdomagain commented on cli/commands/help.go
> +	if options != nil && len(options) > 0 {
Ah, I see. It is indeed necessary. Will this work?
```
if options != nil && len(options) > 0 {
	fmt.Fprintln(tabWriter, "Options:")

	for _, option := range options {
		var optionUsages []string
		optionPrefix := "  "
		if option.ShortName != 0 {
			optionUsages = append(optionUsages, fmt.Sprintf("%s-%c", optionPrefix, option.ShortName))
                         optionPrefix = ""
		} else {
                         optionPrefix = "    "
		}
		if option.LongName != "" {
			optionUsages = append(optionUsages, fmt.Sprintf("%s--%s", optionPrefix, option.LongName))
		}
		optionText := strings.Join(optionUsages, ", ")

		fmt.Fprintf(tabWriter, "%s \t %s\n", optionText, option.Description)
	}

	fmt.Fprintln(tabWriter)
}
```

2019-01-01 21:59 UTC, itswisdomagain requested changes
Last lap, I believe. You'll have to rebase your branch with master to be able to effect some of the requested changes

2019-01-01 21:59 UTC, itswisdomagain commented on cli/runner/parsercommand.go
> +type ParserCommand struct{}
The `commanderStub` is back on master, this can go. Use `commands. commanderStub` instead

2019-01-01 21:59 UTC, itswisdomagain commented on cli/runner/parsercommand.go
> +type ParserCommandRunner interface {
Add this to `runner/runners.go`

2019-01-01 21:59 UTC, itswisdomagain commented on cli/commands/help.go
> +	usageText := fmt.Sprintf("Usage: %s %s", appName, command.Name)
To maintain consistency with parser.WriteHelp as you rightly recommended, the usage text should be printed in 2 lines like this
![screenshot 2019-01-01 at 10 33 23 pm](https://user-images.githubusercontent.com/18400051/50576602-829dea00-0e15-11e9-900f-f85b1e5e8ede.png)

I think `usageText := fmt.Sprintf("Usage:\n  %s %s", appName, command.Name)` does the trick. (2 spaces after the breakline)

2019-01-01 21:59 UTC, itswisdomagain commented on cli/commands/help.go
> +			fmt.Fprintln(tabWriter,fmt.Sprintf("%s %s \t %s", arg.Name, required, arg.Description))
Also, in keeping consistent with parser.WriteHelp, this should be prefixed with 2 spaces

2019-01-01 21:59 UTC, itswisdomagain commented on cli/commands/help.go
> +				optionUsage += "-" + string(option.ShortName) + ", "
There'd be a trailing comma on this output if there's no long name (not all config options) will have long name. Consider this (notice the subtle change to the comment too):

```
// option printout attempts to add 2 whitespace for options with short name and 6 for those without
// This is an attempt to stay consistent with the output of parser.WriteHelp
for _, option := range options {
	var optionUsage string

	if option.ShortName != 0 && option.LongName != "" {
		optionUsage = fmt.Sprintf("  -%c, --%s", option.ShortName, option.LongName)
	} else if option.ShortName != 0 {
		optionUsage = fmt.Sprintf("  -%c", option.ShortName)
	} else {
		optionUsage = fmt.Sprintf("      --%s", option.LongName)
	}

	fmt.Fprintln(tabWriter,fmt.Sprintf("%s \t %s", optionUsage, option.Description))
}
```

2019-01-01 22:36 UTC, ademuanthony commented
![23-29-01-help](https://user-images.githubusercontent.com/11990092/50576977-ff34c680-0e1d-11e9-8057-82776ed2d520.png)

2019-01-01 22:43 UTC, itswisdomagain requested changes
1 last change, then `go fmt ./...` your code

2019-01-01 22:43 UTC, itswisdomagain commented on cli/runner/runners.go
> +	Run(parser *flags.Parser, args []string) error
We don't really have a need for `args []string`, it can go

2019-01-01 22:57 UTC, itswisdomagain approved these changes

2019-01-01 22:57 UTC, merged