[WIP] createwallet command
raedahgroup/godcr-old pull request #99
Opened 2018-12-31 19:52 UTC by itswisdomagain

Running a godcr command without an existing wallet prompts user to create one.
This PR introduces a new `godcr createwallet` command that a user can run at any time to create a wallet.

2018-12-31 22:27 UTC, barisere requested changes

2018-12-31 22:27 UTC, barisere commented on cli/walletloader/helpers.go
> +		if userResponse == "" || strings.EqualFold("y", userResponse) || strings.EqualFold("N", userResponse) {
- The response from the user should be treated as case-insensitive.
- When using a polar question with y for yes and n for no, the uppercased option specifies the default. Are we encouraging the user to not create a wallet?

2018-12-31 22:27 UTC, barisere commented on cli/walletloader/helpers.go
> +		if userResponse == "" || strings.EqualFold("y", userResponse) || strings.EqualFold("N", userResponse) {
There may be other use cases for requesting yes/no answers from the user. This can be factored into a function in `package termio`.

2018-12-31 22:53 UTC, itswisdomagain commented on cli/walletloader/helpers.go
> +		if userResponse == "" || strings.EqualFold("y", userResponse) || strings.EqualFold("N", userResponse) {
- The response is currently treated as case-insensitve (strings.EqualFold)
- The "no" default was as suggested by @raedah, it made sense too because prior to asking users whether to create a wallet, if there was no wallet, the program just exits with a message asking users to run the `godcr createwallet` command to create a wallet. This maintains that behaviour, by default, the program exits. User can create the wallet manually by running the appropriate command. That said, what other option does the user have than to create a wallet if none exists? "Yes" default makes sense
- Correct, will do

2018-12-31 23:01 UTC, barisere commented on cli/walletloader/helpers.go
> +		if userResponse == "" || strings.EqualFold("y", userResponse) || strings.EqualFold("N", userResponse) {
For the `createwallet` command, "yes" makes sense as default. No would make sense if we we're suggesting owing to the absence of a wallet, but not when to the user is asking to create a wallet.

2019-01-01 13:00 UTC, barisere requested changes

2019-01-01 13:00 UTC, barisere commented on cli/termio/terminalprompt/terminalprompt.go
> +func RequestYesNoOption(message, defaultOption string) (string, error) {
This function will be used to ask polar questions, so the return string represents only two possible states: the user either agrees or disagrees. Thus, we can use a boolean instead of string as the first return value.
The benefit is that there won't be a need for a string comparison of the user input at the call sites; we know it was affirmative if `true` is returned, negative otherwise.

2019-01-01 13:00 UTC, barisere commented on cli/termio/terminalprompt/terminalprompt.go
> +	return userResponse, nil
`userResponse` here can be either "y", "yes", "n", or "no", based on the logic in `validateUserResponse`. It's easy to miss these if we do string comparison of the user input at the call site. Hence my previous suggestion to use boolean return value.

2019-01-01 13:00 UTC, barisere commented on cli/walletloader/helpers.go
> +	if strings.EqualFold("n", userResponse) {
My previous addresses a possible error on this line.

2019-01-01 13:00 UTC, barisere commented on cli/walletloader/walletloader.go
> +	syncBlockchainResponse, err := terminalprompt.RequestYesNoOption(syncBlockchainPrompt, "Y")
Check the subsequent use of `syncBlockchainResponse`. It should be a boolean, if you've made the change suggested in the preceding comments.

2019-01-01 13:02 UTC, barisere requested changes

2019-01-01 13:02 UTC, barisere commented on cli/commands/receive.go
> +	confirm, err := terminalprompt.RequestYesNoOption("Would you like to generate a QR code?", "N")
See https://github.com/raedahgroup/godcr/pull/99#discussion_r244636630 and the other comments in that review.

2019-01-01 13:03 UTC, barisere commented on cli/commands/send.go
> +	confirm, err := terminalprompt.RequestYesNoOption("Are you sure?", "")
See https://github.com/raedahgroup/godcr/pull/99#discussion_r244636630

2019-01-01 13:05 UTC, barisere requested changes

2019-01-01 13:05 UTC, barisere commented on cli/commands/send.go
> +	confirm, err := terminalprompt.RequestYesNoOption("Are you sure?", "")
See https://github.com/raedahgroup/godcr/pull/99#discussion_r244636630

2019-01-01 14:00 UTC, barisere approved these changes

2019-01-01 14:15 UTC, merged